{100}{}{Это дверная консоль.}
{101}{}{Эта консоль управляет, главным образом, дверью убежища.}
{102}{}{Э... что-то я тут ни хрена не понимаю...}
{103}{}{Эта консоль не для юзеров. Подучились бы сперва.}
{104}{}{На позывные никто не отвечает.}
{105}{}{Вы получаете опыт за нахождение своих собратьев.}

{107}{}{Перед вами консоль. Вы не сможете через нее открыть дверь в убежище, но сможете подать сигнал.}
{108}{}{Дать сигнал в убежище.}
{109}{}{(Уйти)}
{110}{}{(Из динамика доносится писк и шипение, затем треск, и через несколько секунд вы слышите голос) Эээ... Здравствуйте...}
{111}{}{Пиццу заказывали?}
{112}{}{Чт... (пауза) Эээ... Нет.}
{113}{}{А фильм "Глубокая глотка"?}
{114}{}{Нет.}
{115}{}{Это не вы потеряли носовой платок?}
{116}{}{Нет.}
{117}{}{Жаль. Красивый такой... А вы не скажете, который час?}
{118}{}{Нет.}
{119}{}{Странно... А вы не могли бы...}
{120}{}{Нет.}
{121}{}{О... и все же - это не ваш носовой платок?}
{122}{}{Нет, не мой.}
{123}{}{Тогда зачем я здесь стою?}
{124}{}{Не знаю. А где... вы стоите?}
{125}{}{Снаружи, перед дверьми вашего убежища. А разве непонятно?}
{126}{}{Но... но этого не может быть! Где вы?! То есть... вы звоните из другого убежища?}
{127}{}{Ну не совсем. Да, я из другого убежища. Но сейчас я стою перед вашим.}
{128}{}{Так... а как вы сюда добрались?!}
{129}{}{Пешком. Это было несложно. Ну если не считать всяких мутантов и бандюков, которые заполонили Пустошь. А вы не могли бы открыть дверь, чтобы мы смогли пообщаться за рюмкой колы?}
{130}{}{(пауза) Извините, но я не могу рисковать. Я не знаю обстановки за дверью. Вдруг сюда проникнут эти... мутанты и бандюки? К тому же я до сих пор не уверен, что это не шутка.}
{131}{}{А как же мониторы вашего убежища? Вы их проверяете? На самом деле в Пустоши уже можно выходить! Мы уже вышли и воссоздаем будущий город.}
{132}{}{Как воссоздаете?}
{133}{}{С помощью ГЭКК, разумеется!}
{134}{}{Возможно, стоит кое-что проверить. И все-таки пока мы воздержимся и еще посидим за дверьми. Спасибо, что связались с нами. Но извините, мне пора идти на совещание.}
{135}{}{Чт... Куда!?...}

{136}{}{(сигнал пропал)}
{137}{}{Чертов ссыкун!}
{138}{}{(Выйти)}
{139}{}{От ссыкла слышу! (сигнал опять пропал)}
{140}{}{(Выйти)}