{100}{}{Вы видите консоль охраны.}
{101}{}{Перед вами консоль для ввода удаленных команд охранной системе станции.}
{102}{}{Для активации консоли нужен научный метод.}

{103}{}{Вы уже отключили систему безопасности.}
{104}{}{Не сработает}
{105}{}{Вы взломали и отключили систему безопасности.}
{106}{}{Ваших научных знаний недостаточно, чтобы взломать эту консоль.}
{107}{}{Не могу}
{108}{}{Вот так-то!}
{109}{}{В этот раз вам не удалось взломать охранную систему.}
{110}{}{Неудача}
{111}{}{}
{112}{}{Охранная система не отвечает.}
{113}{}{Нет сигнала}
