#Описания
{100}{}{Вы видите сейф с кодовым замком.}
{101}{}{Перед вами очень прочный сейф.}

#При нанесении урона
{102}{}{Этот сейф не удастся взорвать, так как он сделан из сверхпрочного сплава.}

#При получение бонуса - бумажки управляющего
{103}{}{Ваша зоркость поражает! Вы обнаружили в сейфе тайник, а в тайнике какую-то записку.}

#Применение навыков и предметов
{104}{}{Это очень прочный сейф местного управляющего. Такие обычно содержат много ценных вещей.}
{105}{}{Это здесь не поможет.}
{106}{}{Очень прочный сейф. Наверняка в нем хранятся ценные вещи.}
{107}{}{Бесполезно}
{108}{}{Механические отмычки здесь не помогут - сейф заперт на электронный замок.}
{109}{}{Не то}

#Попытка обезвредить ловушку
{110}{}{Вы находите электрическую ловушку на сейфе, но ваших навыков не хватит для ее отключения.}
{111}{}{Вы отключили ловушку на сейфе.}
{112}{}{Вот так-то!}
{113}{}{Ловушка ударила вас током, но амуниция погасила удар.}
{114}{}{Ловушка ударила вас током, но резиновые сапоги частично смягчили удар.}
{115}{}{Ловушка ударила вас током.}
{116}{}{Неудача}
{117}{}{Дьявол!}
{118}{}{Ловушек нет.}

#Попытка взлома
{120}{}{Этот сейф уже взломан.}
{121}{}{Ваших навыков не хватает для вскрытия замка. Дальше пытаться бессмысленно.}
{122}{}{На сейфе электрическая ловушка. Ее нужно отключить прежде, чем пытаться взломать сейф.}
{123}{}{Обнаружена ловушка}
{124}{}{Сейф запитан кабелем с высоким напряжением.}

{125}{}{Вы искусно взламываете этот сейф.}
{126}{}{Ну-ка! Что тут у нас?!}
{127}{}{Вам не удалось взломать сейф.}

#Плавающие реплики при неудаче взлома:
{130}{}{Неудача}
{131}{}{Ну же!}
{132}{}{Аргх!}
{133}{}{Сим-сим, откройся!}
{134}{}{Приказываю - открывайся!}
{135}{}{Ну давай уже!}
{136}{}{Сколько я буду ждать?!}
{137}{}{Я хочу тебя открыть!}
{138}{}{Что у тебя внутри?}
{139}{}{Еще немного...}
{140}{}{Совсем чуть-чуть...}
{141}{}{Умммм...}
{142}{}{Торопыга...}
{143}{}{Гадство!}
{144}{}{Чую роскошь...}
