{100}{}{Вы видите Питера Грейвса.}
{101}{}{Перед вами Питер Грейвс, начальник службы безопасности Города Убежища.}

#Разное
{102}{}{}
{103}{}{}
{104}{}{Черт возьми! Да здесь было целое побоище!}
{105}{}{О, Боже! Что здесь произошло?!}

{114}{}{До свидания.}
{117}{}{Без проблем. Я не подведу.}

#После получения первого задания:
{124}{}{Мне больше нечего вам сообщить, гражданин. Дальше придется разбираться самому.}
{125}{}{Вот засада...}

#Сдача Комплектов
{126}{}{Я нашел SoS в Хоторне!}
{127}{}{Я нашел SoS в Зоне 51!}
{128}{}{Мне нужно немного времени, чтобы проанализировать ситуацию и лучше изучить улики. Приходите через 2 часа, тогда все обсудим.}
{129}{}{Не сейчас. Приходите через пару часов.}
{130}{}{По поводу Зоны 51 - дело дрянь. Ангар, в котором хранилась вся информация о Комплекте, был разрушен.}

{150}{}{Я знал, что могу на вас рассчитывать, гражданин. А теперь показывайте Комплект!}
{151}{}{Вот он!}
{152}{}{Хм... Он какой-то легкий... (поворачивает и рассматривает с разных сторон) Говорите, отыскался в Хоторне? Надо бы проверить это устройство, я пока не уверен, что это то, что нужно...}
{153}{}{Ну тогда проверяйте.}

{154}{}{Уф... (Питер вскрывает крышку коробки) Срань Господня!}
{155}{}{Что?! Что случилось?!}
{156}{}{Гррм... Я зря вас отослал в этот Хоторн. (швыряет крышку) Это пустышка! Его недоделали! Здесь не хватает и половины деталей! Бесполезная коробка с проводами!}
{157}{}{Бесполезная?! Вот черт... и что же теперь делать?}

{158}{}{Хм... Тяжелый, зараза... (поворачивает и рассматривает с разных сторон) Говорите, отыскался в Зоне 51? Это радует. Давайте подключим провода и посмотрим, есть ли контакт? Мне не нравится, что внутри корпуса что-то болтается.}
{159}{}{(Питер некоторое время проводит за работой, затем отворачивает крышку и швыряет ее в сторону) Я так и думал... очередной промах!}
{160}{}{Вы напрасно бегали в эту Зону 51. Это просто пустышка! Смотрите, гражданин! (достает заплесневелые бутылки) Я не знаю, что у них внутри, но для меня это мусор! Мне нужна *действующая* система или хотя бы детали, чтобы ее собрать. А здесь остатки от военной контрабанды! В довоенное время я бы расстрелял тех, кто это сделал!}
{161}{}{Что делать? А как думаете? Искать чертов Комплект на складах в Хоторне! Немедленно отправляйтесь на эту чертову базу и ищите там! С этого и надо было начинать поиски!}
{162}{}{Ясно.}
{163}{}{Что делать? А как вы думаете?! Будем искать дальше!}

#Проверка на улики из Хоторна
{170}{}{Что-нибудь еще было найдено в Хоторне?}
{171}{}{Больше ничего полезного по теме.}
{172}{}{Да, голодиск с отчетом о дезертирах базы.}
{173}{}{Да, голодиск с приказом об испытаниях Комплекта на полигоне.}
{174}{}{Да, отчет об испытаниях Комплекта на полигоне.}
{180}{}{Здесь ничего интересного. Какое мне дело до дезертиров?}
{181}{}{Ясно...}
{182}{}{Слабовато. Судя по приказу, Комплект привезли в Хоторн с другой военной базы и тестировали на местном полигоне. Это ни о чем не говорит.}
{183}{}{А вот это интересно! Вдумайтесь? Комплект привезли в Хоторн из Зоны 51, хотя там есть собственный полигон испытаний. Почему? Что-то мне подсказывает, что именно в Зоне 51 занимались разработкой этой технологии. Держу пари, что там есть и документация, и могли сохраниться некоторые недопоставленные экземпляры самого Комплекта!}

#Проверка на улики из Зоны 51
{190}{}{Постойте! Что-нибудь еще было найдено в этой Зоне 51?}
{191}{}{Больше ничего полезного по теме.}
{192}{}{Да, дипломат со множеством документов. Нашел в кабинете одной из казарм.}
{193}{}{Да, голодиск с отчетом об испытаниях Комплекта на полигоне. Но он зашифрован.}
{194}{}{Вы принесли хорошую информацию. Мне нужно еще немного времени, чтобы лучше их изучить. Молодец, гражданин.}
{195}{}{Судя по названию, вы принесли очень полезную информацию! Я отдам голодиск на расшифровку. Возможно, здесь есть ответ на вопрос, где искать работающий экземпляр Комплекта. Вы хорошо постарались. Молодец!}
{196}{}{Грм, гражданин, вы принесли плохую новость. Но вы уверены, что это именно *тот* ангар?}
{197}{}{Да. Об этом свидетельствуют документы из казарм.}
{198}{}{Да. Я изучил некоторую информацию и даже собрал кое-что на зашифрованный голодиск.}
{199}{}{Ну да. Я там был и все видел! Что же теперь делать?}

#Отправляет в Зону 51
{200}{}{Дело дрянь. Этот липовый Комплект из Хоторна никуда не годен. Нужно искать в других местах. Есть одна зацепка. Комплект тестировали в Хоторне, но разрабатывали на другой базе, в Зоне 51. Это довоенная база, она хорошо охранялась в свое время. Вам придется отправиться туда. Но точных координат у нас нет, узнайте их в близлежащих населенных пунктах, например, в Вегасе. Сэм выдаст инвентарь в дорогу. Свободны.}
{201}{}{Какого хрена! Я вам не кусок дерьма, чтобы отправлять меня на истребление!}
{202}{}{Послушайте, гражданин, вы ценны уже тем, что оторвали свою задницу от родного убежища! И вы уже довольно много путешествовал в Пустошах, вы имеете опыт выживания, которого нет ни у кого другого из нас. Только *вы* справитесь с этой задачей.}

#Отправляет в Нью-Рино
{203}{}{Я внимательно изучил данные, которые вы собрали во время выполнения задания. Что ж, вы не зря потрудились. Надежда есть. Но прежде чем я смогу объяснить вам суть происходящего, вам придется еще раз выйти во внешний мир.}
{204}{}{Ох, опять туда?...}
{205}{}{Мне нужна информация о всех возможных убежищах и их координатах в Неваде и соседствующих штатах.}
{206}{}{Нам своего не хватает?}
{207}{}{Гражданин, вам пока не положено знать всех деталей. Я объясню подробнее, когда вы вернетесь с данными. Найдите эвакуационный бункер в Нью-Рино, проникните внутрь и соберите как можно больше документальной информации. Скорее всего, в годы войны бункер законсервировали, но у нас сохранился пароль. А теперь - свободны.}
{208}{}{Будет сделано!}

{209}{}{Я внимательно изучил данные. Ваши старания оказались бесполезны. Вы не собрали никаких улик. Но надежда есть.}
{210}{}{Это радует.}
{211}{}{К сожалению, наше положение очень шатко. И нам придется рискнуть. Вы должны отправиться в самое небезопасное место в Пустошах - в город Нью-Рино.}
{212}{}{Что там надо сделать?}
{213}{}{Мне нужна информация о всех возможных убежищах и их координатах в Неваде и соседствующих штатах.}
{214}{}{Нам своего не хватает?}
{215}{}{Гражданин, вам пока не положено знать всех деталей. Я объясню подробнее, когда вы вернетесь с данными. Найдите эвакуационный бункер в Нью-Рино, проникните внутрь и соберите как можно больше документальной информации. Скорее всего, в годы войны бункер законсервировали, но у нас сохранился пароль. А теперь - свободны.}
{216}{}{Будет сделано!}

# Сдача голодиска из бункера Рино
{217}{}{Гражданин, не разочаровывайте меня! Вы принесли информацию из бункера?}
{218}{}{Нет, извините, я над этим работаю...}
{219}{}{Так точно! Вот голодиск с информацией из бункера!}
{220}{}{}
{221}{}{}
{222}{}{}
{223}{}{Будет сделано, сэр!}
{224}{}{Я все еще не слышу хороших вестей, гражданин.}
{225}{}{Извините, сэр! Будет исправлено, сэр!}

#Сдача квеста на станцию Баттл-Маунтин
{226}{}{(рассказать о сигнале)}
{227}{}{Все сходится. Направление, в котором движется банда Собирателя, совпадает с направлением того пункта, в который был подан сигнал из нашего Убежища при первом выходе на поверхность.}
{228}{}{Это насколько далеко?}

{229}{}{Координаты этого пункта нам известны благодаря информации из бункера в Нью-Рино. Вы не зря выполняли это задание.}
{230}{}{Координаты этого пункта довольно примерны. Вы так и не предоставили их. Поэтому вам придется еще раз отправиться в бункер Нью-Рино, чтобы уточнить их.}
{231}{}{Хорошо, сэр.}

{232}{}{Ваша задача - *любой ценой* остановить их. Вы... понимаете меня, гражданин?}
{233}{}{Значит, если мне не удастся вернуть Смотрителя, то его надо... Ага. Я вас понял.}
{234}{}{Что?! Убить Смотрителя?! Вы рехнулись!}
{235}{}{Нет, к чему вы клоните?}

{236}{}{У нас нет иного выбора. Смотритель знает слишком много о городе и убежище. Его знания - это оружие, которым можно уничтожить город.}
{237}{}{Если вы не сможете спасти Смотрителя, то его нужно ликвидировать. У нас нет иного выбора. Смотритель знает слишком много о городе и убежище. Его знания - это оружие, которым можно уничтожить город.}
{238}{}{Да, это будет нелегко.}
{239}{}{Я не подведу, сэр.}

#Разное
{240}{}{Добрый день, гражданин. Рад видеть вас в добром здравии.}
{241}{}{Я тоже, сэр. До свидания.}
{242}{}{И еще. Даже если вы не сможете догнать похитителей, то не исключено, что среди остатков техники в том убежище может отыскаться и система SoS. Поэтому будьте внимательны.}

#Стартовый диалог, изъятие паспорта:
{250}{}{Та-ак! Гражданин, где ваши документы?}
{251}{}{Э... Я оставил их в убежище, сэр.}
{252}{}{Вот они, сэр.}
{253}{}{Э... я их потерял, сэр...}

{254}{}{За халатность вам надо бы сделать строгий выговор. Но с другой стороны, в этом задании вы должны действовать тихо. Никто не должен узнать о ваших связях с нашим Убежищем, иначе последствия могут быть необратимы.}
{255}{}{Вам это не понадобится. Я конфискую документы, пока вы не выполните задание.}
{256}{}{Что?! Гражданин, куда пропала ваша бдительность?! Вы потеряли самый *важный* документ о вашей гражданской чистоте!... Впрочем, это даже к лучшему. В этом задании любые намеки на наше убежище могут оказаться критичны.}
{257}{}{Понятно. А что за задание?}
{258}{}{Хм... Вы достаточно сообразительны. Я надеюсь, Смотритель не ошибся в выборе. Да, вы временно лишены гражданства ради общей безопасности. И пока не выполните задание, мы не вернем вам гражданство.}
{259}{}{Что за черт!? Меня умышленно лишают гражданства?!}

#Объяснение первого задания (поиск в Хоторне)
{260}{}{Прежде чем перейти к описанию, давайте определимся. Первое - вам не положено знать всех подробностей ситуации, не задавайте лишних вопросов и не суйте нос, куда вам не велено. Второе - ваше задание тайное, не упоминайте во внешнем мире о вашем поиске и существовании нашего города. Даже наши рядовые граждане не в курсе событий.}
{261}{}{Звучит очень серьезно. Так что там нужно было сделать?}
{262}{}{Смотритель распорядился найти прибор, который нам должны были поставить до запечатывания убежища, но этого по неизвестным причинам не произошло. Прибор называется "Комплект Наружной Безопасности" или сокращенно "SoS". Вы должны найти его. По нашим данным, наиболее вероятное место нахождения - армейская база "Хоторн", там тестировали прибор на полигоне. Расположение базы отмечено в вашем Pip-Boy. Вам придется выйти во внешний мир и найти этот прибор. Звучит удручающе, понимаю, но это *крайне* важно для нас... Вероятно, у вас остались вопросы, возможно, я смогу на них ответить.}
{263}{}{Да, у меня остались вопросы.}
{264}{}{Вопросов нет.}

{265}{}{Хорошо. Что вы хотели узнать?}

{266}{}{Расскажите о Комплекте подробнее?}
{267}{}{Мне выдадут снаряжение для путешествия?}
{268}{}{Можно подробнее, что это за место - Хоторн?}
{269}{}{К чему такая конспирация?}
{270}{}{Что меня может ожидать во внешнем мире?}
{271}{}{Что это за мерзость в соседней комнате?}
{272}{}{Да вы рехнулись! Что, если я откажусь?}

{275}{}{Понятно. Другой вопрос.}
{276}{}{Думаю, это все, что хотелось узнать.}

{277}{}{Комплект - сложный компьютер, управляющий системой турелей и другой охранной автоматикой. Если мы найдем его, то сможем автоматизировать нашу защиту, и тогда Город Убежища станет неприступной крепостью.}
{278}{}{Так точно. Складом заведует Сэм, он в курсе дел и выдаст назначенный инвентарь. Расходуйте его с умом, наши запасы не безграничны.}
{279}{}{Это довоенная база. Там тестировали военную технику и оружие массового поражения. Скорее всего за прошедшие полстолетия база опустела, но все же будьте предельно внимательны, это место может оказаться небезопасно.}
{280}{}{Как я уже говорил, не задавайте лишних вопросов. Есть на то... причины. Боюсь, вы еще не готовы знать правду, а жители Пустоши - тем более. Именно поэтому вам выдан этот нестандартный серый комбинезон, и именно поэтому вы временно лишены гражданства. Мы должны затаиться, пока не будем готовы.}
{281}{}{Готовы?! К чему готовы?!}
{282}{}{(проговаривает сквозь зубы) Гражданин, советую одуматься, пока не поздно. Помните, язык - ваш первый враг в Пустошах.}
{283}{}{Хороший вопрос, хвалю! Там по-прежнему живут люди... если их можно таковыми назвать. Периодически мы контактируем с некоторыми проходимцами, особенно с караванами. Но в основном стараемся отпугивать пришлых нашими патрулями. В Пустошах уже блуждают слухи о существовании нашего "города-сада", но это опасные слухи, они прельщают рейдерские группы, бандитов и мародеров. К сожалению, общество за пределами города настолько опущено, что ни в коей мере не способно соперничать с нами в развитости и интеллекте. Вы должны относиться к ним снисходительно и не провоцироваться на их агрессию. Помните - они лишь приматы по сравнению с вами. Дикие грязные обезьяны, лишенные разума.}
{284}{}{Мы знаем только со слов других караванщиков, что это якобы безобидный весельчак, который водил караваны по всей Калифорнии и Неваде. Время его не пощадило. Или... не пощадила какая-то уникальная форма вируса. Впрочем, это уже его проблемы. Вернемся к своим.}
{285}{}{Гражданин, вы важны уже тем, что оторвали свою задницу от кресла в убежище. Вас избрал сам Смотритель, он считает вас особенным... гражданином. Вы не можете отказаться еще и потому, что вы лишены гражданства и не можете пользоваться стандартными процедурами нашего города. По сути, вы... изгнаны до тех пор, пока не завершите поиск. Хотите вернуться к своему родному городу - помогите ему спастись от полного уничтожения, докажите свою преданность! Ну же, гражданин! Вы *нужны* нам!}

{286}{}{Что ж, удачи, гражданин. Не забывайте хранить молчание. Мы выдадим вам немного денег в дорогу, внешний мир до сих пор падок на это довоенное средство обмена товарами. Расходуйте их с умом. И... поторопитесь, гражданин. Вы нужны городу.}
{287}{}{Будет сделано, сэр!}
{288}{}{Вы получили новые квесты. Откройте Pip-Boy для просмотра.}

#Вопросы и ответы
{330}{}{Мне нужно вам кое о чем рассказать.}
{331}{}{Я вас внимательно слушаю, гражданин.}

{332}{}{Тут у меня бомба из Хоторна...}
{333}{}{Нашел в Хоторне ящик с патронами.}
{334}{}{Нашел голодиск с приказом генштаба с АЭС.}
{335}{}{Нашел список радиопунктов на АЭС.}
{336}{}{Нашел кейс с документами на радиостанции в Шайенне.}
{337}{}{Я отыскал радиостанцию недалеко от Шайенн.}
{338}{}{Вы можете выдать мне боевую броню?}
{339}{}{Я выторговал какие-то железки, говорят, они для SoS.}
{340}{}{Извините, уже ничего.}

{341}{}{Что?! Срань Господня! Гражданин! Немедленно унести это за пределы города! Немедленно! Или я вас изолирую на две недели!!!}
{342}{}{Срань Господня!!! Гражданин, вы сошли с ума! Немедленно унести ее за пределы города! Она может взорваться в любой момент! Вы подвергаете опасности весь город!!!}
{343}{}{Вы идиот!!! Она может взорваться в любой момент! Вы подвергаете опасности весь город!!! Немедленно унести ее как можно дальше!!! Немедленно!!!}
{344}{}{Ок.}
{345}{}{Очень жаль, гражданин, но ваша находка не подойдет ни к одной единице нашего вооружения. Скорее всего, это патроны от тяжелых самоходных пулеметов. Для нас эти патроны бесполезны.}
{346}{}{Вы принесли очень любопытный документ. Похоже, что правительство знало о надвигающейся войне. Возможно, верхушка власти успела укрыться в убежище, которое указано в подписи к голодиску. Я возьму голодиск для детального изучения. Но впредь постарайтесь не совать свой нос в такие сомнительные и небезопасные места, как АЭС Посейдон Ойл.}
{347}{}{Хм, я в этом не разбираюсь. Возможно, центр технической поддержки сможет выжать из этой информации что-то полезное. Обратись к ним.}
{348}{}{Вы принесли *очень* важную информацию, гражданин! Нам понадобится немало времени, чтобы подобрать шифр, однако уже то, что можно прочитать, говорит о многом. Благодарю, гражданин.}
{349}{}{Всякая работающая радиостанция позволяет нам расширить зону радиоперехвата. Вы правильно поступили, что рассказали мне об этой станции. Я отдам координаты нашим техникам, возможно, когда-нибудь мы займемся и этим вопросом. Благодарю, гражданин.}
{350}{}{Гражданским лицам не положено выдавать такие дефицитные средства защиты. Но вам и не нужна эта броня - ваша миссия мирная, не забывайте об этом. К тому же вам будет сложнее таскать на себе дополнительный вес.}
{351}{}{Так и есть. В нашей документации о Комплекте эта запчасть указана. Это специальная плата для ускоренной обработки данных, поступающих от локационной системы. Будь у нас работающий Комплект, установка этой платы значительно расширила бы возможности наших турелей. Молодец, гражданин, это очень полезная находка. Раз вам пришлось потратиться на ее приобретение, мне придется выплатить вам гонорар. Свободны.}
{352}{}{Ух ты! Сколько денег!}
{353}{}{Что же делать?}
{354}{}{И что с того?}

#Предохранитель
{370}{}{Мне отказывают в выдаче предохранителя. Нельзя ли изменить правила?}
{371}{}{Аргументируйте.}
{372}{}{Поселение Джерлака нуждается в починке водяного насоса. Я хочу им помочь.}
{373}{}{[ложь] Во внешнем мире есть связной, он требует предохранитель за информацию.}
{374}{}{[ложь] Это нужно для починки поезда.}
{375}{}{[ложь] Это нужно для запуска радара Баттл-Маунтин.}
{376}{}{У меня нет веских оснований, но я их найду!}

{377}{}{Надеюсь, вы понимаете, что делаете. Мы не можем разбрасываться технологиями. Я дам команду на склад, и вам выдадут этот инвентарь. Свободны.}
{378}{}{Благодарю.}

{379}{}{Джерлак? Поселение на юге? Не понимаю, зачем нам помогать пришлым. В любом случае, за южный сектор отвечает сержант Старк. Вы сможете найти его в здании на другой стороне дороги.}
{380}{}{Благодарю. Пойду искать этого сержанта.}

#Если стал врагом Убежища 8 (плавающие реплики во время боя):
{500}{}{Это предательство! Умри!!!}
{501}{}{Какое предательство!}
{502}{}{Почему ты так поступаешь с нами?}
{503}{}{Неужели Пустоши дороже, чем родное Убежище?!}
{504}{}{Мне следовало догадаться, что у тебя грязная душонка!}
{505}{}{Предатель!}
{506}{}{Иди-ка сюда!}
{507}{}{Подло! Это очень подло!}
{508}{}{Мне хотелось добра, но придется расхотеть!}
{509}{}{За хлеб, за воду! За чистую природу!}
{510}{}{Это Моро сделал из тебя чудовище?!}

# Случайные плавающие реплики, по таймеру:
{550}{}{Потом натру этим мальчикам уши}
{551}{}{:: кряхтит ::}
{552}{}{Ох уж мне эти караваны...}
{553}{}{Надеюсь, я больше не услышу эти завывания Гарольда}
{554}{}{У меня есть *план*!}
{555}{}{Слишком тихо. Не нравится мне это}
{556}{}{:: зевает, не прикрывая рта ::}
{557}{}{Жрать охота}
{558}{}{Дел слишком много}
{559}{}{Будешь меня доставать - пришибу к такой-то матери!}

{560}{}{Сэм? Где Сэм?}
{561}{}{Нужно организовать стрельбище}
{562}{}{Вот дерьмо...}
{563}{}{А если его облучить, ты будешь плакать?}
{564}{}{Теперь будем работать вахтовым методом}
{565}{}{Руководители всех подразделений! На планерку!}
{566}{}{Это кто там шляется?}

#Про нападение Собирателя Душ, получение квеста на Благодатное
{600}{}{Хорошо, что вы вернулись, гражданин.}
{601}{}{Черт возьми!!! Что здесь произошло?!}
{602}{}{Без паники, гражданин! Соберитесь!}
{603}{}{Хорошо. Все, я в норме. Так что здесь происходит, черт возьми?!}
{604}{}{То, чего мы опасались. Появился Собиратель.}
{605}{}{А я подозревал, что вы что-то недоговариваете... Кто он такой?}

{606}{}{Загадочная личность с мешком на голове. Самая зловещая сила, которую можно найти в нашем регионе. Он и пальцем не пошевелил, чтобы убить пятерых охранников и увести Смотрителя из города.}
{607}{}{Что?! Смотрителя похитили?!}
{608}{}{Так точно. Собиратель не простой человек, если он... вообще человек. Он легко прошел незамеченным через город вместе со своей бандой и проник в убежище. Мы успели обнаружить его и устроили засаду у выхода, но против его банды мы были бессильны.}
{609}{}{Зачем ему нужен Смотритель?}
{610}{}{Есть несколько предположений. Некоторые считают, что он будет шантажировать город и требовать выкуп. Но у меня другое мнение. Собиратель уже бывал в нашем убежище и прекрасно ориентируется в городе....}
{611}{}{Э, вы хотите сказать, он был выходцем из нашего убежища!?}
{612}{}{Нет, он из *другого* убежища.}
{613}{}{Вы уверены?! И насколько оно далеко?}
{614}{}{Мы не имеем точных координат. Я направил вас в Нью-Рино, чтобы вы отыскали список убежищ. Возможно, там есть ответ. Доподлинно мы знаем только то, что это правительственное убежище, и находится оно намного севернее Солт-Лейка. Именно туда был послан сигнал, когда наши предки впервые выходили на поверхность из убежища, 49 лет назад.}
{615}{}{Звучит невероятно.}
{616}{}{Еще более невероятно выглядят записи нашего Смотрителя и те знания, которые он оставил нам с вами.}
{617}{}{Продолжайте.}
{618}{}{Смотритель доверял мне и предупреждал об опасности. Он знал, что сеть убежищ, к которой относится и наше восьмое, была экспериментом правительства США. Назначение убежища мне неизвестно, в отличие от смотрителя. Что-то творилось за нашими спинами все это время. Думаю, некто пытается тайно влиять на события в городе, и Собиратель - лишь одна из фигур в этой истории.}
{619}{}{Поэтому смотрителя увезли - он слишком много знает?}
{620}{}{Смотритель не просто знал секрет убежища, он пытался все исправить. Поэтому он дал задание найти систему SoS. Тем не менее Комплекта по-прежнему нет, а теперь еще и пропал человек, который знал слишком много о городе. Практически мы остались открыты для любого удара.}
{621}{}{Что же теперь делать?}
{622}{}{Прежде чем продолжить, решим прошлый вопрос. Где информация из бункера?}
{623}{}{Вот голодиск.}
{624}{}{Простите, сэр. Я не донес ее.}

{625}{}{Это радует. Что ж, перед смертью не надышишься. И все же нам придется что-то предпринять. К счастью, личный Pip-Boy Смотрителя имеет встроенный жучок для слежки за передвижениями. Он есть у всех наших сограждан, кроме вас. Мы позаботились о вашем жучке заранее.}
{626}{}{Значит, мы можем проследить, куда движутся Смотритель и этот Собиратель?}
{627}{}{Гражданин, ваше... омерзительное отношение к работе почета вам не делает. Возможно, вам еще предстоит вернуться туда, но сейчас есть дела поважнее. К счастью, личный Pip-Boy Смотрителя имеет встроенный жучок для слежки за передвижениями. Он есть у всех наших сограждан, кроме вас. Мы позаботились о вашем жучке заранее.}
{628}{}{Лишь в радиусе половины штата. Сигнал движется очень быстро. Траектория движения повторяет железнодорожную линию, очевидно, Смотрителя перевозят на какой-то железнодорожной технике.}
{629}{}{Где они сейчас?}
{630}{}{Движутся в восточном направлении. Скоро их сигнал исчезнет, поэтому вам необходимо добраться до пустующего поселения Баттл-Маунтин и проследить движение Смотрителя на местном радаре. Несколько лет назад мы пытались уже это сделать, но микроядерный заряд давно иссяк. Скорее всего, радар до сих пор функционирует, и вы могли бы проследить дальнейшую дислокацию беглецов с его помощью. Отправляйтесь туда немедленно. Дальше - по своему усмотрению.}

#Женские реплики (Иван):
{1124}{}{Мне больше нечего вам сообщить, гражданка. Дальше придется разбираться самой.}
{1126}{}{Я нашла SoS в Хоторне!}
{1127}{}{Я нашла SoS в Зоне 51!}
{1150}{}{Я знал, что могу на вас рассчитывать, гражданка. А теперь показывайте Комплект!}
{1160}{}{Вы напрасно бегали в эту Зону 51. Это просто пустышка! Смотрите, гражданка! (достает заплесневелые бутылки) Я не знаю, что у них внутри, но для меня это мусор! Мне нужна *действующая* система или хотя бы детали, чтобы ее собрать. А здесь остатки от военной контрабанды! В довоенное время я бы расстрелял тех, кто это сделал!}
{1192}{}{Дипломат со множеством документов. Нашла в кабинете одной из казарм.}
{1194}{}{Вы принесли хорошую информацию. Мне нужно еще немного времени, чтобы получше их изучить. Молодец, гражданка.}
{1196}{}{Эх, гражданка, вы принесли плохую новость. Но вы уверены, что это именно *тот* ангар?}
{1198}{}{Да. Я изучила некоторую информацию и даже собрала кое-что на зашифрованный голодиск.}
{1199}{}{Ну да. Я там была и все видела! Что же теперь делать?}
{1202}{}{Послушайте, гражданка, вы ценны уже тем, что оторвали свою задницу от родного убежища! И вы уже довольно много путешествовали в Пустошах, вы имеете опыт выживания, которого нет ни у кого другого из нас. Только *вы* справитесь с этой задачей.}
{1207}{}{Гражданка, вам пока не положено знать всех деталей. Я объясню подробнее, когда вы вернетесь с данными. Найдите эвакуационный бункер в Нью-Рино, проникните внутрь и соберите как можно больше документальной информации. Скорее всего, в годы войны бункер законсервировали, но у нас сохранился пароль. А теперь - свободны.}
{1215}{}{Гражданка, вам пока не положено знать всех деталей. Я объясню подробнее, когда вы вернетесь с данными. Найдите эвакуационный бункер в Нью-Рино, проникните внутрь и соберите как можно больше документальной информации. Скорее всего, в годы войны бункер законсервировали, но у нас сохранился пароль. А теперь - свободны.}
{1217}{}{Гражданка, не разочаровывайте меня! Вы принесли информацию из бункера?}
{1224}{}{Я все еще не слышу хороших вестей, гражданка.}
{1232}{}{Ваша задача - *любой ценой* остановить их. Вы... понимаете меня, гражданка?}
{1233}{}{Значит, если мне не удастся вернуть Смотрителя, значит его надо... Ага. Я вас поняла.}
{1240}{}{Добрый день, гражданка. Я рад видеть вас в добром здравии.}
{1250}{}{Та-ак! Гражданка, где ваши документы?!}
{1251}{}{Я оставила их в убежище.}
{1253}{}{Э... я их потеряла, сэр...}
{1255}{}{Вам это не понадобится. Я конфискую документы, пока вы не выполните задание.}
{1256}{}{Что?! Гражданка, куда пропала ваша бдительность?! Вы потеряли самый *важный* документ о вашей гражданской чистоте!... Впрочем, это даже к лучшему. В этом задании любые намеки на наше убежище могут оказаться плачевными.}
{1282}{}{(проговаривает сквозь зубы) Гражданка, советую одуматься, пока не поздно. Помните, язык - ваш первый враг в Пустошах.}
{1285}{}{Гражданка, вы важны уже тем, что оторвали свою задницу от кресла в убежище. Вас избрал сам Смотритель, он считает вас особенным... гражданином. Вы не можете отказаться еще и потому, что вы лишены гражданства и не можете пользоваться стандартными процедурами нашего города. По сути, вы... изгнаны до тех пор, пока не завершите поиск. Хотите вернуться к своему родному городу - помогите ему спастись от полного разорения, докажите свою преданность! Ну же, гражданка! Вы *нужны* нам!}
{1286}{}{Что ж, удачи, гражданка. Не забывайте хранить молчание. Мы выдадим вам немного денег в дорогу, внешний мир до сих пор падок на это довоенное средство обмена товарами. Расходуйте их с умом. И... поторопитесь, гражданка. Вы нужны городу.}
{1331}{}{Я вас внимательно слушаю, гражданка.}

{1333}{}{Нашла в Хоторне ящик с патронами.}
{1334}{}{Нашла голодиск с приказом генштаба с АЭС.}
{1335}{}{Нашла список радиопунктов на АЭС.}
{1336}{}{Нашла кейс с документами на радиостанции Шайенн.}
{1337}{}{Я отыскала радиостанцию недалеко от Шайенна.}
{1339}{}{Я купила какие-то железки, говорят, они для SoS.}

{1341}{}{Что?! Срань Господня! Гражданка! Немедленно унести это за пределы города! Немедленно!!! Или я вас посажу в карцер на две недели!!!}
{1342}{}{Срань Господня!!! Гражданка, вы сошли с ума! Немедленно унести ее за пределы города! Она может взорваться в любой момент! Вы подвергаете опасности весь город!!!}
{1343}{}{Вы идиотка!!! Она может взорваться в любой момент! Вы подвергаете опасности весь город!!! Немедленно унести ее как можно дальше!!! Немедленно!!!}

{1345}{}{Очень жаль, гражданка, но ваша находка не подойдет ни к одной единице нашего вооружения. Скорее всего, это патроны от тяжелых самоходных пулеметов. Для нас эти патроны бесполезны.}
{1348}{}{Вы принесли *очень* важную информацию, гражданка! Нам понадобится немало времени, чтобы подобрать шифр, однако уже то, что можно прочитать, говорит о многом. Благодарю, гражданка.}
{1349}{}{Всякая работающая радиостанция позволяет нам расширить зону радиоперехвата. Вы правильно поступили, что рассказали мне об этой станции. Я отдам координаты нашим техникам, возможно, когда-нибудь мы займемся и этим вопросом. Благодарю, гражданка.}
{1351}{}{Так и есть. В нашей документации о Комплекте эта запчасть указана. Это специальная плата для ускоренной обработки данных, поступающих от локационной системы. Будь у нас работающий Комплект, установка этой платы значительно расширила бы возможности наших турелей. Молодец, гражданка, это очень полезная находка. Раз вам пришлось потратиться на ее приобретение, мне придется выплатить вам гонорар. Свободны.}

{1600}{}{Хорошо, что вы вернулись, гражданка.}
{1602}{}{Без паники, гражданка! Соберитесь!}
{1605}{}{А я подозревала, что вы что-то недоговариваете... Кто он такой?}
{1624}{}{Простите, сэр. Я не донесла ее.}
{1627}{}{Гражданка, ваше... омерзительное отношение к работе почета вам не делает. Возможно, вам еще предстоит вернуться туда, но сейчас есть дела поважнее. К счастью, личный Pip-Boy Смотрителя имеет встроенный жучок для слежки за передвижениями. Он есть у всех наших сограждан, кроме вас. Мы позаботились о вашем жучке заранее.}
