{100}{}{Похоже, вы нашли рассадник заразы в Солт-Лейке! Сюда стекается полканализации города, и основные выбросы дает, видимо, завод ядер-колы.}
{101}{}{Так вот откуда расходится зараза по Солт-Лейку!}
