{100}{}{Вы видите Вульви.}
{101}{}{Вы видите одного из немногих жителей Прово.}
{102}{}{Посторонний!}
{103}{}{Я не в настроении с тобой разговаривать}

###################################################
#
#  Плавающий диалог между Вульви и Гэрри
#
#  Маркеры:
#         v - реплика Вульви
#         g - реплика Гэрри
#
###################################################

{200}{v}{Я хочу внимания!!! Мне скучно!!!}
{201}{g}{... Ну хватит жаловаться! Я тут пытаюсь сосредоточиться.}
{202}{v}{Кто это? А, это ты, Гэрри...}
{203}{g}{Конечно, я, кто же еще... Думаешь, тебе одному плохо?}
{204}{g}{На меня Хозяин вообще внимания не обращает...}
{205}{v}{Да ты просто дырка от задницы. А я его главный идейщик!}
{206}{v}{МНЕ НУЖНА СТИМУЛЯЦИЯ!}
{207}{g}{Дырке от задницы тоже нужна стимуляция.}
{208}{g}{Я хочу путешествовать! Увидеть сверкающий Вегас!}
{209}{g}{Хочу блевать в барах и гадить семенами травки у входа в казино...}
{210}{g}{... а вместо этого сижу в этом паршивом отеле.}
{211}{v}{Ничего, дружище, мы добьемся своего, мы увидим сверкающий Вегас.}
{212}{g}{Да ну? И как же мы это сделаем?}
{213}{v}{Есть на примете один план...}
{214}{v}{::оглядывается::}
{215}{v}{Черт! Я тебе потом расскажу, а то мясо сгорит.}
{216}{v}{Вечно оно у нас пригорает...}
{217}{v}{Вот так-то лучше...}
{218}{v}{Немного почистим от сажи и можно жрать.}
{219}{v}{И почему это Хозяин не сделает нормальную кухню?}
{220}{v}{Вечно я сижу в этих гребаных штанах, а мне нужен фартук.}
{221}{v}{Делов-то - сходил в рейд на караван и все...}
{222}{v}{::о чем-то задумался::}
{223}{v}{Наверное, шериф в Солте его пугает!}
{224}{v}{Да этот засранец сюда и шагу не сделает!}
{225}{v}{Оба друг друга ненавидят и оба друг друга боятся...}
{226}{v}{Какой бред, а!?}
{227}{v}{У меня были *такие* идеи, а Хозяин все спустил в унитаз!}
{228}{v}{Зачем я живу тогда? Зачем?!}
{229}{v}{Чтобы жарить мясо с навозом на сковородке?!}
{230}{v}{Что? Медаль за старания? Но как же?! Ведь я встал позже всех!}
{231}{v}{Что? Отпуск в Рино? Но братки еще не позавтракали!}
{232}{v}{Неее-нееет! Никаких вознаграждений! Я этого, черт возьми, не заслужил.}
{233}{v}{Ооо! Как же меня прет!}
{234}{v}{Я полон идей! Мой мозг скоро взорвется от гениальных мыслей!}
{235}{v}{Я мог бы поднять на ноги банду, если бы не этот... Хозяин!}
{236}{v}{Но зачем все это, если я даже не могу приобрести фартук?!!}
{237}{v}{Хозяин только и знает, что посылает все мои идеи за дверь...}
{238}{v}{... а я был серьезным...}
{239}{v}{::почти плачет::}
{240}{v}{... я хотел быть просто полезным...}
{241}{v}{... а он мне даже спасибо не скажет!}
{242}{v}{И по голове не погладит!}
{243}{v}{А я ВУЛЬВИ, надери меня геккон! А не дырка от задницы!}
