{100}{}{Ржавая дверь.}
{101}{}{Очень прочная и очень ржавая дверь. Такие ставили в тюрьмах. Выбить невозможно!}
{102}{}{Без ключа не взломать.}
{103}{}{Без ключа не открыть.}
{104}{}{Дверь открыта!}
{105}{}{Не получилось.}
{106}{}{Замок не поддается.}
{107}{}{Вы отпираете сложный замок и получаете 100 опыта.}
{108}{}{Здесь механический замок.}
{109}{}{Нужен ключ или отмычка.}
{110}{}{Дверь слишком прочная для такого удара.}
{111}{}{Проклятье!}
{112}{}{Вы заперли дверь на ключ.}
{113}{}{Дверь закрыта.}
{114}{}{Замок уже взломан}
{115}{}{Замок уже взломан и повторному взлому не поддается.}
