{0}{}{}
{100}{}{Вы видите консоль.}
{101}{}{Перед вами консоль для ввода пароля. Видимо, она управляет рядом стоящей дверью.}
{102}{}{Вы уже взломали эту консоль, теперь от нее нет пользы.}
{103}{}{Мне это не нужно}
{104}{}{К этой консоли не поступает электричество.}
{105}{}{Нет энергии}

#Начало диалога:
{110}{}{Здравствуйте. Пожалуйста, введите пароль.}
{111}{}{Хм, не попробовать ли эти пароли на бумажке директора из АЭС?}
{112}{}{Попытаться угадать пароль.}
{113}{}{Выход.}

{114}{}{Пароль принят. Добро пожаловать!}
{115}{}{Завершить.}
{116}{}{Вы обманули систему защиты и получаете }
{117}{}{ опыта.}
{118}{}{Вы верно угадали пароль и получаете }
{119}{}{О, круто! Что ж, пора воспользоваться привилегиями в чужом кабинете.}

#Процесс подбора пароля
{120}{}{Система принимает пароль, состоящий только из латинских букв. Остается лишь перебирать массу вариантов.}
{121}{}{Ввести буквы пароля.}
{122}{}{Вы вводите пароль: }
{123}{}{?}
{124}{}{Удалить последнюю букву.}
{125}{}{Очистить значения и начать заново.}
{126}{}{Пароль неверен.}
{127}{}{Пароль принят! Добро пожаловать!}
{128}{}{}
{129}{}{}
{130}{}{}

{150}{}{A}
{151}{}{B}
{152}{}{C}
{153}{}{D}
{154}{}{E}
{155}{}{F}
{156}{}{G}
{157}{}{H}
{158}{}{I}
{159}{}{J}
{160}{}{K}
{161}{}{L}
{162}{}{M}
{163}{}{N}
{164}{}{O}
{165}{}{P}
{166}{}{Q}
{167}{}{R}
{168}{}{S}
{169}{}{T}
{170}{}{U}
{171}{}{V}
{172}{}{W}
{173}{}{X}
{174}{}{Y}
{175}{}{Z}
{176}{}{Еще.}
{177}{}{Завершить ввод пароля.}
{178}{}{В начало алфавита.}
{179}{}{Назад.}
