{100}{}{Вы видите рабочий компьютер.}
{101}{}{Перед вами вполне работоспособный компьютер.}

#Запуск компьютера:
{110}{}{Компьютер не работает из-за нехватки электроэнергии.}
{111}{}{Нет энергии}
{112}{}{Компьютер работает, но не может подключиться к серверу станции, расположенному в отдельном помещении бункера.}
{113}{}{Выход.}
{114}{}{Ваших научных знаний недостаточно для работы со столь своеобразным программным обеспечением.}

#Главное меню:
{115}{}{Вас приветствует информационный канал сети радиовещания "Лавлок".}
{116}{}{Изучить историю трансляций.}
{117}{}{}
{118}{}{Прослушать частоты.}
{119}{}{}
{120}{}{Искать базу данных на служащих станции.}
{121}{}{Искать сведения о назначении станции.}
{122}{}{Завершить сеанс.}
{123}{}{В главное меню.}
{124}{}{Завершить.}

#Данные о служащих:
{126}{}{Список служащих состоит из 32 человек. Состав по подразделениям: 1 ответственный руководитель, 1 клерк, 5 охранников, 20 радистов, 2 технолога, 1 разнорабочий, 1 водитель, 1 повар. На каждого из рабочих формируется отдельное досье и выдается именной магнитный жетон.}
{127}{}{Найти служащего по этой карте доступа.}
{128}{}{Обработка запроса... Ждите... Искомое лицо найдено. Имя: Роджер Смит. Должность: начальник охраны станции. Степень доступа к информационной базе: низкая. Степень доступа на территории станции: высокая.}
{129}{}{Попытаться изменить данные об этом служебном лице.}
{130}{}{Ваших прав недостаточно для изменения базы данных служащих.}
{131}{}{Попытаться взломать систему.}
{132}{}{Неверная контрольная сумма.}
{133}{}{Попытаться еще раз.}
{134}{}{Дьявол! [Выйти]}

{135}{}{Доступ разрешен! Что вы хотите изменить?}
{136}{}{Изменить данные о Роджере Смите.}
{137}{}{Повысить степень доступа к информационной базе.}
{138}{}{Выполнено.}
{139}{}{Вот и чудненько!}

{140}{}{Доступ запрещен. Ваших прав недостаточно для информационного запроса в базе данных.}
{141}{}{}

#Функции станции
{150}{}{Доступ разрешен для: Роджер Смит. Поиск информации... Готово. Радиостанция "Лавлок" предназначена для кодированного радиовещания правительственного и военного назначения. Подразделение носит конспиративный характер. Рабочие, занятые здесь, обязаны подписывать документы о неразглашении какой-либо информации, полученной в ходе приема, обработки и трансляции радиосигнала на станции "Лавлок". Основные текущие функции: получение, обработка и передача радиосигналов между военными базами, генштабом правительства, сетью убежищ и стационарными засекреченными лабораториями в пределах штата Невада.}

#История трансляций
{151}{}{Доступ разрешен для: Роджер Смит. Поиск информации... Готово.}
{152}{}{Искать пункты связи.}
{153}{}{Искать каналы связи.}
{154}{}{}

#Попытка трансляции
{155}{}{Доступ разрешен для: Роджер Смит. Инициализация программы... (Радиосигнал слишком слабый, и, кроме "белого шума", ничего не слышно)}
{156}{}{Посмотреть зону покрытия связи.}
{157}{}{Зона покрытия на текущий момент составляет }
{158}{}{ км. (Видимо, из-за обрушения антенны зона покрытия стала слишком мала, и сигнал еле достигает Города Убежища)}
{159}{}{Прослушать каналы.}
{160}{}{Отослать сообщение.}
{161}{}{На сигнал никто не откликается.}
{162}{}{В эфире ничего, кроме "белого шума", не транслируется.}
{163}{}{Прослушать частоты еще раз.}
{164}{}{(булый шум) ...йте вашему пр... ***шшш*** ...мы всегда рады... ***шшш-тр-шш*** ...но. Когда будет готова новая партия? -- Нам нужно время, очень непросто их обманывать. Дайте нам... ***трык-чик-шшш*** ...будет готово. -- Хорошо, я буду ждать. Следите за смотрителем. Он слишком много знает. -- Мы постараемся, но не забывайте, что *он* наше руководство, а не вы. -- Даже не думайте... ***чик-шшш-трык*** ...есть опасения за начальника охраны. Он о чем-то догадывается и часто бывает у смотрителя наедине. -- Я им займусь. Конец связи.}
{165}{}{Упс... Что это было, черт возьми!}
{166}{}{Вы случайно подслушали разговор двух неизвестных, который может иметь отношение к вашему убежищу.}
{167}{}{Прослушать каналы, обозначенные на бумажке директора АЭС.}
{168}{}{(Список пунктов связи вмещает в себя в основном населенные пункты, где велась тайная прослушка, три военные базы (Сьерра, Хоторн и Зона 51), а также несколько убежищ (8-е, 13-е, 15-е) и закрытых лабораторий. Все эти объекты разбросаны в штате Невада или недалеко от его границ, но выяснить их местоположение вы здесь не сможете, так как связи с ними нет, как и точных координат. По большому счету, радистам и не нужны точные координаты - она работают только с каналами связи.}
{169}{}{Станция имеет заранее определенный спектр каналов связи, за которым поручено следить радистам. Некоторые из них входят в список наиболее приоритетных, включенных в военную программу "}
{170}{}{". Индикаторы их прослушки колеблются близко к нулю, что означает, что они не используются на текущий момент.}
{171}{}{Военная программа? Что это?!}
{172}{}{Система секретного закодированного радиовещания между наиболее важными военными и правительственными ведомствами. Система "}
{173}{}{" была выбрана как эталонная. Она подразумевает сложную схему кодировки сигнала, некоторый фиксированный набор каналов связи, недоступных для гражданского пользования, а также сеть опорных станций по всей стране, способных работать без обслуживающего персонала (то есть автономно) в течение 100 лет и обеспечивать в чрезвычайных ситуациях гарантированную связь между ведомствами.}
{174}{}{Ага, понятно. Хм, название какое-то... знакомое?}
{175}{}{Система "}
{176}{}{" названа так в честь одного из наиболее мощных ядерных испытаний в истории США.}
{177}{}{Ладно, хватит читать всяческое занудство...}

#!!!Устаревшие реплики, не используются:
{200}{}{Вы медленно прокручиваете доступные каналы связи, и вдруг среди "белого шума" возникает чей-то едва различимый голос!}
{201}{}{Прослушать этот канал.}
{202}{}{Вы подкручиваете тумблеры и речь неизвестного становится куда более разборчивой.}
{203}{}{Слушать дальше.}
{204}{}{Сигнал пропадает и вы ничего не можете расслышать.}
{205}{}{... когда он... *шум* ... на нашем радио был впервые... *шум* Элвис, конечно, не мастер, но у него большой потенциал. То, что он исполнил в Тьюпелло, заинтересовало даже... *шум* ... мы будем работать. "The Mississippi - Alabama Fair" - это отличная возможность для многих... *шум* ...бо! WELO Radio не заканчивает обзор событий на ярмарке, скоро мы продолжим репортаж... *слышится какая-то задорная музыкальная пауза*}

#Пароли:
{301}{}{HIROSHIMA}
{302}{}{NAGASAKI}
{303}{}{TRINITY}
{304}{}{CASTLE}
{305}{}{BRAVO}
{306}{}{EASY}
{307}{}{RANGER}
{308}{}{YOKE}
{309}{}{BAKER}
{310}{}{FATMAN}
{311}{}{LITTLEBOY}
