{100}{}{Вы видите водосборник.}
{101}{}{Вы видите здоровенный бак с вонючей водой. Кое-где он сильно проржавел и протекает.}
{102}{}{Вы видите здоровенный бак с водой, в рабочем состоянии.}
{103}{}{Вы не можете осматривать водосборник во время боя!}

#Описание при юзанье или использовании навыков
{110}{}{Это просто большой бак}
{111}{}{Вы видите большой бак для воды. Он почти пуст.}
{112}{}{Как новенький!}
{113}{}{Корпус водосборника восстановлен на радость всему племени.}

#Описание в режиме диалоге
{120}{}{Перед вами неработающий водосборник племени.}
{121}{}{Осмотреть внимательней.}
{122}{}{Попытаться починить.}
{123}{}{Оставить.}

{124}{}{Бак сильно проржавел в нескольких местах и больше не может хранить в себе воду. Для его починки нужно заменить старые листы железа, используя сварочный аппарат и различный металлолом. Но если железо найти вокруг не проблема, то с остальным придется постараться. Возможно, такими вещами обладают техники в более крупных поселениях.}
{125}{}{Бак сильно проржавел в нескольких местах и больше не может хранить в себе воду. Для его починки нужно заменить старые листы железа, используя сварочный аппарат и различный металлолом.}
{126}{}{У вас нет оборудования для ремонта.}
{127}{}{У вас нет металлолома для сварочного процесса и замены некоторых элементов корпуса.}
{128}{}{Вы откровенно неумело начинаете работу и после создания нескольких неудачных "соплей" из сварного металла, понимаете, что вам просто не хватает навыка в ремонте.}
{129}{}{Используя сварочный аппарат и свои умелые руки, вам удалось восстановить поврежденные участки бака. Теперь водосборник может прослужить племени еще лет двадцать.}
{130}{}{Отлично!}
{131}{}{Вы починили водосборник, за что получаете }
{132}{}{ опыта.}
