{100}{}{Служебный компьютер.}
{101}{}{Вы видите обычный служебный компьютер. Единственное, что его отличает от остальных - он до сих пор работает.}
{102}{}{Кажется, вы недостаточно образованны для пользования этим компьютером.}
{103}{}{Не понятно}

#Типовые фразы:
{110}{}{Перед вами служебный компьютер какого-то начальника.}
{111}{}{Выйти.}
{112}{}{Завершить.}
{113}{}{Назад.}
{114}{}{Назад к списку.}
{115}{}{Следующая записка.}

#Список служебок:
{120}{}{Смотреть список служебных записок.}
{121}{}{Смотреть схемы помещений ангара.}

{122}{}{Служебки об ошибке в программе управления турелями.}
{123}{}{Служебки о функционировании силовых полей.}
{124}{}{Служебки о Комплекте SoS.}

#Схемы помещений:
{130}{}{Оказывается, ангар тянется на многие этажи вниз. Некоторые этажи просмотреть нельзя из-за отсутствия прав доступа. Почти каждый этаж - это целая лаборатория или военно-техническая мастерская. Видимо, у местных военных был весьма плотный график работ.}
{131}{}{Смотреть первый подземный этаж.}
{132}{}{Первый подземный этаж также представляет собой большую лабораторию. Кроме этого, там расположен центр управления наружной безопасности (видимо, речь идет о турелях и камерах видеонаблюдения), генератор аварийного освещения этого уровня, центр управления силовыми полями и вентиляция с выходом на открытый воздух. Пробраться ниже первого подземного уровня вам не удастся из-за строгой системы защиты.}

#Служебки:
{140}{}{Служебные записки за последний рабочий месяц были распределены по темам. В основном это обычные расходники и производственные отчеты, но есть несколько любопытных записок.}
{141}{}{Выберите служебную записку для прочтения.}

{142}{}{"Об очередной ошибке в программе управления турелями"}
{143}{}{"Предложение об установке Комплекта SoS"}
{144}{}{"Расписка о получении Комплекта SoS"}
{145}{}{"Отчет об установке Комплекта SoS"}

{146}{}{Уведомление от работника службы безопасности, в котором говорится об очередной ошибке в программе управления турелями. Программа регулярно давала сбои, после которых запускался процесс перезагрузки программы. Это выводило турели из строя на срок от 10 до 20 секунд. Несмотря на попытку исправления программы, программисты не смогли решить эту проблему. По их мнению, виноваты опыты на нижних уровнях ангара, которые создают сильное электромагнитное волнение.}
{147}{}{Суть предложения работника службы безопасности заключается в установке Комплекта SoS взамен программы управления турелями. Это могло бы исправить проблему перезапуска и значительно повысить эффективность защиты ангара. Ответная служебка от руководителя была одобрительной.}
{148}{}{Как значится в расписке, работник службы безопасности получил Комплект SoS. Комплект был привезен из Хоторна после тестов на полигонах и доработан местными инженерами в соответствии с отчетом об этих испытаниях. Службе безопасности дан приказ подключить комплект и проверить его работоспособность.}
{149}{}{Как значится в отчете, установка Комплекта SoS, протестированного в Хоторне, не дала результатов. Комплект не заработал по неустановленным причинам. Установщик Комплекта направил заявление о необходимости еще раз протестировать Комплект, но ответных записок дано не было. Видимо, военные не успели завершить начатое из-за начала Великой Войны. Таким образом ангар оказался без внешней защиты - турели оказались временно отключены.}

{150}{}{"Приказ о плановой проверке силовых полей"}
{151}{}{"Предложение об ужесточении контроля за силовыми полями"}
{152}{}{"Уведомление о начале работ над перепрограммированием силовых полей"}

{153}{}{Приказ о проведении системной плановой проверки силовых полей. О каждом случае нарушения их работы необходимо сообщать начальнику службы безопасности и руководству лабораторий.}
{154}{}{Отдел службы безопасности предлагает ввести уникальные ключ-карты для управления отдельными силовыми полями, т.к. любой работник со средним уровнем допуска может включать или отключать поля, что не соответствует нормам безопасности. Руководством был дан приказ о перепрограммировании силовых полей и выдаче магнитных ключ-карт с высоким уровнем защиты от взлома. Соответствующий приказ был направлен в ремонтно-технический сектор для коррекции работы силовых полей.}
{155}{}{Работник ремонтно-технического сектора сообщает, что силовые поля будут временно отключены в целях перепрограммирования сроком до трех суток.}
{156}{}{"Отчет о результатах перепрограммирования полей"}
{157}{}{Ремонтно-технический сектор сообщает о положительных результатах работы по перепрограммированию силовых полей. Определен список персонала, которому выданы магнитные ключ-карты, а также установлен новый порядок в работе силовых полей.}
{158}{}{"Уведомление о режимности работы силовых полей"}
{159}{}{Ремонтно-технический сектор сообщает о строгом режиме работы силовых полей. В частности сказано, что по причине сильной амортизации оборудования, генерирующего силовые поля, будет происходить периодическое плановое отключение полей на 2 часа. При отсутствии контрольной проверки, которая должна проводиться каждые 60 суток и фиксироваться в управляющем компьютере на первом подземном уровне, силовые поля будут автоматически отключены в противопожарных целях до момента принудительного включения (т.е. до следующей контрольной проверки).}

{160}{}{"Уведомление о военно-курьерской доставке"}
{161}{}{"Акт приема Комплекта SoS"}
{162}{}{"Акт передачи Комплекта SoS службе безопасности"}
{163}{}{Срочное уведомление о прибытии посылки из Хоторна, в которой наличествует Комплект SoS и отчет о проведенных над ним испытаниях. Военный курьер должен лично передать посылку руководству под расписку.}
{164}{}{В акте значится, что военный курьер лично передал посылку с Комплектом и отчетом о его испытаниях руководству. Далее Комплект был отправлен на доработку в техническую лабораторию.}
{165}{}{В акте значится, что Комплект после доработки технической лабораторией был передан службе безопасности ангара для его подключения к системе турелей и прочей охранной автоматике. Так как служебок или актов о последующей передаче этого экземпляра не значится, то можно предположить, что он до сих пор находится в центре управления на нижнем этаже.}

{166}{}{"Отчет об испытаниях Комплекта для 'Благодатного'"}

{167}{}{Оказывается, один из комплектов полностью прошел все испытания и был перевезен в некое убежище для монтажа. Видимо, это убежище было особенно приоритетным, т.к. разработка велась усиленными темпами.}
{168}{}{Смотреть отчет.}
{169}{}{Отчет может содержать массу полезных сведений о конструкции и деталях комплекта, поэтому вы копируете его на голодиск. К сожалению, документ зашифрован, придется написать целую программу для расшифровки. Этим мог бы заняться кто-то из вашего убежища.}
{170}{}{Конец.}
