{100}{}{You see: door console.}
 {101}{}{This console is desighned for the control of vault outer door.}
 {102}{}{Uh... seems like I have no fucking idea how it works...}
 {103}{}{This console is not for non-advanced users like you. You'd better learn a little more before trying it.}
 {104}{}{Nobody answers for your signal.}
 {105}{}{You gain experience points for discovering your fellows, hiding in another vault.}

 {107}{}{Before you a console. You cannot open the vault door with it, but you may try to send a signal inwards.}
 {108}{}{Transmit a signal to the vault.}
 {109}{}{(Leave it)}
 {110}{}{(some noise and interference are heard from the dynamic, and a moment later you hear the voice) Umm... Hello...}
 {111}{}{Did you order a pizza?}
 {112}{}{What... (silence) Um... No.}
 {113}{}{And how about the "Deep throat" movie?}
 {114}{}{No.}
 {115}{}{Haven't you lost your handkerchief by the way?}
 {116}{}{No.}
 {117}{}{What a pity! This one is so beautiful... But maybe you'll tell me what time is it now...}
 {118}{}{No.}
 {119}{}{This is strange... But may you...}
 {120}{}{No.}
 {121}{}{Uh... and yet - ain't this handkerchief yours?}
 {122}{}{No, it's definitely not mine.}
 {123}{}{So why the hell am I standing here?}
 {124}{}{I don't know. But there are you... standing?}
 {125}{}{From the outside, in front of the outer door of your vault, for sure. Isn't it clear indeed?}
 {126}{}{But... but this cannot be! Where are you?! That is... you're calling from another vault?}
 {127}{}{Not exactly so. Yes, I'm actually from another vault. But now I'm standing in front of the yours.}
 {128}{}{Well... but how did you get there?!}
 {129}{}{On foot. That wasn't too difficult, except for different mutants and bandits, filled the wastes. Could you open an outer door to talk with you in the more suitable conditions??}
 {130}{}{(silence) Sorry, but I can't risk. I don't know the situation beyond the vault. What if those, as you said, mutants and bandits enter here? Besides, I'm still not sure that's not a joke.}
 {131}{}{But how about the monitors of your vault? Do you check them at all? In fact you can come to the surface by now! We have already come up and now construct a city of the future!}
 {132}{}{How do you construct it?}
 {133}{}{Using the G.E.C.K., for sure!}
 {134}{}{We probably have to check some instrument readings out. But now we'd better abstain from unsealing and will sit here in vault for some time. Thank you for contact with us, but, excuse me, I have to go to a meeting now..}
 {135}{}{Uh... What!?...}

 {136}{}{(no signal)}
 {137}{}{Craven chiken!}
 {138}{}{(End)}
 {139}{}{Chiken yourself! (no signal again)}
 {140}{}{(End)}