{101{}}{You see The Host}
{101}{}{Before you stands the local boss, who's called The Host}
{102}{}{Alarm! Enemy's in here!}

#talk starts
{108}{}{Nothing. I'm getting outta here}
{109}{}{You again? Nice. What is it this time?}
{110}{}{Stop right there and keep your hands in sight! Why the heck have you stormed in here?}
{111}{}{Got any job for a stranger?}
{112}{}{Ya heard the news? Factory ain't gonna recover from the troubles soon.}
{113}{}{I'm executing the Salt Lake sheriff's will and therefore I ask you to squeal on the criminal Gary Gilmore right fucking now!}
{114}{}{Heard the news? Salt Lake Sheriff's dead!}
{115}{}{Thought it'd be some kind of a hotel. Apparently, it isn't.}

#nuka plant sabotage
{116}{}{The messenger told us about the sabotage. A long-headed fellow, ain't ya? Guess we'll keep your alive this time. *smiles* Here's your pay (gives you 20.000 bucks). And, kiddo, if I were you - I'd lie low for a coupla' weeks in another city.}
{117}{}{Huh, wish all my jobs would be as well-paid as this one.}
{118}{}{Maybe... If we...umm...concur. Ya see me?}
{119}{}{Smells like shady deals. I like it.}
{120}{}{}
{121}{}{Guess you already know about the Nuka-Cola plant in Salt Lake. That is, all residents of our camp live and dream to see somebody sabotagin' the damned thing. You got two options here: either break the conveyor or poison the tanks.}
{122}{}{What's the pay?}
{123}{}{No way, no more dirty business for me!}
{124}{}{}

{125}{}{Don't you worry about the money, we're rollin' in cash here. Let it be... 20 000. I'll even give you the poison from my own stash, still keep a few flasks for a shiny day...}
{126}{}{Why'd you want this plant sabotaged?}
{127}{}{We're going to settle accounts with Salt Lake. Some old affairs, which are none of yor business, lemme tell you. Just get the job done and the cash is yours.}
{128}{}{Fine. I'm ready to get down to work.}
{129}{}{Ain't gonna do no more dirty business. No!}
{130}{}{Excellent! Take the flask, then. You only have to break into the workshop and pour it into tanks, and I don't care how exactly will you do it. It is rumored to have a tunnel underneath leading to the site... It's up for you to choose the means, we'll pay for the result anyway.}
{131}{}{I'll do that.}

#refusing the sabotage quest
{132}{}{What's the matter, wanderer? Haven't got the guts for the job?}
{133}{}{I disapprove any shady business!}
{134}{}{It's your choice. But remember - cash's waiting for ya, fella, and sure as hell it's a good one.}
{135}{}{I need some time to think it over.}

#Gacy line
{136}{}{(Screws up his eye) Don't remember the guy/the gal. Is he/she ours?}
{137}{}{So what, he's here or not?}
{138}{}{Huh. Why the fuck should I give him away?}
{139}{}{You've just confessed. I still advise you to solve the problem in a good and well-mannered way.}
{140}{}{And what you're gonna do?! There is no mommy-sheriff who'd stand up for ya, sucker ...}
{141}{}{I'll just slay you all and bring your heads as a gift to sheriff!}
{142}{}{Nevermind. I'll find him myself.}

{143}{}{I suspected the sheriff has no balls to visit us in person. Send him my words, he's just a moustached pussy!}
{144}{}{Hmm... If you hate him so much, can I consider a counteroffer for an appropriate payment?}
{145}{}{How dare you defame the name of the saint man! [Attack]}
{146}{}{I'll send him the message, and soon we'll return with bloodthirsty friends and heavy fireworks.}

{147}{}{That's impressive! If he kicks the bucket, I'll pay you 20 thousands.}
{148}{}{OK, I'll do that.}
{149}{}{No, I reject your proposal.}
{150}{}{But don't you forget - we had nothing to do with this.}
{151}{}{Got it. Prepare the cash.}
{152}{}{Good news. Gotta give you a credit - not many  would venture to do that even for such money (gives 20.000 bucks). Excellent job.}
{153}{}{Uh, wonder how profitable the killer job gets .}

Внимание! Этот перевод, возможно, ещё не готов.
Его статус: перевод редактируется

Переведено на Нотабеноиде
http://notabenoid.com/book/36834/132683

Переводчики: Pyotr

