#======================================================
#
#      Старые названия локаций из Fallout 1 (не используются?)
#
#======================================================

{100}{}{Desert}
{101}{}{Desert}
{102}{}{Desert}
{103}{}{Убежище 8}
{104}{}{Убежище 8}
{105}{}{Убежище 8}
{106}{}{Ветер Войны}
{107}{}{Ветер Войны}
{108}{}{Ветер Войны}
{109}{}{База 'Сигма'}
{110}{}{База 'Сигма'}
{111}{}{База 'Сигма'}
{112}{}{База 'Сигма'}
{113}{}{База 'Сигма'}
{114}{}{База 'Сигма'}
{115}{}{Vault City}
{116}{}{Vault City}
{117}{}{Vault City}
{118}{}{error:Map Name}
{119}{}{City Ruins}
{120}{}{Coast}
{121}{}{Coast}
{122}{}{Desert}
{123}{}{Desert}
{124}{}{error:Map Name}
{125}{}{error:Map Name}
{126}{}{error:Map Name}
{127}{}{error:Map Name}
{128}{}{error:Map Name}
{129}{}{error:Map Name}
{130}{}{error:Map Name}
{131}{}{error:Map Name}
{132}{}{error:Map Name}
{133}{}{error:Map Name}
{134}{}{error:Map Name}
{135}{}{error:Map Name}
{136}{}{error:Map Name}
{137}{}{Hub}
{138}{}{Hub}
{139}{}{Hub}
{140}{}{Hub}
{141}{}{Hub}
{142}{}{Glow}
{143}{}{Glow}
{144}{}{Boneyard}
{145}{}{Boneyard}
{146}{}{Boneyard}
{147}{}{Cathedral}
{148}{}{Армейская база Хоторн}
{149}{}{Mountains}
{150}{}{Mountains}
{151}{}{Desert}
{152}{}{Desert}
{153}{}{Desert}
{154}{}{Desert}
{155}{}{Brotherhood}
{156}{}{Desert}
{157}{}{Desert}
{158}{}{Mountains}
{159}{}{Mountains}
{160}{}{Viper Camp}
{161}{}{Desert}
{162}{}{Mountains}
{163}{}{Desert}
{164}{}{Mountains}

#======================================================
#
#       Названия уровней карт -- AUTOMAP Names
#
#======================================================

#----------------------------------------
# 00: Desert, DESERT1.MAP
#----------------------------------------
{200}{}{Desert}
{201}{}{}
{202}{}{}
#----------------------------------------
# 01: Desert, DESERT2.MAP
#----------------------------------------
{203}{}{Desert}
{204}{}{}
{205}{}{}
#----------------------------------------
# 02: Desert, DESERT3.MAP
#----------------------------------------
{206}{}{Desert}
{207}{}{}
{208}{}{}
#----------------------------------------
# 03: Vault8 Vault, ARCAVES.MAP
#----------------------------------------
{209}{}{Убежище, уровень 1}
{210}{}{Убежище, уровень 2}
{211}{}{Убежище, уровень 3}
#----------------------------------------
# 04: Vault8 VCity, arvillag.MAP
#----------------------------------------
{212}{}{Город}
{213}{}{Убежище, уровень 1}
{214}{}{}
#----------------------------------------
# 05: Vault8 Desert, arbridge.MAP
#----------------------------------------
{215}{}{Пустошь}
{216}{}{}
{217}{}{}
#----------------------------------------
# 06: Wind Basa, denbus1.MAP
#----------------------------------------
{218}{}{Вокзал}
{219}{}{Гарнизон}
{220}{}{Подвал вокзала}
#----------------------------------------
# 07: Wind Minivault, denbus2.MAP
#----------------------------------------
{221}{}{Вход в убежище}
{222}{}{Разрушенное убежище}
{223}{}{Пещера}
#----------------------------------------
# 08: Wind Desert, denres1.MAP
#----------------------------------------
{224}{}{Разрушенные окраины}
{225}{}{Тайник в подвале}
{226}{}{}
#----------------------------------------
# 09: Klamath Downtown, kladwtwn.MAP
#----------------------------------------
{227}{}{Downtown}
{228}{}{}
{229}{}{}
#----------------------------------------
# 10: Klamath Mall, klamall.MAP
#----------------------------------------
{230}{}{Mall}
{231}{}{}
{232}{}{}
#----------------------------------------
# 11: Klamath Rat Caves, klaratcv.MAP
#----------------------------------------
{233}{}{Rat Caves}
{234}{}{}
{235}{}{}
#----------------------------------------
# 12: SL Provo, klatoxcv.MAP
#----------------------------------------
{236}{}{Центральная площадь}
{237}{}{}
{238}{}{}
#----------------------------------------
# 13: Klamath Trapping Caves, klatrap.MAP
#----------------------------------------
{239}{}{Trapping Grounds}
{240}{}{Trapping Grounds}
{241}{}{Trapping Grounds}
#----------------------------------------
# 14: Vault City Laba, VCtyLab.MAP
#----------------------------------------
{242}{}{Помещения инкубатора}
{243}{}{}
{244}{}{}
#----------------------------------------
# 15: Vault City Courtyard, vctyctyd.MAP
#----------------------------------------
{245}{}{Courtyard}
{246}{}{}
{247}{}{}
#----------------------------------------
# 16: Special Bomba Encounter, rndBomba.MAP
#----------------------------------------
{248}{}{Пустошь}
{249}{}{}
{250}{}{}
#----------------------------------------
# 17: SaltLakeShadow, vctycocl.MAP
#----------------------------------------
{251}{}{Зона поражения}
{252}{}{Семейное убежище}
{253}{}{}
#----------------------------------------
# 18: Shaien Village, modmain.MAP
#----------------------------------------
{254}{}{Стойбище племени}
{255}{}{Каньон}
{256}{}{}
#----------------------------------------
# 19: Shaien Raiders, modinn.MAP
#----------------------------------------
{257}{}{База рейдеров}
{258}{}{База рейдеров, 2й этаж}
{259}{}{База рейдеров, подвал}
#----------------------------------------
# 20: Shaien Pastures, modbrah.MAP
#----------------------------------------
{260}{}{Плантации}
{261}{}{}
{262}{}{}
#----------------------------------------
# 21: Shaien Radio Outside, modgard.MAP
#----------------------------------------
{263}{}{Наземный уровень станции}
{264}{}{Подземный уровень станции}
{265}{}{}
#----------------------------------------
# 22: Black Rock, BlckRck.MAP
#----------------------------------------
{266}{}{Поселение}
{267}{}{Пустыня}
{268}{}{Пустыня}
#----------------------------------------
# 23: Howthorne Cazarmes, MBASE00.MAP
#----------------------------------------
{269}{}{Территория гарнизона}
{270}{}{Территория гарнизона}
{271}{}{Территория гарнизона}
#----------------------------------------
# 24: Baikers: Owl, gstfarm.MAP
#----------------------------------------
{272}{}{Центральная улица}
{273}{}{}
{274}{}{}
#----------------------------------------
# 25: Baikers: Basa, gstcav1.MAP
#----------------------------------------
{275}{}{Радарная станция}
{276}{}{}
{277}{}{}
#----------------------------------------
# 26: Ely Depo, gstcav2.MAP
#----------------------------------------
{278}{}{Железнодорожная развязка}
{279}{}{}
{280}{}{}
#----------------------------------------
# 27: Zona Start, depolv1.MAP
#----------------------------------------
{281}{}{Рулежная дорожка}
{282}{}{}
{283}{}{}
#----------------------------------------
# 28: Zona Kasarmes, depolva.MAP
#----------------------------------------
{284}{}{Personnel}
{285}{}{Personnel}
{286}{}{Вход в ангар}
#----------------------------------------
# 29: Zona Angar, depolvb.MAP
#----------------------------------------
{287}{}{Ангар, верхний уровень}
{288}{}{Ангар, подземный уровень}
{289}{}{Ангар, вентиляция}
#----------------------------------------
# 30: Vault City Vault, vctyvlt.MAP
#----------------------------------------
{290}{}{Vault: Level 1}
{291}{}{Vault: Level 2}
{292}{}{Vault: Level 3}
#----------------------------------------
# 31: Gecko Settlement, gecksetl.MAP
#----------------------------------------
{293}{}{Поселок}
{294}{}{}
{295}{}{}
#----------------------------------------
# 32: Gecko Power Plant, geckpwpl.MAP
#----------------------------------------
{296}{}{Power Plant}
{297}{}{}
{298}{}{}
#----------------------------------------
# 33: Gecko Junkyard, geckjunk.MAP
#----------------------------------------
{299}{}{Окраина}
{300}{}{Крыша гаража}
{301}{}{}
#----------------------------------------
# 34: OldTribeCaves, oldTrbCv.MAP
#----------------------------------------
{302}{}{Вход в логово гекко}
{303}{}{Выход из логова гекко}
{304}{}{Логово гекко}
#----------------------------------------
# 35: Vault8 CityDestr, argarden.MAP
#----------------------------------------
{305}{}{Опаловый прииск}
{306}{}{Катакомбы}
{307}{}{}
#----------------------------------------
# 36: HarrelsonMap, Harelson.MAP
#----------------------------------------
{308}{}{Проход в логово}
{309}{}{Логово Харрельсона}
{310}{}{}
#----------------------------------------
# 37: New Reno Tommigun, newr6.MAP
#----------------------------------------
{311}{}{Здание муниципалитета}
{312}{}{Служебное убежище}
{313}{}{}
#----------------------------------------
# 38: New Reno DeadRunch, newr9.MAP
#----------------------------------------
{314}{}{Заброшенная ферма}
{315}{}{}
{316}{}{}
#----------------------------------------
# 39: BlackRockCave, BlckRck2.MAP
#----------------------------------------
{317}{}{Вход в пещеру}
{318}{}{Выход из пещеры}
{319}{}{Пещера}
#----------------------------------------
# 40: New Reno Teatr, newRTR.MAP
#----------------------------------------
{320}{}{Открытый кинотеатр}
{321}{}{Место проведения кинопоказа}
{322}{}{}
#----------------------------------------
# 41: Special DesertRanger, slShadow.MAP
#----------------------------------------
{323}{}{Лагерь}
{324}{}{Пещера}
{325}{}{}
#----------------------------------------
# 42: Vegas: The Streep, ncr1.MAP
#----------------------------------------
{326}{}{Чистый Город}
{327}{}{Чистый Город, 2й этаж}
{328}{}{Чистый Город, 3й этаж}
#----------------------------------------
# 43: Vegas: HardRock cafe, ncr2.MAP
#----------------------------------------
{329}{}{Кафе 'Хард-Рок'}
{330}{}{}
{331}{}{}
#----------------------------------------
# 44: Vegas: SlaverTown, ncr3.MAP
#----------------------------------------
{332}{}{Офис работорговцев}
{333}{}{Рабский ринг}
{334}{}{}
#----------------------------------------
# 45: Vegas: GhoulTown, ncr4.MAP
#----------------------------------------
{335}{}{Мертвый отель}
{336}{}{Крысиные норы}
{337}{}{}
#----------------------------------------
# 46: Vegas: Sign, ncrent.MAP
#----------------------------------------
{338}{}{Стоянка караванов}
{339}{}{Автостоянка}
{340}{}{Подкоп}
#----------------------------------------
# 47: Vegas: Hoover Dum, ncrex.MAP
#----------------------------------------
{341}{}{Наземный уровень дамбы}
{342}{}{Подземные помещения дамбы}
{343}{}{Электростанция}
#----------------------------------------
# 48: Howthorne: Angar 2, mbaseRA.MAP
#----------------------------------------
{344}{}{Помещения реактора}
{345}{}{}
{346}{}{}
#----------------------------------------
# 49: Howthorne Angar, mbase12.MAP
#----------------------------------------
{347}{}{Армейские склады}
{348}{}{Подземный ангар}
{349}{}{Крыши складов}
#----------------------------------------
# 50: Howthorne Voksal, mbase34.MAP
#----------------------------------------
{350}{}{Железнодорожная станция}
{351}{}{}
{352}{}{}
#----------------------------------------
# 51: Howthorne ElCapitan, mbclose.MAP
#----------------------------------------
{353}{}{Мертвый город}
{354}{}{Мертвый город}
{355}{}{Мертвый город}
#----------------------------------------
# 52: Wind Run DenRun.MAP
#----------------------------------------
{356}{}{Лагерь}
{357}{}{Поселение}
{358}{}{База рейдеров}
#----------------------------------------
# 53: Car Desert out-of-gas, CarDesrt.MAP
#----------------------------------------
{359}{}{Desert}
{360}{}{}
{361}{}{}
#----------------------------------------
# 54: New Reno Silver, newr1.MAP
#----------------------------------------
{362}{}{Отель 'Сильвер'}
{363}{}{Канализация}
{364}{}{Отель 'Сильвер', 2й этаж}
#----------------------------------------
# 55: New Reno Eldorado, newr2.MAP
#----------------------------------------
{365}{}{Казино 'Эльдорадо'}
{366}{}{Казино 'Эльдорадо', 2й этаж}
{367}{}{Ночлежка Патрика}
#----------------------------------------
# 56: New Reno Straiker, newr3.MAP
#----------------------------------------
{368}{}{Стадион}
{369}{}{Эвакуационный бункер}
{370}{}{Стадион, 2й этаж}
#----------------------------------------
# 57: New Reno Depo, newr4.MAP
#----------------------------------------
{371}{}{Железнодорожный вокзал}
{372}{}{Подвал вокзала}
{373}{}{}
#----------------------------------------
# 58: New Reno Oliver, newrcs.MAP
#----------------------------------------
{374}{}{Ранчо}
{375}{}{Место сделки}
{376}{}{}
#----------------------------------------
# 59: PepGaz, newrgo.MAP
#----------------------------------------
{377}{}{Автозаправочная станция}
{378}{}{}
{379}{}{}
#----------------------------------------
# 60: Vegas Stables, newrst.MAP
#----------------------------------------
{380}{}{Охраняемая территория}
{381}{}{}
{382}{}{}
#----------------------------------------
# 61: New Reno Boxing Arena, newrba.MAP
#----------------------------------------
{383}{}{Boxing Arena}
{384}{}{}
{385}{}{}
#----------------------------------------
# 62: Wendover Angar, RedWame.Map
#----------------------------------------
{386}{}{Мастерская}
{387}{}{Крыша ангара}
{388}{}{}
#----------------------------------------
# 63: Wendover BigAngar, RedWan1.MAP
#----------------------------------------
{389}{}{Большой ангар, крыша}
{390}{}{Большой ангар, уровень 1}
{391}{}{Большой ангар, уровень 2}
#----------------------------------------
# 64: Wendover Center, RedDown.MAP
#----------------------------------------
{392}{}{Downtown}
{393}{}{Residential}
{394}{}{Подземные помещения}
#----------------------------------------
# 65: Wendover TrapperTown, RedMEnt.MAP
#----------------------------------------
{395}{}{Ассоциация охотников, стоянка}
{396}{}{Ассоциация охотников, 2й этаж}
{397}{}{Ассоциация охотников, крыша}
#----------------------------------------
# 66: Wendover KislotBog, RedDTun.MAP
#----------------------------------------
{398}{}{Охотничьи угодья}
{399}{}{Охотничьи угодья}
{400}{}{Охотничьи угодья}
#----------------------------------------
# 67: Wendover CityDestroy, redmtun.MAP
#----------------------------------------
{401}{}{Руины Уэндовера}
{402}{}{Руины Уэндовера}
{403}{}{Руины Уэндовера}
#----------------------------------------
# 68: Random Encounter, City 1
{404}{}{City}
{405}{}{City}
{406}{}{City}
# 69: Random Encounter, Cavern 0
{407}{}{Mountain}
{408}{}{Mountain}
{409}{}{Mountain}
# 70: Random Encounter, Cavern 1
{410}{}{Caverns}
{411}{}{Cavern}
{412}{}{Cavern}
# 71: Random Encounter, Cavern 2
{413}{}{Cavern}
{414}{}{Cavern}
{415}{}{Cavern}
# 72: Random Encounter, Cavern 3
{416}{}{Cavern}
{417}{}{Cavern}
{418}{}{Cavern}
# 73: Random Encounter, Cavern 4
{419}{}{Cavern}
{420}{}{Cavern}
{421}{}{Cavern}
# 74: Random Encounter, Mountain 1
{422}{}{Mountain}
{423}{}{Mountain}
{424}{}{Mountain}
# 75: Random Encounter, Mountain 2
{425}{}{Mountain}
{426}{}{Mountain}
{427}{}{Mountain}
# 76: Random Encounter, Coast 1
{428}{}{Coast}
{429}{}{Coast}
{430}{}{Coast}
# 77: Random Encounter, Coast 2
{431}{}{Coast}
{432}{}{Coast}
{433}{}{Coast}
#----------------------------------------
# 78: Ely City, broken1.map
#----------------------------------------
{434}{}{Общежитие, 1й этаж}
{435}{}{Общежитие, 2й этаж}
{436}{}{Общежитие, 3й этаж}
#----------------------------------------
# 79: Ely Altar, broken2.map
#----------------------------------------
{437}{}{Католический храм}
{438}{}{Подземелье храма}
{439}{}{Верхние этажи храма}
#----------------------------------------
# 80: Random Encounter, Cavern 5
{440}{}{Cavern}
{441}{}{Cavern}
{442}{}{Cavern}
# 81: Random Encounter, Desert 4
{443}{}{Desert}
{444}{}{Desert}
{445}{}{Desert}
# 82. Random Encounter, Desert 5
{446}{}{Заброшенный лагерь}
{447}{}{Заброшенный лагерь}
{448}{}{Заброшенный лагерь}
# 83. Random Encounter, Desert 6
{449}{}{Заброшенная ферма}
{450}{}{Заброшенная ферма}
{451}{}{Заброшенная ферма}
# 84. Random Encounter, Desert 7
{452}{}{Кактусовое поле}
{453}{}{Кактусовое поле}
{454}{}{Кактусовое поле}
# 85. Random Encounter, Coast 3
{455}{}{Coast}
{456}{}{Coast}
{457}{}{Coast}
# 86. Random Encounter, Coast 4
{458}{}{Coast}
{459}{}{Coast}
{460}{}{Coast}
# 87. Random Encounter, Coast 5
{461}{}{Трасса}
{462}{}{Трасса}
{463}{}{Трасса}
# 88. Random Encounter, Coast 6
{464}{}{Coast}
{465}{}{Coast}
{466}{}{Coast}
# 89. Random Encounter, Coast 7
{467}{}{Coast}
{468}{}{Coast}
{469}{}{Coast}
# 90. Random Encounter, Coast 8
{470}{}{Трасса}
{471}{}{Трасса}
{472}{}{Трасса}
# 91. Random Encounter, Coast 9
{473}{}{Coast}
{474}{}{Coast}
{475}{}{Coast}
#----------------------------------------
# 92. RejectionCity, Reject.MAP
#----------------------------------------
{476}{}{Поселение рабочих}
{477}{}{Шахтерский лагерь}
{478}{}{Штольня}
#----------------------------------------
# 93. DlzhsDead, DlsDeadMAP
#----------------------------------------
{479}{}{Место нападения.}
{480}{}{}
{481}{}{}
#----------------------------------------
# 94. Broken Hills, Random Encounter, Desert
#----------------------------------------
{482}{}{Desert}
{483}{}{Desert}
{484}{}{Desert}
#----------------------------------------
# 95. Broken Hills, Random Encounter, Mountain
#----------------------------------------
{485}{}{Mountain}
{486}{}{Mountain}
{487}{}{Mountain}
#----------------------------------------
# 96. Special Encounter: Roads, rndwhale.MAP
#----------------------------------------
{488}{}{Место засады}
{489}{}{}
{490}{}{}
#----------------------------------------
# 97. Special Encounter: AnalDen, rndtinwd.MAP
#----------------------------------------
{491}{}{Зловонное отверстие}
{492}{}{Внутри отверстия}
{493}{}{}
#----------------------------------------
# 98. Special Encounter: Mina Pole, rndBHead.MAP
#----------------------------------------
{494}{}{Центр свалки}
{495}{}{}
{496}{}{}
#----------------------------------------
# 99. Special Encounter: Tanker, rndShutl.MAP
#----------------------------------------
{497}{}{Палуба танкера}
{498}{}{Верхний уровень танкера}
{499}{}{Нижний уровень танкера}
#----------------------------------------
# 100. Special Encounter: Unwashed Villagers
#----------------------------------------
{500}{}{Станция}
{501}{}{Подвал станции}
{502}{}{Desert}
#----------------------------------------
# 101. Special Encounter: Black Isle Office, rndbridg.MAP
#----------------------------------------
{503}{}{1й этаж офиса}
{504}{}{2й этаж офиса}
{505}{}{3й этаж офиса}
#----------------------------------------
# 102. Special Encounter: Cafe of Broken Dreams
#----------------------------------------
{506}{}{Кафе "Новые надежды"}
{507}{}{Подвальные помещения}
{508}{}{}
#----------------------------------------
# 103. Special Encounter: Big Egg
#----------------------------------------
{509}{}{Desert}
{510}{}{}
{511}{}{}
#----------------------------------------
# 104. Special Encounter: Bobby
#----------------------------------------
{512}{}{Пустыня}
{513}{}{}
{514}{}{}
#----------------------------------------
# 105. Special Encounter: HomeRoad
#----------------------------------------
{515}{}{Временный лагерь}
{516}{}{}
{517}{}{}
#----------------------------------------
# 106. Special Encounter: Toxic Waste Dump
#----------------------------------------
{518}{}{Пустыня}
{519}{}{}
{520}{}{}
#----------------------------------------
# 107. Special Encounter: Cowboy
#----------------------------------------
{521}{}{Трасса}
{522}{}{}
{523}{}{}
#----------------------------------------
# 108. Special Encounter: Piknik
#----------------------------------------
{524}{}{Оазис}
{525}{}{Пещера}
{526}{}{Пещера}
#----------------------------------------
# 109. Old Rubby, Rubby.MAP
#----------------------------------------
{527}{}{Хижина старика Рабби}
{528}{}{}
{529}{}{}
#----------------------------------------
# 110. Coast Encounter 10
{530}{}{Coastline}
{531}{}{Coastline}
{532}{}{Coastline}
# 111. Coast Encounter 11
{533}{}{Трасса}
{534}{}{Трасса}
{535}{}{Трасса}
# 112. Coast Encounter 12
{536}{}{Кислотные болота}
{537}{}{Кислотные болота}
{538}{}{Кислотные болота}
# 113. Desert Encounter 8
{539}{}{Чернолесье}
{540}{}{Чернолесье}
{541}{}{Чернолесье}
# 114. Desert Encounter 9
{542}{}{Чернолесье}
{543}{}{Чернолесье}
{544}{}{Чернолесье}
# 115. Desert Encounter 10
{545}{}{Чернолесье}
{546}{}{Чернолесье}
{547}{}{Чернолесье}
# 116. Desert Encounter 11
{548}{}{Desert}
{549}{}{Desert}
{550}{}{Desert}
# 117. Desert Encounter 12
{551}{}{Desert}
{552}{}{Desert}
{553}{}{Desert}
# 118. Cavern Encounter 5
{554}{}{Cavern}
{555}{}{Cavern}
{556}{}{Cavern}
# 119. PsiFarm
{557}{}{Центр поселения}
{558}{}{Подвал}
{559}{}{}
# 120. BeattyCity, Beatty.MAP
{560}{}{Центральная улица}
{561}{}{Здание ратуши}
{562}{}{Здание ратуши, 2й этаж}
# 121. Mountain Encounter 3
{563}{}{Mountain}
{564}{}{Mountain}
{565}{}{Mountain}
# 122. Mountain Encounter 4
{566}{}{Mountain}
{567}{}{Mountain}
{568}{}{Mountain}
# 123. Mountain Encounter 5
{569}{}{Mountain}
{570}{}{Mountain}
{571}{}{Mountain}
# 124. Mountain Encounter 6
{572}{}{Mountain}
{573}{}{Mountain}
{574}{}{Mountain}
# 125. City Encounter
{575}{}{Abandoned City}
{576}{}{Ruined City}
{577}{}{Ruined City}
#----------------------------------------
# 126. Vault8 FirstStart, artemple.MAP
#----------------------------------------
{578}{}{2091 год - убежище}
{579}{}{2091 год - внешний мир}
{580}{}{2091 год - внешний мир}
#----------------------------------------
# 127. VaultCityDestroy, ardead.MAP
#----------------------------------------
{581}{}{Опустошенный город}
{582}{}{Опустошенный город}
{583}{}{Опустошенный город}
#----------------------------------------
# 128. Enclave Vault, encdet.MAP
#----------------------------------------
{584}{}{Убежище, уровень 1}
{585}{}{Убежище, уровень 2}
{586}{}{Убежище, уровень 3}
#----------------------------------------
# 129. Enclave Stop, encdock.MAP
#----------------------------------------
{587}{}{Остановка}
{588}{}{Лагерь}
{589}{}{Железнодорожный мост}
#----------------------------------------
# 130. Enclave Angar, encfite.MAP
#----------------------------------------
{590}{}{Ангар}
{591}{}{}
{592}{}{}
#----------------------------------------
# 131. Enclave PostStop, encgd.MAP
#----------------------------------------
{593}{}{Временная остановка}
{594}{}{}
{595}{}{}
#----------------------------------------
# 132. Enclave PresdntHead, encpres.MAP
#----------------------------------------
{596}{}{Убежище, уровень 4}
{597}{}{}
{598}{}{}
#----------------------------------------
# 133. Old Tribe, oldtribe.MAP
#----------------------------------------
{599}{}{Поселение}
{600}{}{Подвал}
{601}{}{Каньон}
#----------------------------------------
# 134. Ely Bunker, enctrp.MAP
#----------------------------------------
{602}{}{Надземный уровень станции}
{603}{}{Подземный уровень станции}
{604}{}{}
#----------------------------------------
# 135. SL Train, sftanker.MAP
#----------------------------------------
{605}{}{Железнодорожное депо}
{606}{}{Подземные коммуникации}
{607}{}{Железнодорожное депо}
#----------------------------------------
# 136. SL Ogden, sfdock.MAP
#----------------------------------------
{608}{}{Площадь возрождения}
{609}{}{Семейное убежище}
{610}{}{}
#----------------------------------------
# 137. SL Center, sfchina.MAP
#----------------------------------------
{611}{}{Бизнес-центр}
{612}{}{}
{613}{}{}
#----------------------------------------
# 138. SL Anal, SFSHUTL1.MAP
#----------------------------------------
{614}{}{Каньон}
{615}{}{Канализация}
{616}{}{Канализация}
#----------------------------------------
# 139. SL Mormones, SFSHUTL2.MAP
#----------------------------------------
{617}{}{Храм}
{618}{}{Крыша храма}
{619}{}{Подземелье храма}
#----------------------------------------
# 140. SL Artesian, sfelronb.MAP
#----------------------------------------
{620}{}{Трущобы}
{621}{}{Артезианская башня}
{622}{}{Семейное убежище}
#----------------------------------------
# 141. City Encounter 3
{623}{}{Destroyed City}
{624}{}{Destroyed City}
{625}{}{Destroyed City}
# 142. City Encounter 4
{626}{}{Destroyed City}
{627}{}{Destroyed City}
{628}{}{Destroyed City}
# 143. City Encounter 5
{629}{}{Destroyed City}
{630}{}{Destroyed City}
{631}{}{Destroyed City}
# 144. City Encounter 6
{632}{}{Destroyed City}
{633}{}{Destroyed City}
{634}{}{Destroyed City}
# 145. City Encounter 7
{635}{}{Destroyed City}
{636}{}{Destroyed City}
{637}{}{Destroyed City}
# 146. City Encounter 8
{638}{}{Destroyed City}
{639}{}{Destroyed City}
{640}{}{Destroyed City}
#----------------------------------------
# 147. New Reno Raider, newrvb.MAP
#----------------------------------------
{641}{}{Руины города}
{642}{}{}
{643}{}{}
#----------------------------------------
# 148. SL NukeCola, sfchina2.MAP
#----------------------------------------
{644}{}{Завод ядер-колы}
{645}{}{Завод ядер-колы, 2й этаж}
{646}{}{Завод ядер-колы, подвал}
#----------------------------------------
# 149. In Game Movie, gammovie.MAP
#----------------------------------------
{647}{}{Desert}
{648}{}{Desert}
{649}{}{Desert}
#----------------------------------------
# 150. RndBess, rndbess.MAP
#----------------------------------------
{650}{}{Временный лагерь}
{651}{}{Desert}
{652}{}{Desert}

#==========================================================
#
#	Названия локаций на карте мира и в мини-карте
#       Нумерация: 1500+Area. Номер area см. в CITY.TXT разделы вида [Area ??]
#
#==========================================================

{1500}{}{Город Убежища}
{1501}{}{Ветер Войны}
{1502}{}{База 'Сигма'}
{1503}{}{Лавлок}
{1504}{}{Бэйди}
{1505}{}{АЭС "Посейдон Ойл"}
{1506}{}{Эйли}
{1507}{}{New Reno}
{1508}{}{Зона 51}
{1509}{}{Бриджпорт}
{1510}{}{Лас-Вегас}
{1511}{}{Район Прово}
{1512}{}{Армейская база 'Хоторн'}
{1513}{}{Уэндовер}
{1514}{}{Солт-Лейк-Сити}
{1515}{}{Старик Рабби}
{1516}{}{Правительственное убежище}
{1517}{}{Джерлак}
{1518}{}{Уран-Сити}
{1519}{}{Питомник}
{1520}{}{Баттл-Маунтин}
{1521}{}{Car Outta Power}
{1522}{}{Город Убежища}
{1523}{}{Дорожный затор}
{1524}{}{Операция Ветра Войны}
{1525}{}{Блэк-Рок}
{1526}{}{Desert}
{1527}{}{Mountain}
{1528}{}{Ruined City}
{1529}{}{Coast}
{1530}{}{Заправка}
{1531}{}{Перекресток}
{1532}{}{Большое отверстие}
{1533}{}{Свалка покрышек}
{1534}{}{Танкер в пустыне}
{1535}{}{Аномальное место}
{1536}{}{Затерянный офис}
{1537}{}{Кафе 'Новые надежды'}
{1538}{}{Гигантское яйцо}
{1539}{}{Хижина Бобби}
{1540}{}{Дом на колесах}
{1541}{}{'Далше'}
{1542}{}{Заброшенный пост рейнджеров}
{1543}{}{Место для пикника}
{1544}{}{Caravan}
{1545}{}{"Дорогой Джон"}
{1546}{}{Харрельсон}
{1547}{}{Random Encounter}
{1548}{}{Разбитый дилижанс}
{1549}{}{Автомобиль}
{1550}{}{Окрестности Убежища 8}
{1551}{}{Нью-Рино (2)}
{1552}{}{Вспомнить все}