#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used in PIPBOY.C
#
# (These MUST match "text message" enumeration on the top of PIPBOY.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

#
# Special holiday dates
#
{100}{}{Happy New Year's Day!}      # New years
{101}{}{Happy Valentine's Day!}     # April fools
{102}{}{Happy All Fool's Day!}      # April fools
{103}{}{Happy Ship Day!}            # Shipping day!
{104}{}{Happy Independence Day!}    # Independence day
{105}{}{Happy Halloween!}           # Halloween
{106}{}{Happy Thanksgiving Day!}    # Thanksgiving
{107}{}{Merry Christmas!}           # X-mas

#
# System messages
#
{200}{}{MORE}
{201}{}{BACK}
{202}{}{STATUS}
{203}{}{No current tasks.}
{204}{}{CLUES}  # clues gone
{205}{}{AUTOMAPS}
{206}{}{VIDEO ARCHIVES}
{207}{}{DATA}
{208}{}{}
{209}{}{}
{210}{}{Status}
{211}{}{DATA}
{212}{}{of}
{213}{}{Page}
{214}{}{DONE}
{215}{}{You cannot rest at this location!}

#
# Alarm clock
#
{300}{}{ALARM CLOCK}
{301}{}{Hit Points}
{302}{}{Rest for ten minutes}
{303}{}{Rest for thirty minutes}
{304}{}{Rest for an hour}
{305}{}{Rest for two hours}
{306}{}{Rest for three hours}
{307}{}{Rest for four hours}
{308}{}{Rest for five hours}
{309}{}{Rest for six hours}
{310}{}{Rest until morning (0800)}
{311}{}{Rest until noon (1200)}
{312}{}{Rest until evening (1800)}
{313}{}{Rest until midnight (0000)}
{314}{}{Rest until healed}
{315}{}{Rest until party is healed}

#
# Holodisk titles
#
{400}{}{Поручение склада}
{401}{}{Предварительный отчет}
{402}{}{Список вещей}
{403}{}{-пусто-}
{404}{}{Отчет о дезертирах}
{405}{}{-пусто-}
{406}{}{Записи из дневника}
{407}{}{Медицинский отчет}
{408}{}{Исход}
{409}{}{Документы радиостанции}
{410}{}{Сообщение Джея}
{411}{}{История Ветра Войны}
{412}{}{Анализ карты памяти}
{413}{}{Заметка о Великом Луи}
{414}{}{Записи замурованного}
{415}{}{Записи офицера}
{416}{}{-пусто-}
{417}{}{-пусто-}
{418}{}{Уголовное дело 4783}
{419}{}{Реклама дилижансов}
{420}{}{-пусто-}

#
# Movie archive titles
# Order must match the list (see gmovie.h)
#
{500}{}{Предупреждение}
{501}{}{Intro}
{502}{}{2091 год}
{503}{}{2140 год}
{504}{}{Изгнание}
{505}{}{Впервые на поверхности}
{506}{}{Starting the Car}
{507}{}{Панорама Хоторна}
{508}{}{-пусто-}
{509}{}{Отправка на поезде}
{510}{}{-пусто-}
{511}{}{Возвращение в Солт-Лейк}
{512}{}{Напоминание 1}
{513}{}{Напоминание 2}
{514}{}{Напоминание 3}
{515}{}{Сигнал бедствия}
{516}{}{Credits}

#
# Things for the Mac version to speak
#
#
{600}{}{Status}
{601}{}{Clues}  # Clues gone
{602}{}{Automaps}
{603}{}{Archives}
{604}{}{Alarm Clock}
{605}{}{Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo}
{606}{}{Welcome to the Rob Co Pipboy 2009.}
{607}{}{So long.}
{608}{}{Wake up.}


#
# Holodisk text
#

# Спецзадание склада ГУ - список
# GVAR_VC_SUPERBONUS
{1000}{}{Складу убежища 8 требуется найти следующие}
{1001}{}{предметы технологий Волт-Тек:}
{1002}{}{}
{1003}{}{  * Ионный синтезатор}
{1004}{}{  * Газоанализатор}
{1005}{}{  * Импульсный модулятор}
{1006}{}{  * Регулятор давления}
{1007}{}{  * Чип синтезатора одежды}
{1008}{}{}
{1009}{}{**END-DISK**}

# Убежище 8: Отчет испектора
# GVAR_HOLODISK_COUNTRY_MSG (GVAR_HOLODISK_MB_OUTSIDE)
{2000}{}{Черновик отчета о поимке преступника}
{2001}{}{}
{2002}{}{Автор Малкольм Риверз, помощник шерифа}
{2003}{}{}
{2004}{}{}
{2005}{}{Я стал писать этот отчет на случай, если с нами}
{2006}{}{что-нибудь случится. Если вы обнаружите эти}
{2007}{}{записи, отправьте их шерифу округа Уошо,}
{2008}{}{штат Невада.}
{2009}{}{}
{2010}{}{Запись 1}
{2011}{}{}
{2012}{}{Илай Горбински - подлый сукин сын. Он убежал}
{2013}{}{от правосудия после убийства афроамериканца}
{2014}{}{на улицах Рино. Суд отпустил его под подписку}
{2015}{}{о невыезде. Я не могу просто так оставить этот акт}
{2016}{}{откровенного расизма! Поэтому я стал следить}
{2017}{}{за преступником, и не зря. Он действительно}
{2018}{}{уехал из города в северном направлении,}
{2019}{}{игнорируя приказ суда. Почуяв слежку, Горбински}
{2020}{}{попытался скрыться, но я долго не выпускал его}
{2021}{}{из поля зрения, пока мы ехали по автомагистрали.}
{2022}{}{В нескольких милях от АЭС "Посейдон Ойл"}
{2023}{}{мы сравнялись, и преступник попытался сбить}
{2024}{}{мою машину. Случилась автокатастрофа, оба транспорта}
{2025}{}{разбиты вдребезги. Горбински получил удар}
{2026}{}{по голове и потерял сознание, я отделался лишь}
{2027}{}{ушибами (повезло!). Пока ублюдок приходил в себя,}
{2028}{}{я успел вызвать по рации подкрепление.}
{2029}{}{}
{2030}{}{Нам прислали эвакуатор из АЭС, тот отвез нас}
{2031}{}{к станции. Чтобы Горбински опять не вытворил}
{2032}{}{чего-нибудь, я сковал нас наручниками}
{2033}{}{и отобрал у него все вещи. На станции нам}
{2034}{}{не могли помочь, там была суматоха. Такое}
{2035}{}{ощущение, что АЭС спешно консервируется, а люди}
{2036}{}{готовятся к переселению. Но мне некогда было}
{2037}{}{разбираться. Подкрепление так и не выслали.}
{2038}{}{Пришлось утром отправиться на рейсовом автобусе}
{2039}{}{вместе с преступником в Рино. Водитель сделал}
{2040}{}{остановку в опаловом шахтерском поселке семьи}
{2041}{}{Вилсонов. Эта добрая и отзывчивая семейная чета,}
{2042}{}{добывающая опал в живописной долине, приняла}
{2043}{}{нас довольно радушно.}
{2044}{}{}
{2045}{}{Примерно в 12:30 по местному времени Илай}
{2046}{}{Горбински сбежал от меня. Будучи прикованным}
{2047}{}{наручниками к батарее, пока я ходил в туалет и}
{2048}{}{магазин, он нашел способ взломать замок куском}
{2049}{}{проволоки. Когда я выбежал на улицу, он уже}
{2050}{}{мчался на угнанном автобусе в южном направлении.}
{2051}{}{Причем он уехал вместе с пассажирами, которые}
{2052}{}{даже не подозревали об этом. Водителя позже}
{2053}{}{нашли мертвым в туалете.}
{2054}{}{}
{2055}{}{Рации здесь нет, а следующий автобус приедет}
{2056}{}{только завтра в обед. Местный грузовик находится}
{2057}{}{в состоянии ремонта, и в лучшем случае его}
{2058}{}{починят завтра утром. Остается надеяться, что}
{2059}{}{за это время Горбински не успеет создать проблем.}
{2060}{}{}
{2061}{}{Но, так или иначе, я в любом случае добьюсь}
{2062}{}{справедливости! Преступники не могут гулять}
{2063}{}{на свободе. Даже в такой глуши, как наш тихий округ.}
{2064}{}{}
{2065}{}{Запись 2}
{2066}{}{}
{2067}{}{Я ждал рейсовый автобус до 16:00. Поняв, что он}
{2068}{}{уже не приедет, стал наседать на механика,}
{2069}{}{чтобы тот починил местный грузовик. Но механик}
{2070}{}{был сильно пьян. Я вновь вынужден проторчать}
{2071}{}{здесь до завтра, пока чертов Горбински безнаказанно}
{2072}{}{разъезжает на свободе! Это будет мучительное}
{2073}{}{ожидание, ведь я *должен* его остановить,}
{2074}{}{а сижу здесь, скованный какими-то техническими}
{2075}{}{проблемами. Неужели я единственный, кого здесь}
{2076}{}{волнует правосудие?..}
{2077}{}{}
{2078}{}{Мы завернули тело водителя автобуса в простынь}
{2079}{}{и положили в прохладном месте в ангаре. Ублюдок!}
{2080}{}{Когда я доберусь до Горбински, его ни один судья}
{2081}{}{уже не спасет!}
{2082}{}{}
{2083}{}{Запись 3}
{2084}{}{}
{2085}{}{Сегодня был тяжелый день...}
{2086}{}{}
{2087}{}{Рейсовый автобус вновь не приехал. В обед я}
{2088}{}{насильно заставил механика починить мотор}
{2089}{}{в грузовике. Мы поехали в сторону Рино,}
{2090}{}{но по пути, в соседней долине, обнаружили тот}
{2091}{}{самый автобус, на котором Горбински скрылся.}
{2092}{}{Он был пуст. И почему-то повернут в сторону поселка.}
{2093}{}{Или Горбински вернулся, или вообще не уезжал!}
{2094}{}{Я попытался связаться по рации в автобусе}
{2095}{}{с патрульными или хотя бы с автобусным центром}
{2096}{}{в Рино, но в ответ - только "белый шум".}
{2097}{}{Они там что, все передохли, черт возьми?!}
{2098}{}{}
{2099}{}{Мы вернулись в поселок, чтобы предупредить}
{2100}{}{людей об опасности, но было поздно - один из}
{2101}{}{рабочих погиб в столовой насильственной смертью.}
{2102}{}{Такого и врагу не пожелаешь.}
{2103}{}{}
{2104}{}{Я решил остаться, чтобы помочь местным жителям.}
{2105}{}{Иначе на кой черт я ношу знак помощника шерифа, а?}
{2106}{}{Именно здесь нужна жесткая рука Фемиды, которой}
{2107}{}{так не хватает Америке последние годы...}
{2108}{}{И я не зря остался.}
{2109}{}{Поздно вечером Вилсоны обнаружили отрезанную}
{2110}{}{голову второго работника в стиральной машине.}
{2111}{}{}
{2112}{}{Этот сукин сын определенно бродит где-то поблизости!}
{2113}{}{Я обязан его остановить, пока не появились}
{2114}{}{новые жертвы...}
{2115}{}{}
{2116}{}{Запись 4}
{2117}{}{}
{2118}{}{... Почти не спал. Ночью загорелся грузовик. Механик}
{2119}{}{был внутри. Перед этим его видели пьяным, и Вилсоны}
{2120}{}{решили, что он сам спровоцировал пожар в машине.}
{2121}{}{Но я-то знаю, чьих рук это дело!}
{2122}{}{}
{2123}{}{Теперь мы остались без транспорта. Совсем.}
{2124}{}{Тех же, кто мешал моему расследованию, я запер}
{2125}{}{в столовой. Пусть подумают, пока я не разберусь}
{2126}{}{с этим сукиным сыном...}
{2127}{}{}
{2128}{}{Запись 5}
{2129}{}{}
{2130}{}{Я остался один.}
{2131}{}{Все это время с моей последней записи Горбински тихо}
{2132}{}{и хитро уносил по одной жизни каждый день...}
{2133}{}{Ублюдок! Что б ты сдох!!! ...}
{2134}{}{Теперь никто, кроме меня, не сможет остановить его}
{2135}{}{и восстановить справедливость.}
{2136}{}{Если бы... ЕСЛИ БЫ этот судья посадил его }
{2137}{}{на электрический стул...}
{2138}{}{ЕСЛИ БЫ патрульные вовремя среагировали на мои}
{2139}{}{позывные...}
{2140}{}{Но что происходит в мире, черт возьми?!}
{2141}{}{Почему нас никто не ищет?}
{2142}{}{Почему до сих пор не приехал автобус?}
{2143}{}{Неужели случилась война?..}
{2144}{}{}
{2145}{}{Я собираюсь остановить ублюдка *любым способом*.}
{2146}{}{И пусть меня лишат звания, но я так просто}
{2147}{}{это не оставлю.}
{2148}{}{**END-DISK**}

# Список вещей
# GVAR_PIPBOY_LIST_CARAVAN_ITEMS
{3000}{}{Список вещей, которые заказал караванщик.}
{3001}{}{}
{3002}{}{  * Кувалда}
{3003}{}{  * Шкура гекко (любого)}
{3004}{}{  * Лопата}
{3005}{}{  * Аптечка}
{3006}{}{  * Фальшфейер (3 шт.)}
{3007}{}{  * Веревка}
{3008}{}{  * Пустая фляжка (2 шт.)}
{3009}{}{  * Металлолом}
{3010}{}{  * Резиновые сапоги}
{3011}{}{  * Гаечный ключ}
{3012}{}{  * Оружейные детали}
{3013}{}{}
{3014}{}{Нужно поторопиться с их сбором, так как}
{3015}{}{через три дня караван отправится в путь.}
{3016}{}{**END-DISK**}

# Свободное место
{4000}{}{--ПУСТО--}
{4001}{}{**END-DISK**}

# Хоторн: Отчет о дезертирах
# GVAR_HOWTHORNE_DSK_DESERTIRES (GVAR_HOLODISK_MB_LEVEL_3)
{5000}{}{}
{5001}{}{В этом документе содержится отчет о случае}
{5002}{}{массового дезертирства.}
{5003}{}{}
{5004}{}{Как установила комиссия, группа военнослужащих}
{5005}{}{захватила технику и оружие со складов Хоторна,}
{5006}{}{после чего с боем вырвалась за периметр базы.}
{5007}{}{Причиной, толкнувшей военных на преступление,}
{5008}{}{послужили панические настроения, вызванные якобы}
{5009}{}{рассекреченной информацией о готовящейся ядерной}
{5010}{}{войне.}
{5011}{}{}
{5012}{}{Дезертиры забрали с собой семьи и личные вещи.}
{5013}{}{Установлено, что группа укрылась в убежище}
{5014}{}{под кодовым названием "Ветер Войны".}
{5015}{}{Это тестовое убежище расположено вблизи города}
{5016}{}{Парамп. Оно было предназначено для тестирования}
{5017}{}{стройматериалов, использовавшихся в проекте сети}
{5018}{}{убежищ Волт-Тек, после чего передано в ведомство}
{5019}{}{военной базы для учебных целей. Координаты}
{5020}{}{убежища прилагаются.}
{5021}{}{}
{5022}{}{Отчет датирован 22 октября 2077 года.}
{5023}{}{**END-DISK**}

# Свободное место
{6000}{}{--ПУСТО--}
{6001}{}{**END-DISK**}

# Правит. убежище: Записи из дневника Степлтона
# GVAR_HOLODISK_ENCLAV_DIARY (GVAR_HOLODISK_SIERRA_EXP_LOG)
{7000}{}{Записи из дневника мистера Степлтона}
{7001}{}{}
{7002}{}{(Записи проводились с переменной регулярностью}
{7003}{}{на протяжении нескольких лет пребывания в убежище.}
{7004}{}{Вы записали только самые интересные фрагменты.)}
{7005}{}{}
{7006}{}{**END-PAR**}
{7007}{}{9 июля, 2077 год}
{7008}{}{Двери убежища закрыли. Убежище запечатано. У людей }
{7009}{}{возникают смешанные чувства. Некоторые явно склонны }
{7010}{}{к клаустрофобии и в припадках носятся по коридорам. }
{7011}{}{Наш доктор все время завален работой с такими }
{7012}{}{нервными придурками. Вице-президент после нервного }
{7013}{}{срыва вышел из столовой в мокрых штанах и потом }
{7014}{}{долго всем пытался доказать, что это пролитая }
{7015}{}{ядер-кола. Кстати, кола стала разъедать ткань}
{7016}{}{его комбинезона. Интересно, из чего делают колу?}
{7017}{}{}
{7018}{}{15 июля, 2077 год}
{7019}{}{Все помалу успокоились. Президент распорядился}
{7020}{}{включить шум ручья в центре газончика напротив}
{7021}{}{столовой. Теперь там хорошо и мирно.}
{7022}{}{}
{7023}{}{10 августа, 2077 год}
{7024}{}{Все прекрасно обжились в своих номерах и не хотят}
{7025}{}{оттуда выходить. Всем стало на все плевать, занимаются}
{7026}{}{только своими делами. За исключением охраны - этим}
{7027}{}{беднягам приходится каждый день делать зарядку и}
{7028}{}{упражняться в тренажерном зале. Говорят, рядовой}
{7029}{}{Мак-Кинли отказался подниматься с постели на}
{7030}{}{зарядку, и за это сержант урезал ему выдачу}
{7031}{}{ядер-колы. Жестокое наказание.}
{7032}{}{}
{7033}{}{10 сент, 2077 год. От ядер-колы у людей начинается}
{7034}{}{отрыжка и красятся языки, но никто не пытается}
{7035}{}{даже волноваться по этому поводу, потому что всем}
{7036}{}{это только по кайфу. В убежище начались}
{7037}{}{соревнования по самой громкой отрыжке.}
{7038}{}{Пока лидирует рядовой Мак-Кинли.}
{7039}{}{}
{7040}{}{12 сент, 2077. Хотя рядовой Мак-Кинли немного}
{7041}{}{отстал в соревнованиях, но все говорят, что его}
{7042}{}{отрыжка если не самая громкая, то самая звучная.}
{7043}{}{Среди населения набирается команда музыкантов,}
{7044}{}{которая будет играть и петь, используя только}
{7045}{}{отрыжку самой разной частоты. Думаю, я прекрасно}
{7046}{}{подойду для тенора.}
{7047}{}{}
{7048}{}{18 сент, 2077. Вот ведь гадство! Сегодня сделали}
{7049}{}{общее предупреждение, что впредь концерты}
{7050}{}{отрыжкопевцов запрещены, так как при таких темпах}
{7051}{}{потребления ядер-колы ее скоро просто не останется}
{7052}{}{в убежище. А жаль. Ведь первые концерты}
{7053}{}{отрыжкопения прошли успешно. Как же мы теперь}
{7054}{}{будем без их незабываемых композиций...}
{7055}{}{}
{7056}{}{20 сент, 2077. Рядовой Мак-Кинли придумал новое}
{7057}{}{соревнование! Плевки на дальнее расстояние! Черт,}
{7058}{}{это классная идея! Надеюсь, хотя бы это нам не}
{7059}{}{запретят!}
{7060}{}{}
{7061}{}{21 сент, 2077. Рядовой Мак-Кинли стал жертвой}
{7062}{}{собственной идеи. При попытке плевка}
{7063}{}{колпачком авторучки колпачок провалился в}
{7064}{}{трахею рядового, и тот задохнулся. Доктор}
{7065}{}{говорит, что случай уникален, и никогда в его}
{7066}{}{практике такого не случалось.}
{7067}{}{Вытаскивать колпачок доктор отказался.}
{7068}{}{Бедный колпа... То есть бедный рядовой.}
{7069}{}{}
{7070}{}{27 сент, 2077. Без рядового Мак-Кинли стало скучно.}
{7071}{}{Поэтому смотритель приказал устраивать в столовой}
{7072}{}{вечеринки по субботам. Клево. Надеюсь, будут}
{7073}{}{выдавать ядер-колу.}
{7074}{}{}
{7075}{}{30 сент, 2077. На вечеринке сержант перебрал}
{7076}{}{ядер-колы и набил морду вице-президенту. Причиной}
{7077}{}{оказался спор о том, чья отрыжка была круче -}
{7078}{}{вице-президент говорил, что его более звучная,}
{7079}{}{а сержант утверждал, что свою отрыжку отработал}
{7080}{}{лучше всех. Завязалась драка.}
{7081}{}{}
{7082}{}{31 сент, 2077. Сержант и вице-президент}
{7083}{}{сидели в столовой за столиком, как старые кореша.}
{7084}{}{Наверное, так и есть.}
{7085}{}{**END-PAR**}
{7086}{}{*********}
{7087}{}{}
{7088}{}{5 авг, 2078. В убежище ходят слухи, что война так и}
{7089}{}{не произошла. Конечно, рядовым жителям этого не дано}
{7090}{}{знать, но если это так, то что же это получается - }
{7091}{}{мы все это время занимались безделием, когда снаружи}
{7092}{}{мир жил как раньше?! Надо созвать совет, чтобы}
{7093}{}{смотритель изложил нам всю ситуацию, как есть.}
{7094}{}{}
{7095}{}{13 авг, 2078. Смотритель вдруг неожиданно сообщил,}
{7096}{}{что синтезатор ядер-колы в убежище испортился, и}
{7097}{}{теперь мы остались без любимого развлечения.}
{7098}{}{Народ в панике.}
{7099}{}{}
{7100}{}{15 авг, 2078. Народу надоело ждать, и все стали}
{7101}{}{писать петицию президенту, чтобы синтезатор}
{7102}{}{ядер-колы скорее починили.}
{7103}{}{}
{7104}{}{20 авг, 2078. От нечего делать жители стали писать}
{7105}{}{петиции на имя президента. Я тоже написал, чтобы}
{7106}{}{мне покрасили стены в голубой цвет, а сосед пожелал}
{7107}{}{веревку и кусок мыла.}
{7108}{}{Интересно, зачем они ему нужны?}
{7109}{}{}
{7110}{}{27 авг, 2078. Вот черт! Почему просьбу моего}
{7111}{}{соседа выполнили, а мою нет?! Я разочарован!}
{7112}{}{И куда только смотрят эти чертовы бюрократы в}
{7113}{}{правительственном кабинете!}
{7114}{}{Может быть, написать петицию еще раз?}
{7115}{}{}
{7116}{}{**END-PAR**}
{7117}{}{}
{7118}{}{*********}
{7119}{}{}
{7120}{}{5 февр, 2086. Ситуация просто хреновая! Убежище}
{7121}{}{разделилось на два лагеря. Одни защищают}
{7122}{}{сержанта с его политикой "оставаться на месте",}
{7123}{}{а другие поддерживают вице-президента, который}
{7124}{}{призывает всех покинуть убежище, чтобы помочь}
{7125}{}{нуждающимся после войны во внешнем мире.}
{7126}{}{Я не думаю, что стоит делиться своими технологиями}
{7127}{}{ради всяких радиоактивных зомби. Пока только}
{7128}{}{смотритель и сам президент остаются на стороне и}
{7129}{}{умалчивают свое мнение.}
{7130}{}{}
{7131}{}{12 марта, 2086. Стычки между группировками стали}
{7132}{}{настолько острыми, что скоро располовинят столовую!}
{7133}{}{}
{7134}{}{13 марта, 2086. Все. Это конец. Сегодня в столовой}
{7135}{}{после массового распития ядер-колы разразилась целая}
{7136}{}{битва между группировками. Дрались врукопашную и}
{7137}{}{стульями. Почему люди такие дикие? Может, в}
{7138}{}{ядер-колу добавляют что-то, повышающее агрессию?}
{7139}{}{}
{7140}{}{14 марта, 2086. Группировки, мать их!}
{7141}{}{Они опять напились и устроили драку!}
{7142}{}{Сержант заехал стулом по башке самому президенту!}
{7143}{}{А та и отвалилась.}
{7144}{}{Что же теперь будет!?}
{7145}{}{}
{7146}{}{15 марта, 2086. Группировки заключили временное}
{7147}{}{перемирие, чтобы решить проблему с отсутствием}
{7148}{}{президента. Точнее, эту проблему теперь решают}
{7149}{}{смотритель и доктор. Они решили подсоединить}
{7150}{}{оторванную голову к проводам и попытаться ее}
{7151}{}{оживить. Черт знает, кому это нужно, но задумка}
{7152}{}{любопытная!}
{7153}{}{}
{7154}{}{20 марта, 2086. Кто бы мог подумать?! Сегодня}
{7155}{}{состоялся торжественный запуск головы президента.}
{7156}{}{Первые слова, которые произнесла голова при}
{7157}{}{включении тумблеров: "Мать вашу, придурки! Где моя}
{7158}{}{кукла?!" Куклу отыскали в кабинете президента,}
{7159}{}{и после этого голова успокоилась. Все ожидали}
{7160}{}{другой реакции.}
{7161}{}{}
{7162}{}{**END-PAR**}
{7163}{}{1 апр, 2087. Голова стала невыносима!}
{7164}{}{Оказалось, что она все это время подчиняла себе}
{7165}{}{компьютерные системы. Теперь из репродуктора}
{7166}{}{доносятся зловещие шуточки, а автомат с пончиками}
{7167}{}{стал печь пончики в виде виселичной петли.}
{7168}{}{Пора что-то делать! Нам страшно выходить из}
{7169}{}{собственной комнаты!}
{7170}{}{}
{7171}{}{3 июля, 2087. Ну все! Эта уродина без волос и тела}
{7172}{}{достала даже смотрителя! Завтра состоится открытый}
{7173}{}{совет, что делать с этой оторванной башкой.}
{7174}{}{}
{7175}{}{4 июля, 2087. Совет не пришел к единому выводу.}
{7176}{}{Оказалось, что отключить голову от проводов мы}
{7177}{}{не можем. Голова уже настолько сильно вживилась} 
{7178}{}{в сеть убежища, что стала контролировать даже}
{7179}{}{подачу электроэнергии. В общем, я не знаю,} 
{7180}{}{как долго, но эта проблема останется открытой.}
{7181}{}{}
{7182}{}{10 янв, 2090. Последние годы мы сидели по своим}
{7183}{}{местам и почти не общались. Дурацкие шуточки головы} 
{7184}{}{сменились прямыми угрозами. Голова жалуется, что}
{7185}{}{ее не слушают и за ней не ухаживают, не чешут ей} 
{7186}{}{пяток и т.д. Стало опасно. Голова в состоянии}
{7187}{}{нервного срыва, как и все мы. Говорят, она даже} 
{7188}{}{управляет охранными турелями. Правда ли это?}
{7189}{}{**END-PAR**}
{7190}{}{15 янв, 2090. Мы уходим.}
{7191}{}{До свидания, автомат с пончиками.}
{7192}{}{До свидания, ядер-кола.}
{7193}{}{Я вас не забуду.}
{7194}{}{**END-DISK**}

# Правит. убежище: Медотчет про голову
# GVAR_HOLODISK_ENCLAV_MED (GVAR_HOLODISK_SIERRA_MED_LOG)
{8000}{}{}
{8001}{}{О психическом состоянии головы президента}
{8002}{}{}
{8003}{}{Нами была проведена беседа с головой бывшего}
{8004}{}{президента. Выводы неутешительные. За несколько}
{8005}{}{лет в отсутствие естественного человеческого}
{8006}{}{общения голова потеряла контроль над своими}
{8007}{}{фантазиями и зачастую принимает свои мысли}
{8008}{}{за истину. Голова склонна отождествлять}
{8009}{}{себя со своей куклой. Помимо длительного отсутствия}
{8010}{}{общения причиной агрессии является также}
{8011}{}{изначально завышенный эгоцентризм. Голове}
{8012}{}{необходимо внимание, но так как его не оказывают,}
{8013}{}{то она избирает все более жесткие и}
{8014}{}{кардинальные меры для того, чтобы его добиться.}
{8015}{}{Боюсь, через пару лет голова станет неуправляемым}
{8016}{}{психопатом.}
{8017}{}{}
{8018}{}{Требуется длительное психиатрическое лечение.}
{8019}{}{**END-DISK**}

# Правит. убежище: Исход
# GVAR_HOLODISK_ENCLAV_ISHOD (GVAR_HOLODISK_SIERRA_EVACUATION)
{9000}{}{На этом диске находится различная информация}
{9001}{}{из главного компьютера правительственного убежища,}
{9002}{}{в том числе записи о последних днях перед "исходом" -}
{9003}{}{случаем, заставившим жителей покинуть убежище.}
{9004}{}{ }
{9005}{}{Общий смысл в том, что убежище было создано}
{9006}{}{для правительственной элиты Соединенных Штатов,}
{9007}{}{включая президента, его семью и обслуживающий персонал.}
{9008}{}{Убежище оборудовали по последнему слову техники,}
{9009}{}{однако это не спасло его обитателей. После}
{9010}{}{запечатывания убежища в нем случилось несчастье с }
{9011}{}{президентом - ему оторвало голову. Голову оживили }
{9012}{}{в лаборатории, чтобы не потерять сокровенные знания }
{9013}{}{господина президента. Однако голова оказалась слишком }
{9014}{}{эгоцентричной и после потери внимания к собственной }
{9015}{}{персоне стала вести себя деспотично. Подшучивания над }
{9016}{}{гражданами сменились явной угрозой их жизни или }
{9017}{}{здоровью. Рекомендация по уничтожению головы}
{9018}{}{была запоздалой - голова успела подчинить себе }
{9019}{}{компьютерные системы и различную робототехнику. }
{9020}{}{Любая оплошность могла стать критичной для жителей. }
{9021}{}{В итоге было решено покинуть убежище и }
{9022}{}{передислоцироваться на резервную правительственную }
{9023}{}{базу на нефтевышке в океане. Однако в день исхода }
{9024}{}{голова пыталась остановить беглецов.}
{9025}{}{ }
{9026}{}{Группа смельчаков из охраны решила уничтожить }
{9027}{}{резервуар с головой, но когда они попали в лабораторию,}
{9028}{}{завязался бой с турелями, в результате они погибли.}
{9029}{}{После этого голова стала истреблять всех, кого }
{9030}{}{могли достать турели. И все же большая часть граждан }
{9031}{}{спаслась, включая ныне действующего президента. Они }
{9032}{}{забрали самую ценную технику и улетели прочь.}
{9033}{}{ }
{9034}{}{Убежище было брошено.}
{9035}{}{**END-DISK**}

# Сообщение Джея Кукиша
# GVAR_HOWTHORNE_DSK_BAIKER_MSG (GVAR_SIERRA_MISSION_HOLODISK)
{10000}{}{Не ожидал, что тебе удастся зайти так далеко.}
{10001}{}{Но раз ты здесь, то это не случайно.}
{10002}{}{Для встречи со мной тебе придется постараться.}
{10003}{}{Проникни в военный ангар V9 на севере и найди там}
{10004}{}{глушитель радиосигнала. Чтобы снизить риск,}
{10005}{}{попробуй отключить электростанцию на подземном}
{10006}{}{уровне там же. Далее подсоедини глушитель}
{10007}{}{к радиооборудованию на втором этаже здания}
{10008}{}{в гарнизоне и жди меня у выхода.}
{10009}{}{Это все.}
{10010}{}{**END-DISK**}

# Кейс с документами из радиостанции
# GVAR_SHAIEN_RADIO_KEISHOLODISK (GVAR_SIERRA_GNN_HOLODISK)
{11000}{}{В кейсе из радиостанции находится плотная пачка}
{11001}{}{документов и дисков. Они могли бы показаться}
{11002}{}{бесполезным мусором, если бы не их засекреченность.}
{11003}{}{К тому же часть информации зашифрована, что}
{11004}{}{наводит на некоторые мысли.}
{11005}{}{}
{11006}{}{Судя по всему, радиостанция в Лавлоке была одним}
{11007}{}{из пунктов военного радиовещания. Здесь занимались}
{11008}{}{налаживанием связи между генштабом,}
{11009}{}{военными базами, сетью убежищ, лабораториями,}
{11010}{}{а также - по необходимости - тайной прослушкой.}
{11011}{}{}
{11012}{}{Среди документов вы неожиданно обнаруживаете}
{11013}{}{отчеты о слежении за убежищем 8:}
{11014}{}{переговоры по внешней и внутренней связи,}
{11015}{}{перехват данных компьютерных систем и т.п.}
{11016}{}{Убежище было под пристальным надзором военных -}
{11017}{}{информация передавалась в армейскую базу Хоторн.}
{11018}{}{}
{11019}{}{Понадобится время, чтобы расшифровать всю}
{11020}{}{документацию, но уже сейчас понятно, что она может}
{11021}{}{иметь значение для вашего города.}
{11022}{}{**END-DISK**}

# История Ветра Войны
# GVAR_WIND_HISTORY_HOLODISK (GVAR_ELRON_HOLODISK)
{12000}{}{Краткая история Ветра Войны}
{12001}{}{}
{12002}{}{(Аудиозапись разговора с военнослужащим)}
{12003}{}{}
{12004}{}{"Все мы - потомки людей, переживших Великую Войну}
{12005}{}{в спасительном убежище. Наши предки были элитным}
{12006}{}{подразделением военнослужащих на военной базе}
{12007}{}{"Хоторн". По крайней мере, нам они так говорили.}
{12008}{}{Когда уже некого было спасать в Неваде, они}
{12009}{}{укрылись в тестовом убежище неподалеку отсюда.}
{12010}{}{Убежище имело кодовое название "Ветер Войны",}
{12011}{}{его построили исключительно для проверки материалов}
{12012}{}{и технологий сети убежищ."}
{12013}{}{}
{12014}{}{}
{12015}{}{"Прошло время, и родились мы, еще запечатанные}
{12016}{}{внутри. Когда ресурсы убежища иссякли,}
{12017}{}{нам пришлось выйти на поверхность и начать новую}
{12018}{}{жизнь в борьбе за свое место под солнцем.}
{12019}{}{Генерал Вескер взял ситуацию под контроль.}
{12020}{}{Мы осели в этих руинах, оборудовали их,}
{12021}{}{утащили из Хоторна некоторую технику и оружие.}
{12022}{}{Далее взорвали убежище и стали жить здесь.}
{12023}{}{Но оказалось, что мы не годны к работе в сельском}
{12024}{}{хозяйстве, а жить как-то надо. В основном мы жили}
{12025}{}{за счет охоты, но в этой местности одни пустыни,}
{12026}{}{не так просто найти здесь пропитание. После появления}
{12027}{}{"пришельцев" охота стала особенно тяжелой.}
{12028}{}{И генерал нашел другой способ заработка -}
{12029}{}{мы стали защитниками для мелких поселений и}
{12030}{}{перевалочным пунктом для караванщиков.}
{12031}{}{Так что медленно дела стали идти в гору."}
{12032}{}{**END-DISK**}

# Карта памяти робота-дилижансера
# GVAR_NEW_RENO_DILIZHAS_ROBOTMODUL (GVAR_RESERVED_VAR13)
{13000}{}{}
{13001}{}{}
{13002}{}{Здесь собрана важная информация с расшифрованной}
{13003}{}{данных регистратора робота-охранника, сопровождавшего}
{13004}{}{дилижанс из Солт-Лейка в Нью-Рино.}
{13005}{}{}
{13006}{}{Как оказалось, байкеры не нападали на дилижанс,}
{13007}{}{это сделали сами члены экипажа - те самые,}
{13008}{}{которые позже вернулись в город и свалили всю вину}
{13009}{}{на байкеров.}
{13010}{}{}
{13011}{}{К этой информации определенно возникнет интерес}
{13012}{}{сразу у нескольких человек.}
{13013}{}{}
{13014}{}{**END-DISK**}

# Вырезки из газет про Армстронга
# GVAR_LIST_ARMSTRONG_PANIHIDA (GVAR_VAULT_CITY_DESIGNER_NOTES)
{14000}{}{Новости из газеты "Вашингтон пост":}
{14001}{}{}
{14002}{}{Смерть Луи Армстронга вызвала настоящий поток}
{14003}{}{самых искренних и глубоких соболезнований.}
{14004}{}{Многие газеты не только в США, но и в других}
{14005}{}{странах поместили на первой полосе сообщение}
{14006}{}{о его кончине.}
{14007}{}{}
{14008}{}{Похороны прошли очень торжественно}
{14009}{}{и транслировались по телевидению на всю страну.}
{14010}{}{8 июля тело было выставлено для торжественного}
{14011}{}{прощания в учебном манеже Национальной гвардии,}
{14012}{}{предоставленном для этих целей по личному}
{14013}{}{распоряжению президента США. В заявлении,}
{14014}{}{сделанном президентом Никсоном, говорилось:}
{14015}{}{}
{14016}{}{"Госпожа Никсон и я разделяем горе миллионов}
{14017}{}{американцев в связи со смертью Луи Армстронга.}
{14018}{}{Он был одним из творцов американского искусства.}
{14019}{}{Человек яркой индивидуальности, Армстронг}
{14020}{}{завоевал всемирную известность.}
{14021}{}{Его блестящий талант и благородство обогатили}
{14022}{}{нашу духовную жизнь, сделали ее более насыщенной"}
{14023}{}{**END-PAR**}
{14024}{}{**END-DISK**}

# Записи замурованного
# Автор текста - Kerb (Александр Агафонцев)
# GVAR_HOLODISK_SALT_MINIVAULT (GVAR_NCR_SPY_HOLO_DOWNLOAD)
{15000}{}{}
{15001}{}{(Обычный блокнот в потертом кожаном переплете.}
{15002}{}{Первые страницы заполнены аккуратным убористым}
{15003}{}{почерком, но дальше вы с трудом различаете}
{15004}{}{неровные строчки на запятнанных кровью}
{15005}{}{измятых листах.)}
{15006}{}{}
{15007}{}{}
{15008}{}{}
{15009}{}{День 1}
{15010}{}{}
{15011}{}{Мать вашу, я это сделал! Можете там теперь}
{15012}{}{друг друга хоть на фарш пускать,}
{15013}{}{хоть живьем хавать. Я все пережду здесь,}
{15014}{}{уж ждать-то я научился хорошо...}
{15015}{}{Хотел бы я, чтоб ты знал это, Уоткинс!}
{15016}{}{И ты, Куровски, пшек чертов...}
{15017}{}{Ну ничего, я вас не забуду.}
{15018}{}{Приду поссать на ваши могилки!}
{15019}{}{Последнюю ходку за едой я так и не сделал...}
{15020}{}{Почему-то решил, что лучше наружу}
{15021}{}{больше не выходить. Это не страх... нет,}
{15022}{}{просто предосторожность... С нервами у меня}
{15023}{}{все в порядке, должно быть только так...}
{15024}{}{}
{15025}{}{День2}
{15026}{}{}
{15027}{}{В основном отсыпаюсь, набиваю брюхо.}
{15028}{}{Читал мало - свет для меня пока тоже}
{15029}{}{невозобновляемый ресурс.}
{15030}{}{Снаружи слышал пару выстрелов. Началось?}
{15031}{}{}
{15032}{}{День 3}
{15033}{}{}
{15034}{}{Дерьмо! Да они там вообще с болта сорвались!!}
{15035}{}{Пальба и взрывы целый день, крики...}
{15036}{}{Одного, похоже, свалили прямо у моих дверей...}
{15037}{}{Ревет не переставая, что твоя скотина на бойне...}
{15038}{}{Черт, да добейте же его кто-нибудь...}
{15039}{}{}
{15040}{}{День 4}
{15041}{}{}
{15042}{}{Сдох наконец-то или просто ослаб...}
{15043}{}{Интересно, я вроде немного привык к этому доходяге}
{15044}{}{- даже что-то втирал ему...}
{15045}{}{В одностороннем порядке, разумеется, хе-хе...}
{15046}{}{Теперь тихо, очень тихо...}
{15047}{}{}
{15048}{}{День 5}
{15049}{}{}
{15050}{}{Никогда бы не подумал, что пытка тишиной}
{15051}{}{может иметь место быть...}
{15052}{}{Постоянно говорю сам с собой, гремлю снаряжением...}
{15053}{}{Только бы отогнать ее еще на миг...}
{15054}{}{}
{15055}{}{День 6}
{15056}{}{}
{15057}{}{Проснулся ночью от того, что почувствовал -}
{15058}{}{кто-то рядом... Свет не разгоняет тьму,}
{15059}{}{лишь заставляет ее забиться в дальний угол...}
{15060}{}{Нет, не может быть, я здесь один...}
{15061}{}{Один во тьме...}
{15062}{}{Ха-ха...}
{15063}{}{}
{15064}{}{День 7}
{15065}{}{}
{15066}{}{Света больше нет...}
{15067}{}{Тишина высверливает мозг, темнота выдавливает}
{15068}{}{глаза... Но - никаких звуков! Оно только и ждет этого...}
{15069}{}{Или этого нет? Я ведь вроде один?}
{15070}{}{Что-то я запутался... только не спать...}
{15071}{}{От часов больше нет проку - время остановилось...}
{15072}{}{Каково это - не спать в вечности?}
{15073}{}{}
{15074}{}{День ?}
{15075}{}{}
{15076}{}{Меньше еды, воды, жизни...}
{15077}{}{Тишина уже внутри меня...}
{15078}{}{Начинает пожирать меня...}
{15079}{}{Медленно...}
{15080}{}{Главное, не спать, оно не может мне повредить,}
{15081}{}{если я не сплю...}
{15082}{}{Или если я не издаю шума? Или оно не одно...}
{15083}{}{}
{15084}{}{Вне времени}
{15085}{}{}
{15086}{}{Припасы кончились...}
{15087}{}{Но выйти я не могу - дверь завалило...}
{15088}{}{Или замок сломан...}
{15089}{}{Или кто-то ждет меня там...}
{15090}{}{Я не могу выйти, не могу, не должен выходить,}
{15091}{}{не должен... Это мой день, детка!!!}
{15092}{}{Я обману их!!! Они не смогут сожрать меня,}
{15093}{}{если я сам съем себя!!! Ха-ха!!}
{15094}{}{Они не ждали, что я закинусь обезболивающими}
{15095}{}{под завязку...}
{15096}{}{Они выбили из меня дух, но я все-таки успел}
{15097}{}{выковырять глаза... Отсоси, тьма!}
{15098}{}{И левую руку отхватил по локоть...}
{15099}{}{только не забывать пить кровь...}
{15100}{}{Тишине не достанется ни капли...}
{15101}{}{На очереди - язык и уши...}
{15102}{}{... которые у них наверняка считаются деликатесом...}
{15103}{}{... так что пусть обломаются!..}
{15104}{}{**END-DISK**}

# Аудиозаписи военнослужащего в Зоне 51
# Автор текста - Kerb (Александр Агафонцев)
# GVAR_ZONA_SOLDAT_AUDIO_HOLODISK (GVAR_NCR_HISTORY_HOLO_DOWNLOAD)
{16000}{}{Аудиозаписи офицера}
{16001}{}{}
{16002}{}{[Сквозь фоновый шум вы четко слышите чей-то}
{16003}{}{уверенный хриплый голос]}
{16004}{}{}
{16005}{}{**END-PAR**}
{16006}{}{}
{16007}{}{3 августа 2077}
{16008}{}{}
{16009}{}{[На заднем плане слышен грохот сапог по плацу;}
{16010}{}{команда "Левое плечо вперед! Запевай!" - слов}
{16011}{}{не разобрать, но похоже, что одна из рот}
{16012}{}{исполняет гимн спецназа]}
{16013}{}{}
{16014}{}{После утреннего построения наш трехзвездный}
{16015}{}{наместник бога на земле в генеральских погонах}
{16016}{}{обрадовал меня, что вместо отпуска в Китае}
{16017}{}{в компании недобитых гуков, меня - во главе}
{16018}{}{второго взвода - ожидает "Зона 51". Почему}
{16019}{}{для охраны эсбешников местных не достаточно -}
{16020}{}{непонятно. Так мало того - прикрепили к нам}
{16021}{}{каких-то штатских... Как их там... Хрено... Ксено...}
{16022}{}{В общем, что-то в этом духе. Один из этих дятлов}
{16023}{}{попросил им оружие выдать. Долго смеялся.}
{16024}{}{Да по ним видно, что они прибор-то свой с трудом}
{16025}{}{в туалете удержать могут, чего уж про винтовку}
{16026}{}{говорить. Ладно, посмотрим, как оно будет...}
{16027}{}{}
{16028}{}{**END-PAR**}
{16029}{}{}
{16030}{}{14 августа 2077}
{16031}{}{}
{16032}{}{Если коротко - полная задница. А если по порядку,}
{16033}{}{то охранять нам придется... чужих.}
{16034}{}{Нет, я не нажрался до зеленых чертей, хотя желание}
{16035}{}{есть. Это их так местные называют.}
{16036}{}{Если кто-то так тупо пошутить хотел, то у него вполне}
{16037}{}{вышло. По прибытии начальник СБ не стал проводить}
{16038}{}{инструктаж, а просто повел нас смотреть на камеры}
{16039}{}{с этими тварями. Это он хорошо придумал.}
{16040}{}{Впечатлений - полные штаны. Как им в пасть глянешь -}
{16041}{}{сразу хочется хоть в Китае геройствовать, хоть снова}
{16042}{}{Анкориджские утесы штурмовать, но лишь бы}
{16043}{}{подальше отсюда.}
{16044}{}{Официальная легенда гласит, что их корабль якобы}
{16045}{}{потерпел крушение как раз недалеко от Грум-Лейк.}
{16046}{}{Братья по разуму... Ну что за чушь?!}
{16047}{}{Как по мне, так это все эксперименты яйцеголовых,}
{16048}{}{вроде тех, которых мы с собой приволокли. Вот уж}
{16049}{}{кого от камер не оттащишь. Исследователи, чтоб их...}
{16050}{}{}
{16051}{}{**END-PAR**}
{16052}{}{}
{16053}{}{2 сентября 2077}
{16054}{}{}
{16055}{}{Эти ученые задрали в корень уже. И пропускной режим}
{16056}{}{их напрягает, и постоянное сопровождение мешает...}
{16057}{}{Да еще эти дятлы, РПК Джонс и капрал Стерлинг,}
{16058}{}{нажрались спиртяги... Хрен теперь Стерлингу,}
{16059}{}{а не сержантские лычки. Выручил Маккой, начальник СБ -}
{16060}{}{показал всем записи с камер наблюдения, когда один}
{16061}{}{из чужих вырвался на свободу где-то с полгода назад.}
{16062}{}{Пока его завалили, загнав в тупик у замурованных}
{16063}{}{помещений в секторе С (вот че их замуровали,}
{16064}{}{тоже вопрос), он успел половину охраны порвать.}
{16065}{}{Так что все пока поутихли. Вопрос - надолго ли?}
{16066}{}{}
{16067}{}{}
{16068}{}{**END-PAR**}
{16069}{}{}
{16070}{}{10 сентября 2077}
{16071}{}{}
{16072}{}{Работаем. Проверяем тварей на прочность.}
{16073}{}{5мм, 7,62 или там 9 - как слону дробина,}
{16074}{}{даже бронебойные. Нет, эффект есть, конечно,}
{16075}{}{но извести пол-БК взвода на одного противника}
{16076}{}{- это не есть хорошо. Лазер, электричество -}
{16077}{}{те же эффекты. Высоколобики пробуют яды и}
{16078}{}{радиацию, но пока без особых результатов.}
{16079}{}{Ладно, завтра тяжелое вооружение подкинут.}
{16080}{}{Чуть снял напряг, кстати - один из местных}
{16081}{}{стукачей хотел в мой планшет залезть.}
{16082}{}{Ну ничего, за пару недель любые кости}
{16083}{}{срастаются.}
{16084}{}{}
{16085}{}{**END-PAR**}
{16086}{}{12 сентября 2077}
{16087}{}{}
{16088}{}{Стало повеселее. Не удержался - лично из Бозара}
{16089}{}{завалил одного. Лучше всего пока огнеметы себя}
{16090}{}{зарекомендовали. Парни по полной отрываются,}
{16091}{}{даже пара хмырей-ученых к ним подтянулась.}
{16092}{}{Один из них сказал, что эти твари видят нас}
{16093}{}{в инфракрасном диапазоне.}
{16094}{}{Температурные поля, тепловое излучение, все дела...}
{16095}{}{Единственная стоящая информация от этих}
{16096}{}{высоколобых за время пребывания здесь, кстати.}
{16097}{}{И все бы ничего, только вот...}
{16098}{}{Я не особо впечатлительный, но последнее время}
{16099}{}{ощущение складывается, что кто-то пытается}
{16100}{}{мне в мозги забраться...}
{16101}{}{Место, что ль, здесь такое?}
{16102}{}{}
{16103}{}{**END-PAR**}
{16104}{}{}
{16105}{}{3 октября 2077}
{16106}{}{}
{16107}{}{Посыпался шифер у одного яйцеголового - Хаббарда.}
{16108}{}{Начал орать, что мы, мол, истребляем разумную}
{16109}{}{форму жизни, что с "звездными гостями"}
{16110}{}{надо договариваться миром, тряс отчетами о своих}
{16111}{}{наблюдениях... Откуда-то прознал про моих предков}
{16112}{}{из России и назвал меня коммунистической свиньей.}
{16113}{}{А потом вознамерился войти в одну из камер [смех].}
{16114}{}{С гордостью могу теперь заявить, что спецназ}
{16115}{}{не стал помехой на пути научного прогресса.}
{16116}{}{Да и правда - дипломатия в наше время эффективнее}
{16117}{}{оружия. Мир и любовь, все дела... Ну а то, что чужой}
{16118}{}{его потрохами всю камеру разукрасил - ну так}
{16119}{}{это у них, наверное, обычаи такие, надо}
{16120}{}{с пониманием относиться.}
{16121}{}{----}
{16122}{}{В районе высоты 117 БПЛА засекли какую-то}
{16123}{}{подозрительную активность.}
{16124}{}{Завтра с двумя отделениями выдвигаюсь туда.}
{16125}{}{}
{16126}{}{**END-PAR**}
{16127}{}{}
{16128}{}{19 октября 2077}
{16129}{}{}
{16130}{}{Пропал Джонс и один из эсбешников.}
{16131}{}{На базе есть "мертвые зоны" у сектора C,}
{16132}{}{с ограниченным доступом, но зачем им было туда}
{16133}{}{идти? Теперь мы по одному не ходим,}
{16134}{}{патрулирование, контроль периметра...}
{16135}{}{В голове черт-те что творится... Объявлена боевая}
{16136}{}{готовность... Из штаба поступил приказ ожидать}
{16137}{}{дальнейших инструкций...}
{16138}{}{}
{16139}{}{**END-PAR**}
{16140}{}{}
{16141}{}{21 октября 2077}
{16142}{}{}
{16143}{}{Что-то пробралось в казармы СБ и убило всех}
{16144}{}{сменившихся... Кровью забрызгано все до потолка,}
{16145}{}{клочья мяса и требуха повсюду...}
{16146}{}{Связь со штабом прервана... Система безопасности}
{16147}{}{постоянно сбоит, контроль над базой частично потерян...}
{16148}{}{Двумя отделениями прочесываем базу, два остальных}
{16149}{}{держат периметр...}
{16150}{}{}
{16151}{}{**END-PAR**}
{16152}{}{}
{16153}{}{22 октября 2077}
{16154}{}{}
{16155}{}{[Слышны выстрелы разнокалиберных стволов, взрывы,}
{16156}{}{крики, вой аварийных сирен. Перекрывая их,}
{16157}{}{то и дело раздается чей-то визг, сменяющийся}
{16158}{}{шипением]}
{16159}{}{}
{16160}{}{Вопросов больше не осталось, но и ответы не радуют...}
{16161}{}{Та тварь, которую завалили полгода назад, оказалась}
{16162}{}{самкой... Успела как-то пробраться в замурованные}
{16163}{}{помещения и отложить яйца...}
{16164}{}{Как только мы вскрыли двери, тут-то и началось...}
{16165}{}{РПК Айрон и лейтенант Паркер спалили первую волну}
{16166}{}{из огнеметов, но потом эти гниды обошли нас с тыла...}
{16167}{}{Рвал их очередями, пока одна из тварей не зажевала}
{16168}{}{мою руку... Отбился, покромсав ее ножом...}
{16169}{}{Укрылся на складе в блоке H...}
{16170}{}{}
{16171}{}{**END-PAR**}
{16172}{}{}
{16173}{}{}
{16174}{}{}
{16175}{}{}
{16176}{}{25 октября 2077}
{16177}{}{}
{16178}{}{[Некоторое время слышно лишь хриплое дыхание]}
{16179}{}{}
{16180}{}{Я остался один... Стрельба сменилась рукопашной,}
{16181}{}{потом меня вырубило... Теперь все тихо...}
{16182}{}{Еле держусь на ногах, рука не подчиняется...}
{16183}{}{Обкололся медикаментами так, что уже плохо соображаю,}
{16184}{}{что реальность, а что галлюцинации...}
{16185}{}{Помощи не жду - после того, как мы не ответили}
{16186}{}{на контрольный сигнал, ГНР уже должна была быть тут...}
{16187}{}{Но кое-что могу сделать и я...}
{16188}{}{Навесил на себя кордекса, сколько смог...}
{16189}{}{Лишь бы повезло забрать их с собой побольше...}
{16190}{}{Примерно так мой предок уничтожил "тигра"}
{16191}{}{во Второй мировой... В конце концов, даже один боец}
{16192}{}{сил специального назначения есть боевая единица}
{16193}{}{сама в себе... Ну что, парни, работаем?..}
{16194}{}{**END-DISK**}

# Свободное место
{17000}{}{--ПУСТО--}
{17001}{}{**END-DISK**}

# Свободное место
{18000}{}{--ПУСТО--}
{18001}{}{**END-DISK**}

# Солт-Лейк-Сити, Уголовное дело 4783
# GVAR_HOLODISK_SALT_RAPORT
{19000}{}{Уголовное дело номер 4783}
{19000}{}{}
{19001}{}{[ Изрядно подпорченная грызунами, временем}
{19002}{}{и сыростью папка с материалами уголовного дела.}
{19003}{}{Но кое-что еще можно разобрать. ]}
{19004}{}{}
{19005}{}{[ Дневник в кожаном переплете с искусным тиснением}
{19006}{}{на церковную тематику ]}
{19007}{}{}
{19008}{}{День I}
{19009}{}{}
{19010}{}{Сегодня Эмили призналась, что без разрешения}
{19011}{}{сорвала цветок на клумбе нашего соседа, мистера}
{19012}{}{Флауэрса. Мы всей семьей принесли сему достойному}
{19013}{}{человеку извинения, которые он благосклонно принял.}
{19014}{}{Пока я пишу это, Эмили усердно молит Господа }
{19015}{}{нашего о прощении. Она делает это добровольно, }
{19016}{}{ибо семя веры нашей дало в ее светлой душе всходы,}
{19017}{}{что неустанно радуют мое сердце...}
{19018}{}{Но к делу, к делу! Мой приход ждет своего пастыря,}
{19019}{}{ибо даже на райских пажитях завещано нам неустанно }
{19020}{}{трудиться во благо Господа нашего!}
{19021}{}{}
{19022}{}{День II}
{19023}{}{}
{19024}{}{Печальная весть пришла в наш городок - сын миссис}
{19025}{}{Шульц, майор Отто Шульц, погиб в провинции Гирин...}
{19026}{}{Обязательно зайду к сей несчастной сегодня же}
{19027}{}{вечером. Надеюсь, что смогу хоть немного облегчить}
{19028}{}{ее страдания и помочь примириться с богом...}
{19029}{}{Почему же люди не могут жить в мире? Ведь все мы}
{19030}{}{братья под всевидящим оком Отца нашего...}
{19031}{}{}
{19032}{}{День III}
{19033}{}{}
{19034}{}{Судный День настал... Все предшествующие события}
{19035}{}{я вспоминаю урывками... Сигнал тревоги, подобный}
{19036}{}{трубам Иерихона... Мои бедные Мэри и Эмили,}
{19037}{}{торопливо собирающие вещи... Паническое бегство...}
{19038}{}{Затоптанная озверевшими от страха скотами пожилая}
{19039}{}{пара... Кровь на мостовых... Двери частного убежища}
{19040}{}{мистера Флауэрса, где три десятка уцелевших смогли}
{19041}{}{найти приют... Но одно я запомнил ясно...}
{19042}{}{Пока камеры наружного наблюдения не вышли}
{19043}{}{из строя, я узрел огненный шар на горизонте,}
{19044}{}{что стремительно рванулся во все стороны, жадно }
{19045}{}{поглощая души несчастных агнцев божьих...}
{19046}{}{И ослепительная вспышка...}
{19047}{}{Погибель пришла с неба, но мне казалось, что это}
{19048}{}{было вырвавшееся из-под земли пламя преисподней...}
{19049}{}{}
{19050}{}{День IV}
{19051}{}{}
{19052}{}{Господь, укрепи мою руку... Мэри, моя милая Мэри...}
{19053}{}{Мистер Флауэрс сказал, что защита убежища}
{19054}{}{оказалась недостаточной... Радиация...}
{19055}{}{От препаратов, которые мы принимали для защиты,}
{19056}{}{у нее началась аллергия... Ее распухшие, в пятнах}
{19057}{}{руки, тянущиеся ко мне...}
{19058}{}{Затуманенные болью глаза...}
{19059}{}{Жуткие крики боли...}
{19060}{}{За что Господь так жесток со мной?}
{19061}{}{Я так нужен ей в эти последние часы, но сил у меня}
{19062}{}{остается все меньше...}
{19063}{}{}
{19064}{}{День V}
{19065}{}{}
{19066}{}{Восславим же Господа нашего! Как же я был слеп...}
{19067}{}{Я долго постился, укрепляя свой дух молитвами,}
{19068}{}{и откровение снизошло на меня! Все произошедшее -}
{19069}{}{великий замысел Творца по вознесению всех}
{19070}{}{страждущих на небеса! Та вспышка, что чуть}
{19071}{}{не ослепила меня - свет райских врат,}
{19072}{}{что открылись для всех праведных и верных!}
{19073}{}{А нас слуги дьявола заманили в это чистилище,}
{19074}{}{дабы искушать возможностью ложной жизни, вопреки}
{19075}{}{воле Отца нашего... Мэри, я знаю, ты ждешь меня}
{19076}{}{на небесах, но я же пастырь агнцев божьих,}
{19077}{}{у меня еще остались незавершенные дела на нашей}
{19078}{}{грешной земле... Но наша дочь скоро присоединится}
{19079}{}{к тебе, как ни печалит меня расставание с ней...}
{19080}{}{}
{19081}{}{День VI}
{19082}{}{}
{19083}{}{Сегодня я открыл врата, дабы сила Творца, которую}
{19084}{}{невежды зовут "радиацией", освятила это проклятое}
{19085}{}{место. Сатанинская тварь, принявшая облик Флауэрса,}
{19086}{}{пыталась остановить меня, но пожарный топор в моих}
{19087}{}{руках подобно пылающему мечу архангела изрубил}
{19088}{}{в куски визжащего посланца сатаны.}
{19089}{}{О да, многие из них приняли смерть в этот день}
{19090}{}{от моих рук... Еды здесь не осталось, но силою}
{19091}{}{Господа нашего я причастился их плотью и кровью,}
{19092}{}{что была для меня лучше любого вина...}
{19093}{}{Но, Мэри, теперь самое главное! Наше прелестное}
{19094}{}{дитя скоро вновь соединится с тобой!}
{19095}{}{Она почему-то упорно сопротивлялась, когда}
{19096}{}{я выдавливал ее дух из бренной плоти...}
{19097}{}{Может, стоило предварительно смыть с себя кровь}
{19098}{}{и почистить одежду?}
{19099}{}{}
{19100}{}{День VII}
{19101}{}{}
{19102}{}{Здесь я закончил, но сколько же еще душ мне}
{19103}{}{предстоит отправить к райским вратам...}
{19104}{}{Плоть моя меняется под воздействием божественной}
{19105}{}{силы, что доставляет некоторые неудобства...}
{19106}{}{Но верю я - это лишь к лучшему! Возрадуйтесь,}
{19107}{}{страждущие, и убоитесь, неверующие!}
{19108}{}{Ибо я иду к вам...}
{19109}{}{}
{19110}{}{[Обрывки из протоколов осмотра мест происшествия]}
{19111}{}{}
{19112}{}{Осмотр начат: 19 ч. 1...}
{19113}{}{Осмотр оконч...}
{19114}{}{}
{19115}{}{...Одноэтажное кирпичное здание...}
{19116}{}{Размеры внутреннего помещения: 6,5м Х...}
{19117}{}{Мужчина, европеоид... Распят на западной стене}
{19118}{}{головой вниз... Кожа частично снята с левой ноги...}
{19119}{}{Множество кусаных ран в области лица, шеи и живота...}
{19120}{}{Женщина... Голова отсутствует... Судя по характеру}
{19121}{}{раны, возможно была оторвана...}
{19122}{}{}
{19123}{}{Осмотр...}
{19124}{}{}
{19125}{}{... Поляна к северо-западу от...}
{19126}{}{Колья, высотой примерно 2 метра... Расставлены}
{19127}{}{в форме креста... Мужчины и женщины... Насажены}
{19128}{}{на колья... Половая принадлежность некоторых}
{19129}{}{убитых не определена ввиду сильных повреждений}
{19130}{}{и отсутствия частей тел... На уцелевших фрагментах}
{19131}{}{кожи видны надписи... Возможно, латынь...}
{19132}{}{}
{19133}{}{С места происшествия изъяты:}
{19134}{}{1. Деревянное распятие...}
{19135}{}{2. Книга в переплете из кожи...}
{19136}{}{[ На удивление хорошо сохранившаяся открытка}
{19137}{}{с изображением не особо одетой киноактрисы...}
{19138}{}{определенного жанра. Оборотная сторона заполнена}
{19139}{}{каллиграфическим почерком. ]}
{19140}{}{}
{19141}{}{Доброго времени суток, Шериф Кроуч!}
{19142}{}{Довожу до вашего сведения, что я, совместно}
{19143}{}{с детективом Гастингсом, отправляюсь на поиски}
{19144}{}{нашего Джона Доу. Материалы данного дела}
{19145}{}{позволили нам установить его местонахождение,}
{19146}{}{а так как по имеющимся данным можно предположить,}
{19147}{}{что он скоро вновь выйдет на охоту, мы не стали}
{19148}{}{дожидаться возвращения вашей поисковой партии}
{19149}{}{от Гнилой Скалы. Предполагаю, что вы зададитесь}
{19150}{}{во всеуслышание вопросом: "И зачем священнику}
{19151}{}{понадобилось соваться в это дело?" (конечно, вы}
{19152}{}{выразитесь гораздо менее изящно и вежливо).}
{19153}{}{Ну, что тут сказать... Этот несчастный был}
{19154}{}{когда-то моим братом по вере, весьма усердным}
{19155}{}{на своем посту в помощи страждущим. А вот когда}
{19156}{}{ему самому потребовалась помощь...}
{19157}{}{И пусть запоздало, но я все-таки хочу помочь ему}
{19158}{}{упокоиться с миром.}
{19159}{}{}
{19160}{}{"Тогда он отрет всякую слезу с их глаз, и смерти}
{19161}{}{уже не будет, ни скорби, ни вопля, ни боли}
{19162}{}{уже не будет. Прежнее прошло".}
{19163}{}{}
{19164}{}{                                  Пастор Маклейн}
{19165}{}{}
{19166}{}{P.S. И ради всех святых - не переводите всю бумагу}
{19167}{}{на самокрутки! Представьте, если бы вам пришлось}
{19168}{}{писать письмо, возможно последнее, на греховном}
{19169}{}{изображении девицы (не очень привлекательной,}
{19170}{}{на мой взгляд)! Впрочем, учитывая ваши склонности,}
{19171}{}{для вас это был бы наиболее предпочтительный}
{19172}{}{вариант. А посему, если я не вернусь, мой помощник}
{19173}{}{наложит на вас 10-летнюю епитимью. Так что в ваших}
{19174}{}{же интересах помолиться за успех нашей миссии.}
{19175}{}{**END-DISK**}

# Рекламный голодиск дилижансов
# GVAR_HOLODISK_DILIZHANS_INFO -- GVAR_HOLODISK_ENCLAVE_WORD
{20000}{}{}
{20001}{}{Решили срубить деньжат на продаже бус и огненной}
{20002}{}{воды дикарям-шайеннам? Или захотелось начать} 
{20003}{}{новую жизнь в Вегасе из-за проблем с неким шерифом}
{20004}{}{(все знают, о ком я)?}
{20005}{}{Но Вы боитесь пересечь Пустошь из-за дикого зверья}
{20006}{}{и отмороженных рейдеров... Ну, что сказать?}
{20007}{}{Вы правы, наша благословенная земля - не лучшее}
{20008}{}{место для прогулок. Но... Сушите штаны, господа!}
{20009}{}{Дядя Джо и "Невадский экспресс" защитят Вашу задницу}
{20010}{}{от посягательств нелюдей всех ростов и оттенков!}
{20011}{}{Завалялись 1000 баксов в кармане? Этого вполне хватит!}
{20012}{}{К тому же мы всегда готовы протянуть руку помощи}
{20013}{}{хорошему человеку и пересмотреть условия сделки!}
{20014}{}{}
{20015}{}{1. А кто вы такие? Что за дилижанс такой?}
{20016}{}{}
{20017}{}{Мы - команда профессионалов в вопросах логистики}
{20018}{}{и выбивания дерьма из желающих причинить вред}
{20019}{}{нашим уважаемым клиентам. Некоторые фирмы видят}
{20020}{}{в Вас только начинку для гробов - мы же}
{20021}{}{рассматриваем Вас как потенциального члена нашей}
{20022}{}{крепкой семьи!}
{20023}{}{}
{20024}{}{2. Хм, с вами точно безопасно?}
{20025}{}{}
{20026}{}{Приходите в любое наше отделение и оцените}
{20027}{}{выправку и снаряжение наших парней! Можем скромно}
{20028}{}{добавить, что если бы Иисус собрался отправиться}
{20029}{}{в вояж по Пустоши - он бы выбрал "Невадский экспресс"!}
{20030}{}{Распятым оказался бы кто угодно, только не он!}
{20031}{}{}
{20032}{}{3. И как давно вы на этом рынке?}
{20033}{}{}
{20034}{}{Достаточно давно, чтобы большинство наших}
{20035}{}{конкурентов обратились в прах. Еще в 2050 караваны}
{20036}{}{наших отцов-основателей бороздили просторы штатов.}
{20037}{}{Масштабы у нас сейчас, конечно, не те, но качество}
{20038}{}{предоставляемых услуг только улучшилось.}
{20039}{}{}
{20040}{}{4. Насчет масштабов, кстати. Куда и откуда ходят}
{20041}{}{ваши караваны?}
{20042}{}{}
{20043}{}{Наши филиалы есть и в сверкающем Вегасе,}
{20044}{}{и в городе контрастов Рино, и в Солте с его}
{20045}{}{неподражаемой атмосферой декаданса. Наши караваны}
{20046}{}{ходят между ними регулярно и безостановочно,}
{20047}{}{как часы. А если хорошо попросить, то остановим}
{20048}{}{специально ради Вас у Ветра Войны с его вояками}
{20049}{}{или около стойбища краснокожих шайеннов.}
{20050}{}{}
{20051}{}{5. То, что надо! Но хватит ли у меня денег...}
{20052}{}{}
{20053}{}{Более демократичного подхода к клиентам не найти}
{20054}{}{на всей Невадской Пустоши - 1000 баксов и вперед!}
{20055}{}{К тому же мы никогда не забываем оказанных нам услуг}
{20056}{}{и предоставляем неплохую скидку своим друзьям.}
{20057}{}{}
{20058}{}{6. Дело за малым - когда же все-таки мы отправимся?}
{20059}{}{}
{20060}{}{Стартуем 1-го, 11-го и 21-го числа каждого месяца.}
{20061}{}{Опоздавших не ждем вне зависимости от причин;}
{20062}{}{задержались в борделе или в церкви - }
{20063}{}{это Ваши трудности.}
{20064}{}{**END-PAR**}
{20065}{}{**END-DISK**}

# Elron Bible
# GVAR_HOLODISK_ENCLAVE_ATOMIC
{21000}{}{--ПУСТО--}
{21001}{}{}
{21002}{}{**END-PAR**}
{21003}{}{**END-DISK**}