{100}{}{Leather Armor}
{101}{}{Your basic all leather apparel. Finely crafted from tanned brahmin hide.}
{200}{}{Metal Armor}
{201}{}{Polished metal plates, crudely forming a suit of armor.}
{300}{}{Power Armor}
{301}{}{A self-contained suit of advanced technology armor. Powered by a micro-fusion reactor, with enough fuel to last a hundred years.}
{400}{}{Knife}
{401}{}{A sharp-bladed cutting and stabbing weapon. Min ST: 2.}
{500}{}{Club}
{501}{}{Несмертельное оружие ближнего боя из резины и стали, применявшееся силами правопорядка. Min ST: 3.}
{600}{}{Sledgehammer}
{601}{}{A large hammer with big handle. Very popular with the muscular crowd. Min ST: 6.}
{700}{}{Spear}
{701}{}{A razor tipped polearm. The shaft is wooden, and the tip is worked steel. Min ST: 4.}
{800}{}{10mm Pistol}
{801}{}{A Colt 6520 10mm autoloading pistol. Each pull of the trigger will automatically reload the firearm until the magazine is empty. Single shot only, using the powerful 10mm round. Min ST: 3.}
{900}{}{10mm SMG}
{901}{}{H&K MP9 Submachinegun (10mm variant). A medium-sized SMG, capable of single shot and burst mode. Min ST: 4.}
{1000}{}{Hunting Rifle}
{1001}{}{A Colt Rangemaster semi-automatic rifle, in .223 caliber. Single-shot only. Min ST: 5.}
{1100}{}{Flamer}
{1101}{}{A Flambe 450 model flamethrower, varmiter variation. Fires a short spray of extremely hot, flamable liquid. Requires specialized fuel to work properly. Min ST: 6.}
{1200}{}{Minigun}
{1201}{}{A Rockwell CZ53 Personal Minigun. A multi-barrelled chaingun firing 5mm ammunition at over 60,000 RPM. Min ST: 7.}
{1300}{}{Rocket Launcher}
{1301}{}{A Rockwell BigBazooka rocket launcher. With the deluxe 3 lb. trigger. Fires AP or Explosive Rockets. Min ST: 6.}
{1400}{}{Explosive Rocket}
{1401}{}{A rocket with a large explosive warhead.}
{1500}{}{Plasma Rifle}
{1501}{}{A Winchester Model P94 Plasma Rifle. An industrial-grade energy weapon, firing superheated bolts of plasma down a superconducting barrel. Powered by Micro Fusion Cells. Min ST: 6.}
{1600}{}{Laser Pistol}
{1601}{}{A Wattz 1000 Laser Pistol. Civilian model, so the wattage is lower than military or police versions. Uses small energy cells. Min ST: 3.}
{1700}{}{Combat Armor}
{1701}{}{High tech armor, made out of advanced defensive polymers.}
{1800}{}{Desert Eagle .44}
{1801}{}{An ancient Desert Eagle pistol, in .44 magnum. Interest in late 20th century films made this one of the most popular handguns of all times. Min ST: 5.}
{1900}{}{Rock}
{1901}{}{It's a rock. Looks like Granite. Min ST: 1.}
{2000}{}{Crowbar}
{2001}{}{A very solid and heavy piece of metal, specially designed to exert leverage. Or pound heads. Min ST: 5.}
{2100}{}{Brass Knuckles}
{2101}{}{Hardened knuckle grip that is actually made out of steel. They protect your hand, and do more damage, in unarmed combat. Min ST: 1.}
{2200}{}{Карабин караванщика}
{2201}{}{Старая варминт-винтовка. Ствол укорочен, а приклад максимально облегчен, что делает оружие более легким и удобным, правда, в ущерб точности. Мин. сила: 4.}
{2300}{}{Assault Rifle}
{2301}{}{An AK-112 5mm Assault Rifle. An old military model, out of use around the time of the war. Can fire single-shot or burst, using the high velocity 5mm rounds. Min ST: 5.}
{2400}{}{Plasma Pistol}
{2401}{}{Glock 86 Plasma Pistol. Designed by the Gaston Glock AI. Shoots a small bolt of superheated plasma. Powered by a small energy cell. Min ST: 4.}
{2500}{}{Grenade (Frag)}
{2501}{}{A generic fragmentation grenade. Contains a small amount of high explosives, the container itself forming most of the damaging fragments. Explodes on contact. Min ST: 3.}
{2600}{}{Grenade (Plasma)}
{2601}{}{A magnetically sealed plasma delivery unit, with detonating explosives. Creates a blast of superheated plasma on contact. Min ST: 4.}
{2700}{}{Grenade (Pulse)}
{2701}{}{An electromagnetic pulse grenade, generating an intense magnetic field on detonation. Doesn't affect biological creatures. Contact fuze. Min ST: 4.}
{2800}{}{Страйкер}
{2801}{}{Пистолет-дробовик, разработанный африканским инженером. Использует патроны 12 калибра, заряжаемые в специальный барабан. При этом прекрасно управляется одной рукой. Мин. сила: 6.}
{2900}{}{10mm JHP}
{2901}{}{Ammunition. Caliber: 10mm, jacketed hollow-points}
{3000}{}{10mm AP}
{3001}{}{Ammunition. Caliber: 10mm, armor piercing.}
{3100}{}{.44 Magnum JHP}
{3101}{}{A brick of ammunition, .44 magnum caliber, hollow-points.}
{3200}{}{Flamethrower Fuel}
{3201}{}{A cylinder containing an extremely flammable liquid fuel for flamethrowers.}
{3300}{}{12 калибр Магнум}
{3301}{}{Вид боеприпасов довоенного производства для дробовика. Снаряжены более мощным порохом и увеличенным количеством картечи, чем классические патроны того же калибра.}
{3400}{}{.223 FMJ}
{3401}{}{A case of ammunition, .223 caliber, Full Metal Jacket.}
{3500}{}{5mm JHP}
{3501}{}{A brick of small, lightweight ammunition. Caliber: 5mm, jacketed hollow-point.}
{3600}{}{5mm AP}
{3601}{}{A brick of small caliber ammunition. 5mm armor piercing.}
{3700}{}{Rocket AP}
{3701}{}{A rocket shell, with a smaller explosive, but designed to pierce armor plating.}
{3800}{}{Small Energy Cell}
{3801}{}{A small, self-contained energy storage unit.}
{3900}{}{Micro Fusion Cell}
{3901}{}{A medium sized energy production unit. Self-contained fusion plant.}
{4000}{}{Stimpak}
{4001}{}{A healing chem. When injected, the chem provides immediate healing of minor wounds.}
{4100}{}{Money}
{4101}{}{Платежное средство в мире Пустошей, сохранившееся с довоенных времен. Пока еще жители Невады пользуются ими для обмена, но как знать - долго ли продлится эта традиция?}
{4200}{}{Fridge}
{4201}{}{A refrigerator. Out of coolant.}
{4300}{}{Ice Chest}
{4301}{}{On old-style ice chest. The hinges are in good working condition.}
{4400}{}{Ice Chest}
{4401}{}{On old-style ice chest. The hinges are in good working condition.}
{4500}{}{Throwing Knife}
{4501}{}{A knife, balanced specifically for throwing. Made of titanium, and laser sharpened. Min ST: 3.}
{4600}{}{Рация Читера}
{4601}{}{Это рация мистера Читера.}
{4700}{}{First Aid Kit}
{4701}{}{A small kit containing basic medical equipment. Bandages, wraps, antiseptic spray, and more.}
{4800}{}{RadAway}
{4801}{}{A chemical solution that bonds with radiation particles and passes them through your system. Takes time to work.}
{4900}{}{Antidote}
{4901}{}{A bottle containing a home-brewed antidote for poison. A milky liquid with floating pieces of radscorpion flesh.}
{5000}{}{Reserved Item}
{5001}{}{This is a reserved item. DO NOT USE.}
{5100}{}{Dynamite}
{5101}{}{A high explosive, consisting of nitroglycerin mixed with the absorbent substance kiselguhr. Includes a timer.}
{5200}{}{Geiger Counter}
{5201}{}{A Wattz Electronics C-Radz model Geiger Counter. Detects the presence and strength of radiation fields.}
{5300}{}{Ультрапротивоядие}
{5301}{}{Упаковка сильнодействующего противоядия. Скорее всего, имеет военное происхождение.}
{5400}{}{Stealth Boy}
{5401}{}{A RobCo Stealth Boy 3001 personal stealth device. Generates a modulating field that transmits the reflected light from one side of an object to the other.}
{5500}{}{Фильтр}
{5501}{}{Это мощный фильтр для очистки подземных вод. Используется в какой-то специализированной технике.}
{5600}{}{Антикурильщик}
{5601}{}{Просроченные на целое столетие таблетки для желающих бросить курить. Тело употребившего на короткое время становится сверхактивным, а голова необычайно проясняется.}
{5700}{}{---}
{5701}{}{---}
{5800}{}{---}
{5801}{}{---}
{5900}{}{Motion Sensor}
{5901}{}{A Wattz Electronics C-U model motion sensor. Detects the movement of biological material over a distance of meters using a tuned radar device.}
{6000}{}{Bookcase}
{6001}{}{A wooden bookcase.}
{6100}{}{Bookcase}
{6101}{}{A wooden bookcase.}
{6200}{}{Bookcase}
{6201}{}{A wooden bookcase.}
{6300}{}{Bookcase}
{6301}{}{A wooden bookcase.}
{6400}{}{Bookcase}
{6401}{}{A wooden bookcase.}
{6500}{}{Bookcase}
{6501}{}{A wooden bookcase.}
{6600}{}{Desk}
{6601}{}{A wooden desk.}
{6700}{}{Desk}
{6701}{}{A wooden desk.}
{6800}{}{Dresser}
{6801}{}{A wooden dresser.}
{6900}{}{Dresser}
{6901}{}{A wooden dresser.}
{7000}{}{Dresser}
{7001}{}{A wooden dresser.}
{7100}{}{Fruit}
{7101}{}{A strange piece of fruit. No preservatives and no additional food coloring added.}
{7200}{}{Кейс Бертолини}
{7201}{}{Бронированный чемоданчик, обтянутый кожей для солидности и запертый на кодовый замок. Внутри, должно быть, несметные богатства.}
{7300}{}{Big Book of Science}
{7301}{}{A set of books, containing information about different scientific fields.}
{7400}{}{Leather Jacket}
{7401}{}{A black, heavy leather jacket.}
{7500}{}{Tool}
{7501}{}{Классический мультитул. Представляет собой складные плоскогубцы с полыми ручками, в которых припрятано множество дополнительных полезных инструментов.}
{7600}{}{Deans Electronics}
{7601}{}{A study book on the field of electronics. A note on the cover says that it is for the "budding young electrician in everyone!"}
{7700}{}{Electronic Lockpick}
{7701}{}{A Wattz Electronics Micromanipulator FingerStuff electronic lockpick. For defeating electronic locks and security devices.}
{7800}{}{Fuzzy Painting}
{7801}{}{An image of a singer. Obviously, very old. The image has a felt coating that is still in good condition. Looks like it could be valuable.}
{7900}{}{Flare}
{7901}{}{A flare. Creates light for a short period of time. The paper is a little worn, but otherwise it is in good condition. Twist the top to activate it.}
{8000}{}{First Aid Book}
{8001}{}{A study book on the concepts and practical use of first aid skills.}
{8100}{}{Iguana-on-a-stick}
{8101}{}{A cooked iguana, roasted in it's own skin. Невкусно и малопитательно. К тому же вы не уверены, что она обитала в экологически чистой среде.}
{8200}{}{Ключ для куботана}
{8201}{}{Обыкновенный ключ, ничего значительного из себя не представляющий.}
{8300}{}{Ключ от подсобки}
{8301}{}{Ключ одного из братьев Квок от подсобки магазина в Солт-Лейк-Сити.}
{8400}{}{Lockpicks}
{8401}{}{A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks.}
{8500}{}{Plastic Explosives}
{8501}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. Includes a timer.}
{8600}{}{Scout Handbook}
{8601}{}{A book on the methods and ideals of Scouting. Very practical information regarding outdoor life.}
{8700}{}{Buffout}
{8701}{}{Highly advanced steroids. While in effect, they increase strength and reflexes. Very addictive.}
{8800}{}{Watch}
{8801}{}{An expensive watch. Not really working, but it still looks nice.}
{8900}{}{Серводвигатель}
{8901}{}{Мощный и точный электрический двигатель вращательного пошагового действия.}
{9000}{}{Набор для ухода}
{9001}{}{Суперклевый набор для ухода за телом в фирменном жестяном боксе. Пора пустить его в дело.}
{9100}{}{Doctor's Bag}
{9101}{}{This brown bag contains instruments and chems used by doctors in the application of their trade.}
{9200}{}{Scorpion Tail}
{9201}{}{The severed tail of a radscorpion.}
{9300}{}{Жучок}
{9301}{}{Древнее устройство для тайной прослушки.}
{9400}{}{Shotgun}
{9401}{}{A Winchester Widowmaker double-barreled 12-gauge shotgun. Short barrel, with mahogany grip. Min ST: 5.}
{9500}{}{12 ga. Shotgun Shells}
{9501}{}{Shotgun ammunition. This particular ammo is marked: "12-gauge shells, not for use by children under the age of 3."}
{9600}{}{Карта допуска}
{9601}{}{Огромная карта допуска для очень мощной двери.}
{9700}{}{Символ}
{9701}{}{Кусок отшлифованного камня с символикой штата Невада. Судя по штырям с обратной стороны, символ должен куда-то крепиться.}
{9800}{}{Металлолом}
{9801}{}{Куски различных металлов, а также канифоли и проводов. Возможно, что-то из этого поможет в ремонте.}
{9900}{}{Gold Locket}
{9901}{}{A valuable gold locket.}
{10000}{}{Radio}
{10001}{}{A camouflage painted model 2043B Radio Communicator, from the fine people at Wattz Electronics. Not operational.}
{10100}{}{Lighter}
{10101}{}{A silver butane lighter, in good condition.}
{10200}{}{Guns and Bullets}
{10201}{}{A gun rag. A magazine devoted to the practical use of firearms, and the occasional biased review.}
{10300}{}{Iguana bits}
{10301}{}{Some charred meat and vegetables on a cooking stick. Вкусно и питательно, но как знать - по каким вредным местам могли бегать эти игуаны?}
{10400}{}{Отчет Берча}
{10401}{}{Множество зашифрованной информации. Надпись на ярлыке: "Доставить в Хаб, Союз Рабочих-Атомщиков".}
{10500}{}{Ключ зажигания}
{10501}{}{Ключ зажигания автомобиля.}
{10600}{}{Nuka-Cola}
{10601}{}{A bottle of Nuka-Cola, the flavored softdrink of the post-nuclear world. Warm and flat.}
{10700}{}{Платяной шкаф}
{10701}{}{Деревянный платяной шкаф. В относительно неплохом состоянии.}
{10800}{}{Стол}
{10801}{}{Деревянный стол. В относительно неплохом состоянии.}
{10900}{}{Rad-X}
{10901}{}{Anti-radiation chems to be taken before exposure. No known side effects.}
{11000}{}{Psycho}
{11001}{}{An unique delivery system filled with strange and unknown chemicals of probably military origin. It is supposed to increase the combat potential of a soldier.}
{11100}{}{.44 magnum FMJ}
{11101}{}{A brick of ammunition, .44 magnum caliber, full metal jacket.}
{11200}{}{Дротик}
{11201}{}{Самодельный дротик для игры в дартс. Мин. сила: 1.}
{11300}{}{---}
{11301}{}{---}
{11400}{}{Кулон}
{11401}{}{Личный именной кулон с фотографией внутри.}
{11500}{}{Super Sledge}
{11501}{}{A Super Sledgehammer, manufactured using the finest weapons technology available. Includes a kinetic energy storage device, to increase knockback. Min ST: 5.}
{11600}{}{Ripper}
{11601}{}{A Ripper(tm) vibroblade. Powered by a small energy cell, the chainblade rips and tears into it's target. Min ST: 4.}
{11700}{}{Пистолет 9 мм}
{11701}{}{Пистолет под патрон калибра 9 мм. В отличном состоянии. Идеальная точность выстрела. Мин. сила: 2.}
{11800}{}{Laser Rifle}
{11801}{}{A Wattz 2000 Laser Rifle. Uses micro fusion cells for more powerful lasers, and an extended barrel for additional range. Min ST: 6.}
{11900}{}{Ключ от бункера}
{11901}{}{Ключ от калитки, ведущей в эвакуационный бункер Рино.}
{12000}{}{Помповый дробовик}
{12001}{}{Некогда очень популярное спортивное оружие 12 калибра. Мин. сила: 6.}
{12100}{}{9mm ball}
{12101}{}{A collection of ancient 9x19mm rounds. Heavy grease to preserve them from the environment. Standard bullets.}
{12200}{}{Пистолет 9 мм}
{12201}{}{Пистолет под патрон калибра 9 мм. Все еще в рабочем состоянии, но ему не помешают небольшой ремонт и чистка механизмов. Мин. сила: 2.}
{12300}{}{Ящик}
{12301}{}{Этот ящик был выкопан из земли.}
{12400}{}{Beer}
{12401}{}{Some type of home brewed beer.}
{12500}{}{Booze}
{12501}{}{Самодельный алкогольный напиток.}
{12600}{}{Чистая вода}
{12601}{}{Живительная питьевая вода, очищенная от нечистот и радиации. Используется при заболеваниях, отравлениях, оказании первой медицинской помощи и просто для питья.}
{12700}{}{Rope}
{12701}{}{A strong, thick line. About 45 feet in length.}
{12800}{}{Footlocker}
{12801}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{12900}{}{Footlocker}
{12901}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{13000}{}{Footlocker}
{13001}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{13100}{}{Footlocker}
{13101}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{13200}{}{Locker}
{13201}{}{A storage container.}
{13300}{}{Locker}
{13301}{}{A storage container.}
{13400}{}{Locker}
{13401}{}{A storage container.}
{13500}{}{Locker}
{13501}{}{A storage container.}
{13600}{}{Locker}
{13601}{}{A storage container.}
{13700}{}{Locker}
{13701}{}{A storage container.}
{13800}{}{Locker}
{13801}{}{A storage container.}
{13900}{}{Locker}
{13901}{}{A storage container.}
{14000}{}{---}
{14001}{}{---}
{14100}{}{---}
{14101}{}{---}
{14200}{}{Динамитная шашка}
{14201}{}{Небольшой, но мощный заряд динамита с зажигательным фитилем. Красуйся, детка!}
{14300}{}{Sniper Rifle}
{14301}{}{A DKS-501 Sniper Rifle. Excellent long range projectile weapon. Originally .308, this one is chambered in the more common .223 caliber. Min ST: 5.}
{14400}{}{Super Stimpak}
{14401}{}{An advanced healing chem. Very powerful. Superstims will cause a small amount of damage after a period of time due to powerful nature of the chemicals used.}
{14500}{}{Bookshelf}
{14501}{}{A wooden bookshelf.}
{14600}{}{Bookshelf}
{14601}{}{A wooden bookshelf.}
{14700}{}{Bookshelf}
{14701}{}{A wooden bookshelf.}
{14800}{}{Bookshelf}
{14801}{}{A wooden bookshelf.}
{14900}{}{Bookshelf}
{14901}{}{A wooden bookshelf.}
{15000}{}{Bookshelf}
{15001}{}{A wooden bookshelf.}
{15100}{}{Shelves}
{15101}{}{A set of wooden shelves.}
{15200}{}{Shelves}
{15201}{}{A set of wooden shelves.}
{15300}{}{Shelves}
{15301}{}{A set of wooden shelves.}
{15400}{}{Shelves}
{15401}{}{A set of wooden shelves.}
{15500}{}{Shelves}
{15501}{}{A set of wooden shelves.}
{15600}{}{Shelves}
{15601}{}{A set of wooden shelves.}
{15700}{}{Workbench}
{15701}{}{A workbench. Yep, your standard old, run of the mill, workbench. Looks nice sitting there, too.}
{15800}{}{Tool Board}
{15801}{}{This board holds a variety of tools above the popular workbench.}
{15900}{}{Molotov Cocktail}
{15901}{}{A home-made flammable grenade. Min ST: 3.}
{16000}{}{Cattle Prod}
{16001}{}{A Farmer's Best Friend model cattle prod from Wattz Electronics. Uses small energy cells for power. Min ST: 4.}
{16100}{}{UD M42}
{16101}{}{Пистолет-пулемет, схожий по конструкции с ПП Томпсона. Оснащен двумя магазинами, связанными по схеме "валет" для быстрой перезарядки. Не снискал популярности, но некоторое время активно использовался Управлением стратегических служб. Мин. сила: 6.}
{16200}{}{Пистолет-пулемет 9 мм}
{16201}{}{Простое и весьма надежное полицейское оружие, применявшееся в Неваде и Калифорнии. Обладает довольно вместительным магазином, который вставляется в рукоять. Мин. сила: 4.}
{16300}{}{12 калибр пулевой}
{16301}{}{Упаковка боеприпаса для дробовика. Патроны снаряжены пулями.}
{16400}{}{Бойцовский стимулятор}
{16401}{}{Допинг для бойцов ринга. Нагнетает организм, кратковременно повышая сопротивляемость урону и понижая болевой порог. Спустя некоторое время наносит удар по организму из-за вредных химикатов, входящих в его состав.}
{16500}{}{Люк самолета}
{16501}{}{Вы видите разорванный взрывом люк самолета.}
{16600}{}{Table}
{16601}{}{A generic table. Holds stuff off the ground.}
{16700}{}{Table}
{16701}{}{A generic table. Holds stuff off the ground.}
{16800}{}{Stuff}
{16801}{}{These are miscellaneous items, also known as "stuff".}
{16900}{}{Stuff}
{16901}{}{These are miscellaneous items, also known as "stuff".}
{17000}{}{Stuff}
{17001}{}{These are miscellaneous items, also known as "stuff".}
{17100}{}{Stuff}
{17101}{}{These are miscellaneous items, also known as "stuff".}
{17200}{}{Stuff}
{17201}{}{These are miscellaneous items, also known as "stuff".}
{17300}{}{Stuff}
{17301}{}{These are miscellaneous items, also known as "stuff".}
{17400}{}{Stuff}
{17401}{}{These are miscellaneous items, also known as "stuff".}
{17500}{}{Stuff}
{17501}{}{These are miscellaneous items, also known as "stuff".}
{17600}{}{Stuff}
{17601}{}{These are miscellaneous items, also known as "stuff".}
{17700}{}{Stuff}
{17701}{}{These are miscellaneous items, also known as "stuff".}
{17800}{}{Stuff}
{17801}{}{These are miscellaneous items, also known as "stuff".}
{17900}{}{Stuff}
{17901}{}{These are miscellaneous items, also known as "stuff".}
{18000}{}{Crate}
{18001}{}{A wooden crate filled with generic stuff.}
{18100}{}{Desk}
{18101}{}{A generic desk. Seen one desk, you've seen them all.}
{18200}{}{Desk}
{18201}{}{A generic desk.}
{18300}{}{Desk}
{18301}{}{A generic desk.}
{18400}{}{Desk}
{18401}{}{A generic desk.}
{18500}{}{Desk}
{18501}{}{A generic desk.}
{18600}{}{Desk}
{18601}{}{A generic desk.}
{18700}{}{Desk}
{18701}{}{A generic desk.}
{18800}{}{Locker}
{18801}{}{Старый контейнер для хранения вещей.}
{18800}{}{Locker}
{18901}{}{Старый контейнер для хранения вещей.}
{19000}{}{Уголовное дело}
{19001}{}{Изрядно подпорченная грызунами, временем и сыростью папка с материалами старого уголовного дела. Кое-что в ней еще можно разобрать.}
{19100}{}{Диск с саундтреком}
{19101}{}{Голографическая пленка с саундтреком "Fallout: Nevada".}
{19200}{}{Книга "Homo Ludens"}
{19201}{}{Довоенное издание трактата Йохана Хейзинги "Человек играющий". В книге рассматривается универсальная роль игры в становлении человеческой цивилизации.}
{19300}{}{Бэкап "Энциклопедии Fallout"}
{19301}{}{Диск, до отказа заполненный различной информацией по миру Fallout.}
{19400}{}{Библия Невады}
{19401}{}{Раритетный доисторический документ. Буквально *каждое* новое прочтение даст вам прилив опыта. Правда, весьма незначительного.}
{19500}{}{Успокоительное}
{19501}{}{Этот шприц Жане наполнен отличным "успокоительным".}
{19600}{}{Реклама дилижансов}
{19601}{}{На эту пленку записана рекламная информация о "Невадском экспрессе". Вы можете скопировать данные на свой Pip-Boy.}
{19700}{}{Box}
{19800}{}{Box}
{19900}{}{Box}
{20000}{}{Box}
{20100}{}{Box}
{20200}{}{Box}
{20300}{}{Box}
{20400}{}{Box}
{20500}{}{Flare}
{20501}{}{A flare. Creates light for a short period of time. The paper is a little worn, but otherwise it is in good condition. It is lit.}
{20600}{}{Dynamite}
{20601}{}{A high explosive, consisting of nitroglycerin mixed with the absorbent substance kiselguhr. Includes a timer, which is ticking.}
{20700}{}{Geiger Counter}
{20701}{}{A Wattz Electronics C-Radz model Geiger Counter. Detects the presence and strength of radiation fields. It is on.}
{20800}{}{Motion Sensor}
{20801}{}{A Wattz Electronics C-U model motion sensor. Detects the movement of biological material over a distance of meters using a tuned radar device. It is on.}
{20900}{}{Plastic Explosives}
{20901}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. Includes a timer, which is ticking.}
{21000}{}{Stealth Boy}
{21001}{}{A RobCo Stealth Boy 3001 personal stealth device. Generates a modulating field that transmits the reflected light from one side of an object to the other.}
{21100}{}{Bones}
{21101}{}{You see Ed. Ed's dead.}
{21200}{}{Чистая вода}
{21201}{}{Живительная питьевая вода, очищенная от нечистот и радиации фильтрами убежища 8.}
{21300}{}{Резервуар}
{21301}{}{Резервуар для сохранения жизнеспособности живых клеток или организма в целом.}
{21400}{}{Ящики для документов}
{21401}{}{Картотечный шкаф для различных документов.}
{21500}{}{Лабораторный стол}
{21501}{}{Стол для проведения опытов с химикатами.}
{21600}{}{Лабораторный стол}
{21601}{}{Стол для проведения опытов с химикатами.}
{21700}{}{Лабораторный стол}
{21701}{}{Стол для проведения опытов с химикатами.}
{21800}{}{Прах праотца}
{21801}{}{Противная смесь пепла, облученной земли и трупного компоста.}
{21900}{}{Бортовой компьютер}
{21901}{}{Важная компьютерная деталь, осуществляющая контроль над всеми системами поезда. В настоящий момент не работает.}
{22000}{}{Бортовой компьютер}
{22001}{}{Важная компьютерная деталь, осуществляющая контроль над всеми системами поезда.}
{22100}{}{Security Card}
{22101}{}{Именная ключ-карта, дающая пропуск в бункер радиостанции Лавлок.}
{22200}{}{Энкодер}
{22201}{}{Старое, но хорошо сохранившееся устройство. Его основное достоинство - оно все еще работает.}
{22300}{}{Дистанционный ключ}
{22301}{}{Это ключ для электронного замка. По нажатии на кнопку он выдает радиосигнал определенной частоты, действующий на коротком расстоянии.}
{22400}{}{Кабель}
{22401}{}{Бухта длинного высоковольтного кабеля.}
{22500}{}{Cat's Paw Magazine}
{22501}{}{An issue of Cat's Paw magazine.}
{22600}{}{Box Of Noodles}
{22601}{}{You have no idea what "Instant Spaghetti" means. But apparently you can cook it.}
{22700}{}{TV Dinner}
{22701}{}{A television dinner. You're not sure, but it doesn't look edible. You're not quite sure if it ever was.}
{22800}{}{Меласса}
{22801}{}{Бурая масса довольно сомнительного происхождения. Обладает неприятным запахом и какими-то непонятными примесями.}
{22900}{}{Фотонный пистолет}
{22901}{}{Это необычное оружие работает на основе квантового генератора. Мин. сила: 3.}
{23000}{}{Координаты свалки покрышек}
{23001}{}{На этой пленке записаны координаты свалки покрышек, расположенной недалеко от Вегаса.}
{23100}{}{Координаты свалки покрышек}
{23101}{}{На этой пленке записаны координаты свалки покрышек, расположенной недалеко от Вегаса.}
{23200}{}{Медицинская пижама}
{23201}{}{Пижама из особого синтетического волокна, которое стабилизирует тепловой и воздушный режим тела. До войны выдавалась больным после проведения химиотерапии.}
{23300}{}{Турбоплазменное ружье}
{23301}{}{Усовершенствованное плазменное ружье Винчестер P94. Плазменная камера оснащена тепловой обмоткой для ускорения процесса формирования плазменного заряда. Мин. сила: 6.}
{23400}{}{Spiked Knuckles}
{23401}{}{An improved version of the classic Brass Knuckles. The Spiked Knuckles do more damage, tearing into the flesh of your opponent in unarmed combat. Min ST: 1.}
{23500}{}{Power Fist}
{23501}{}{A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. Others are just scared. Powered by small energy cells. Min ST: 1.}
{23600}{}{Combat Knife}
{23601}{}{A high-quality combat knife, the Stallona is from SharpWit, Inc. The edge of this blade is guaranteed sharp for over a decade of use! Min ST: 2.}
{23700}{}{Газеты}
{23701}{}{Несколько выпусков газеты "Денвер пост". Среди материалов - обзор ядерных испытаний в Неваде, очередные свидетельства о наблюдениях НЛО в 100 км от Лас-Вегаса и реклама новых товаров от "Pretty & Glamour".}
{23800}{}{Пароли}
{23801}{}{Листок бумаги с паролями, написанными в спешке.                  Раз: 153-648-987.     Два: 045-896-509.     Три: 987-469-876.     Четыре: 013-486-498.}
{23900}{}{Бронежилет}
{23901}{}{Легкий армейский бронежилет с элементами разгрузки под всякое барахло. Защищает лишь часть торса, так как рассчитан на применение группами быстрого реагирования. В отличном состоянии.}
{24000}{}{Tesla Armor}
{24001}{}{This shining armor provides superior protection against energy attacks. The three Tesla Attraction Coil Rods disperse a large percentage of directed energy attacks.}
{24100}{}{Гражданская винтовка}
{24101}{}{Эта винтовка широко использовалась в различных военных конфликтах задолго до Великой Войны. После обновления американской армии излишки хлынули на гражданский рынок, где быстро укрепились в качестве доступного и надежного оружия. Мин. сила: 5.}
{24200}{}{Combat Shotgun}
{24201}{}{A Winchester City-Killer 12-gauge combat shotgun, bullpup variant. In excellent condition, it has the optional DesertWarfare environmental sealant modification for extra reliability. Min ST: 6.}
{24300}{}{Pot}
{24301}{}{A finely crafted clay pot.}
{24400}{}{Pot}
{24401}{}{A finely crafted clay pot.}
{24500}{}{Chest}
{24501}{}{Самодельный деревянный сундук.}
{24600}{}{Shelf}
{24601}{}{Самодельная металлическая полка, собранная из труб и гнутых железных листов.}
{24700}{}{Shelf}
{24701}{}{Самодельная металлическая полка, собранная из труб и гнутых железных листов.}
{24800}{}{Pot}
{24801}{}{A finely crafted clay pot.}
{24900}{}{Pot}
{24901}{}{A finely crafted clay pot.}
{25000}{}{Bones}
{25001}{}{A pile of human bones.}
{25100}{}{Погремушка}
{25101}{}{Связка консервных банок с гайками внутри них. Казалось бы, в этом хламе уже нет никакой пользы...}
{25200}{}{Балаклава}
{25201}{}{Обтягивающий головной убор, почти полностью скрывающий истинное лицо носителя. Может быть совместим со многими видами брони, однако ношение этого предмета наверняка заставит насторожиться случайного прохожего.}
{25300}{}{Fuel Cell Controller}
{25301}{}{This chip controls the flow of power into a car's electric engines. Many drivers quickly burnt out this chip through frequent rapid acceleration. Still a valuable part to have-- if you only had a car to install it in.}
{25400}{}{Топливный регулятор}
{25401}{}{Некоторые водители устанавливали этот регулятор, вдвое уменьшающий расход топлива, но большинство водителей не заботило, сколько жрут их машины. В конце концов, оно дешево стоит, и его много, так чего же волноваться?}
{25500}{}{Останки командира}
{25501}{}{Этот скелет лежит здесь очень давно. На нем одета истлевшая военная форма, а в черепе зияет здоровенная дыра.}
{25600}{}{Мятая бумажка}
{25601}{}{На этом клочке бумаги записаны сложные буквенно-числовые коды, которые вам ни о чем не говорят.}
{25700}{}{Парадная форма}
{25701}{}{Военная парадная форма для высоких чинов. Теперь это просто одежда.}
{25800}{}{Роллбар}
{25801}{}{Мобильная тележка для приготовления и продажи горячей еды прямо на улице.}
{25900}{}{Карамель}
{25901}{}{Сладкая конфетка с неожиданной полунаркотической начинкой. При упортреблении ощущается сонливость, голова тяжелеет, мышцы работают медленнее, но зато выражение лица становится мягче, а голос - менее грубым.}
{26000}{}{Не использовать}
{26001}{}{Не использовать!}
{26100}{}{"Месть Микки"}
{26101}{}{Ваше личное самодельное оружие ближнего боя. В чем-то могло бы конкурировать даже с заводскими шокерами. Мин. сила: 3.}
{26200}{}{Rubber Boots}
{26201}{}{An old pair of sturdy rubber work boots. They look durable enough to keep out sludge, at least for a while.}
{26300}{}{Сундук}
{26301}{}{Самодельный деревянный сундук.}
{26400}{}{Кладка яиц}
{26500}{}{Куртка охранника ранчо}
{26501}{}{Это очень прочная кожаная куртка, укрепленная металлическими вставками. Опознавательные знаки на спине и рукавах свидетельствуют, что носитель является охранником ранчо Оливера Лучиано.}
{26600}{}{Фляжка}
{26601}{}{Пустая металлическая фляжка с винтовой крышкой для хранения и переноски жидкости.}
{26700}{}{Пропуск}
{26701}{}{Обыкновенный пропуск с магнитной полосой.}
{26800}{}{H&K CAWS}
{26801}{}{The CAWS, short for Close Assault Weapons System, shotgun is a useful tool for close-range combat. The bullpup layout gives the weapon a short, easily handleable, length while still retaining enough barrel length for its high velocity shells. Min ST: 6.}
{26900}{}{Тяжелые пули}
{26901}{}{Горсть "удачно" отстрелянных пуль от патронов 12 калибра. Конкретно эту подборку еще можно использовать для изготовления новых патронов.}
{27000}{}{Robo Rocket Launcher}
{27001}{}{Only used by rocket equipped robots.}
{27100}{}{Broc Flower}
{27101}{}{Соцветие солнцелюбивого растения, произрастающего на каменистой почве. Применяется в традиционной медицине благодаря своим целебным свойствам.}
{27200}{}{Xander Root}
{27201}{}{Редкий корень тенелюбивого растения, произрастающего в рыхлой почве с достаточным увлажнением. Применяется в традиционной медицине благодаря своим целебным свойствам.}
{27300}{}{Healing Powder}
{27301}{}{A very powerful healing magic- though it will bring the feeling of sleep to your head.}
{27400}{}{Robo Rocket Ammo}
{27401}{}{Only used by rocket equipped robots.}
{27500}{}{Автомобиль}
{27501}{}{Этот автомобиль простоял под открытым небом больше десяти лет. Возможно, он еще мог бы проехать какое-то расстояние, но вы все равно не умеете водить.}
{27600}{}{Gecko Pelt}
{27601}{}{This is the dried and cured hide of an ordinary Gecko.}
{27700}{}{Golden Gecko Pelt}
{27701}{}{This is the dried and cured hide of a Golden Gecko.}
{27800}{}{Тостер-электроплитка}
{27801}{}{Комбинированный прибор от компании Ваттс Электроникс. Представляет собой гибрид электрической плитки с маленькой духовкой и тостером. Предназначен для использования в тесных трейлерах.}
{27900}{}{Голова Гилмора}
{27901}{}{Оторванная голова в мешке, которая некогда принадлежала Гэри Гилмору. Это - прямое доказательство его смерти.}
{28000}{}{Sharpened Spear}
{28001}{}{A razor tipped polearm. The shaft is wooden, and the tip is sharpened steel. Min ST: 4.}
{28100}{}{Шпилька}
{28101}{}{Шпилька для волос. Отлично гнется, принимая всевозможные формы.}
{28200}{}{Сварочный аппарат}
{28201}{}{Сварочный аппарат с электромагнитным принципом действия. Меры предосторожности: беречь от детей и электроприборов. Мин. сила: 6.}
{28300}{}{Tommy Gun}
{28301}{}{This Thompson M1928 submachine gun is a sinister looking weapon; every time you hold it, you have an urge to put on a fedora hat and crack your knuckles. The Thompson is well-fed by a large 50 round drum magazine. Min ST: 5.}
{28400}{}{Meat Jerky}
{28401}{}{These smoked and dried chunks of beast-flesh remain chewy-licious and even somewhat nutritious for years, and years, and years....}
{28500}{}{Тайник}
{28501}{}{Крепкий деревянный ящик, зарытый в землю по самую крышку.}
{28600}{}{"Белые стены"}
{28601}{}{Набор для покраски автомобильных шин. Мода на белые колеса в США была весьма распространенной во времена Великой Депрессии. С тех пор эта краска медленно сохла и в итоге превратилась в бесполезный камень.}
{28700}{}{Scoped Hunting Rifle}
{28701}{}{Nothing's better than seeing that surprised look on your target's face. The Loophole x20 Scope on this hunting rifle makes it easier than ever before. Accurate from first shot to last, no matter what kind of game you're gunning for. Min ST: 5.}
{28800}{}{Топливо для генератора}
{28801}{}{Мощный источник энергии, используемый в электрогенераторах Ваттс Электроникс. Если найдете иссякший генератор, то эта вещь окажется незаменимой.}
{28900}{}{Shovel}
{28901}{}{This is a shovel for digging ditches and stuff.}
{29000}{}{Robo Melee Weapon 1}
{29001}{}{For Floating Eye Robot. Does Electrical Damage.}
{29100}{}{Robo Melee Weapon 2}
{29101}{}{For Floating Eye Robot. Does Electrical damage.}
{29200}{}{Boxing Gloves}
{29201}{}{A pair of boxing gloves that smell faintly of sweat. They look like they have seen a lot of use: many old blood stains still remain.}
{29300}{}{Plated Boxing Gloves}
{29301}{}{Someone has "accidentally" slipped metal plates into these boxing gloves. It could technically be considered cheating, but you prefer to think of it as an increased opportunity to dispense bone-crunching damage.}
{29400}{}{Охотничий свисток}
{29401}{}{Самодельный охотничий свисток для подзыва мутировавших ящериц. Обладает весьма неприятным звучанием.}
{29500}{}{Побои Харрельсона}
{29501}{}{Используется садистами и извергами.}
{29600}{}{HK P90c}
{29601}{}{The Heckler & Koch P90c was just coming into use at the time of the war. The weapon's bullpup layout, and compact design, make it easy to control. The durable P90c is prized for its reliability, and high firepower in a ruggedly-compact package. Min ST: 4.}
{29700}{}{Усовершенствованный гранатомет}
{29701}{}{Гранатомет Роквелла "Супербазука", оснащенный более совершенным компенсатором отдачи. Мин. сила: 5.}
{29800}{}{Ключ от коммуникаций}
{29801}{}{Необычной формы ключ-перевертыш, который следует раскрыть после размещения внутри замочной скважины.}
{29900}{}{Pipe Rifle}
{29901}{}{This is a hand-made single shot rifle. Min ST: 5.}
{30000}{}{"Дикарь"}
{30001}{}{Однозарядный дробовик с укороченным стволом. Хотя это оружие уже весьма изношено и морально устарело, его неоспоримый плюс - быстрая перезарядка. Мин. сила: 4.}
{30100}{}{Полотенце}
{30101}{}{Сконструированное в лаборатории "Pretty & Glamour" полотенце со встроенным чипом, определяющим сухость кожи. Информация на бирке запрещает курить вблизи полотенца.}
{30200}{}{Посмертная записка}
{30201}{}{"Тому, кто меня убьет: я вступил на путь разбоя потому, что Чистый Город аннексировал мою землю. Урожай забирают подонки из Вегаса, мне нечем себя кормить. Я так больше не могу."}
{30300}{}{Пустой диск}
{30301}{}{На этот диск вам необходимо записать информацию со всех мониторов на поверхности.}
{30400}{}{Deck of "Tragic" Cards}
{30401}{}{This is a deck of cards for a collectible card game. Looks like it could be an expensive hobby if you got hooked.}
{30500}{}{Ключ к компьютеру}
{30501}{}{Магнитный ключ доступа от компьютерного терминала в Ветре Войны.}
{30600}{}{Карта допуска лаборатории "Альфа"}
{30601}{}{Электронная карта допуска первого уровня в ангаре Зоны 51.}
{30700}{}{Остатки патронов}
{30701}{}{Компоненты старых патронов: гильзы, пули и порох, бережно собранный по крупицам. Что-то из этого еще можно использовать в производстве нового боезапаса.}
{30800}{}{Суперремнабор}
{30801}{}{Впечатляющий набор инструментов линии "Скорая помощь".}
{30900}{}{Старый голодиск}
{30901}{}{Голодиск, найденный в заброшенном поселении близ Города Убежища. Информация записана устаревшим кодом, для прочтения требуется дешифровка.}
{31000}{}{Довоенный виски}
{31001}{}{Крепкий алкогольный напиток с весьма достойной выдержкой. Очень высоко ценится в постядерной Неваде по сравнению с другими видами алкоголя.}
{31100}{}{Вокас}
{31101}{}{Орехи мутировавшей водной лилии, произрастающей в соленых водах рядом с Солт-Лейком. Адаптация под местные условия даровала орехам уникальное свойство - они выводят из организма радиочастицы.}
{31200}{}{Буксировочный трос}
{31201}{}{Прочный автомобильный трос длиной примерно 18 футов. На его концах привязаны карабины.}
{31300}{}{.44 Magnum Revolver}
{31301}{}{Being that this is the most powerful handgun in the world, and can blow your head clean-off, you've got to ask yourself one question. Do I feel lucky? Well, do ya punk?. Min ST: 5.}
{31400}{}{Condom (Blue Package)}
{31401}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one is ribbed for her pleasure.}
{31500}{}{Condom (Green package)}
{31501}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one contains phosphorous green dye #2 and is slathered in spermicidal lubricant for added protection.}
{31600}{}{Condom (Red Package)}
{31601}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one contains phosophorous red dye #5 and has a yummy cinnamon bun flavor... or so you heard.}
{31700}{}{Cosmetics Case}
{31701}{}{This is a genuine Mary May brand cosmetics case.}
{31800}{}{Empty Hypodermic}
{31801}{}{This is an empty hypodermic.}
{31900}{}{Switchblade}
{31901}{}{The blade of this small knife is held by a spring. When a button on the handle is pressed, the blades shoots out with a satisfying "Sssssshk" sound. Min ST: 1.}
{32000}{}{Sharpened Pole}
{32001}{}{A wood pole sharpened at one end. Min ST: 4.}
{32100}{}{Оторванная голова}
{32101}{}{Человеческая голова в мешке. Ранее принадлежала жителю Прово, теперь она ваша по праву.}
{32200}{}{Таинственное устройство}
{32201}{}{Высокотехнологичное устройство неясного для вас назначения.}
{32300}{}{Глушитель сигнала}
{32301}{}{Любому действию всегда есть противодействие. Это высокотехнологичное устройство предназначено для подавления радиосигнала и вывода из строя электронных узлов его источника. Радиус действия восемь миль.}
{32400}{}{Дезинфекция}
{32401}{}{Таблетки полностью уничтожают различную биологическую заразу в воде и похожих жидкостях. С их помощью можно очистить даже воду из канализации и пить ее без вреда для здоровья.}
{32500}{}{Dice}
{32501}{}{A standard pair of gambling dice. It'd be cool to get a fuzzy pair for your car.}
{32600}{}{Loaded Dice}
{32601}{}{A pair of loaded dice. Don't be flashing these around the casino.}
{32700}{}{Диск драгдилера}
{32701}{}{На этом диске содержатся какие-то радиочастоты. Без рабочей рации тут не разберешься.}
{32800}{}{Записи регистратора}
{32801}{}{Голодиск с записями регистратора событий робота-охранника, сопровождавшего дилижанс дилижанс из Солт-Лейка в Нью-Рино. Возможно, здесь сохранилась некоторая информация, правда, в зашифрованном виде. Ваш Pip-Boy мог бы ее прочитать.}
{32900}{}{Удавка}
{32901}{}{Обыкновенная серебряная гитарная струна, настраиваемая на ноту ре. Впрочем, ею уже давно не пользовались по назначению.}
{33000}{}{Сундучок}
{33001}{}{Старый проржавевший сундучок, предназначенный для хранения вещей.}
{33100}{}{"Супернаука"}
{33101}{}{Пожалуй, единственный довоенный журнал, сплошь посвященный теме энергетического оружия. Расхватывался читателями, как горячие пирожки, поэтому найти его - большая удача!}
{33200}{}{M3A1 "Grease Gun" SMG}
{33201}{}{This submachine gun filled National Guard arsenals after the Army replaced it with newer weapons. However, the "Grease Gun" was simple and cheap to manufacture so there are still quite a few still in use. Min ST: 4.}
{33300}{}{Heart Pills}
{33301}{}{These pills are used by people with heart problems.}
{33400}{}{"Коновал"}
{33401}{}{A hypodermic needle full of powerful poison.}
{33500}{}{Чемоданчик курьера}
{33501}{}{Этот чемоданчик перевозил тайный курьер из Вегаса в Рино. Вы не смогли его открыть. Интересно, что же в нем?}
{33600}{}{Обрез Максона}
{33601}{}{Вы торгуетесь с Максоном за этот предмет.}
{33700}{}{Ментаты}
{33701}{}{Таблетки из химического вещества, расширяющего сознание. Улучшает функции головного мозга, связанные с памятью, а также ускоряет некоторые умственные процессы. Вызывает сильное привыкание.}
{33800}{}{Фруктовые ментаты}
{33801}{}{Таблетки из химического вещества, расширяющего сознание. Улучшает функции головного мозга, связанные с памятью, а также ускоряет некоторые умственные процессы. Не вызывает привыкания.}
{33900}{}{Записи замурованного}
{33901}{}{Дневник человека, замурованного в мини-убежище Солт-Лейка. Очень животрепещущее описание.}
{34000}{}{Останки}
{34001}{}{Истлевшие останки человека, умершего в расслабленной позе. Пролежали, возможно, не одно десятилетие.}
{34100}{}{Голодиск робота}
{34101}{}{На голодиске содержится информация о состоянии окружающей среды, которую собрал робот-разведчик за время своего путешествия.}
{34200}{}{Путевые заметки}
{34201}{}{Это беглые наброски жизнеописания Джедедии Смита. Автор описывает быт и уклад жизни посещенных им поселений.}
{34300}{}{Яблочный пирог}
{34301}{}{М-м, пирог! Из маисового теста и мутафруктов.}
{34400}{}{Gravesite}
{34500}{}{Gravesite}
{34600}{}{Gravesite}
{34700}{}{Gravesite}
{34800}{}{Уродливая броня}
{34801}{}{Довольно уродливая броня. Тот, кто это сделал, видимо, был не в своем уме... или рассчитывал на устрашение своим видом.}
{34900}{}{Полицейская броня}
{34901}{}{Упрощенная версия боевой брони для использования в рядах полиции.}
{35000}{}{Пулемет M2041}
{35001}{}{Ручной пулемет с воздушным охлаждением быстросменного ствола - реинкарнация старой коммерческой разработки под современные требования. Часть пулеметов после выпуска ушла "налево", для продажи и обмена странам "третьего мира". Мин. сила: 6.}
{35100}{}{Кий}
{35101}{}{Обыкновенный бильярдный кий. Ничего особенного.}
{35200}{}{H&K G11}
{35201}{}{This gun revolutionized assault weapon design. The weapon fires a caseless cartridge consisting of a block of propellant with a bullet buried inside. The resultant weight and space savings allow this weapon to have a very high magazine capacity. Min ST: 5.}
{35300}{}{Пригласительный билет}
{35301}{}{Этот билет дает обладателю разовый бесплатный пропуск в ночной клуб Нью-Рино.}
{35400}{}{Pancor Jackhammer}
{35401}{}{The Jackhammer, despite its name, is an easy to control shotgun, even when fired on full automatic. The popular bullpup design, which places the magazine behind the trigger, makes the weapon well balanced & easy to control. Min ST: 6.}
{35500}{}{Винтовой пистолет-пулемет}
{35501}{}{Это необычное оружие оснащено шнековым магазином, в котором умещается огромное количество патронов. Мин. сила: 2.}
{35600}{}{CL 3000}
{35601}{}{Переносное лабораторное оборудование, включающее центрифугу и жидкостный нагреватель. Вы могли бы пользоваться им для приготовления медикаментов в полевых условиях.}
{35700}{}{.45 Caliber}
{35701}{}{Ammunition. .45 Caliber.}
{35800}{}{2mm EC}
{35801}{}{Ammunition.}
{35900}{}{4.7mm Caseless}
{35901}{}{Ammunition. Caliber: 4.7mm, caseless.}
{36000}{}{Энергоячейка}
{36001}{}{Необычная единица хранения энергии.}
{36100}{}{---}
{36101}{}{---}
{36200}{}{Граната 40 мм}
{36201}{}{Кассета со снарядами для ручного гранатомета.}
{36300}{}{Патроны калибра 0,30}
{36301}{}{Винтовочный вид боеприпасов. Калибр: 0,30.}
{36400}{}{Марки}
{36401}{}{Очень странные марки серии "Розовый слон". Их назначение столь же непонятно, сколько непонятно и то, как абсорбирующая бумага сохранилась за все эти долгие годы.}
{36500}{}{Plant Spike}
{36501}{}{An organic seed-spike that the carnivorous plants spit at potential food or seed carriers.}
{36600}{}{---}
{36601}{}{---}
{36700}{}{Ammo Crate}
{36800}{}{Ammo Crate}
{36900}{}{Ammo Crate}
{37000}{}{Ammo Crate}
{37100}{}{Claw}
{37101}{}{Claw}
{37200}{}{Claw}
{37201}{}{Claw}
{37300}{}{Карта допуска в бункер}
{37301}{}{An electronic security key от внутренней двери бункера в Рино.}
{37400}{}{Gravesite}
{37500}{}{Gravesite}
{37600}{}{Gravesite}
{37700}{}{Станок для снаряжения патронов}
{37701}{}{Мобильное самодельное устройство для снаряжения патронов при наличии пороха, гильз и пуль. Специальное реле позволяет настроить пресс под различные калибры.}
{37800}{}{Станок для снаряжения патронов (доп.)}
{37801}{}{Мобильное самодельное устройство для снаряжения патронов при наличии пороха, гильз и пуль. Специальное реле позволяет настроить пресс под различные калибры. Дополнен битами для патронов бронебойного типа.}
{37900}{}{Leather Armor Mark II}
{37901}{}{An enhanced version of the basic leather armor with extra layers of protection. Finely crafted from tanned brahmin hide.}
{38000}{}{Metal Armor Mark II}
{38001}{}{Polished metal plates, finely crafted into a suit of armor.}
{38100}{}{Combat Armor Mark II}
{38101}{}{High tech armor, made out of advanced defensive polymers.}
{38200}{}{Flamethrower Fuel MKII}
{38201}{}{This flamethrower fuel uses an advanced super-burn mix.}
{38300}{}{Не использовать}
{38301}{}{Не использовать!}
{38400}{}{Wrench}
{38401}{}{A typical wrench used by mechanics. Min ST: 3.}
{38500}{}{Sawed-Off Shotgun}
{38501}{}{Someone took the time to chop the last few inches off the barrel and stock of this shotgun. Now, the wide spread of this hand-cannon's short-barreled shots makes it perfect for short-range crowd control. Min ST: 5.}
{38600}{}{Baseball bat}
{38601}{}{This all-American, hardwood, baseball bat Оборудована шипами для усиления удара. Мин. сила: 4.}
{38700}{}{M60}
{38701}{}{This relatively light machine gun was prized by militaries around for world for its high rate of fire. This reliable, battlefield-proven design, was used on vehicles and for squad level fire-support. Min ST: 7.}
{38800}{}{---}
{38801}{}{---}
{38900}{}{Avenger Minigun}
{38901}{}{Rockwell designed the Avenger as the replacement for their aging CZ53 Personal Minigun. The Avenger's design improvements include improved, gel-fin, cooling and chromium plated barrel-bores. This gives it a greater range and lethality. Min ST: 7.}
{39000}{}{Solar Scorcher}
{39001}{}{Without the sun's rays to charge this weapon's cpacitors this gun can't light a match. However, in full daylight, the experimental photo-electric cells that power the Scorcher allow it to turn almost anything into a crispy critter. Min ST: 3.}
{39100}{}{Винтовка Келли}
{39101}{}{Личная винтовка Келли. Сильно изношенное, но по-прежнему надежное оружие. Мин. сила: 5.}
{39200}{}{M72 Gauss Rifle}
{39201}{}{The M72 rifle is of German design. It uses an electromagnetic field to propel rounds at tremendous speed... and pierce almost any obstacle. Its range, accuracy and stopping power is almost unparalleled. Min ST: 6.}
{39300}{}{Пулемет 0,223}
{39301}{}{Ручной пулемет под винтовочные патроны. Мин. сила: 6.}
{39400}{}{PPK12 Gauss Pistol}
{39401}{}{Praised for its range and stopping power, the PPK12 Gauss Pistol is of German design. The pistol uses an electromagnetic field to propel rounds at tremendous speed and punch through almost any armor. Min ST: 4.}
{39500}{}{M16K}
{39501}{}{Пистолет-пулемет, спроектированный фирмой "Ла Франс" в Сан-Диего на основе автомата M16. Некоторое время был популярен среди отрядов специального назначения и полиции в отдельных штатах. Мин. сила: 4.}
{39600}{}{YK32 Pulse Pistol}
{39601}{}{The YK32 is an electrical pulse weapon that was developed by the Yuma Flats Energy Consortium. Though powerful, the YK32 was never considered a practical weapon due to its inefficient energy usage and bulky design. Min ST: 3.}
{39700}{}{YK42B Pulse Rifle}
{39701}{}{The YK42B is an electrical pulse weapon that was developed by the Yuma Flats Energy Consortium. It is considered a far superior weapon to the YK32 pistol, having a greater charge capacity and range. Min ST: 3.}
{39800}{}{.44 Magnum (Speed Load)}
{39801}{}{A .44 Magnum Revolver with a speed loader. Min ST: 5.}
{39900}{}{Super Cattle Prod}
{39901}{}{A Farmer's Best Friend model cattle prod from Wattz Electronics. This model has been upgraded to increase the electrical discharge. Min ST: 4.}
{40000}{}{Improved Flamer}
{40001}{}{A Flambe 450 model flamethrower, varmiter variation. Fires a short spray of extremely hot, flamable liquid. Requires specialized fuel to work properly. This model has been modified to fire a hotter mixture which causes greater combustibility. Min ST: 6.}
{40100}{}{Laser Rifle (Ext. Cap.)}
{40101}{}{This Wattz 2000 laser rifle has had its recharging system upgraded and a special recycling chip installed that reduces the drain on the micro fusion cell by 50%. Min ST: 6.}
{40200}{}{Magneto-Laser Pistol}
{40201}{}{This Wattz 1000 laser pistol has been upgraded with a magnetic field targeting system that tightens the laser emission, giving this pistol extra penetrating power. Min ST: 3.}
{40300}{}{Винтовка Генри}
{40301}{}{Старый, но все еще верный карабин, сконструированный в эпоху "золотой лихорадки". Будучи популярным спортивным оружием, объектом коллекционирования и показухи, производился вплоть до Великой Войны для гражданского населения. Мин. сила: 4.}
{40400}{}{Desert Eagle (Exp. Mag.)}
{40401}{}{An ancient Desert Eagle pistol, in .44 magnum. Interest in late 20th century films made this one of the most popular handguns of all times. This one has been equipped with an expanded magazine for longer fun and games! Min ST: 5.}
{40500}{}{Assault Rifle (Exp. Mag.)}
{40501}{}{This Assault Rifle has an extended, military sized, ammunition clip. The expanded magazine capacity makes it more fun than ever to Spray-and-Pray. Min ST: 5.}
{40600}{}{Plasma Pistol (Ext. Cap.)}
{40601}{}{This Glock 86 Plasma Pistol has had its magnetic housing chamber realigned to reduce the drain on its energy cell. Its efficiency has doubled, allowing it to fire more shots before the battery is expended. Min ST: 4.}
{40700}{}{Mega Power Fist}
{40701}{}{A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. This one has upgraded power servos for increased strength. Powered by small energy cells. Min ST: 1.}
{40800}{}{Field Medic First Aid Kit}
{40801}{}{A small kit containing basic emergency medical equipment. Bandages, wraps, antiseptic spray, and more.}
{40900}{}{Paramedics Bag}
{40901}{}{This bag contains instruments and chems used by paramedics in the field. The tools contained are specifically designed for high trauma and emergency cases.}
{41000}{}{Expanded Lockpick Set}
{41001}{}{A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks. This set also includes some special tools for more difficult mechanical locking mechanisms.}
{41100}{}{Electronic Lockpick MKII}
{41101}{}{This is the second generation Wattz Electronics Micromanipulator FingerStuff electronic lockpick. For defeating electronic locks and security devices. This Mark II version includes updated software and interface tools.}
{41200}{}{Оружейные детали}
{41201}{}{Детали от различных видов огнестрельного оружия. Можно использовать в качестве расходного материала для починки или улучшения другого оружия.}
{41300}{}{Фотография девушки}
{41301}{}{Перед вами фотография голой девушки с прожженными отверстиями на месте глаз. Кажется, девушка была красивой. На обороте написано "Вирджиния Стрит, 75".}
{41400}{}{Ключ от подвала}
{41401}{}{Стандартный ключ от дверного замка на станции Нью-Рино.}
{41500}{}{Яйцо гекко}
{41501}{}{Оно могло бы дать в будущем милого и забавного зверька. Но вместо этого пойдет на прокорм каких-нибудь богачей.}
{41600}{}{Дань Страйкера}
{41601}{}{Металлический дипломат, обтянутый кожей брамина. Предназначен для Большого Луи. Содержимое дипломата неизвестно.}
{41700}{}{Лабораторный шлем}
{41701}{}{Когда-то этот защитный шлем входил в комплект специального герметичного комбинезона. Теперь он остался единственной его уцелевшей частью.}
{41800}{}{Крысоловка}
{41801}{}{Древнее механическое устройство. Превосходно против мелкой и неразумной живности.}
{41900}{}{Закуска из богомола}
{41901}{}{Приготовленная правильным образом лапа богомола.}
{42000}{}{"Слепая ярость"}
{42001}{}{Изношенный меч с деревянными ножнами, замаскированный под трость. Хотя качество стали оставляет желать лучшего, это оружие явно не раз спасало жизнь своему владельцу. Мин. сила: 3.}
{42100}{}{Пороховая граната}
{42101}{}{Самодельная ручная граната с химическим детонатором. Снаряжена поражающими элементами вокруг мощного порохового запала.}
{42200}{}{Шампунь}
{42201}{}{Непочатый флакон с шампунем. До войны это была довольно известная торговая марка.}
{42300}{}{Рутбир}
{42301}{}{Приготовленный в полевых условиях сорт корневого пива. Немного хмелит, зато обладает целебными свойствами.}
{42400}{}{Тактическая ракета}
{42401}{}{Редкий боеприпас - ракета для гранатомета с обогащенным ураном. Приберегите для особого случая.}
{42500}{}{Пост смотрителя}
{42501}{}{Пост смотрителя с давно разложившимся трупом, от которого по всему посту разрослась биологическая зараза.}
{42600}{}{Ящики}
{42601}{}{Два больших деревянных ящика. Надписи на бортах уже не различить.}
{42700}{}{Flame Breath}
{42800}{}{Вещи знахаря}
{42801}{}{Личные вещи лекаря Нискигвана. Среди них имеются различные инструменты, полезные в сборе и обработке лекарственных трав.}
{42900}{}{Gold Tooth}
{42901}{}{Вы выбили этот золотой зуб из челюсти Туко. Теперь он ваш.}
{43000}{}{Конечность богомола}
{43001}{}{Хрустящая лапа от насекомого гигантских размеров.}
{43100}{}{Приклад}
{43101}{}{Специальный приклад-кобура для пистолета 9 мм. Внутри также имеются все необходимые детали и инструменты для чистки и простого ремонта оружия.}
{43200}{}{Куртка байкера}
{43201}{}{Потертая боевая куртка с нашивкой байкеров. Имеет прослойку из фольги и металла, которая усиливает защиту от лазерного и плазменного воздействия.}
{43300}{}{Амулет шайеннов}
{43301}{}{Тотемный амулет вождя племени шайеннов. Когда вы держите его в руках, сама удача улыбается вам.}
{43400}{}{Wagon}
{43401}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{43500}{}{Wagon}
{43501}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{43600}{}{Deck of Cards}
{43601}{}{A standard set of playing cards.}
{43700}{}{Pack of Marked Cards}
{43701}{}{Стандартный набор игральных карт, имеющий особые неприметные отметки на "рубашке".}
{43800}{}{Карта допуска к реактору}
{43801}{}{Электронная карта допуска на реакторный уровень в ангаре V9.}
{43900}{}{Рецепт: "Закуска из богомола"}
{43901}{}{Рецепт приготовления закуски из ноги богомола, вымоченной в пиве и затем зажаренной с кусочками мутафрукта.}
{44000}{}{Браминье молоко}
{44001}{}{Питательное молочко брамина. Содержит множество полезных веществ, которые компенсируются... радиоактивностью.}
{44100}{}{Именная собачья бирка}
{44101}{}{Бирка с именем собаки и ее хозяина.}
{44200}{}{Предохранитель}
{44201}{}{Тонкая проволока в вакуумной стеклянной оболочке, отвечающая за безопасность оборудования при аварийном превышении тока.}
{44300}{}{Отравленный самогон}
{44301}{}{Бутылка самогона, отравленного смертельным ядом.}
{44400}{}{"Дело диверсанта"}
{44401}{}{Популярные очерки старого вояки Меддокса, ветерана диверсионно- разведывательных групп. Автор раскрывает методы ведения диверсионных операций, рассказывает о ловушках и устройствах массового поражения.}
{44500}{}{Долговая расписка}
{44501}{}{Расписка за карточные долги перед казино "Эльдорадо".}
{44600}{}{Cтиратель памяти}
{44601}{}{Эта технология позволяет стереть определенное воспоминание короткой продолжительности и заменить его другим, иллюзорным. Так из врага можно сделать друга. Но если это не удастся, то такие шутки вам не простят.}
{44700}{}{Договор о покупке рабов}
{44701}{}{Это ваш договор с гильдией работорговцев Вегаса о приобретении крупной партии рабов.}
{44800}{}{Записка Эрику}
{44801}{}{"Эрик, тебя хотят увести драться на ринг. Ты знаешь, что это значит. Но это нам только на руку! Когда тебя выведут из загона, начнется перестрелка. В этот момент беги со всех ног! За меня не волнуйся. Твой брат Гарет".}
{44900}{}{Do not use}
{44901}{}{Do not use!}
{45000}{}{---}
{45001}{}{---}
{45100}{}{Записка старателя}
{45101}{}{Эта записка находилась у трупа старателя в Хоторне. В ней от руки написано: "Если я погибну, передайте моей семье в Рино, что я их люблю". Подпись: Роберт Гейт.}
{45200}{}{Обеденный жетон}
{45201}{}{Этот жетон с символикой ядер-колы сделан из старой покерной фишки.}
{45300}{}{Ящик для бутылок}
{45301}{}{Этот деревянный ящик предназначен для безопасной перевозки стеклянных бутылок.}
{45400}{}{Повозка}
{45401}{}{Эта караванная повозка подготовлена специально для перевозки бутылок.}
{45500}{}{Car Trunk}
{45501}{}{The trunk is a great place to store your stuff.}
{45600}{}{Ключи Большого Луи}
{45601}{}{Связка ключей от базы рейдеров в Лавлоке.}
{45700}{}{Расписка Дэвида и Нормана}
{45701}{}{Расписка, по которой Норман обязуется выплатить Дэвиду свои игорные долги в виде собственного надпочечника.}
{45800}{}{Дело Илая Горбински}
{45801}{}{The label reads: "Дело Илая Горбински, предварительный отчет".}
{45900}{}{---}
{45901}{}{---}
{46000}{}{Сообщение Джея}
{46001}{}{На этом голодиске записано сообщение, адресованное вам лично.}
{46100}{}{Отчет о дезертирах}
{46101}{}{Голодиск из Хоторна с отчетом о группе беглых военных.}
{46200}{}{---}
{46201}{}{---}
{46300}{}{Медицинский отчет}
{46301}{}{The label reads: "Рекомендации по обслуживанию головы бывшего президента".}
{46400}{}{Записи гражданина}
{46401}{}{Дневниковые записи жителя правительственного убежища. Довольно любопытное чтиво. Этот текст можно скопировать в ваш Pip-Boy.}
{46500}{}{"Исход"}
{46501}{}{Голодиск с информацией о проекте правительственного убежища.}
{46600}{}{Пульт управления}
{46601}{}{Пульт дистанционного управления силовыми полями. Зона действия 12 шагов.}
{46700}{}{Капот}
{46800}{}{Сэндвич}
{46801}{}{Питательный сэндвич, сделанный из мяса брамина под густым темно-желтым соусом, зажатого с двух сторон аппетитной мягкой булочкой и листком какой-то зелени. Очень вкусно.}
{46900}{}{Rot Gut}
{46901}{}{A very strong liquor or cleaning fluid, you decide.}
{47000}{}{Дробитель}
{47001}{}{Большой молот с массивной рукоятью, снабженный самодельными шипами на обухе для усиления урона. Для приготовления отбивных лучше взять молоток меньшего размера. Мин. сила: 6.}
{47100}{}{Пособие по нейрохирургии}
{47101}{}{Очень редкое пособие для высоко- квалифицированных хирургов. Похоже, что здесь собрана очень важная информация, но она настолько научна и сложна, что для изучения понадобится очень много времени и знаний.}
{47200}{}{Взгляд в лицо смерти}
{47201}{}{Вы смелы, и потому вам проще сориентироваться, когда вокруг творится сплошной кавардак.}
{47300}{}{Облученная ядер-кола}
{47301}{}{Дивный довоенный напиток в немного грязной бутылке. Обладает чудесным привкусом и весьма сомнительным свечением в темноте.}
{47400}{}{Магнито-лазерный пистолет М2}
{47401}{}{Этот лазерный пистолет Ваттс 1000 подвергся различным усовершенствованиям, которые увеличили его мощность на 50%, однако в ущерб дальнобойности и энергопотреблению. Мин. сила: 3.}
{47500}{}{Не использовать}
{47501}{}{Не использовать!}
{47600}{}{"Кровавая Мэри"}
{47601}{}{Сильноалкогольный коктейль. Очень кстати после тяжелого рабочего дня в конце недели.}
{47700}{}{Кейс с документами}
{47701}{}{В кейсе лежат отчеты радиостанции Лавлок. В них часто упоминается убежище 8. К сожалению, большая их часть зашифрована, но остальное вы можете ввести в свой Pip-Boy.}
{47800}{}{---}
{47801}{}{---}
{47900}{}{Отравляющий газ}
{47901}{}{Баллон высокого давления с крайне опасным газом. Был предназначен для уничтожения всего живого в ангаре Зоны 51 в случае чрезвычайной ситуации.}
{48000}{}{Хороший сон}
{48001}{}{Хорошенько отоспавшись в отеле, вы получаете бонус +1 к Восприятию и Интеллекту на час.}
{48100}{}{Обострение внимания}
{48101}{}{Посещение мест с отличным обзором временно повышает ваше Восприятие.}
{48200}{}{Турбо-кола}
{48201}{}{Наркотик самодельного производства. Вызывает короткий всплеск адреналина, после которого мощно бьет по артериям, вызывая сильный жар.}
{48300}{}{Фотоаппарат}
{48301}{}{Древнее средство фотосъемки от компании "Кодак". Для работы требует фотопленку на 24 кадра.}
{48400}{}{Ключ Нельсона}
{48401}{}{Стандартный ключ от склада в штольне Уран-Сити.}
{48500}{}{Шкафчик}
{48501}{}{Автоматизированный шкафчик для хранения вещей. Оснащен системой голосовых команд, которая почему-то не работает.}
{48600}{}{Шкафчик}
{48601}{}{Автоматизированный шкафчик для хранения вещей. Оснащен системой голосовых команд, которая почему-то не работает.}
{48700}{}{Каталог "Крайслус Моторс"}
{48701}{}{Издание автомобильной компании "Крайслус Моторс". Содержит много полезной информации как для водителей, так и для автомехаников.}
{48800}{}{Противопехотная мина}
{48801}{}{Боеприпас нажимного действия, предназначенный для поражения живой силы противника.}
{48900}{}{Special Boxer Weapon}
{49000}{}{Записи офицера}
{49001}{}{Голодиск с аудиозаписями военнослужащего.}
{49100}{}{Mr. Nixon Doll}
{49101}{}{You see a small doll with a big red nose. For some reason, you don't trust this seemingly-innocent child's toy.}
{49200}{}{Tanker Fob}
{49201}{}{An encoded passkey that provides access to high security areas.}
{49300}{}{Вырезки из газет}
{49301}{}{Пачка страниц, вырванных из различных газет. Все они об одном и том же - о потере Великого Луи.}
{49400}{}{Шкура кислотного гекко}
{49401}{}{Содранная с трупа кислотного гекко шкура. Ценится своими огнеупорными и плазмостойкими качествами.}
{49500}{}{Спецкарта}
{49501}{}{Электронная карта допуска от многих дверей правительственного убежища.}
{49600}{}{Шест Бо}
{49601}{}{Очень прочный и сбалансированный шест с закругленными концами, на которых крепятся мягкие подушки. Тренировочная версия от компании "Сувениры Хаттори". Мин.сила: 3.}
{49700}{}{Куботан}
{49701}{}{Древнее оружие нелетального действия, изначально сконструированное для нужд полиции. Важно отметить, что оно становится отличным подспорьем в драке лишь для тех, кто обладает достаточными навыками боевых искусств. Мин.сила: 1.}
{49800}{}{Dual Plasma Cannon}
{49801}{}{Only use for Gun Turret critter.}
{49900}{}{Банка с едой}
{49901}{}{Перед вами банка с собачьим кормом. И судя по дате на крышке, ей больше 70 лет. Если осмелитесь вскрывать ее, то лучше заранее одеть противогаз.}
{50000}{}{Старый револьвер}
{50001}{}{Очень старая модель некогда популярного револьвера. Возможно, музейный экспонат. Мин. сила: 1.}
{50100}{}{Wall Safe}
{50200}{}{Floor Safe}
{50300}{}{Blue Memory Module}
{50301}{}{A read only computer memory module containing medical information. This module details charisma enhancements.}
{50400}{}{Green Memory Module}
{50401}{}{A read only computer memory module containing medical information. This module details perception enhancements.}
{50500}{}{Red Memory Module}
{50501}{}{A read only computer memory module containing medical information. This module details strength enhancements.}
{50600}{}{Yellow Memory Module}
{50601}{}{A read only computer memory module containing medical information. This module details intelligence enhancements.}
{50700}{}{Decomposing Body}
{50701}{}{This is a partially decomposed body of a humanoid creature.}
{50800}{}{Пистолет 10 мм (увел. магазин)}
{50801}{}{Самозарядный пистолет Кольт 6520 калибра 10 мм с увеличенным магазином. Мин. сила: 3.}
{50900}{}{Обрез Максона}
{50901}{}{Старенький дробовик, некогда принадлежавший рейдеру Максону. Ствол и приклад обрезаны для расширения разброса дроби. Мин. сила: 5.}
{51000}{}{Pool Table}
{51100}{}{Pool Table}
{51200}{}{Pool Table}
{51300}{}{Pool Table}
{51400}{}{Pool Table}
{51500}{}{Pool Table}
{51600}{}{Карта озера}
{51601}{}{Помятая довоенная карта окрестностей Солт-Лейк-Сити и его большого озера. По всей карте рассыпаны различные маркеры, указывающие местные достопримечательности и заведения. Практически готовый путеводитель.}
{51700}{}{Секач}
{51701}{}{Огромный нож, предназначенный для разделки мяса. Мин. сила: 3.}
{51800}{}{Dual Minigun}
{51801}{}{Only use for Auto-Cannon critter.}
{51900}{}{Bottle Caps}
{51901}{}{These are worthless bottle caps используемые на заводе ядер-колы. Ходит легенда, что когда-нибудь их ценность станет выше, чем сейчас. Но пока это кажется вам странноватой байкой.}
{52000}{}{Heavy Dual Minigun}
{52001}{}{Only use for Auto-Cannon Critter.}
{52100}{}{Охотничий стол}
{52101}{}{Стол для разделки добычи.}
{52200}{}{Ржавое мачете}
{52201}{}{Кто-то обработал лезвие газонокосилки, заострив ему один край, и плотно обмотал рукоять кожей брамина. Мин. сила: 5.}
{52300}{}{Журнал "Торговля"}
{52301}{}{Довоенный еженедельник, выпускавшийся для людей, ведущих свой бизнес. И хотя сейчас время не то, все же вы сможете почерпнуть из этого издания полезные для торговли сведения.}
{52400}{}{Изношенная куртка}
{52401}{}{Эта грязная вонючая куртка когда-то принадлежала рейдеру. Она настолько изношена, что слышно, как нитки рвутся при движении.}
{52500}{}{Форсажная жвачка}
{52501}{}{Метамфетаминовая резинка, завернутая в газетный огрызок. По словам Форсажника, ее употребление кратковременно стимулирует центральную нервную систему.}
{52600}{}{Останки}
{52601}{}{Бренные останки жителя убежища. Труп настолько долго лежит здесь, что иссох до костей.}
{52700}{}{Останки}
{52701}{}{Бренные останки жителя убежища. Труп настолько долго лежит здесь, что иссох до костей.}
{52800}{}{Айра Кейн}
{52801}{}{Этот парень, кажется, умер от отравления парами метана.}
{52900}{}{Плита}
{52901}{}{Обыкновенная плита для приготовления пищи. Ее уже очень давно не использовали по назначению.}
{53000}{}{Камин}
{53001}{}{Некогда прекрасный декоративный камин с фотографией индийского философа.}
{53100}{}{Лазерный пистолет (полиц.)}
{53101}{}{Лазерный пистолет Ваттс 1500, полицейская модель. Мощность выше, чем у гражданских моделей, за счет использования кристаллов вместо дешевых диодов. Мин. сила: 3.}
{53200}{}{---}
{53300}{}{---}
{53400}{}{---}
{53500}{}{---}
{53600}{}{---}
{53700}{}{---}
{53800}{}{---}
{53900}{}{---}
{54000}{}{---}
{54100}{}{---}
{54200}{}{---}
{54300}{}{---}
{54400}{}{---}
{54500}{}{---}
{54600}{}{---}
{54700}{}{---}
{54800}{}{Ящик с патронами}
{54801}{}{Редкие крупнокалиберные патроны для очень тяжелых пулеметов - таких, о которых вы даже понятия не имеете.}
{54900}{}{Пугач}
{54901}{}{Жалкое подобие пистолета, известное под названием "пугач". И этим словом все сказано. Мин. сила: 1.}
{55000}{}{Полка под инструменты}
{55100}{}{Портмоне}
{55101}{}{Мужское обветшалое портмоне с различными документами и записками торгового содержания. Для вас здесь нет ничего ценного, а для бывшего хозяина утрата этой вещи наверняка не пройдет бесследно.}
{55200}{}{Лицензия}
{55201}{}{Это выданная производителем ваша личная лицензия на продажу знаменитого тонизирующего напитка "Ядер-кола".}
{55300}{}{Дорожный чек}
{55301}{}{Билет на дилижанс в один конец.}
{55400}{}{Штучки}
{55401}{}{Металлические пластины размером с обычную монету. Теоретически это должны быть абсолютно бесполезные вещи.}
{55500}{}{Неразменная монета}
{55501}{}{Это вполне полноценная юбилейная монета... если не считать того, что кто-то просверлил в ней отверстие и просунул туда крепкую нить.}
{55600}{}{Металлоискатель}
{55601}{}{Прибор, работающий от ядерных батареек. Предназначен для обнаружения металлических объектов в радиусе не более 4 метров.}
{55700}{}{Металлоискатель}
{55701}{}{Прибор, работающий от ядерных батареек. Предназначен для обнаружения металлических объектов в радиусе не более 9 метров. Установка ультразвукового сканера позволила вдвое расширить зону локации.}
{55800}{}{Взрывчатка C-4}
{55801}{}{Ящик с пластичным взрывчатым веществом военного назначения.}
{55900}{}{Комбинезон караванщика}
{55901}{}{Специальная одежда для максимально мобильного передвижения в условиях пустыни. Прилагаются защитные очки и маска от пыли.}
{56000}{}{Антирадиационный костюм}
{56001}{}{Надежное персональное средство защиты от облучения.}
{56100}{}{Противогазовый комбинезон}
{56101}{}{Защитный комбинезон для рабочих, занятых на грязной и вонючей работе. Снабжен противогазом, резиновыми сапогами и съемными очками. Хорошо защищает от вредных испарений в воздухе и весьма неудобен в обращении.}
{56200}{}{"Атомные лезвия"}
{56201}{}{Набор лезвий для бритвы. Производство "Pretty & Glamour", город Ноксвилл, штат Теннеси. На коробке изображено атомное испытание в Тихом океане.}
{56300}{}{Огрызок мыла}
{56301}{}{Ароматное мыло от компании "Pretty & Glamour" со следами укуса. Судя по отпечаткам зубов, кусал взрослый человек.}
{56400}{}{Зубная паста}
{56401}{}{Зубная паста с торием. Выпускалась компанией "Pretty & Glamour". Нежно полирует зубную эмаль, делая ее белой и блестящей. Свечение зубов можно заметить даже в темноте.}
{56500}{}{Журнал комиксов}
{56501}{}{Забавные комиксы про веселого парня Пип-Боя, который постоянно искал приключений на свою задницу.}
{56600}{}{Лечебная вода}
{56601}{}{Маленький флакон с якобы целебной водой "Радиум" от компании "Pretty & Glamour".}
{56700}{}{Револьвер Кольт}
{56701}{}{Очень мощное эксклюзивное оружие. Поверхность раскрашена традиционным индейским орнаментом. Когда вы смотрите на него в свете мерцающих огней Вегаса, вам кажется, что вы - бог. Мин. сила: 5.}
{56800}{}{"Черный Динамит"}
{56801}{}{Необычайно крутой и стильный револьвер. Мин. сила: 6.}
{56900}{}{Соль для ванн}
{56901}{}{Соль от компании "Pretty & Glamour" для обогащения радоном воды в ванной. Применяется при нервных расстройствах, бессоннице, упадке сил, артрите и ревматизме.}
{57000}{}{Отрыжка}
{57001}{}{Зловонная отрыжка кислотных гекко. Мин. сила: 1.}
{57100}{}{REZ-4}
{57101}{}{Редкая электромагнитная пушка. Вам повезло... если, конечно, управитесь с оружием таких размеров. Сложность также в отсутствии установки для подзарядки батареи. Когда заряд закончится, это оружие станет бесполезным. Мин. сила: 8.}
{57200}{}{Цеп}
{57201}{}{Брутальное оружие байкеров - крупнокалиберная цепь с тяжелым металлическим шаром на конце. Мин. сила: 5.}
{57300}{}{Ржавая катана}
{57301}{}{Меч из подарочного набора от компании "Сувениры Хаттори". Хотя оружие явно уступает по качеству своему японскому прародителю, в сильной руке оно может надолго устранить противника с поля боя, даже если тот окажется в броне. Мин. сила: 4.}
{57400}{}{Очки битника}
{57401}{}{Круглые очки. Ничего особенного из себя не представляют, но выглядят стильно.}
{57500}{}{Опасная бритва}
{57501}{}{Бритва с открытым лезвием от компании "Остряк". Все еще острая. Мин. сила: 1.}
{57600}{}{Обезболивающее}
{57601}{}{Эта карпула наполнена мощным довоенным анальгетиком. Препарат просрочен более чем на 40 лет, из-за чего еще более пагубно и непоправимо влияет на сердце и сосуды, чем раньше.}
{57700}{}{Влажные салфетки}
{57701}{}{Герметичная упаковка с гигиеническими салфетками. Могут заменить собой ванну во время странствий по Пустошам. Производство компании "Pretty & Glamour".}
{57800}{}{Банка из-под еды}
{57801}{}{Вскрытая банка, в которой больше 70 лет хранился просроченный собачий корм. Похоже, что тот парень вас обманул! (Все весело показывают на вас пальцем и издают протяжный звук "Фууууу!")}
{57900}{}{Пропуск на склад}
{57901}{}{Электронная карта допуска АЭС "Посейдон Ойл".}
{58000}{}{Пропуск оперативного персонала}
{58001}{}{Электронная карта допуска АЭС "Посейдон Ойл".}
{58100}{}{Пицца}
{58101}{}{Отменная пицца с мясом геккона и грибами. И очень много перца.}
{58200}{}{Травка Высера}
{58201}{}{Это все, что осталось от Высера - ничем не примечательный и на первый взгляд безобидный пучок травы.}
{58300}{}{Ядер-кола (вишн.)}
{58301}{}{Бутылка ядер-колы, ароматизированного безалкогольного напитка постъядерного мира. Изготавливается из листьев мутировавшей коки и сока некоторых фруктов. Теплая и выдохшаяся. С вишневым вкусом.}
{58400}{}{Ядер-кола с привкусом}
{58401}{}{Бутылка самогонной ядер-колы. Кто-то решил заработать на продаже такого низкокачественного продукта в обход "официального" производителя.}
{58500}{}{"Дезерт игл"}
{58501}{}{"Дезерт игл" калибра 0,44 Магнум. Оснащен современным точным прицелом. Мин. сила: 5.}
{58600}{}{Перстень}
{58601}{}{Массивный металлический перстень в форме черепа. Довольно брутальный экземпляр. Он настолько въелся в кожу, что пришлось оторвать его вместе с пальцем.}
{58700}{}{Расписка наркодилера}
{58701}{}{Договор между Жирюгой и наркодилером о приобретении партии химического сырья. На обратной стороне написана расписка - ставка на бойцов ринга "Эльдорадо".}
{58800}{}{Расписка киллера}
{58801}{}{Улика, оставшаяся на теле киллера на стоянке в Новом Вегасе. Похоже, что тот технарь из Ветра Войны заказал вас! Причем заказал у своих же.}
{58900}{}{Эмульгатор Е30}
{58901}{}{Рассыпающееся желтое вещество с невыносимым запахом сотни помоек. Внешний вид доверия не внушает.}
{59000}{}{Признание Геллера}
{59001}{}{Голодиск с записью, которую вы сделали во время разговора с Ларри Геллером. В разговоре Ларри признался, что когда-то производил наркотики. Полиции этого будет достаточно.}
{59100}{}{Расписка работорговцев}
{59101}{}{Листок бумаги, на котором корявым почерком написан договор между двумя лицами - начальником работорговцев и неизвестным вам исполнителем. Исполнитель по договору обязуется подбросить в отель выродков наркотик и доложить об этом полиции.}
{59200}{}{Сомнительный пакет}
{59201}{}{Этот наркотик вам дал Хэл Уоллис, чтобы вы подложили его в отель выродков.}
{59300}{}{Компромат на Х.Уоллиса}
{59301}{}{Голодиск с записью, которую вы сделали во время разговора с Хэлом Уоллисом при получении задания на выродков. Полиции это будет интересно.}
{59400}{}{"Дезерт игл"}
{59401}{}{"Дезерт игл" калибра 0,44 Магнум, принадлежавший Бобу Нилу. Помимо внушительного внешнего вида обладает усиленным механизмом, увеличивающим пробивную силу этого оружия. Мин. сила: 5.}
{59500}{}{Признание Х.Уоллиса}
{59501}{}{Голодиск с записью, которую вы сделали во время разговора с Хэлом Уоллисом при получении задания на Боба Нила. Прямое доказательство.}
{59600}{}{Расписка О.Дэвиса}
{59601}{}{Расписка между О.Дэвисом и Т.Паркером. Оказывается, Дэвис получает из городской казны неоправданно высокие гонорары за скорейшее решение проблемы с Сэмом Филлипсом. Интересно, к чему такие затраты? И почему мэрия так заинтересована в этом деле?}
{59700}{}{Расписка Тома Паркера}
{59701}{}{Расписка между двумя лицами. Том Паркер обязался вернуть начальнику работорговцев 6% акций дамбы Гувера. Документ пока подписан только одной из сторон договора, Т.Паркером. Не понятно, к чему бы это?}
{59800}{}{Ларри о Филлипсе}
{59801}{}{Голодиск с записью, которую вы незаметно сделали во время разговора с Ларри Геллером о Сэме Филлипсе. Тот засвидетельствовал, что Филлипс некогда имел контакт с наркодилерами.}
{59900}{}{Наркодилер о Филлипсе}
{59901}{}{Голодиск с записью, которую вы незаметно сделали во время разговора с наркодилером о Сэме Филлипсе. Тот засвидетельствовал, что Филлипс некогда имел контакт с наркодилерами.}
{60000}{}{Расписка из Питомника}
{60001}{}{Расписка между Хэлом Уоллисом и администрацией наркотической лаборатории "Питомник", по которой лаборатория обязуется предоставить Уоллису крупную партию очень сильного наркотика.}
{60100}{}{Компромат на Боба Нила}
{60101}{}{Запись вашего разговора с Бобом Нилом, в котором Боб Нил открыто просит вас ликвидировать Хэла Уоллиса.}
{60200}{}{Солдатский жетон}
{60201}{}{На этом жетоне записана личная информация о его носителе - имя, дата рождения, какой-то порядковый номер и другие точные данные.}
{60300}{}{---}
{60400}{}{---}
{60500}{}{Силовая броня}
{60501}{}{Это ваша персональная броня, оснащенная автономными системами, которые делают ее схожей с высокотехнологичной довоенной броней T-51b.}
{60600}{}{Автономная система T-51b}
{60601}{}{Сложная система устройств, включающая малый ядерный реактор, силовой модуль экзоскелета, блок охлаждения и прочие составные части, необходимые в сборке брони T-51b.}
{60700}{}{Центральный процессор}
{60701}{}{Это центральное звено моторизированной брони T-51b. Без этого процессора половина возможностей брони, включая силовые качества, не могут быть запущены.}
{60800}{}{ПЛК}
{60801}{}{Программируемый логический контроллер. Не работает.}
{60900}{}{ПЛК}
{60901}{}{Программируемый логический контроллер. Готов к работе.}
{61000}{}{Личный сейф}
{61001}{}{Ваш личный сейф с кодовым замком для хранения вещей.}
{61100}{}{Личный сейф}
{61101}{}{Ваш личный сейф с кодовым замком для хранения вещей.}
{61200}{}{---}
{61201}{}{---}
{61300}{}{Комод с зеркалом}
{61301}{}{Шикарная мебель с большим треснувшим зеркалом.}
{61400}{}{Комод с зеркалом}
{61401}{}{Шикарная мебель с большим треснувшим зеркалом.}
{61500}{}{Столик}
{61501}{}{Немного испачканный жирными пятнами столик.}
{61600}{}{Комод с зеркалом}
{61601}{}{Шикарная мебель с большим треснувшим зеркалом.}
{61700}{}{Ящики для документов}
{61701}{}{Картотечный шкаф для различных документов.}
{61800}{}{Комод}
{61801}{}{Старый комод с дверцами.}
{61900}{}{Стеллаж}
{61901}{}{Разваливающийся стеклянный стеллаж.}
{62000}{}{Стеллаж}
{62001}{}{Разваливающийся стеклянный стеллаж.}
{62100}{}{Книжный стеллаж}
{62101}{}{Библиотечный стеллаж с книгами.}
{62200}{}{Книжный стеллаж}
{62201}{}{Библиотечный стеллаж с книгами.}
{62300}{}{Книжный стеллаж}
{62301}{}{Библиотечный стеллаж с книгами.}
{62400}{}{Книжный стеллаж}
{62401}{}{Библиотечный стеллаж с книгами.}
{62500}{}{Ингрэм Полис}
{62501}{}{Американский пистолет-пулемет, производимый в середине прошлого века. Полицейский вариант отличается передней рукоятью, частично оребренным стволом и мушкой без намушника. Мин. сила: 5.}
{62600}{}{Ракетница}
{62601}{}{Невостребованное оружие Роквелла под снаряды калибра 40 мм. Просто в обращении, но для эффективного применения требует значительной силы. Мин. сила: 5.}
{62700}{}{Гранатомет 40 мм}
{62701}{}{Ручной гранатомет Роквелла, созданный в продолжение древних моделей Спрингфилдского арсенала. Рассчитан на сильных солдат. Мин. сила: 6.}
{62800}{}{Гранатомет 40 мм (увел. магазин)}
{62801}{}{Ручной гранатомет Роквелла, созданный в продолжение древних моделей Спрингфилдского арсенала. Снабжен магазином барабанного типа на 6 снарядов. Мин. сила: 7.}
{62900}{}{Укрепленная куртка}
{62901}{}{Черная плотная кожаная куртка, укрепленная разномастными бронепластинами.}
{63000}{}{Куртка личного пошива}
{63001}{}{Черная плотная кожаная куртка, пошив которой полностью адаптирован под ваше тело. В такой куртке вам будет гораздо удобнее.}
{63100}{}{Костюм}
{63101}{}{В этом концертном костюме вы неотразимы! Одевайте его, если хотите произвести впечатление на собеседника.}
{63200}{}{Кожаная броня М3}
{63201}{}{Кожаная броня с дополнительным слоем защиты из шкур кислотных гекко. Известные свойства этих шкур делают броню более стойкой к повреждениям от огня, кислоты и плазмы.}
{63300}{}{Металлическая броня М2 (укреп.)}
{63301}{}{Броня, искусно сформированная из полированных металлических пластин с дополнительной защитой для колен, локтей и других менее защищенных частей тела.}
{63400}{}{Металлическая броня М2 (зерк.)}
{63401}{}{Броня, искусно сформированная из полированных металлических пластин с зеркальной поверхностью, отражающей световые или тому подобные атаки.}
{63500}{}{Металлическая броня М3}
{63501}{}{Броня, искусно сформированная из полированных металлических пластин со множеством укреплений и зеркальной поверхностью.}
{63600}{}{Ключ реднека}
{63601}{}{Стандартный ключ от одной из дверей в Прово.}
{63700}{}{Набор юного атомщика}
{63701}{}{Миниатюрная атомная электростанция. Немного урановой руды прилагается.}
{63800}{}{Ключ от номера 26}
{63801}{}{Это ключ от одного из номеров в отеле "Трехкарточный Монти".}
{63900}{}{Ключ от номера 14}
{63901}{}{Это ключ от одного из номеров в отеле "Трехкарточный Монти".}
{64000}{}{Таинственный бластер (нераб.)}
{64001}{}{Необычное оружие неизвестного происхождения. На корпусе стоит отметка: "Собственность Зоны 51". Почему-то не работает.}
{64100}{}{Таинственный бластер}
{64101}{}{Необычное оружие неизвестного происхождения. На корпусе стоит отметка: "Собственность Зоны 51". Мин. сила: 3.}
{64200}{}{Ключ от тайника}
{64201}{}{Стандартный ключ от какого-то замка в Ветре Войны.}
{64300}{}{Ключ от дома}
{64301}{}{Стандартный ключ от жилого дома в Ветре Войны.}
{64400}{}{Ключи от загона}
{64401}{}{Набор старых ключей от рабского загона в Питомнике.}
{64500}{}{Мусорный бак}
{64501}{}{Мусорный бак. Вы едва можете разобрать надпись на наклейке: "Сохраняй улицы своего города в чистоте!"}
{64600}{}{Ключ от номера 7}
{64601}{}{Это ключ от одного из номеров в отеле "Сильвер Легаси".}
{64700}{}{Действующая рация}
{64701}{}{Действующая рация модели 2043B от прекрасной компании Ваттс Электроникс. Надежная, прочная и камуфлированная.}
{64800}{}{Тело полицейского}
{64801}{}{Труп полицейского, убитого точным выстрелом в голову.}
{64900}{}{Ключ-карта Боба Нила}
{64901}{}{Ключ-карта от двери личного кабинета Боба Нила на дамбе Гувера.}
{65000}{}{Ключи от завода}
{65001}{}{Связка различных ключей с завода ядер-колы в Солт-Лейк-Сити.}
{65100}{}{Ключ Мамаши}
{65101}{}{Ключ от раздевалки в ночном клубе Нью-Рино.}
{65200}{}{Письмо жителя трущоб}
{65201}{}{"Здорово, брат! Помнишь, я рассказывал про кретина Теда, у которого мы выкупили дом? Он перебрался в самую глушь Рино, на ж/д станцию, подальше от людей. И я подумал, а давай проведаем уродца? А то мне нужны деньги для оплаты жилья, и взять их негде..."}
{65300}{}{---}
{65301}{}{---}
{65400}{}{Пруток}
{65401}{}{Самодельное оружие, созданное из стального прутка от канализационной решетки. Мин.: 1.}
{65500}{}{Послание Патрику}
{65501}{}{Письмо от общины мормонов Патрику. Ничего такого, что было бы вам интересно.}
{65600}{}{Портсигар}
{65601}{}{Медный футляр для сигар. Сам по себе ничего особенного не представляет.}
{65700}{}{Джазовая труба}
{65701}{}{Простой на вид медный музыкальный инструмент альтово-сопранового регистра. Идеально подошел бы для какого-нибудь джаз-бенда.}
{65800}{}{"Ядерная лихорадка"}
{65801}{}{Детская стратегическая игра. Суть ее сводится к получению кредитов и разведке залежей ядерного топлива на игровой карте. В итоге выигрывает тот, кто получил больше всех прибыли. Увы, как в жизни, второй остается проигравшим.}
{65900}{}{Старый кулон}
{65901}{}{Кто-то потерял этот семейный кулон, а вы его нашли. Теперь он ваш по праву.}
{66000}{}{Ключ Вортиса}
{66001}{}{Ключ от сувальдного сейфа в Городе Рабов.}
{66100}{}{Сломанная броня}
{66101}{}{Остатки поврежденной силовой брони. Дезинтеграция силового модуля привела к разрыву броневой оболочки и уничтожению части несущей конструкции. Теперь это невозможно даже одеть.}
{66200}{}{Чертежи T-51. Часть 1}
{66201}{}{Эти чертежи описывают только несущую конструкцию силовой брони T-51b. Раритетная информация.}
{66300}{}{Чертежи T-51. Часть 2}
{66301}{}{Эти чертежи описывают только внутренние автономные модули силовой брони T-51b. Очень раритетная информация.}
{66400}{}{"Дутень"}
{66401}{}{Гражданский плазменный пистолет для самозащиты. Работает от аккумулятора, которого хватает лишь на 4 выстрела. Мин. сила: 1.}
{66500}{}{Ваши вещи}
{66501}{}{Здесь хранятся ваши личные вещи.}
{66600}{}{Деликатный скальпель}
{66601}{}{Очень острый медицинский инструмент для рассечения тканей. Необходимо иметь богатый хирургический опыт, чтобы им управлять, в противном случае этот предмет может оказаться опасным для самого обладателя.}
{66700}{}{Деликатный скальпель}
{66701}{}{Очень острый медицинский инструмент для рассечения тканей. Необходимо иметь богатый хирургический опыт, чтобы им управлять, в противном случае этот предмет может оказаться опасным для самого обладателя.}
{66800}{}{Тактический нож выживания}
{66801}{}{Предназначен для выполнения работ по обустройству лагеря в полевых условиях и обеспечения автономности существования человека в "дикой" природе.}
{66900}{}{"Счастливчик"}
{66901}{}{Сильно изношенный плазменный пистолет оборонительного действия, гражданская модель первого поколения. Такие вышли из моды еще задолго до Войны.}
{67000}{}{"Счастливчик"}
{67001}{}{Сильно изношенный плазменный пистолет оборонительного действия, гражданская модель первого поколения. После чистки и калибровки его мощность и дальнобойность увеличились на десять процентов.}
{67100}{}{Ягоды паслена}
{67101}{}{Недозревшие ягоды дикорастущего растения. Сладко-горькие на вкус и ядовитые.}
{67200}{}{Обед караванщика}
{67201}{}{Сытный обед, который можно легко и быстро приготовить в полевых условиях.}
{67300}{}{"Кровочист"}
{67301}{}{Народное лекарственное средство, основанное на действии трав. Способно выводить из организма яды и радионуклиды и даже излечивать от некоторых видов инфекционных заболеваний.}
{67400}{}{Концертные афиши}
{67401}{}{Это рукописные афиши вашего концерта, выполненные в черно-белых тонах. Их можно было бы отдать в хорошие руки, чтобы распространить по всему Рино.}
{67500}{}{Ореховый раствор}
{67501}{}{Народный аналог антирадина для внутривенного использования. Для полного эффекта требует времени.}
{67600}{}{Гильза}
{67601}{}{Стреляная гильза от патрона калибра 0,223.}
{67700}{}{Катана}
{67701}{}{Меч из подарочного набора от компании "Сувениры Хаттори". Хотя оружие явно уступает по качеству своему японскому прародителю, в сильной руке оно может надолго устранить противника с поля боя, даже если тот окажется в броне. Мин. сила: 4.}
{67800}{}{Мачете}
{67801}{}{Кто-то обработал лезвие газонокосилки, заострив ему один край, и плотно обмотал рукоять кожей брамина. Мин. сила: 5.}
{67900}{}{Схема "Месть Микки"}
{67901}{}{Инструкция по созданию самодельного рукопашного оружия. Разработчик - некий Микки. Кому он собрался мстить - неизвестно. Зато известно, что для создания этого оружия нужен тостер и некоторые другие детали.}
{68000}{}{Останки робота}
{68001}{}{Присыпанный дорожной пылью охранный робот. Точнее - то, что от него осталось.}
{68100}{}{Контракт Райта}
{68101}{}{Контракт между Райтом и Марком, по которому исполнитель вынужден поставить несколько ящиков взрывчатки заказчику. Условия, скажем прямо, жесткие.}
{68200}{}{Автомобильные фары}
{68201}{}{Фары головного освещения машины с однонитевыми галогенными лампами на 65 Ватт.}
{68300}{}{Автомобильные фары}
{68301}{}{Фары головного освещения машины с однонитевыми галогенными лампами на 65 Ватт.}
{68400}{}{Тент}
{68401}{}{Это небольшой тент для укрепления багажника. В самый раз для пикапа.}
{68500}{}{Тент}
{68501}{}{Это небольшой тент для укрепления багажника. В самый раз для пикапа.}
{68600}{}{Топливный регулятор}
{68601}{}{Некоторые водители устанавливали этот регулятор, вдвое уменьшающий расход топлива, но большинство водителей не заботило, сколько жрут их машины. В конце концов, оно дешево стоит, и его много, так чего же волноваться?}
{68700}{}{"Дикарь" с патронташем}
{68701}{}{Однозарядный дробовик с укороченным стволом и патронташем на прикладе. Хотя это оружие уже весьма изношено и морально устарело, его неоспоримый плюс - быстрая перезарядка. Мин. сила: 4.}
{68800}{}{Поврежденный робот}
{68801}{}{Этот робот поврежден и ремонту не подлежит.}
{68900}{}{Ключ Илая #10}
{68901}{}{Стандартный ключ от дверного замка.}
{69000}{}{Рабский ошейник}
{69001}{}{Электрошокер довоенного производства в виде ошейника. Когда-то его использовали в тюрьмах, теперь же это отличный инструмент для торговли рабами и их эксплуатации.}
{69100}{}{Старый револьвер}
{69101}{}{Очень старая модель револьвера. Возможно, музейный экспонат. Мин. сила: 3.}
{69200}{}{Тренировочное ружье}
{69201}{}{Спортивная модель лазерного ружья, предназначенная для тренировок и состязаний в меткости. Обладает заниженными характеристиками по сравнению с обычным лазерным ружьем, но почти не уступает ему в дальнобойности. Мин. сила: 5.}
{69300}{}{Ящик}
{69301}{}{Старый деревянный ящик.}
{69400}{}{Ящик}
{69401}{}{Старый деревянный ящик.}
{69500}{}{Схема "Коктейль Молотова"}
{69501}{}{Инструкция для создания зажигательной гранаты в "домашних" условиях.}
{69600}{}{Детали}
{69601}{}{Разные детали роботов, компьютеров и бытовой техники.}
{69700}{}{Холодильник для напитков}
{69800}{}{Холодильник для напитков}
{69900}{}{Вырванная страница}
{69901}{}{Страница из учетной книги казино "Монти". Здесь есть однодневные записи о выигрыше Мерфи и долге Ирвина.}
{70000}{}{Схема "Пороховая граната"}
{70001}{}{Инструкция для создания самодельной гранаты на основе пороха и химического детонатора. В изготовлении используются только подручные средства.}
{70100}{}{---}
{70200}{}{---}
{70300}{}{---}
{70400}{}{---}
{70500}{}{Палец миссис Мордино}
{70501}{}{Этот мизинец принадлежал жене мистера Мордино.}
{70600}{}{Шоковый кастет}
{70601}{}{Предшественник полицейского силового кастета от компании "Бью". Используется вместе с резиновой перчаткой.}
{70700}{}{Ультразвуковой сканер}
{70701}{}{Неработающий сканер для эхолота металлоискателя. Его назначение - анализировать ультразвуковые волны для моделирования пространства на круглом цифровом табло.}
{70800}{}{Потроха со специями}
{70801}{}{Браминьи потроха, приготовленные по особому рецепту. Кроме очевидного браминьего рубца, в них может быть все что угодно.}
{70900}{}{Ионный синтезатор}
{70901}{}{Некое довоенное устройство от компании Волт-Тек.}
{71000}{}{Газоанализатор}
{71001}{}{Некое довоенное устройство от компании Волт-Тек.}
{71100}{}{Импульсный модулятор}
{71101}{}{Некое довоенное устройство от компании Волт-Тек.}
{71200}{}{Регулятор давления}
{71201}{}{Некое довоенное устройство от компании Волт-Тек.}
{71300}{}{Чип синтезатора одежды}
{71301}{}{Некое довоенное устройство от компании Волт-Тек.}
{71400}{}{Ключи "Эльдорадо"}
{71401}{}{Связка ключей от различных дверей казино "Эльдорадо".}
{71500}{}{Кий Бертолини}
{71501}{}{Складной кий с королевским узором в удобном кожаном футляре. Варварски переломлен посередине в месте соединения.}
{71600}{}{Кий Бертолини}
{71601}{}{Складной кий с королевским узором в удобном кожаном футляре. Металлическая врезка на месте скола позволяет использовать кий по назначению, как и прежде.}
{71700}{}{Кий Бертолини}
{71701}{}{Складной кий с королевским узором в удобном кожаном футляре с "неожиданным" вторым дном. Металлическая врезка на месте скола позволяет использовать кий по назначению, как и прежде.}
{71800}{}{Трупный амфетамин}
{71801}{}{Доза гиперболизирующего вещества, синтезированного из плазмы сильно облученной крови, эндорфинов и различных ферментов человекоподобного организма.}
{71900}{}{Пиво с привкусом}
{71901}{}{Какой-то сорт домашнего пива. Отличается немного странноватым жгучим привкусом.}
{72000}{}{Испорченный лазерный пистолет}
{72001}{}{Лазерный пистолет Ваттс 1000, гражданская модель. Почему-то не работает.}
{72100}{}{Химикаты}
{72101}{}{Набор химикатов широкого спектра назначения. Судя по метке на ампулах и коробках, пакет имеет военное происхождение.}
{72200}{}{Испорченная микроядерная батарея}
{72201}{}{Эта микроядерная батарея была повреждена, поэтому в настоящий момент ее эксплуатация невозможна.}
{72300}{}{Презервативы (отрав.)}
{72301}{}{Это презервативы марки "Джимми Хэтс". Очень надежная марка, однако странным образом в оболочке обнаружилась маленькая дырочка... возможно, от иглы.}
{72400}{}{Депрессия Томпсона}
{72401}{}{Это - некая условная единица депрессивности Томпсона. Бедняга узнал о кончине своей козырной сучки...}
{72500}{}{Эмпатический усилитель Pip-Boy}
{72501}{}{Этот усилитель состоит из акустического и оптического сенсоров, диска с программой и шнура. Его назначение - анализировать мимику и голоса собеседников для определения их эмоционального состояния.}
{72600}{}{Испорченный Pip-Boy}
{72601}{}{Остатки уничтоженного портативного компьютера Pip-Boy 2000. Монитор разбит, корпус помят, некоторые кнопки выпали наружу. Очевидно, ремонту эта вещь не подлежит.}
{72700}{}{Броня из покрышек}
{72701}{}{Довольно неудобная и мерзко пахнущая резиной броня. Но так ли это важно, когда речь идет об ударе электричеством или радиации?}
{72800}{}{Электрокопье}
{72801}{}{Эффективное полицейское средство для разгона толпы бунтовщиков. Многократно использовалось еще до Войны. Мин. сила: 4.}
{72900}{}{Пистолет 10 мм #80}
{72901}{}{Устаревшая модель самозарядного пистолета Кольт 6520 калибра 10 мм. Судя по маркировке на корпусе, произведен в 2051 году. Мин. сила: 3.}
{73000}{}{Пистолет 10 мм с фонариком}
{73001}{}{Полицейская модель самозарядного пистолета Кольт 6520 калибра 10 мм, оснащенная подствольным тактическим фонариком. Правда, иногда он не горит - нужно потрясти. Мин. сила: 4.}
{73100}{}{Запертый кейс}
{73101}{}{Прочный металлический кейс делового человека. Вероятно, внутри содержится что-то ценное, ведь он заперт на кодовый замок.}
{73200}{}{Анатомический анализатор Pip-Boy}
{73201}{}{Этот усилитель состоит из диска с программой, шнура и сенсора. Его назначение - анализировать анатомию противника для определения его наиболее уязвимых мест.}
{73300}{}{Хромированные очки}
{73301}{}{Очки с хромированными стеклами.}
{73400}{}{Бронепластины}
{73401}{}{Защитные полимерные пластины, изготовленные, по-видимому, из остатков уничтоженной боевой брони.}
{73500}{}{Бронежилет М2}
{73501}{}{Легкий армейский бронежилет с элементами разгрузки под всякое барахло. Защищает лишь часть торса, так как рассчитан на применение группами быстрого реагирования. Часть бронепластин заменена на более прочные.}
{73600}{}{Пистолет Винчестер}
{73601}{}{Этот пистолет изготовлен по аналогии с устройством плазменной винтовки компании Винчестер Армс. Популярности не снискал из-за конкуренции с плазменными пистолетами от ИИ Гастона Глока. Мин. сила: 5.}
{73700}{}{Наградной пистолет}
{73701}{}{Именной пистолет Кольт 6520 из легированной стали. Использование более прочных сплавов позволяет этому оружию стрелять с большей убойной силой, но и делает его немного тяжелее. Мин. сила: 4.}
{73800}{}{Тяжелое копье Койотов}
{73801}{}{Тяжелое копье охотников из племени Койотов. По-видимому, в качестве режуще-колющей части используется массивное обточенное лезвие от агротехники. Мин. сила: 5.}
{73900}{}{Ударный нож Койотов}
{73901}{}{Холодное оружие охотников из племени Койотов. По-видимому, изготовлено из выпрямленного лезвия от культиватора. Мин. сила: 4.}
{74000}{}{Агродубинка Койотов}
{74001}{}{Тяжелое холодное оружие охотников из племени Койотов. По-видимому, изготовлено из грунтозацепа и металлической трубы, скрепленных болтами. Мин. сила: 5.}
{74100}{}{Ультратермитная смесь}
{74101}{}{Термитная смесь, дополненная неизвестными компонентами. При горении выделяет ошеломительное количество тепла, тем самым бесшумно и бездымно расплавляя все вокруг. И не забудьте зажигалку!}
{74200}{}{Испорченное оружие Нельсона}
{74201}{}{Этот помповый дробовик был сильно поврежден. Потребуется много труда, чтобы вернуть ему рабочее состояние.}
{74300}{}{Котлета из мяса "земляного дракона"}
{74301}{}{Фаршированное мясо "земляных драконов" с зеленью, завернутое в маисовую лепешку. В этой пище больше протеина, чем в стейке из брамина.}
{74400}{}{Дорожный знак}
{74401}{}{На этом проржавевшем знаке едва усматривается предупреждение для водителей. К вам оно не относится.}
{74500}{}{Разодранная куртка}
{74501}{}{Кожаная куртка в ужасном состоянии. В ней присутствуют многочисленные отверстия, один рукав оторван, а материя на спине разорвана когтями мелкой живности. Впрочем, это еще можно восстановить, если хорошо постараться.}
{74600}{}{Ключ запасного выхода}
{74601}{}{Стандартный ключ от двери запасного выхода в штаб-квартире Страйкера.}
{74700}{}{Ключ от ангара}
{74701}{}{Стандартный ключ от двери ангара на территории ранчо Оливера Лучиано.}
{74800}{}{Инструкция "Куботан"}
{74801}{}{Довоенная инструкция для полицейских по сборке куботана и искусству его применения. Собрать это оружие самообороны несложно, но без надлежащих навыков оно будет бесполезно.}
{74900}{}{Ключ Илая #9}
{74901}{}{Стандартный ключ от дверного замка.}
{75000}{}{Мастерство куботана}
{75001}{}{Обучение приемам борьбы с использованием куботана позволяет вам наносить больше урона противнику.}
{75100}{}{Останки сержанта Конга}
{75101}{}{Иссохшие останки человека, одетого в армейскую жилетку и сжимавшего в руке ковбойскую шляпу. Судя по лычкам, все это когда-то принадлежало сержанту Конгу.}
{75200}{}{Ранцевый огнемет}
{75201}{}{Огнемет модели Факел-450, снабженный большим ранцевым контейнером. Выстреливает короткие струи воспламеняющейся смеси. Для функционирования необходимо специальное топливо. Мин. сила: 6.}
{75300}{}{Покерная фишка "Эль Капитан"}
{75400}{}{Покерная фишка "Эльдорадо"}
{75500}{}{Покерная фишка "Сильвер Легаси"}
{75600}{}{Покерная фишка "Монти"}
{75700}{}{Золотая покерная фишка}
{75701}{}{Глядя на эту красивую вещь, вы всячески убеждаете себя, что теперь ни за что не проиграете при игре в покер или рулетку!}
{75800}{}{"Атомный коктейль"}
{75801}{}{Крепкий алкогольный напиток по довоенному рецепту, явно разбавленный чем-то особенным.}
{75900}{}{Рецепт: "Атомный коктейль"}
{75901}{}{Рецепт приготовления "Атомного коктейля". Едва ли вам удастся добиться довоенного качества, но и так будет неплохо.}
{76000}{}{Изношенный миниган}
{76001}{}{Миниган CZ53 Роквелла в очень плохом состоянии. Мин. сила: 7.}
{76100}{}{Компромат для Мордино}
{76101}{}{Это запись дебатов на собрании Страйкера, в ходе которого мистера Мордино было решено сместить после того, как власть в Рино будет захвачена группировкой Страйкера. Мордино наверняка будет полезно это услышать.}
{76200}{}{"Стиль гонзо"}
{76201}{}{Этим качественным боевым ножом можно легко вскрыть любое притворство и ложь, если хватит навыков. Мин. сила: 1.}
{76300}{}{Выкидной нож байкера}
{76301}{}{Нож, найденный в кармане вашей куртки. Лезвие выдвигается пружиной при нажатии кнопки на ручке. Мин. сила: 1.}
{76400}{}{Гормональный взрыв}
{76500}{}{Окно вытяжки}
{76600}{}{Рецепт: "Рутбир"}
{76601}{}{Рецепт приготовления корневого пива.}
{76700}{}{ЭМИ-перчатка}
{76701}{}{Силовой кастет, снабженный генератором электромагнитного импульса. Мин. сила: 2.}
{76800}{}{"Пламенный поцелуй"}
{76801}{}{Гидравлический кулак, состоящий из огнеупорной перчатки, баллона и распрыскивателя с поршневым механизмом. При ударе механизм выпрыскивает топливо на тело жертвы и затем воспламеняет его. Мин. сила: 2.}
{76900}{}{Труп старателя}
{76901}{}{Все говорит о том, что этого человека убили отнюдь не местные грызуны.}
{77000}{}{Панцирь скорпиона-легенды}
{77001}{}{Очень прочный хитиновый панцирь.}
{77100}{}{Хитиновая броня}
{77101}{}{Ваша персональная броня, созданная из панциря скорпиона-легенды.}
{77200}{}{Останки рабочего}
{77201}{}{Эти останки лежат здесь уже очень много лет. Следов насильственной смерти не видно.}
{77300}{}{Останки старателя}
{77301}{}{Это все, что осталось от старателя, намеревавшегося поживиться местными богатствами. В итоге поживились им.}
{77400}{}{Раковина}
{77401}{}{Фарфоровая раковина, которая еле-еле справляется со своими обязанностями.}
{77500}{}{Раковина}
{77501}{}{Фарфоровая раковина, которая еле-еле справляется со своими обязанностями.}
{77600}{}{Образцы}
{77601}{}{Стерильный набор для взятия образцов крови у мутировавших животных. Выдан доктором Вилмутом.}
{77700}{}{Труп}
{77701}{}{Видимо, этот труп так и останется лежать под солнцем, если его кто-то не закапает, следуя местным обычаям.}
{77800}{}{Тело караванщика}
{77900}{}{Гаусс-пистолет PPK5}
{77901}{}{Ранняя модель пистолета на основе электромагнитного ускорителя. Вскоре после выпуска были разработаны более совершенные модели, поэтому PPK5 быстро вышел из употребления. Мин. сила: 4.}
{78000}{}{Рецепт: "Стимулятор"}
{78001}{}{Рецепт приготовления стимулятора и суперстимулятора.}
{78100}{}{Рецепт: "Докторский чемоданчик"}
{78101}{}{Рекомендации по составлению докторского чемодана в условиях современных Пустошей.}
{78200}{}{Полусъеденный труп}
{78201}{}{Остатки человека в комбинезоне убежища. Половина тела была съедена каннибалами.}