{100}{}{Hero Male}
{101}{}{}
{200}{}{Hero Female}
{201}{}{}
{300}{}{Гражданин Убежища 8}
{400}{}{Гражданка Убежища 8}
{500}{}{Radscorpion}
{501}{}{A small mutated scorpion.}
{600}{}{Radscorpion}
{601}{}{A mutated scorpion.}
{700}{}{Deathclaw}
{701}{}{An immature Deathclaw.}
{800}{}{Deathclaw}
{801}{}{An immature Deathclaw.}
{900}{}{Dog}
{901}{}{A canine, probably of a mixed breed.}
{1000}{}{Brahmin}
{1001}{}{A two headed, mutant cow.}
{1100}{}{Rat}
{1101}{}{A typical large rat.}
{1200}{}{Mantis}
{1201}{}{A mutated Mantis.}
{1300}{}{Сержант Грейвс}
{1400}{}{Док}
{1500}{}{Ричард Грей}
{1600}{}{Spore Plant}
{1601}{}{A carnivorous plant.}
{1700}{}{Cute Slave}
{1800}{}{Handsome Slave}
{1900}{}{Healthy Slave}
{2000}{}{Healthy Slave}
{2100}{}{Strong Slave}
{2200}{}{Strong Slave}
{2300}{}{Combat Slave}
{2400}{}{Combat Slave}
{2500}{}{Clever Slave}
{2600}{}{Clever Slave}
{2700}{}{Generic Slave}
{2800}{}{Generic Slave}
{2900}{}{Anna}
{3000}{}{Tough Thug}
{3100}{}{Tough Thug}
{3200}{}{Melee Thug}
{3300}{}{Melee Thug}
{3400}{}{Agile Thug}
{3500}{}{Agile Thug}
{3600}{}{Gun Thug}
{3700}{}{Gun Thug}
{3800}{}{Big Gun Thug}
{3900}{}{Big Gun Thug}
{4000}{}{Tough Guard}
{4100}{}{Tough Guard}
{4200}{}{Melee Guard}
{4300}{}{Melee Guard}
{4400}{}{Agile Guard}
{4500}{}{Agile Guard}
{4600}{}{Gun Guard}
{4700}{}{Gun Guard}
{4800}{}{Big Gun Guard}
{4900}{}{Big Gun Guard}
{5000}{}{Orphan (Male)}
{5100}{}{Orphan (Female)}
{5200}{}{Child (Male)}
{5300}{}{Child (Female)}
{5400}{}{Loser}
{5500}{}{Loser}
{5600}{}{Bad Merchant}
{5700}{}{Bad Merchant}
{5800}{}{Average Merchant}
{5900}{}{Average Merchant}
{6000}{}{Master Trader}
{6100}{}{Master Trader}
{6200}{}{Некто}
{6300}{}{Weak Peasant}
{6400}{}{Weak Peasant}
{6500}{}{Average Peasant}
{6600}{}{Average Peasant}
{6700}{}{Strong Peasant}
{6800}{}{Strong Peasant}
{6900}{}{Беглый каторжник}
{7000}{}{Weak Melee Guard}
{7100}{}{Weak Gun Guard}
{7200}{}{Weak Gun Guard}
{7300}{}{Repair Bot}
{7400}{}{Repair Bot Mark II}
{7500}{}{Robobrain}
{7600}{}{Floating Eye Bot}
{7700}{}{Sentry Bot}
{7800}{}{Sentry Bot Mark II}
{7900}{}{Robobrain}
{8000}{}{Little Gecko}
{8100}{}{Tough Lil Gecko}
{8200}{}{Wild Dog}
{8201}{}{A mixed breed feral dog.}
{8300}{}{Golden Gecko}
{8400}{}{Deathclaw}
{8500}{}{Deathclaw Spawn}
{8600}{}{Tough Golden Gecko}
{8700}{}{Мишень обычная}
{8800}{}{Мишень бронированная}
{8900}{}{John Cassidy}
{9000}{}{Обычный парень}
{9100}{}{Сержант}
{9200}{}{Citizen}
{9300}{}{Мамаша}
{9400}{}{Up Class Citizen}
{9500}{}{Trapper}
{9600}{}{Trapper}
{9700}{}{Sulik}
{9800}{}{Реднек}
{9900}{}{Реднек}
{10000}{}{Реднек}
{10100}{}{Glowing Ghoul}
{10200}{}{Reactor Ghoul}
{10300}{}{Reactor Guard}
{10400}{}{Илай}
{10500}{}{Абориген свалки}
{10600}{}{The Brain}
{10700}{}{Выродок}
{10800}{}{Харрельсон}
{10900}{}{Джей Кукиш}
{11000}{}{Mole Rat}
{11100}{}{Greater Mole Rat}
{11200}{}{Pig Rat}
{11300}{}{Tough Pig Rat}
{11400}{}{Weak Brahmin}
{11401}{}{A two-headed, mutant animal.}
{11500}{}{A.Pwr.Armor (don't use)}
{11600}{}{Mutated Rat}
{11601}{}{A tough mutant rat.}
{11700}{}{Mutated Mole Rat}
{11701}{}{A tough mutant mole rat.}
{11800}{}{Mutated Pig Rat}
{11801}{}{A tough mutant pig rat.}
{11900}{}{Наемник}
{12000}{}{Наемник}
{12100}{}{Капитан наемников}
{12200}{}{Hero Andro (don't use)}
{12300}{}{Hero Andro (don't use)}
{12400}{}{Hero Male (don't use)}
{12500}{}{Hero Female (don't use)}
{12600}{}{Hero Male (don't use)}
{12700}{}{Hero Female (don't use)}
{12800}{}{Hero Male (don't use)}
{12900}{}{Hero Female (don't use)}
{13000}{}{Hero Male (don't use)}
{13100}{}{Hero Female (don't use)}
{13200}{}{Hero Male (don't use)}
{13300}{}{Hero Female (don't use)}
{13400}{}{Охранник Города Убежища}
{13500}{}{Охранник Города Убежища}
{13600}{}{Киберпес}
{13700}{}{Полицейский}
{13800}{}{Полицейский}
{13900}{}{Тренер}
{14000}{}{Slaver Guard}
{14100}{}{Жирюга Джексон}
{14200}{}{Grand Master Trader}
{14300}{}{Grand Master Trader}
{14400}{}{Ручной коготь смерти}
{14500}{}{Вождь племени}
{14600}{}{Робоглаз-защитник}
{14700}{}{Охотник Койотов}
{14800}{}{Респектабельный гражданин}
{14900}{}{Приспешник братьев Блум}
{15000}{}{Коротышка}
{15100}{}{Один из братьев Блум}
{15200}{}{Goris}
{15300}{}{Наемник}
{15400}{}{Наемник}
{15500}{}{Капитан наемников}
{15600}{}{Наемник}
{15700}{}{Наемник}
{15800}{}{Капитан наемников}
{15900}{}{Generic Ghoul}
{16000}{}{Myron}
{16100}{}{Marcus}
{16200}{}{Доктор}
{16300}{}{Davin}
{16400}{}{Miria}
{16500}{}{Laddie}
{16600}{}{Механик}
{16700}{}{Разнорабочий}
{16800}{}{Разнорабочий}
{16900}{}{Разнорабочий}
{17000}{}{Bouncer}
{17100}{}{Большой Луи}
{17200}{}{Weak Mr. Handy}
{17300}{}{Харди}
{17400}{}{Ник Хауэр}
{17500}{}{Охранник Харди}
{17600}{}{Бертон Хикок}
{17700}{}{test (don't use)}
{17800}{}{Reactor Ghoul}
{17900}{}{Generic Ghoul}
{18000}{}{Майк}
{18100}{}{Райли}
{18200}{}{Bounty Hunter (1-6)}
{18300}{}{B. Hunter Lead (7-12)}
{18400}{}{Рядовой}
{18500}{}{Постовой}
{18600}{}{B. Hunter Lead (13-18)}
{18700}{}{Охранник}
{18800}{}{Bounty Hunter (13-18)}
{18900}{}{B. Hunter Lead (19-?)}
{19000}{}{Bounty Hunter (19-?)}
{19100}{}{Bess}
{19101}{}{A two headed, mutant animal.}
{19200}{}{Человек в мантии}
{19300}{}{Нискигван Взъерошенные Перья}
{19400}{}{Phil}
{19500}{}{"Супер 8"}
{19600}{}{Вшивый нищеброд}
{19700}{}{Дитя}
{19800}{}{Огима Черное Облако}
{19900}{}{Шайенн}
{20000}{}{Макозид Медвежья Лапа}
{20100}{}{Подозрительный тип}
{20200}{}{Primitive Hunter}
{20300}{}{Primitive Hunter}
{20400}{}{Панк}
{20500}{}{Панк}
{20600}{}{Панк}
{20700}{}{Holy Woman}
{20800}{}{Nomad- Low}
{20900}{}{Nomad- Med}
{21000}{}{Nomad- Low}
{21100}{}{Nomad- Med}
{21200}{}{Bandit}
{21300}{}{Bandit}
{21400}{}{Farmer}
{21500}{}{Farmer}
{21600}{}{Mantis}
{21700}{}{Slaver}
{21800}{}{Slaver}
{21900}{}{Wild Brahmin}
{22000}{}{Homesteader}
{22100}{}{Homesteader}
{22200}{}{Патрульный}
{22300}{}{Патрульный}
{22400}{}{Strong Slaver}
{22500}{}{Strong Slaver}
{22600}{}{Crazy}
{22700}{}{Scavenger}
{22800}{}{Glow Crazy}
{22900}{}{Glow Scavenger}
{23000}{}{Рейдер}
{23100}{}{Рейдер}
{23200}{}{Wilder}
{23300}{}{Wilder}
{23400}{}{Bootlegger}
{23500}{}{Bootlegger}
{23600}{}{Prospector}
{23700}{}{Prospector}
{23800}{}{Raider}
{23900}{}{Raider}
{24000}{}{Acid Gecko}
{24100}{}{Tough Acid Gecko}
{24200}{}{Alien}
{24300}{}{Tough Alien}
{24400}{}{Sm Tough Deathclaw}
{24500}{}{Tough Deathclaw}
{24600}{}{Floater}
{24700}{}{Nasty Floater}
{24800}{}{Тарантул}
{24900}{}{Mean Centaur}
{25000}{}{Генерал Вескер}
{25100}{}{Генератор}
{25200}{}{Press Gang}
{25300}{}{Press Gang}
{25400}{}{Mercenary}
{25500}{}{Mercenary}
{25600}{}{Nightkin}
{25700}{}{Tough Nightkin}
{25800}{}{Tough Ghoul}
{25900}{}{Mobster}
{26000}{}{Разбойник}
{26100}{}{Полицейский}
{26200}{}{Полицейский}
{26300}{}{Maurader}
{26400}{}{Maurader}
{26500}{}{Администратор}
{26600}{}{Vorpal Rat}
{26700}{}{Тед Банди}
{26800}{}{Байкер}
{26900}{}{Смотритель}
{27000}{}{Mysterious Stranger}
{27100}{}{Mysterious Stranger}
{27200}{}{Терри Дэверо}
{27300}{}{Дерзкий шахтер}
{27400}{}{Телохранитель}
{27500}{}{Mother Deathclaw}
{27600}{}{Один из Королей}
{27700}{}{Дилижансер}
{27800}{}{Мормон}
{27900}{}{Мормон}
{28000}{}{Mysterious Stranger}
{28100}{}{Mysterious Stranger}
{28200}{}{Mysterious Stranger}
{28300}{}{Mysterious Stranger}
{28400}{}{Mysterious Stranger}
{28500}{}{Mysterious Stranger}
{28600}{}{Mysterious Stranger}
{28700}{}{Mysterious Stranger}
{28800}{}{Pres. Bodyguard}
{28900}{}{Deathclaw Egg}
{29000}{}{Байкер Фил}
{29100}{}{Преследователь}
{29200}{}{Земляной дракон}
{29300}{}{Уильямсон}
{29400}{}{Том Паркер}
{29500}{}{Инженер}
{29600}{}{Курьер из Вегаса}
{29700}{}{Льюис Берч}
{29800}{}{Kid}
{29900}{}{Kid}
{30000}{}{Gun Merchant}
{30100}{}{Административный работник}
{30200}{}{Нельсон}
{30300}{}{Крестьянин}
{30400}{}{Крестьянин}
{30500}{}{Дерзкий шахтер}
{30600}{}{Мэрилин}
{30700}{}{Дерзкий шахтер}
{30800}{}{Вортис}
{30900}{}{Койот}
{31000}{}{Sulik - Stage 1}
{31100}{}{Sulik - Stage 2}
{31200}{}{Sulik - Stage 3}
{31300}{}{Sulik - Stage 4}
{31400}{}{Sulik - Stage 5}
{31500}{}{Sulik - Stage 6}
{31600}{}{Lenny - Stage 1}
{31700}{}{Lenny - Stage 2}
{31800}{}{Lenny - Stage 3}
{31900}{}{Goris - Stage 1}
{32000}{}{Goris - Stage 2}
{32100}{}{Goris - Stage 3}
{32200}{}{Goris - Stage 4}
{32300}{}{Goris - Stage 5}
{32400}{}{Goris - Stage 6}
{32500}{}{Myron - Stage 1}
{32600}{}{Myron - Stage 2}
{32700}{}{Myron - Stage 3}
{32800}{}{Myron - Stage 4}
{32900}{}{Marcus - Stage 1}
{33000}{}{Marcus - Stage 2}
{33100}{}{Marcus - Stage 3}
{33200}{}{Marcus - Stage 4}
{33300}{}{Marcus - Stage 5}
{33400}{}{Cyberdog - Stage 1}
{33500}{}{Cyberdog - Stage 2}
{33600}{}{Cyberdog - Stage 3}
{33700}{}{Cyberdog - Stage 4}
{33800}{}{Cassidy - Stage 1}
{33900}{}{Cassidy - Stage 2}
{34000}{}{Cassidy - Stage 3}
{34100}{}{Cassidy - Stage 4}
{34200}{}{Dogmeat}
{34300}{}{Dogmeat - Stage 1}
{34400}{}{Dogmeat - Stage 2}
{34500}{}{Dogmeat - Stage 3}
{34600}{}{Dogmeat - Stage 4}
{34700}{}{Dogmeat - Stage 5}
{34800}{}{Dogmeat - Stage 6}
{34900}{}{Robobrain - Stage 1}
{35000}{}{Robobrain - Stage 2}
{35100}{}{Robobrain - Stage 3}
{35200}{}{Robobrain - Stage 4}
{35300}{}{Robobrain - Stage 5}
{35400}{}{Queen Alien}
{35500}{}{Black Radscorpion}
{35600}{}{Black Radscorpion}
{35700}{}{Скорпион-легенда}
{35800}{}{Живорез}
{35900}{}{Рейдер}
{36000}{}{Рейдер}
{36100}{}{Боец}
{36200}{}{Панк}
{36300}{}{Панк}
{36400}{}{Охранник ранчо}
{36500}{}{Работник ранчо}
{36600}{}{Байкер}
{36700}{}{Коротышка}
{36800}{}{Проводник}
{36900}{}{Охранник конвоя}
{37000}{}{Охранник конвоя}
{37100}{}{Рикардо Бертолини}
{37200}{}{Респектабельная гражданка}
{37300}{}{Vic - Stage 1}
{37400}{}{Vic - Stage 2}
{37500}{}{Vic - Stage 3}
{37600}{}{Vic - Stage 4}
{37700}{}{Vic - Stage 5}
{37800}{}{Vic - Stage 6}
{37900}{}{RoboBrain - Chimp}
{38000}{}{Robobrain - Abnormal}
{38100}{}{Robobrain - Human}
{38200}{}{Giant Ant}
{38300}{}{Tough Giant Ant}
{38400}{}{Pariah Dog}
{38500}{}{Слабый бойцовый раб}
{38600}{}{Здоровый бойцовый раб}
{38700}{}{Сильный бойцовый раб}
{38800}{}{Мощный бойцовый раб}
{38900}{}{Бойцовый раб-мастер}
{39000}{}{Слабый боец ринга}
{39100}{}{Сильный боец ринга}
{39200}{}{Мощный боец ринга}
{39300}{}{Мастер ринга}
{39400}{}{Боец-профессионал}
{39500}{}{Чемпион ринга}
{39600}{}{Чемпион ринга}
{39700}{}{Интендант}
{39800}{}{Чемпион ринга}
{39900}{}{Чемпион ринга}
{40000}{}{Абсолютный чемпион ринга}
{40100}{}{Мистер Чейз}
{40200}{}{Боб Нил}
{40300}{}{Инженер}
{40400}{}{Angry Brahmin}
{40500}{}{Тренер}
{40600}{}{Предприниматель}
{40700}{}{Реднек}
{40800}{}{Бишоп}
{40900}{}{Мачете}
{41000}{}{Хозяин}
{41100}{}{Старик Джед}
{41200}{}{Джерлак}
{41300}{}{Mrs. Wright}
{41400}{}{Соломон}
{41500}{}{Максон}
{41600}{}{Максон}
{41700}{}{Боец из трущоб}
{41800}{}{Бандерша}
{41900}{}{Бандерша}
{42000}{}{Мистер Лучиано}
{42100}{}{Телохранитель}
{42200}{}{Охрана казино}
{42300}{}{Охранник}
{42400}{}{Директор завода}
{42500}{}{Generic Bartender}
{42600}{}{Generic Bartender}
{42700}{}{Boxer 1}
{42800}{}{Boxer 2}
{42900}{}{Boxer 3}
{43000}{}{Boxer 4}
{43100}{}{Mike the Masticator}
{43200}{}{Holyfeld}
{43300}{}{McKneely}
{43400}{}{Заводила ринга}
{43500}{}{Томпсон}
{43600}{}{Полковник Найт}
{43700}{}{Собиратель Душ}
{43800}{}{Casino Bouncer}
{43900}{}{Casino Bouncer}
{44000}{}{Casino Girl}
{44100}{}{Драгдилер}
{44200}{}{Драгдилер}
{44300}{}{Командир}
{44400}{}{Ополченец}
{44500}{}{Страйкер}
{44600}{}{Байкер}
{44700}{}{Slut}
{44800}{}{Slut}
{44900}{}{Старатель}
{45000}{}{Аптекарь}
{45100}{}{Повар}
{45200}{}{Патрик}
{45300}{}{Ковбой}
{45400}{}{Бартон}
{45500}{}{Путешественник}
{45600}{}{Путешественник}
{45700}{}{Trader 1}
{45800}{}{Trader 2}
{45900}{}{Работорговец}
{46000}{}{Работорговец}
{46100}{}{Работорговец}
{46200}{}{Гилмор}
{46300}{}{Неоновый Гангстер}
{46400}{}{Караванщик}
{46500}{}{Soldier 3}
{46600}{}{Soldier 4}
{46700}{}{Собиратель Душ}
{46800}{}{Президент}
{46900}{}{Bartender}
{47000}{}{Gun Turret}
{47001}{}{This is an automated gun turret equipped with a Dual Plasma Cannon.}
{47100}{}{K-9 (base)}
{47200}{}{K-9 (stage 1)}
{47300}{}{K-9 (stage 2)}
{47400}{}{K-9 (stage 3)}
{47500}{}{K-9 (stage 4)}
{47600}{}{Generic Cyberdog}
{47700}{}{Wanamingo Egg}
{47800}{}{Lo Pan Guard}
{47900}{}{Лихой разработчик}
{48000}{}{Auto-Cannon}
{48100}{}{Special Gecko Critter}
{48200}{}{Grim Reaper}
{48300}{}{Президент}
{48301}{}{The President's Body Guard}