{100}{}{Burning Metal Barrel}
{101}{}{The barrel contains burning paper and other flaming refuse.}
{200}{}{Wooden Door}
{201}{}{A door, made from wood.}
{300}{}{Wooden Table}
{301}{}{A table, made from wood.}
{400}{}{Wooden Table}
{401}{}{A table, made from wood.}
{500}{}{Metal Barrel}
{501}{}{An old barrel, made from steel.}
{600}{}{Metal Barrel}
{601}{}{An old barrel, made from steel.}
{700}{}{Stack of Tires}
{701}{}{A stack of ancient rubber tires. They have vulcanized and hardened, probably due to the heat.}
{800}{}{Security Door}
{801}{}{This door looks very secure. It provides protection from the outside world elements and dangerous creatures.}
{900}{}{Computer}
{901}{}{A computer terminal, hooked into a mainframe computer.}
{1000}{}{Column}
{1001}{}{A support column, providing stress relief for the entire complex.}
{1100}{}{Computer}
{1101}{}{A computer terminal, hooked into a mainframe computer.}
{1200}{}{Computer}
{1201}{}{A computer terminal, hooked into a mainframe computer.}
{1300}{}{Monitor}
{1301}{}{A green-screen display monitor, showing various bits of data. A few bytes occasionally show up.}
{1400}{}{Monitor}
{1401}{}{A green-screen display monitor, showing various bits of data.}
{1500}{}{Auto-Doc}
{1501}{}{This Auto-Doc is designed to heal illnesses and adminster various drugs.}
{1600}{}{Screens}
{1601}{}{A series of three display monitors, showing various bits of data.}
{1700}{}{Screens}
{1701}{}{A set of three display monitors, showing various bits of data from around the Vault.}
{1800}{}{Door}
{1801}{}{It's still a door after closer examination.}
{1900}{}{Door}
{1901}{}{It's still a door after closer examination.}
{2000}{}{Vent}
{2001}{}{An air vent, supplying processed and cleaned air to the entire complex.}
{2100}{}{Vent}
{2101}{}{An air vent, supplying processed and cleaned air to the entire complex.}
{2200}{}{Двери}
{2201}{}{Большие крепкие двери парадного входа.}
{2300}{}{Дверца гардероба}
{2400}{}{Pedestal}
{2401}{}{A hydraulic lift, designed to help provide support, power and communication lines to the platform.}
{2500}{}{Monitor}
{2501}{}{If you've seen one monitor, you've seen them all.}
{2600}{}{Monitor}
{2601}{}{A computer monitor, displaying various bits of data.}
{2700}{}{Grating}
{2701}{}{A floor grating.}
{2800}{}{Pipes}
{2801}{}{Some pipes. After closer examination, they are still pipes.}
{2900}{}{Vent}
{2901}{}{Standard Vault-Tec ventilation system.}
{3000}{}{Column}
{3001}{}{A standard Vault-Tec column support system.}
{3100}{}{Column}
{3101}{}{A standard Vault-Tec column support system.}
{3200}{}{Vent}
{3201}{}{Standard Vault-Tec ventilation system.}
{3300}{}{Vent}
{3301}{}{Standard Vault-Tec ventilation system.}
{3400}{}{Bed}
{3401}{}{A bed, it looks pretty comfortable after what you have been sleeping on.}
{3500}{}{Bed}
{3501}{}{A standard bed. Looks comfy.}
{3600}{}{Bed}
{3601}{}{A standard bed. Looks comfy.}
{3700}{}{Bed}
{3701}{}{A standard bed. Looks comfy.}
{3800}{}{Elevator}
{3801}{}{This is a maintanence elevator.}
{3900}{}{Chair}
{3901}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4000}{}{Chair}
{4001}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4100}{}{Chair}
{4101}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4200}{}{Chair}
{4201}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4300}{}{Monitor}
{4301}{}{A computer monitor, displaying various bits of data.}
{4400}{}{Monitor}
{4401}{}{A computer monitor, displaying various bits of data.}
{4500}{}{Monitor}
{4501}{}{A computer monitor, displaying various bits of data.}
{4600}{}{Monitor}
{4601}{}{A computer monitor, displaying various bits of data.}
{4700}{}{Monitor}
{4701}{}{A computer monitor, displaying various bits of data.}
{4800}{}{Monitor}
{4801}{}{A computer monitor, displaying various bits of data.}
{4900}{}{Exit Grid Map Marker}
{4901}{}{Exit Grid Map Marker}
{5000}{}{Air Processing Unit}
{5001}{}{An APU cleans the old air to provide new air for the complex. This one is broken.}
{5100}{}{Chair}
{5101}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5200}{}{Chair}
{5201}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5300}{}{Chair}
{5301}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5400}{}{Chair}
{5401}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5500}{}{VDU}
{5501}{}{This Video Display Unit has a variety of computer monitors and other screens. It looks very, very busy.}
{5600}{}{VDU}
{5601}{}{This Video Display Unit has a variety of computer monitors and other screens. It looks very, very busy.}
{5700}{}{Chair}
{5701}{}{It's a chair. It looks mighty comfortable.}
{5800}{}{Chair}
{5801}{}{It's a chair. It looks mighty comfortable.}
{5900}{}{Chair}
{5901}{}{It's a chair. It looks mighty comfortable.}
{6000}{}{Chair}
{6001}{}{It's a chair. It looks mighty comfortable.}
{6100}{}{Table}
{6101}{}{It's a table. Before tables, people had to keep their stuff on the floor.}
{6200}{}{Table}
{6201}{}{It's definitely a table.}
{6300}{}{Tumbleweed}
{6301}{}{It's a tumbleweed. Of course, you've never seen a real live tumbleweed before. You'd better keep a close eye on it.}
{6400}{}{Cactus}
{6401}{}{You see nothing special about this cactus.}
{6500}{}{Feroactus}
{6501}{}{You see nothing important about this cactus.}
{6600}{}{Tree}
{6601}{}{A dead tree. Nothing grows well here.}
{6700}{}{Secret Blocking Hex}
{6701}{}{If you can see this, blame the technical designer.}
{6800}{}{Туман}
{6900}{}{Stalagmite}
{6901}{}{A natural extension of the rock floor.}
{7000}{}{Stalagmite}
{7001}{}{A natural extension of the rock floor.}
{7100}{}{Blood Stain}
{7101}{}{There is nothing out of the ordinary with this bloody stain. Except, of course, that someone or something died here.}
{7200}{}{Rock Column}
{7201}{}{This thick column of rock extends from floor to ceiling.}
{7300}{}{Rock Column}
{7301}{}{This thin column of rock extends from floor to ceiling.}
{7400}{}{Rocks}
{7401}{}{You study the rocks for a while, but they never move.}
{7500}{}{Rocks}
{7501}{}{You keep a close eye on these rocks, in case they move to attack you.}
{7600}{}{Доски}
{7601}{}{Стопка аккуратно сложенных досок.}
{7700}{}{Gate}
{7701}{}{A wooden gate.}
{7800}{}{Rocks}
{7801}{}{A large pile of rocks. They look indigenous to this region.}
{7900}{}{Rocks}
{7901}{}{A small pile of rocks.}
{8000}{}{Rocks}
{8001}{}{A small pile of rocks.}
{8100}{}{Rocks}
{8101}{}{A large pile of rocks.}
{8200}{}{Bones}
{8201}{}{A large pile of bleached animal bones. At least, you think all the bones are animal...}
{8300}{}{Bones}
{8301}{}{A large pile of bleached animal bones. At least, you think all the bones are animal...}
{8400}{}{Bones}
{8401}{}{A very large pile of bleached bones. You cannot determine the species of the dead critters.}
{8500}{}{Bones}
{8501}{}{You think these might be Horned Kangaroo bones, but you cannot be sure. They are too weathered to make a final determination.}
{8600}{}{Bones}
{8601}{}{You see the bones of a large, two-headed animal.}
{8700}{}{Gate}
{8701}{}{A wooden gate. It opens, and closes, and opens, and closes, and...}
{8800}{}{Gate}
{8801}{}{A wooden gate.}
{8900}{}{Gate}
{8901}{}{A wooden gate.}
{9000}{}{Rocks}
{9001}{}{A very large pile of rocks. They look dangerous just sitting there.}
{9100}{}{Rocks}
{9101}{}{A large pile of rocks. If you look closely, you can see the faces of little old men in the sides of the stones.}
{9200}{}{Rocks}
{9201}{}{Rocks, rocks, rocks! Everywhere you look, rocks!}
{9300}{}{Rocks}
{9301}{}{A small pile of rocks.}
{9400}{}{Bar}
{9401}{}{This bar has a collection of brewed beverages ready to pour.}
{9500}{}{Chair}
{9501}{}{A rotting old chair made out of an ancient car seat.}
{9600}{}{Chair}
{9601}{}{A smelly old chair that used be to a car seat. The springs have lost their spring.}
{9700}{}{Chair}
{9701}{}{A rotting, smelly old chair sitting on bricks for support. Looks pretty uncomfortable.}
{9800}{}{Chair}
{9801}{}{A rotting, smelly old chair sitting on bricks for support. Looks pretty uncomfortable.}
{9900}{}{Couch}
{9901}{}{A very uncomfortable looking sitting device, sometimes known as a couch.}
{10000}{}{Couch}
{10001}{}{A very uncomfortable looking sitting device, sometimes known as a couch.}
{10100}{}{Tire}
{10101}{}{An old rubber tire sitting in the middle of some weeds.}
{10200}{}{Scrub}
{10201}{}{Some sort of desert weed.}
{10300}{}{Scrub}
{10301}{}{Some sort of desert weed.}
{10400}{}{Scrub}
{10401}{}{Some sort of desert weed.}
{10500}{}{Scrub}
{10501}{}{Some sort of desert weed.}
{10600}{}{Junk}
{10601}{}{It's a rusted car door leaning on a rusted metal barrel. A whole lot of rust is going on.}
{10700}{}{Junk}
{10701}{}{A broken toilet, half-buried in the sand. Life's a pisser, then you die.}
{10800}{}{Weeds}
{10801}{}{Some sort of desert scrub. If it was growing in the recent past, it isn't now.}
{10900}{}{Junk}
{10901}{}{A car tire, buried in the sand. Some small pieces of wood are piled up around it.}
{11000}{}{Junk}
{11001}{}{On closer examination, you think these might actually be pieces of petrified wood.}
{11100}{}{Dirt}
{11101}{}{A small pile of dirt, with a dead weed sticking out of it.}
{11200}{}{Dirt}
{11201}{}{A small pile of dirt.}
{11300}{}{Dirt}
{11301}{}{A small pile of dirt.}
{11400}{}{Dirt}
{11401}{}{A small pile of dirt.}
{11500}{}{Weed}
{11501}{}{A small pile of dirt, with a dry weed sticking out of it.}
{11600}{}{Junk}
{11601}{}{A twisted piece of rusted metal.}
{11700}{}{Junk}
{11701}{}{Some broken pieces of wood.}
{11800}{}{Junk}
{11801}{}{A small pile of random junk.}
{11900}{}{Dirt}
{11901}{}{A small pile of dirt.}
{12000}{}{Dirt}
{12001}{}{A small pile of dirt.}
{12100}{}{Dirt}
{12101}{}{A small pile of dirt.}
{12200}{}{Dirt}
{12201}{}{A small pile of dirt.}
{12300}{}{Dirt}
{12301}{}{A small pile of dirt.}
{12400}{}{Dirt}
{12401}{}{A small pile of dirt.}
{12500}{}{Weed}
{12501}{}{A generic desert weed.}
{12600}{}{Weed}
{12601}{}{A generic desert weed.}
{12700}{}{Weed}
{12701}{}{A generic desert weed.}
{12800}{}{Blocking Hex (NoLight)}
{12900}{}{Танкер}
{13000}{}{Танкер}
{13100}{}{Танкер}
{13200}{}{Танкер}
{13300}{}{Танкер}
{13400}{}{Танкер}
{13500}{}{Танкер}
{13600}{}{Танкер}
{13700}{}{Танкер}
{13800}{}{Танкер}
{13900}{}{Ladder}
{13901}{}{It's an old, fairly rickety ladder.}
{14000}{}{Sewer Hole}
{14001}{}{It looks like an access hole for the underground facilities.}
{14100}{}{Light Source}
{14200}{}{Door}
{14201}{}{This looks like a standard Vault door that has been damaged, perhaps burned. It is still functional, however.}
{14300}{}{Door}
{14301}{}{This looks like a standard Vault door that has been damaged, perhaps burned. It is still functional, however.}
{14400}{}{Cover}
{14401}{}{A heavy man-hole cover. It looks like it is in good shape, and that it was recently moved.}
{14500}{}{Hole}
{14501}{}{A large hole has been blasted through this door.}
{14600}{}{Hole}
{14601}{}{A large hole has been blasted through this door.}
{14700}{}{Bullet Proof Glass}
{14701}{}{Completely unbreakable glass. Don't even try.}
{14800}{}{Bullet Proof Glass}
{14801}{}{Completely unbreakable glass. Don't even try.}
{14900}{}{Bullet Proof Glass}
{14901}{}{Completely unbreakable glass. Don't even try.}
{15000}{}{Bullet Proof Glass}
{15001}{}{Completely unbreakable glass. Don't even try.}
{15100}{}{Цель}
{15101}{}{Эта цель аккуратно нарисована краской на стене.}
{15200}{}{Хвост самолета}
{15300}{}{Хвост самолета}
{15400}{}{Люк самолета}
{15500}{}{Elevator}
{15501}{}{This is the interior of a Vault-Tec elevator. It is squeaky clean!}
{15600}{}{Elevator}
{15601}{}{This is the interior of a Vault-Tec elevator. It is squeaky clean!}
{15700}{}{Сухая трава}
{15701}{}{Трава сухая и есть.}
{15800}{}{Monitor}
{15801}{}{You see a computer monitor.}
{15900}{}{Monitor}
{15901}{}{You see a computer monitor.}
{16000}{}{Computer}
{16001}{}{This is a computer memory databank.}
{16100}{}{Computer}
{16101}{}{This is a computer memory databank.}
{16200}{}{Computer}
{16201}{}{A high-tech computer, using modern reel-to-reel storage devices instead of the antiquated punch cards.}
{16300}{}{Computer}
{16301}{}{A high-tech computer, using modern reel-to-reel storage devices instead of the antiquated punch cards.}
{16400}{}{Monitor}
{16401}{}{You see a computer monitor.}
{16500}{}{Monitor}
{16501}{}{You see a computer monitor.}
{16600}{}{Wire}
{16601}{}{Some thick cable.}
{16700}{}{Wire}
{16701}{}{Some thick cable.}
{16800}{}{Wire}
{16801}{}{Some thick cable.}
{16900}{}{Column}
{16901}{}{A support column.}
{17000}{}{Column}
{17001}{}{A support column.}
{17100}{}{Door Entry Computer}
{17101}{}{This computer controls the large vault door. You have to enter a specific access code for the computer to work.}
{17200}{}{Огонь}
{17300}{}{Vault 8 Outer Door}
{17301}{}{This large door is the link between the vault and the outside world.}
{17400}{}{Vault 8 Outer Door}
{17401}{}{This large door is the link between the vault and the outside world.}
{17500}{}{Основание}
{17501}{}{Автоматизированное основание для поста смотрителя.}
{17600}{}{Down Arrow}
{17700}{}{Up Arrow}
{17800}{}{Crate}
{17900}{}{Crate}
{18000}{}{Crate}
{18100}{}{Включатель}
{18101}{}{Включатель для гидронасоса.}
{18200}{}{Гидронасос}
{18201}{}{Это насос для выкачивания подземных вод. Довольно раритетная техника.}
{18300}{}{Балка}
{18400}{}{Заградительный бетон}
{18500}{}{Заградительный бетон}
{18600}{}{Вентиль}
{18700}{}{Переключатель}
{18800}{}{Заградительный бетон}
{18900}{}{Заградительный бетон}
{19000}{}{Bunk Bed}
{19001}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{19100}{}{Bunk Bed}
{19101}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{19200}{}{Bunk Bed}
{19201}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{19300}{}{Crate}
{19400}{}{Nuka-Cola Machine}
{19401}{}{The advertising on the side of this machine promotes their popular soda.}
{19500}{}{Wall}
{19600}{}{Trapdoor}
{19601}{}{It looks like a perfectly good trapdoor.}
{19700}{}{Manhole}
{19701}{}{The ladder in this manhole leads down into the darkness below. Ohhh, scary.}
{19800}{}{Двери убежища}
{19801}{}{Это внешние двери вашего убежища. Они закрыты и открыть их можно только изнутри.}
{19900}{}{Робот-полицейский}
{19901}{}{Всевозможные запчасти, необходимые для сборки робота-полицейского.}
{20000}{}{Pew}
{20001}{}{This looks just like you would expect it to. Nothing special about this pew.}
{20100}{}{Signpost}
{20101}{}{The sign on this post looks a little rusty.}
{20200}{}{Signpost}
{20201}{}{The sign on this post looks a little rusty.}
{20300}{}{Signpost}
{20301}{}{The sign on this post looks a little rusty.}
{20400}{}{Signpost}
{20401}{}{The sign on this post looks a little rusty.}
{20500}{}{Signpost}
{20501}{}{The sign on this post looks a little rusty.}
{20600}{}{Old Mattress}
{20601}{}{An old, beat-up mattress. You think you see some sort of small bug-like critter infesting it.}
{20700}{}{Old Mattress}
{20701}{}{Even if you were to sleep by yourself on this thing, you would not be sleeping alone.}
{20800}{}{Bed}
{20801}{}{A make-shift bed. The material was scavenged from some other source.}
{20900}{}{Bed}
{20901}{}{A make-shift bed. The material was scavenged from some other source.}
{21000}{}{Bed}
{21001}{}{This bed has seen better days (and probably nights, too.)}
{21100}{}{Bed}
{21101}{}{On closer examination, you determine that the sheets have not been changed in a very, very long time.}
{21200}{}{Bed}
{21201}{}{There are a couple stains of dubious origin on this well-worn sleeping device.}
{21300}{}{Bed}
{21301}{}{This bed has seen a lot of use and wear. Something must have crawled between the mattresses and died, too.}
{21400}{}{Земля}
{21500}{}{Земля}
{21600}{}{Земля}
{21700}{}{Земля}
{21800}{}{Земля}
{21900}{}{Земля}
{22000}{}{Boxes}
{22001}{}{These wooden boxes are falling apart from the weather.}
{22100}{}{Boxes}
{22101}{}{You find no details worth mentioning about these wooden boxes.}
{22200}{}{Boxes}
{22201}{}{You have a lot of time on your hands to be looking closely at this rotten junk.}
{22300}{}{Boxes}
{22301}{}{These wooden boxes are falling apart from the weather.}
{22400}{}{Car}
{22401}{}{This automobile is in terrible shape. You cannot think of a way to restore it.}
{22500}{}{Car}
{22501}{}{This rusted piece of scrap-metal cannot be restored.}
{22600}{}{Car}
{22601}{}{You determine that this vehicle will never drive again. Really.}
{22700}{}{Car}
{22701}{}{There is no way that this junkyard wannabe will ever drive again.}
{22800}{}{Car}
{22801}{}{If the Mechanic of the Year suddenly appeared next to you, both of you could not fix this rusty heap.}
{22900}{}{Chair}
{22901}{}{A comfy chair.}
{23000}{}{Chair}
{23001}{}{This chair looks like it has seen better years.}
{23100}{}{Chair}
{23101}{}{This chair is moldy and gross. As you can guess, it stinks, too.}
{23200}{}{Chair}
{23201}{}{This chair is falling apart. Quickly.}
{23300}{}{Chair}
{23301}{}{If someone paid you a lot of money, and you could use steel britches, you might consider sitting in this chair.}
{23400}{}{Chair}
{23401}{}{This looks like an old office chair, still in pretty good shape after all these years.}
{23500}{}{Chair}
{23501}{}{This is an old office chair. It might even support the weight of a person.}
{23600}{}{Chair}
{23601}{}{This office chair has seen better days. It's pretty much trash, now.}
{23700}{}{Chair}
{23701}{}{This looks like a chair you would see in a mortician's office - dead.}
{23800}{}{Скалы}
{23900}{}{Скалы}
{24000}{}{Лестница}
{24100}{}{Лестница}
{24200}{}{Балка}
{24300}{}{Fire Hydrant}
{24301}{}{This is a fire hydrant. Without Vault ceiling sprinklers, you might need one of these to put out fires.}
{24400}{}{Lamp Post}
{24401}{}{This lamp post looks like it is still in working condition. Imagine that, something that works out here.}
{24500}{}{Lamp Post}
{24501}{}{This lamp post will never work again.}
{24600}{}{Lamp Post}
{24601}{}{This is a working lamp post. At night, it casts a pale, gentle light that reminds you of absolutely nothing.}
{24700}{}{Lamp Post}
{24701}{}{This is a broken lamp post. It cannot be fixed.}
{24800}{}{Lamp Post}
{24801}{}{This light fixture is operational.}
{24900}{}{Lamp Post}
{24901}{}{The light in this lamp post is shattered beyond repair.}
{25000}{}{Lamp Post}
{25001}{}{This is a functional lamp post.}
{25100}{}{Смятая дверь.}
{25101}{}{Эту дверь сплющило взрывом, ее невозможно открыть обычным способом.}
{25200}{}{Junk}
{25201}{}{Definitely useless junk, no doubt about it.}
{25300}{}{Junk}
{25301}{}{Definitely useless junk, no doubt about it.}
{25400}{}{Junk}
{25401}{}{Definitely useless junk, no doubt about it.}
{25500}{}{Junk}
{25501}{}{Definitely useless junk, no doubt about it.}
{25600}{}{Junk}
{25601}{}{Definitely useless junk, no doubt about it.}
{25700}{}{Mailbox}
{25701}{}{The mailbox is empty. You get the feeling it's been that way for a while.}
{25800}{}{Door}
{25801}{}{A nicely crafted wooden door, in good condition.}
{25900}{}{Door}
{25901}{}{A nicely crafted wooden door, in good condition.}
{26000}{}{Door}
{26001}{}{A nicely crafted wooden door, in good condition.}
{26100}{}{Door}
{26101}{}{A nicely crafted wooden door, in good condition.}
{26200}{}{Pew}
{26201}{}{This wooden pew is slowly falling apart.}
{26300}{}{Pew}
{26301}{}{This pew has been neglected, and is showing signs of wear and tear.}
{26400}{}{Pew}
{26401}{}{A wooden pew that has succumbed to the effects of age and abuse.}
{26500}{}{Newspaper Machine}
{26501}{}{The newspaper machine is most likely empty.}
{26600}{}{Newspaper Machine}
{26601}{}{The newspaper machine is most likely empty.}
{26700}{}{Newspaper Machine}
{26701}{}{The newspaper machine is most likely empty.}
{26800}{}{Newspaper Machine}
{26801}{}{The newspaper machine is most likely empty.}
{26900}{}{Newspaper Machine}
{26901}{}{The newspaper machine is most likely empty.}
{27000}{}{Newspaper Machine}
{27001}{}{The newspaper machine is most likely empty. It looks like it once held adult magazines.}
{27100}{}{Junk}
{27101}{}{A bed mattress in terrible condition. Even the rats won't sleep in or on it.}
{27200}{}{Junk}
{27201}{}{A twin bed mattress that has seen many better days than this one.}
{27300}{}{Junk}
{27301}{}{A pile of rotted and weathered wood. Not worth it's weight in, well, anything.}
{27400}{}{Junk}
{27401}{}{A pile of wood, with some rusty useless nails imbedded deeply.}
{27500}{}{Boxes}
{27501}{}{A pile of old, cardboard boxes. You cannot believe that they have survived for this long.}
{27600}{}{Boxes}
{27601}{}{A pile of old, cardboard boxes.}
{27700}{}{Junk}
{27701}{}{Some junk that you think might have been a bed mattress before it was destroyed by the environment.}
{27800}{}{Rocks}
{27900}{}{Rocks}
{28000}{}{Rocks}
{28100}{}{Шахта лифта}
{28200}{}{Sink}
{28201}{}{A porcelain sink that has long lost the ability to function.}
{28300}{}{Sink}
{28301}{}{A broken porcelain sink. There is small puddle of brown water in the basin, with a floating dead rat.}
{28400}{}{Sink}
{28401}{}{This sink is not functional. You can tell this from the large crack down the middle.}
{28500}{}{Sink}
{28501}{}{A broken porcelain sink. There is small puddle of brown water in the basin, with a floating dead rat.}
{28600}{}{Stop Sign}
{28601}{}{A red sign with the word STOP written in large block letters.}
{28700}{}{Stop Sign}
{28701}{}{A red sign with the word STOP written in large block letters. The large bullet hole was added after manufacturing.}
{28800}{}{Stop Light}
{28801}{}{This is an ancient automobile traffic control device.}
{28900}{}{Stop Light}
{28901}{}{This is an ancient automobile traffic control device.}
{29000}{}{Stop Light}
{29001}{}{This is an ancient automobile traffic control device.}
{29100}{}{Street Light}
{29101}{}{This street light provides illumination after night falls, or in darkened areas.}
{29200}{}{Street Light}
{29201}{}{This street light provides illumination after night falls, or in darkened areas.}
{29300}{}{Street Light}
{29301}{}{This street light provides illumination after night falls, or in darkened areas.}
{29400}{}{Street Light}
{29401}{}{This street light provides illumination after night falls, or in darkened areas.}
{29500}{}{Street Light}
{29501}{}{This street light could provide illumination in darkened areas, if it wasn't completely broken.}
{29600}{}{Street Light}
{29601}{}{This street light could provide illumination in darkened areas, if it wasn't completely broken.}
{29700}{}{Street Light}
{29701}{}{This street light could provide illumination in darkened areas, if it wasn't completely broken.}
{29800}{}{Signpost}
{29801}{}{This sign should mark what street it is on, but the letters have faded into obscurity.}
{29900}{}{Signpost}
{29901}{}{This sign should mark what street it is on, but the letters have faded into obscurity.}
{30000}{}{Table}
{30001}{}{A wooden table, in fair to middling condition.}
{30100}{}{Table}
{30101}{}{A wooden table, in fair to middling condition.}
{30200}{}{Table}
{30201}{}{A wooden table, in middling to poor condition.}
{30300}{}{Table}
{30301}{}{A wooden table, with plastic surface, that has been broken for a while.}
{30400}{}{Table}
{30401}{}{A wooden table, painted a puke green color, that is beyond repair.}
{30500}{}{Table}
{30501}{}{This looks like an old coffee table, low to the ground for those really short mutants.}
{30600}{}{Table}
{30601}{}{This looks like an old coffee table, low to the ground for those really short mutants.}
{30700}{}{Toilet}
{30701}{}{The sharpened edges around the seat make this a very uncomfortable place to sit.}
{30800}{}{Toilet}
{30801}{}{This toilet is broken.}
{30900}{}{Toilet}
{30901}{}{Yuck! Whoever used this last did not flush!}
{31000}{}{Toilet}
{31001}{}{This toilet is broken and definitely not useable if you're a woman.}
{31100}{}{Trash}
{31101}{}{Some busted pipes half-buried in the dirt. Nothing important to see here. Move along.}
{31200}{}{Trash}
{31201}{}{Some broken pieces of glass and other ruined pieces of junk.}
{31300}{}{Trash}
{31301}{}{Some broken pieces of glass and other ruined pieces of junk.}
{31400}{}{Trash}
{31401}{}{A pipe that has been snapped in half. It looks like it rusted until it collapsed under it's own weight.}
{31500}{}{Trash Can}
{31501}{}{A trash can. You can barely read the label: Keep your city streets clean!}
{31600}{}{Tree}
{31601}{}{It's a dead tree.}
{31700}{}{Tree}
{31701}{}{A stump. Nothing really exciting. In fact, this might be the least exciting thing you have ever laid your eyes on.}
{31800}{}{Tree}
{31801}{}{It's a dead tree.}
{31900}{}{Tree}
{32000}{}{Tree}
{32100}{}{Tree}
{32200}{}{Завал}
{32300}{}{Truck}
{32301}{}{The ruined remains of a diesel truck. This hunk of metal will never move again.}
{32400}{}{Truck}
{32401}{}{This diesel truck is beyond help. Way beyond help.}
{32500}{}{Bath Tub}
{32501}{}{This bath tub is broken and cracked.}
{32600}{}{Bath Tub}
{32601}{}{On closer examination, you realize that you won't be taking your bath in this tub after all.}
{32700}{}{Urinal}
{32701}{}{It's just a urinal.}
{32800}{}{Urinal}
{32801}{}{It's just a urinal.}
{32900}{}{Urinal}
{32901}{}{It's just a urinal. Nothing special.}
{33000}{}{Urinal}
{33001}{}{It's just a urinal. Nothing special.}
{33100}{}{Water Tank}
{33101}{}{A large tank that holds liquids. In this case, you believe that it was designed to store water.}
{33200}{}{Door}
{33201}{}{A wooden door. Nothing extremely interesting about it.}
{33300}{}{Door}
{33301}{}{A wooden door. It provides an entrance and egress from this building.}
{33400}{}{Wall Lamp}
{33401}{}{This lamp looks it is in good working condition.}
{33500}{}{Wall Lamp}
{33501}{}{A broken lamp. It is not surprising that it does not work.}
{33600}{}{Wall Lamp}
{33601}{}{This lamp looks it is in good working condition.}
{33700}{}{Wall Lamp}
{33701}{}{A broken lamp. It is not surprising that it does not work.}
{33800}{}{Wall Lamp}
{33801}{}{This lamp looks it is in good working condition.}
{33900}{}{Wall Lamp}
{33901}{}{A broken lamp. It is not surprising that it does not work.}
{34000}{}{Wall Lamp}
{34001}{}{This lamp looks it is in good working condition.}
{34100}{}{Wall Lamp}
{34101}{}{A broken lamp. It is not surprising that it does not work.}
{34200}{}{Yield Sign}
{34201}{}{This was a sign to control the flow of traffic.}
{34300}{}{Yield Sign}
{34301}{}{The sign is faded, but you can make out the world YIELD.}
{34400}{}{Block Hex Auto Inviso}
{34401}{}{If you can see this, blame the technical designer.}
{34500}{}{Канализационный люк}
{34600}{}{Door}
{34601}{}{An ornate wooden door. It is obviously made from fine workmanship.}
{34700}{}{Pew}
{34701}{}{This seat is supported by large concrete bricks. That's not important, but you're the one who looked.}
{34800}{}{Staircase}
{34801}{}{This staircase leads up.}
{34900}{}{Земля}
{35000}{}{Земля}
{35100}{}{Опора моста}
{35200}{}{Знак}
{35201}{}{Затертый указатель номера трассы. На нем все еще различимы цифры "14:6".}
{35300}{}{Грузовик}
{35301}{}{Остатки дальнобойного грузовика.}
{35400}{}{Указатель}
{35401}{}{Опрокинутый дорожный указатель.}
{35500}{}{Земля}
{35600}{}{Staircase}
{35601}{}{This staircase leads down.}
{35700}{}{Байк}
{35701}{}{Этот мотоцикл имеет дактилоскопическую защиту от воров, поэтому воспользоваться им может только хозяин.}
{35800}{}{Байк}
{35801}{}{Этот мотоцикл имеет дактилоскопическую защиту от воров, поэтому воспользоваться им может только хозяин.}
{35900}{}{Байк}
{35901}{}{Этот мотоцикл имеет дактилоскопическую защиту от воров, поэтому воспользоваться им может только хозяин.}
{36000}{}{Байк}
{36001}{}{Этот мотоцикл имеет дактилоскопическую защиту от воров, поэтому воспользоваться им может только хозяин.}
{36100}{}{Curtain}
{36101}{}{This curtain looks like it was created by primitive means, but it is very functional.}
{36200}{}{Curtain}
{36201}{}{This curtain looks like it was created by primitive means, but it is very functional.}
{36300}{}{Bowl}
{36301}{}{A finely crafted wooden bowl. This looks like it was designed to crush and separate grains.}
{36400}{}{Bowl}
{36401}{}{A finely crafted wooden bowl.}
{36500}{}{Pot}
{36501}{}{A finely crafted pot.}
{36600}{}{Plant}
{36601}{}{It looks like a mutated cabbage to you. It seems to be thriving in the warm weather.}
{36700}{}{Plant}
{36701}{}{It looks like a mutated cabbage to you. It seems to be thriving in the warm weather.}
{36800}{}{Cart}
{36801}{}{A crude, but effective, agricultural cart.}
{36900}{}{Маис}
{37000}{}{Маис}
{37100}{}{Маис}
{37200}{}{Pot}
{37201}{}{A finely crafted clay pot.}
{37300}{}{Rake}
{37301}{}{This rake is the property of it's owners. You can't even conceive of a use for it.}
{37400}{}{Rake}
{37401}{}{This rake is the property of it's owners. You can't even conceive of a use for it.}
{37500}{}{Rake}
{37501}{}{This rake is the property of it's owners. You can't even conceive of a use for it.}
{37600}{}{Rug}
{37601}{}{A simple rug. The weaver was obviously very talented.}
{37700}{}{Rug}
{37701}{}{A simple rug. The weaver was obviously very talented.}
{37800}{}{Rug}
{37801}{}{A simple rug. The weaver was obviously very talented.}
{37900}{}{Растение}
{37901}{}{Декоративное комнатное растение.}
{38000}{}{Растение}
{38001}{}{Декоративное комнатное растение.}
{38100}{}{Байк}
{38101}{}{Этот мотоцикл имеет дактилоскопическую защиту от воров, поэтому воспользоваться им может только хозяин.}
{38200}{}{Vase}
{38201}{}{A very pretty clay vase.}
{38300}{}{Well}
{38301}{}{A typical well found in the wasteland.}
{38400}{}{Pole}
{38401}{}{This pole helps to support the yurt.}
{38500}{}{Pole}
{38501}{}{This pole helps to support the yurt.}
{38600}{}{Pole}
{38601}{}{This pole helps to support the yurt.}
{38700}{}{Pole}
{38701}{}{This pole helps to support the yurt.}
{38800}{}{Pole}
{38801}{}{This pole helps to support the yurt.}
{38900}{}{Pole}
{38901}{}{This pole helps to support the yurt.}
{39000}{}{Vault Door}
{39001}{}{This vault door is now just a heavy piece of scrap-metal.}
{39100}{}{Дверь убежища 15}
{39101}{}{Такая же большая дверь такого же убежища, как и в вашем городе, только более ржавая.}
{39200}{}{Brace}
{39201}{}{This brace helps to support the defensive wall.}
{39300}{}{Brace}
{39301}{}{This brace helps to support the defensive wall.}
{39400}{}{Brace}
{39401}{}{This brace helps to support the defensive wall.}
{39500}{}{Brace}
{39501}{}{This brace helps to support the defensive wall.}
{39600}{}{Metal Barrel}
{39601}{}{A rusty metal barrel. It is empty.}
{39700}{}{Metal Barrel}
{39701}{}{This barrel is probably empty from the hollow sound.}
{39800}{}{Metal Barrels}
{39801}{}{These barrels are probably empty from their hollow sound.}
{39900}{}{Metal Barrels}
{39901}{}{These barrels are probably empty from their hollow sound.}
{40000}{}{Air Vent}
{40001}{}{This air vent appears to be for an underground structure.}
{40100}{}{Crate}
{40101}{}{A wooden crate. It doesn't look in that bad of shape.}
{40200}{}{Crate}
{40201}{}{A simple wooden crate. In fairly good condition.}
{40300}{}{Crate}
{40301}{}{This simple wooden crate has collapsed under it's own weight.}
{40400}{}{Desk}
{40401}{}{A simple desk with a computer.}
{40500}{}{Desk}
{40501}{}{A simple desk with a computer.}
{40600}{}{Door}
{40601}{}{A wooden door, in fair shape.}
{40700}{}{Cave In}
{40701}{}{A large amount of rock, far more than could ever be moved easily.}
{40800}{}{Car}
{40801}{}{This submerged car cannot be repaired.}
{40900}{}{Car}
{40901}{}{This car is a little wet, and cannot be repaired.}
{41000}{}{Car}
{41001}{}{This car has been poorly parked. Unfortunately, it is beyond repair.}
{41100}{}{Junk}
{41101}{}{This junk has been ruined by the contaminated seawater.}
{41200}{}{Junk}
{41201}{}{This junk has almost washed away.}
{41300}{}{Junk}
{41301}{}{A choice selection of useless junk.}
{41400}{}{Pipes}
{41401}{}{Эти толстые трубы предназначены для перекачки жидкостей в больших объемах.}
{41500}{}{Pipe}
{41501}{}{Эти толстые трубы предназначены для перекачки жидкостей в больших объемах.}
{41600}{}{Pipes}
{41601}{}{Эти толстые трубы предназначены для перекачки жидкостей в больших объемах.}
{41700}{}{Elevator Shaft}
{41701}{}{Part of an elevator system.}
{41800}{}{Elevator Shaft}
{41801}{}{An elevator shaft that stretches deep into the ground. It has been damaged.}
{41900}{}{Elevator}
{41901}{}{An elevator. Use it to go up and down between levels.}
{42000}{}{Elevator Shaft}
{42001}{}{An elevator shaft that stretches deep into the ground. It has been damaged.}
{42100}{}{Электронная дверь}
{42101}{}{Эта дверь имеет электронный замок и она работает от электричества.}
{42200}{}{Pipe}
{42201}{}{A metal pipe. Further details are not important.}
{42300}{}{Dirt}
{42400}{}{Box}
{42500}{}{Box}
{42600}{}{Box}
{42700}{}{Box}
{42800}{}{Rocks}
{42801}{}{A pile of rocks. Not very interesting.}
{42900}{}{Rocks}
{42901}{}{A pile of rocks. Not very interesting.}
{43000}{}{Rocks}
{43001}{}{A small pile of rocks. Not in the least bit interesting to you.}
{43100}{}{Rocks}
{43101}{}{A very small pile of rocks.}
{43200}{}{Rocks}
{43201}{}{A very small pile of rocks.}
{43300}{}{Rocks}
{43301}{}{A very small pile of rocks.}
{43400}{}{Rocks}
{43401}{}{A very small pile of rocks.}
{43500}{}{Rocks}
{43501}{}{A small pile of rocks.}
{43600}{}{Vault Door}
{43601}{}{This vault door is very similar to the one at Vault-8. The door mechanism has been disabled.}
{43700}{}{Door}
{43701}{}{A finely constructed wooden door, reinforced with ornate metal braces of an almost hypnotic design.}
{43800}{}{Door}
{43801}{}{A finely constructed wooden door, reinforced with ornate metal braces of an almost hypnotic design.}
{43900}{}{Тень}
{44000}{}{Тень}
{44100}{}{Тень}
{44200}{}{Тень}
{44300}{}{Тень}
{44400}{}{Тень}
{44500}{}{Груда металла}
{44600}{}{Неприметный мусор}
{44601}{}{Куча грязного мусора, засыпанного песком и поросшего травой. Но что-то в нем есть особенное.}
{44700}{}{Электрощит}
{44800}{}{Решетка}
{44801}{}{Грязная канализационная калитка.}
{44900}{}{Уличный фонарь}
{45000}{}{Well}
{45001}{}{A typical well found in the wasteland.}
{45100}{}{Craps Table}
{45200}{}{Craps Table}
{45300}{}{Craps Table}
{45400}{}{Craps Table}
{45500}{}{Craps Table}
{45600}{}{Craps Table}
{45700}{}{Craps Table}
{45800}{}{Craps Table}
{45900}{}{Craps Table}
{46000}{}{Craps Table}
{46100}{}{Rock}
{46101}{}{A small rock, completely uninteresting in the context of this story.}
{46200}{}{Rock}
{46300}{}{Rock}
{46400}{}{Rock}
{46500}{}{Slot Machine}
{46501}{}{This is a gambling machine.}
{46600}{}{Slot Machine}
{46601}{}{This is a gambling machine.}
{46700}{}{Doorway}
{46800}{}{Elevator}
{46900}{}{Elevator}
{47000}{}{Elevator Door}
{47100}{}{Window}
{47101}{}{Instead of glass, this window is using wax paper.}
{47200}{}{Window}
{47201}{}{Instead of glass, this window is using wax paper.}
{47300}{}{Window}
{47301}{}{Instead of glass, this window is using wax paper.}
{47400}{}{Window}
{47401}{}{Instead of glass, this window is using wax paper.}
{47500}{}{Door}
{47501}{}{This large metal roll-door has been jammed shut from the inside.}
{47600}{}{Door}
{47601}{}{This large metal roll-door has been jammed shut from the inside.}
{47700}{}{Door}
{47701}{}{This large metal roll-door has been jammed shut from the inside. It reads LOADING ONLY.}
{47800}{}{Door}
{47801}{}{This large metal roll-door has been jammed shut from the inside.}
{47900}{}{Door}
{47901}{}{This large metal roll-door has been jammed shut from the inside.}
{48000}{}{Door}
{48001}{}{This large metal roll-door has been jammed shut from the inside. It reads LOADING ONLY.}
{48100}{}{Дверь}
{48101}{}{Эта дверь подозрительно похожа на ту, что установлена на складе.}
{48200}{}{Дверь}
{48201}{}{Эта дверь подозрительно похожа на ту, что установлена на складе.}
{48300}{}{Монитор}
{48301}{}{Устройство для автономного мониторинга окружающей среды. Снабжено 120-фунтовым корпусом для устойчивости.}
{48400}{}{Кабель}
{48500}{}{Podium}
{48501}{}{This is a normal podium for public speaking.}
{48600}{}{Altar}
{48700}{}{Monitor}
{48701}{}{A large monitor, black and white only. Почти как в кинотеатре!}
{48800}{}{Кабель}
{48900}{}{Forcefield}
{48901}{}{This is a powerful field of energy.}
{49000}{}{Forcefield}
{49001}{}{This is a powerful field of energy.}
{49100}{}{Forcefield}
{49101}{}{This is a powerful field of energy.}
{49200}{}{Forcefield}
{49201}{}{This is a powerful field of energy.}
{49300}{}{Table}
{49301}{}{A fairly ordinary wooden table.}
{49400}{}{Table}
{49401}{}{A fairly ordinary wooden table.}
{49500}{}{Table}
{49501}{}{A fairly ordinary wooden table.}
{49600}{}{Table}
{49601}{}{A fairly ordinary wooden table.}
{49700}{}{Table}
{49701}{}{A fairly ordinary wooden table.}
{49800}{}{Table}
{49801}{}{A fairly ordinary wooden table.}
{49900}{}{Тень}
{50000}{}{Тень}
{50100}{}{Тень}
{50200}{}{Тень}
{50300}{}{Тень}
{50400}{}{Тень}
{50500}{}{Altar}
{50501}{}{A simple altar made from painted wood.}
{50600}{}{Кабель}
{50601}{}{Толстый прочный кабель для прокладки высокого напряжения.}
{50700}{}{Кабель}
{50701}{}{Толстый прочный кабель для прокладки высокого напряжения.}
{50800}{}{Altar}
{50801}{}{A simple altar made from painted wood.}
{50900}{}{Вентиляция}
{50901}{}{Проржавевшая вентиляция с разрушенной решеткой. Через отверстие можно перелезть на другую сторону.}
{51000}{}{Тень}
{51100}{}{Тень}
{51200}{}{Тень}
{51300}{}{Тень}
{51400}{}{Тень}
{51500}{}{Тень}
{51600}{}{Следы}
{51601}{}{Вы видите следы от гусениц робота.}
{51700}{}{Следы}
{51701}{}{Вы видите следы от гусениц робота.}
{51800}{}{Следы}
{51801}{}{Вы видите следы от гусениц робота.}
{51900}{}{Следы}
{51901}{}{Вы видите следы от гусениц робота.}
{52000}{}{Баллоны}
{52001}{}{Баллоны с аварийным запасом кислорода. На каждом написано крупными буквами "ВЗРЫВООПАСНО!"}
{52100}{}{Веревка}
{52101}{}{Веревка, прикрепленная к земле и сброшенная в зловонное отверстие.}
{52200}{}{Рельсы}
{52201}{}{Просто рельсы.}
{52300}{}{Отверстие}
{52301}{}{Очень глубокое отверстие. Очень сильно воняет экскрементами и пульсирует.}
{52400}{}{Экскременты}
{52401}{}{Самые настоящие экскременты, весело разлетающиеся в разные стороны.}
{52500}{}{Pew}
{52501}{}{A nicely fashioned, and mighty uncomfortable looking, pew.}
{52600}{}{Тень}
{52700}{}{Wagon}
{52701}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{52800}{}{Wagon}
{52801}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{52900}{}{Wagon}
{52901}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53000}{}{Wagon}
{53001}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53100}{}{Wagon}
{53101}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53200}{}{Wagon}
{53201}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53300}{}{Mat}
{53301}{}{A training mat.}
{53400}{}{Mat}
{53401}{}{A training mat.}
{53500}{}{Mat}
{53501}{}{A training mat.}
{53600}{}{Mat}
{53601}{}{A training mat.}
{53700}{}{Punching Bag}
{53701}{}{This is a StrongMan(tm) punching bag.}
{53800}{}{Stair Stepper}
{53801}{}{An exercise machine.}
{53900}{}{Stair Stepper}
{54000}{}{Treadmill}
{54001}{}{An exercise machine.}
{54100}{}{Treadmill}
{54101}{}{An exercise machine.}
{54200}{}{Bench Press}
{54201}{}{An exercise machine.}
{54300}{}{Bench Press}
{54301}{}{An exercise machine.}
{54400}{}{Wood Planks}
{54401}{}{These sturdy wooden planks have been firmly bound together.}
{54500}{}{Wood Planks}
{54501}{}{These sturdy wooden planks have been firmly bound together.}
{54600}{}{Roulette Table}
{54601}{}{This is a gambling table.}
{54700}{}{Roulette Table}
{54701}{}{This is a gambling table.}
{54800}{}{Roulette Table}
{54801}{}{This is a gambling table.}
{54900}{}{Roulette Table}
{54901}{}{This is a gambling table.}
{55000}{}{Roulette Table}
{55001}{}{This is a gambling table.}
{55100}{}{Barrel}
{55101}{}{This empty metal barrel has the nuclear trefoil symbol painted on the side in bright yellow paint.}
{55200}{}{Barrel}
{55201}{}{This barrel contains some green glowing goo. The nuclear trefoil symbol gives a clue to what the goo might be.}
{55300}{}{Computer}
{55301}{}{A very modern looking computer.}
{55400}{}{Computer}
{55401}{}{A very modern looking computer.}
{55500}{}{Suspension Tank}
{55501}{}{Some sort of medical or experimental apparatus, it looks as if it could contain a human or larger sized body.}
{55600}{}{Broken Suspension Tank}
{55601}{}{A broken piece of equipment. It is beyond repair.}
{55700}{}{Оборудование}
{55701}{}{Какое-то важное оборудование, нашпигованное электроникой под завязку.}
{55800}{}{Support Platform}
{55801}{}{This platform supports оборудование over the специальными коммуникациями.}
{55900}{}{Dont use}
{56000}{}{Dont use}
{56100}{}{Bed}
{56101}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{56200}{}{Bed}
{56201}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{56300}{}{Bed}
{56301}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{56400}{}{Wire}
{56401}{}{It looks like a serial cable of some sort.}
{56500}{}{Wire}
{56501}{}{It looks like a serial cable of some sort.}
{56600}{}{Sign}
{56601}{}{The sign reads BAR. That should be pretty self-evident.}
{56700}{}{Тень}
{56800}{}{Флаг}
{56801}{}{Флаг с эмблемой дилижанса: 4 тележных колеса по углам, по центру - бычья голова в ковбойской шляпе и шейном платке.}
{56900}{}{Shelves}
{56901}{}{You see some metal storage shelves.}
{57000}{}{Shelves}
{57001}{}{You see some metal storage shelves.}
{57100}{}{Shelves}
{57101}{}{You see some metal storage shelves.}
{57200}{}{Shelves}
{57201}{}{You see some metal storage shelves.}
{57300}{}{Bush}
{57400}{}{Bush}
{57500}{}{Bush}
{57600}{}{Камни}
{57601}{}{Большая куча камней. Судя по виду, они местные.}
{57700}{}{Камни}
{57701}{}{Небольшая куча камней.}
{57800}{}{Камни}
{57801}{}{Небольшая куча камней.}
{57900}{}{Камни}
{57901}{}{Большая куча камней.}
{58000}{}{Обрыв}
{58100}{}{Door}
{58101}{}{A door that looks perfectly at home in a cell.}
{58200}{}{Мостовая опора}
{58300}{}{Ladder}
{58301}{}{This ladder leads into the darkness below.}
{58400}{}{Ladder}
{58401}{}{This ladder leads into the darkness below.}
{58500}{}{Machinery}
{58501}{}{It looks like some manufacturing doohikey.}
{58600}{}{Machinery}
{58601}{}{It looks like some manufacturing doohikey.}
{58700}{}{Machinery}
{58701}{}{It looks like some manufacturing doohikey.}
{58800}{}{Machinery}
{58801}{}{It looks like some manufacturing doohikey.}
{58900}{}{Machinery}
{58901}{}{It looks like some manufacturing doohikey.}
{59000}{}{Деталь}
{59001}{}{It looks like some manufacturing doohikey.}
{59100}{}{Table}
{59101}{}{This metal table looks in good condition. There is a drain in the center of it.}
{59200}{}{Table}
{59201}{}{This metal table looks in good condition. There is a drain in the center of it.}
{59300}{}{Table}
{59301}{}{The metal table is covered by some kind of biomass.}
{59400}{}{Table}
{59401}{}{The metal table is covered by some kind of biomass.}
{59500}{}{Table}
{59501}{}{The metal table is covered by some kind of biomass.}
{59600}{}{Bulletin Board}
{59601}{}{Notices for employment are stapled to the board. It looks well used.}
{59700}{}{Guard Shack}
{59701}{}{This guard shack is over seventy years old, but still in excellent condition.}
{59800}{}{Sign}
{59801}{}{This sign says: General Store.}
{59900}{}{Sign}
{59901}{}{This sign says: General Store.}
{60000}{}{Sign}
{60001}{}{This sign says: Market}
{60100}{}{Slime Pool}
{60101}{}{It looks very unhealthy. You might want to wear armored swim trunks before taking a dip.}
{60200}{}{Slime Pool}
{60201}{}{It looks very unhealthy. You might want to wear armored swim trunks before taking a dip.}
{60300}{}{Slime Pool}
{60301}{}{It looks very unhealthy. You might want to wear armored swim trunks before taking a dip.}
{60400}{}{Table}
{60401}{}{A nice looking metal table.}
{60500}{}{Table}
{60501}{}{A nice looking metal table.}
{60600}{}{Table}
{60601}{}{A nice looking metal table.}
{60700}{}{Table}
{60701}{}{A nice looking metal table.}
{60800}{}{Table}
{60801}{}{This metal table has not been treated well. The rust is very pervasive.}
{60900}{}{Table}
{60901}{}{A good looking metal table, except for the rust.}
{61000}{}{Table}
{61001}{}{A good looking metal table, except for the rust.}
{61100}{}{Table}
{61101}{}{A good looking metal table, except for the rust.}
{61200}{}{Fire Pit}
{61201}{}{The fire is burning.}
{61300}{}{Mirror}
{61301}{}{You look at yourself for a while.}
{61400}{}{Mirror}
{61401}{}{You stare at your image in the mirror for a while.}
{61500}{}{Sink}
{61501}{}{A fully functioning sink. Nice and clean, too.}
{61600}{}{Toilet}
{61601}{}{This toilet is very clean. It works, too.}
{61700}{}{Urinal}
{61701}{}{This urinal is functional.}
{61800}{}{Двери поезда}
{61900}{}{Sink}
{61901}{}{This sink is in perfect condition.}
{62000}{}{Urinal}
{62001}{}{This urinal is in perfect condition.}
{62100}{}{Shower}
{62101}{}{A military-style shower. Not to be used by modest people.}
{62200}{}{Shower}
{62201}{}{A military-style shower. Not to be used by modest people.}
{62300}{}{Shower}
{62301}{}{A military-style shower. Not to be used by modest people.}
{62400}{}{Shower}
{62401}{}{A military-style shower. Not to be used by modest people.}
{62500}{}{Shower}
{62501}{}{A military-style shower. Not to be used by modest people.}
{62600}{}{Shower}
{62601}{}{A military-style shower. Not to be used by modest people.}
{62700}{}{Bed}
{62701}{}{A very comfortable looking bed.}
{62800}{}{Bed}
{62801}{}{A very comfortable looking bed.}
{62900}{}{Bed}
{62901}{}{A structurally-enhanced bunk bed.}
{63000}{}{Bed}
{63001}{}{A structurally-enhanced bunk bed.}
{63100}{}{Bed}
{63101}{}{A structurally-enhanced bunk bed.}
{63200}{}{Влажная одежда}
{63201}{}{Кто-то повесил сушиться свои шмотки и оставил их без присмотра.}
{63300}{}{Водосборник}
{63301}{}{В этом огромном чане хранят воду.}
{63400}{}{Стенд}
{63401}{}{Стенд с фотографиями каких-то людей, лица которых вам кажутся знакомыми. Надпись на стенде гласит: "Наши герои"}
{63500}{}{Стенд}
{63501}{}{Стенд с коллективной фотографией работников студии.}
{63600}{}{Кулер}
{63601}{}{Обыкновенный кулер.}
{63700}{}{Computer}
{63701}{}{A large computer.}
{63800}{}{Computer}
{63801}{}{A large computer.}
{63900}{}{Computer}
{63901}{}{A large computer.}
{64000}{}{Terminal}
{64001}{}{The terminal to a large computer.}
{64100}{}{Dead Body}
{64101}{}{It looks as if this person died very painfully.}
{64200}{}{Dead Body}
{64201}{}{It looks as if this person died very painfully.}
{64300}{}{Dead Body}
{64301}{}{It looks as if this person died very painfully.}
{64400}{}{Dead Body}
{64401}{}{It looks as if this person died very painfully.}
{64500}{}{Door}
{64501}{}{This barred door works well as the door to a jail cell.}
{64600}{}{Terminal}
{64700}{}{Terminal}
{64800}{}{Forklift}
{64801}{}{The forklift is inoperable.}
{64900}{}{Forklift}
{64901}{}{The forklift is inoperable.}
{65000}{}{Auto-Doc}
{65001}{}{This Auto-Doc is designed to heal illnesses and adminster various drugs. В настоящий момент пребывает в нерабочем состоянии.}
{65100}{}{Medical Table}
{65101}{}{This table is very rusty. The drain in the center of the table is clogged.}
{65200}{}{Medical Table}
{65201}{}{This table is very rusty.}
{65300}{}{Gate}
{65301}{}{This gate has a bar that raises and lowers.}
{65400}{}{Pipe}
{65500}{}{Pipe}
{65600}{}{Power Generator}
{65601}{}{A Wattz ElectroBox power generator. Fairly standard as back-up generators before the war.}
{65700}{}{Стол с деталями}
{65701}{}{Обыкновенный стол, используемый как верстак для починки оружия.}
{65800}{}{Экспресс}
{65801}{}{Импровизированный транспорт, собранный из автомобильных и автобусных деталей. В настоящий момент умышленно выведен из строя, поэтому никуда не поедет.}
{65900}{}{Table}
{65901}{}{A nicely made table. Hand-made, but it looks much nicer than any table you've seen before.}
{66000}{}{Table}
{66001}{}{A nicely made table. Hand-made, but it looks much nicer than any table you've seen before.}
{66100}{}{Table}
{66101}{}{A nicely made table. Hand-made, but it looks much nicer than any table you've seen before.}
{66200}{}{Chair}
{66201}{}{A very nice looking chair.}
{66300}{}{Chair}
{66301}{}{A very nice looking chair.}
{66400}{}{Chair}
{66401}{}{A very nice looking chair.}
{66500}{}{Chair}
{66501}{}{A very nice looking chair.}
{66600}{}{Chair}
{66601}{}{A very nice looking chair.}
{66700}{}{Chair}
{66701}{}{A very nice looking chair.}
{66800}{}{Chair}
{66801}{}{A very nice looking chair.}
{66900}{}{Chair}
{66901}{}{A very nice looking chair.}
{67000}{}{Chair}
{67001}{}{A very nice looking chair.}
{67100}{}{Chair}
{67101}{}{A very nice looking chair.}
{67200}{}{Chair}
{67201}{}{A very nice looking chair.}
{67300}{}{Chair}
{67301}{}{A very nice looking chair.}
{67400}{}{Chair}
{67401}{}{A very nice looking chair.}
{67500}{}{Chair}
{67501}{}{A very nice looking chair.}
{67600}{}{Chair}
{67601}{}{A very nice looking chair.}
{67700}{}{Chair}
{67701}{}{A very nice looking chair.}
{67800}{}{Bed}
{67801}{}{A very nice looking bed.}
{67900}{}{Bed}
{67901}{}{A very nice looking bed.}
{68000}{}{Bed}
{68001}{}{A very nice looking bed.}
{68100}{}{Bed}
{68101}{}{A very nice looking bed.}
{68200}{}{Stove}
{68201}{}{A functional wood-burning stove.}
{68300}{}{Stove}
{68301}{}{A functional wood-burning stove.}
{68400}{}{Stove}
{68401}{}{A functional wood-burning stove.}
{68500}{}{Stove}
{68501}{}{A functional wood-burning stove.}
{68600}{}{Broken Post}
{68700}{}{Мостовая опора}
{68800}{}{Ступень ракеты-носителя}
{68801}{}{Вы видите обгоревший корпус какого-то аппарата.}
{68900}{}{Погремушка}
{68901}{}{Связка консервных банок и болтов.}
{69000}{}{Toilet}
{69001}{}{A crude, but effective, toilet. There are some leaves dropped into the hole to manage the odor.}
{69100}{}{Mountain}
{69101}{}{These mountain walls look very inaccessible.}
{69200}{}{Mountain}
{69201}{}{These mountain walls look very inaccessible.}
{69300}{}{Mountain}
{69301}{}{These mountain walls look very inaccessible.}
{69400}{}{Mountain}
{69401}{}{These mountain walls look very inaccessible.}
{69500}{}{Mountain}
{69501}{}{These mountain walls look very inaccessible.}
{69600}{}{Mountain}
{69601}{}{These mountain walls look very inaccessible.}
{69700}{}{Автобус}
{69701}{}{Вы видите обычный автобус. Он уже никогда не будет возить детей в школу.}
{69800}{}{Автобус}
{69801}{}{Вы видите сильно погоревший автобус. Точнее, бесполезный кусок ржавчины.}
{69900}{}{Ваш склад ядер-колы}
{69901}{}{Вы видите ящики со своим личным складом ядер-колы.}
{70000}{}{Обвал}
{70001}{}{Вы видите обвалившиеся стены и потолок, погребенные слоем песка и бетона.}
{70100}{}{Рекламный столб}
{70101}{}{Всего лишь старая рекламная вывеска на здоровенном столбе. Проржавела настолько, что на ней уже нельзя ничего прочитать.}
{70200}{}{Стена}
{70201}{}{Просто полуразрушенная стена. И все.}
{70300}{}{Обрыв}
{70301}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{70400}{}{Ступень ракетоносителя}
{70401}{}{Вы видите обгоревший корпус какого-то аппарата.}
{70500}{}{Ступень ракетоносителя}
{70501}{}{Вы видите обгоревший корпус какого-то аппарата.}
{70600}{}{Тень}
{70601}{}{Это тень.}
{70700}{}{Знак}
{70701}{}{Знак требует снизить скорость - не более 20 миль в час. Вам это требуется.}
{70800}{}{Экспресс}
{70801}{}{Реконструированный и переоборудованный довоенный автобус.}
{70900}{}{Указатель улицы}
{71000}{}{Указатель улицы}
{71100}{}{Указатель улицы}
{71200}{}{Указатель улицы}
{71300}{}{Экспресс}
{71301}{}{Реконструированный и переоборудованный довоенный автобус.}
{71400}{}{Обрыв}
{71401}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{71500}{}{Обрыв}
{71501}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{71600}{}{Обрыв}
{71601}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{71700}{}{Обрыв}
{71701}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{71800}{}{Установка}
{71801}{}{Перед вами часть электростанции.}
{71900}{}{Установка}
{71901}{}{Перед вами часть электростанции.}
{72000}{}{Аншлаг}
{72001}{}{Вы видите "кричащее" предупреждение о том, что вы находитесь в зоне федеральной собственности. Здесь запрещено фотографировать и вообще - лучше бы вам убраться отсюда подальше.}
{72100}{}{Goo}
{72101}{}{You see some strange noxious biological goo.}
{72200}{}{Goo}
{72201}{}{You see some strange noxious biological goo.}
{72300}{}{Goo}
{72301}{}{You see some strange noxious biological goo.}
{72400}{}{Тень}
{72500}{}{Обрыв}
{72600}{}{Обрыв}
{72700}{}{Обрыв}
{72800}{}{Обрыв}
{72801}{}{You see some strange noxious biological goo.}
{72900}{}{Goo}
{72901}{}{You see some strange noxious biological goo.}
{73000}{}{Goo}
{73001}{}{You see some strange noxious biological goo.}
{73100}{}{Goo}
{73101}{}{You see some strange noxious biological goo.}
{73200}{}{Goo}
{73201}{}{You see some strange noxious biological goo.}
{73300}{}{Goo}
{73301}{}{You see some strange noxious biological goo.}
{73400}{}{Goo}
{73401}{}{You see some strange noxious biological goo.}
{73500}{}{Goo}
{73501}{}{You see some strange noxious biological goo.}
{73600}{}{Goo}
{73601}{}{You see some strange noxious biological goo.}
{73700}{}{Goo}
{73701}{}{You see some strange noxious biological goo.}
{73800}{}{Goo}
{73801}{}{You see some strange noxious biological goo.}
{73900}{}{Goo}
{73901}{}{You see some strange noxious biological goo.}
{74000}{}{Goo}
{74001}{}{You see some strange noxious biological goo.}
{74100}{}{Goo}
{74101}{}{You see some strange noxious biological goo.}
{74200}{}{Goo}
{74201}{}{You see some strange noxious biological goo.}
{74300}{}{Goo}
{74301}{}{You see some strange noxious biological goo.}
{74400}{}{Goo}
{74401}{}{You see some strange noxious biological goo.}
{74500}{}{Goo}
{74501}{}{You see some strange noxious biological goo.}
{74600}{}{Goo}
{74601}{}{You see some strange noxious biological goo.}
{74700}{}{Goo}
{74701}{}{You see some strange noxious biological goo.}
{74800}{}{Goo}
{74801}{}{You see some strange noxious biological goo.}
{74900}{}{Обрыв}
{74901}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{75000}{}{Въезд}
{75001}{}{Подъем на верхнюю террасу.}
{75100}{}{Въезд}
{75101}{}{Подъем на верхнюю террасу.}
{75200}{}{Обрыв}
{75201}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{75300}{}{Въезд}
{75301}{}{Подъем на верхнюю террасу.}
{75400}{}{Обрыв}
{75401}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{75500}{}{Обрыв}
{75501}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{75600}{}{Обрыв}
{75601}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{75700}{}{Обрыв}
{75701}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{75800}{}{Обрыв}
{75801}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{75900}{}{Обрыв}
{75901}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{76000}{}{Обрыв}
{76001}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{76100}{}{Обрыв}
{76101}{}{По этому осыпающемуся обрыву вверх не взобраться.}
{76200}{}{Знак}
{76201}{}{Знак требует снизить скорость - не более 20 миль в час. Вам это не грозит.}
{76300}{}{Аншлаги}
{76301}{}{Вы видите "кричащие" предупреждения о том, что вы находитесь в зоне федеральной собственности, где нельзя фотографировать и лучше бы вам убраться отсюда подальше.}
{76400}{}{Радар}
{76401}{}{Радар для передачи и получения сообщений на большие расстояния.}
{76500}{}{Устройство}
{76501}{}{Некое устройство, прикрытое брезентом и приготовленное к перевозке.}
{76600}{}{Устройство}
{76601}{}{Некое устройство, прикрытое брезентом и приготовленное к перевозке.}
{76700}{}{Консоль}
{76800}{}{Nuclear bomb}
{76900}{}{Support Base}
{76901}{}{This base cradles the nuclear bomb that is sitting on it.}
{77000}{}{Овраг}
{77100}{}{Тень}
{77200}{}{Chair}
{77201}{}{There is nothing unusual about this chair.}
{77300}{}{Chair}
{77301}{}{There is nothing unusual about this chair.}
{77400}{}{Chair}
{77401}{}{There is nothing unusual about this chair.}
{77500}{}{Chair}
{77501}{}{There is nothing unusual about this chair.}
{77600}{}{Chair}
{77601}{}{There is nothing unusual about this chair.}
{77700}{}{Chair}
{77701}{}{There is nothing unusual about this chair.}
{77800}{}{Chair}
{77801}{}{There is nothing unusual about this chair.}
{77900}{}{Chair}
{77901}{}{There is nothing unusual about this chair.}
{78000}{}{Pillar}
{78001}{}{A support pillar.}
{78100}{}{Pillar}
{78101}{}{A support pillar.}
{78200}{}{Pillar}
{78201}{}{A support pillar.}
{78300}{}{Pillar}
{78301}{}{A support pillar.}
{78400}{}{Сушилка}
{78401}{}{Обыкновенная сушилка для белья и одежды.}
{78500}{}{Bed}
{78501}{}{This bed is in poor condition.}
{78600}{}{Bed}
{78601}{}{This bed is in poor condition.}
{78700}{}{Bed}
{78701}{}{This bed is in pretty bad condition.}
{78800}{}{Monitors}
{78801}{}{These monitors are broken and cannot function.}
{78900}{}{Monitors}
{78901}{}{These monitors are broken and cannot function.}
{79000}{}{Monitors}
{79001}{}{These monitors are broken and cannot function.}
{79100}{}{Monitors}
{79101}{}{These monitors are broken and cannot function.}
{79200}{}{Vent}
{79201}{}{Very little fresh air is coming from this vent.}
{79300}{}{Vent}
{79301}{}{Almost no fresh air is coming from this vent.}
{79400}{}{Vent}
{79401}{}{No fresh air is coming from this vent.}
{79500}{}{Vent}
{79501}{}{Just a tiny amount of fresh air is coming from this vent.}
{79600}{}{Table}
{79601}{}{There is nothing unusual about this table, except that it is almost destroyed.}
{79700}{}{Table}
{79701}{}{This table was badly damaged.}
{79800}{}{Table}
{79801}{}{This table is in very poor condition.}
{79900}{}{Table}
{79901}{}{There is no reason to search this table.}
{80000}{}{СВМ}
{80001}{}{Эта система мониторов в настоящий момент не работает.}
{80100}{}{СВМ}
{80101}{}{Эта система мониторов в настоящий момент не работает.}
{80200}{}{Monitor}
{80201}{}{The monitor screen is cracked and destroyed.}
{80300}{}{Monitor}
{80301}{}{This monitor is worthless with a broken display screen.}
{80400}{}{Computer}
{80401}{}{This computer is broken.}
{80500}{}{Computer}
{80501}{}{This computer is broken.}
{80600}{}{Computer}
{80601}{}{This computer is broken.}
{80700}{}{Кресло}
{80701}{}{У этого кресла повреждена обшивка.}
{80800}{}{Кресло}
{80801}{}{У этого кресла повреждена обшивка.}
{80900}{}{Кресло}
{80901}{}{У этого кресла повреждена обшивка.}
{81000}{}{Кресло}
{81001}{}{У этого кресла повреждена обшивка.}
{81100}{}{Vent}
{81101}{}{This vent has been damaged beyond repair.}
{81200}{}{Vent}
{81201}{}{This vent is very damaged, and cannot be repaired.}
{81300}{}{Vent}
{81301}{}{This vent is not functioning at all.}
{81400}{}{Computer}
{81401}{}{This computer looks like it is barely functional.}
{81500}{}{Computer}
{81501}{}{This computer looks like it is barely functional.}
{81600}{}{Monitor}
{81601}{}{The monitor is barely working.}
{81700}{}{Monitor}
{81701}{}{The monitor is barely working.}
{81800}{}{Computer}
{81801}{}{The computer is not functioning.}
{81900}{}{Computer}
{81901}{}{The computer is not functioning.}
{82000}{}{Monitor}
{82001}{}{The monitor is not functioning.}
{82100}{}{Monitor}
{82101}{}{The monitor is not functioning.}
{82200}{}{Doorway}
{82201}{}{It looks like a very nice doorway. It does the job of holding up a door very well.}
{82300}{}{Monitors}
{82301}{}{The monitors are in good condition.}
{82400}{}{Monitors}
{82401}{}{The monitors are in good condition.}
{82500}{}{Wall}
{82600}{}{Бронированная дверь}
{82601}{}{A very sturdy door. Устоит даже перед взрывом.}
{82700}{}{Light}
{82701}{}{A security light.}
{82800}{}{Light}
{82801}{}{A security light.}
{82900}{}{Веревка}
{83000}{}{Robot Receptacle}
{83001}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83100}{}{Robot Receptacle}
{83101}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83200}{}{Robot Receptacle}
{83201}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83300}{}{Robot Receptacle}
{83301}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83400}{}{Robot Receptacle}
{83401}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83500}{}{Machine}
{83501}{}{This machine has something to do with the robot service bays. It does not look particular interesting.}
{83600}{}{Machine}
{83601}{}{This machine has something to do with the robot service bays. It does not look very interesting.}
{83700}{}{Stripe}
{83800}{}{Stripe}
{83900}{}{Stripe}
{84000}{}{Stripe}
{84100}{}{Stripe}
{84200}{}{Stripe}
{84300}{}{Stripe}
{84400}{}{Stripe}
{84500}{}{Stripe}
{84600}{}{Stripe}
{84700}{}{Stripe}
{84800}{}{Door}
{84801}{}{A very normal wooden door.}
{84900}{}{Door}
{84901}{}{A very normal wooden door.}
{85000}{}{Door}
{85001}{}{A very normal wooden door.}
{85100}{}{Постер}
{85101}{}{Довоенный постер, созывающий на блюзовый концерт в кафе "Хард-Рок".}
{85200}{}{Постер}
{85201}{}{Довоенный постер, созывающий на футбольную олимпиаду на стадионе в Прово.}
{85300}{}{Medical Table}
{85301}{}{This looks like a medical examination table.}
{85400}{}{Веревка}
{85500}{}{Провода}
{85501}{}{Оголенные провода. Будьте осторожны!}
{85600}{}{Graffiti}
{85700}{}{Graffiti}
{85800}{}{Graffiti}
{85900}{}{Graffiti}
{86000}{}{Graffiti}
{86100}{}{Graffiti}
{86200}{}{Graffiti}
{86300}{}{Graffiti}
{86400}{}{Graffiti}
{86500}{}{Graffiti}
{86600}{}{Graffiti}
{86700}{}{Graffiti}
{86800}{}{Graffiti}
{86900}{}{Sign}
{86901}{}{It says: GUNS. They might sell guns there.}
{87000}{}{Sign}
{87001}{}{The sign reads: Police.}
{87100}{}{Приподнятый мост}
{87200}{}{Постер}
{87300}{}{Плакат}
{87301}{}{На этом поблекшем плакате различима пустынная трасса с горной грядой на заднем плане и надписью "Невада - страна развлечений".}
{87400}{}{Стела}
{87500}{}{Sign}
{87501}{}{Это вывеска ринга, который расположен в подвале здания.}
{87600}{}{Sign}
{87601}{}{Надпись на этой малопривлекательной вывеске гласит: "Город караванщиков".}
{87700}{}{Sign}
{87701}{}{Это вывеска гильдии работорговцев.}
{87800}{}{Egg Shell}
{87801}{}{Pieces of a broken egg shell.}
{87900}{}{Egg Shell}
{87901}{}{Pieces of a broken egg shell.}
{88000}{}{Egg Shell}
{88001}{}{Pieces of a broken egg shell.}
{88100}{}{Egg Shell}
{88101}{}{Pieces of a broken egg shell.}
{88200}{}{Egg Shell}
{88201}{}{Pieces of a broken egg shell.}
{88300}{}{Egg Shell}
{88301}{}{Pieces of a broken egg shell.}
{88400}{}{Egg Shell}
{88401}{}{Pieces of a broken egg shell.}
{88500}{}{Egg Shell}
{88501}{}{Pieces of a broken egg shell.}
{88600}{}{Lamp Post}
{88601}{}{A lamp post. It looks like it is in good working order.}
{88700}{}{Sign}
{88701}{}{The sign reads: Motel.}
{88800}{}{Mushrooms}
{88801}{}{This table planter has been filled with dung, and mushrooms are happily growing in it.}
{88900}{}{Mushrooms}
{88901}{}{This table planter has been filled with dung, and mushrooms are happily growing in it.}
{89000}{}{Skeleton}
{89100}{}{Бочка}
{89200}{}{Бочка}
{89300}{}{Sign}
{89301}{}{An advertisement for Blades-brand razor blades.}
{89400}{}{Shower}
{89401}{}{A fairly normal shower stall.}
{89500}{}{Shower}
{89501}{}{A fairly normal shower stall.}
{89600}{}{Крыша}
{89700}{}{Тень}
{89800}{}{Тень}
{89900}{}{Тень}
{90000}{}{Стела}
{90100}{}{Elevator Shaft}
{90101}{}{The shaft has a rope hanging from above.}
{90200}{}{Elevator Shaft}
{90201}{}{The shaft has a rope hanging down from the edge.}
{90300}{}{Medical Bed}
{90301}{}{This bed has a built-in display for monitoring the patients progress.}
{90400}{}{Water Pump}
{90401}{}{This is a piece of machinery that pumps water up from below.}
{90500}{}{Смотритель}
{90501}{}{Это Смотритель. Можете не верить своим глазам, но это он.}
{90600}{}{Power Armor Parts}
{90601}{}{These are parts to a suit of Power Armor.}
{90700}{}{Light}
{90701}{}{This security light is currently pulsating a bright red.}
{90800}{}{Light}
{90801}{}{This security light is currently pulsating a bright red.}
{90900}{}{Symbol}
{91000}{}{Symbol}
{91100}{}{Symbol}
{91200}{}{Symbol}
{91300}{}{Symbol}
{91400}{}{Symbol}
{91500}{}{Rope}
{91600}{}{Rope}
{91700}{}{Rope}
{91800}{}{Rope}
{91900}{}{Rope}
{92000}{}{Rope}
{92100}{}{Rope}
{92200}{}{Rope}
{92300}{}{Скала}
{92400}{}{Скала}
{92500}{}{Скала}
{92600}{}{Скала}
{92700}{}{Панорама}
{92800}{}{Терминал}
{92801}{}{Терминал для удаленного управления подъемным краном в ангаре.}
{92900}{}{Скала}
{93000}{}{Скала}
{93100}{}{Гигантская буква}
{93101}{}{Эта буква упала с вышки. Раньше она составляла надпись "Artesian Water".}
{93200}{}{Гигантская буква}
{93201}{}{Откуда она здесь?}
{93300}{}{Гигантская буква}
{93301}{}{Откуда она здесь?}
{93400}{}{Скелеты}
{93401}{}{Видимо, смерть застала этих людей спящими и даже не позволила проснуться.}
{93500}{}{Torch}
{93501}{}{A lit torch in a wall sconce.}
{93600}{}{Torch}
{93601}{}{A lit torch in a wall sconce.}
{93700}{}{Танк}
{93701}{}{Огромная емкость для сыпущих материалов.}
{93800}{}{Stone Monument}
{93900}{}{Stone Monument}
{94000}{}{Skull Pole}
{94001}{}{A pole with human skulls attached.}
{94100}{}{Skull Pole}
{94101}{}{A pole with human skulls attached.}
{94200}{}{Skull Pole}
{94201}{}{A pole with human skulls attached.}
{94300}{}{Plant}
{94400}{}{Plant}
{94500}{}{Tree}
{94600}{}{Tree}
{94700}{}{Tree}
{94800}{}{Bed}
{94900}{}{Bed}
{95000}{}{Генератор}
{95001}{}{Самодельная электростанция на базе автомобильного двигателя.}
{95100}{}{Raised Stone Plate}
{95101}{}{A raised stone plate.}
{95200}{}{Disabled Stone Plate}
{95201}{}{A disabled stone plate.}
{95300}{}{Triggered Stone Plate}
{95301}{}{A triggered stone plate.}
{95400}{}{Door}
{95500}{}{Электрощиток}
{95501}{}{Просто трансформатор в цепи питания электричеством. Ничего интересного.}
{95600}{}{Дверь}
{95700}{}{Дверь}
{95800}{}{Дверь}
{95900}{}{Дверь}
{96000}{}{Дверь}
{96100}{}{Дверь}
{96200}{}{Дверь}
{96300}{}{Маис}
{96400}{}{Маис}
{96500}{}{Маис}
{96600}{}{Маис}
{96700}{}{Маис}
{96800}{}{Маис}
{96900}{}{Wood Support}
{97000}{}{Wood Support}
{97100}{}{Wood Support}
{97200}{}{Wood Support}
{97300}{}{Wood Support}
{97400}{}{Wood Support}
{97500}{}{Damaged Wood Support}
{97501}{}{This support looks like it could collapse if stressed.}
{97600}{}{Collapsed Floor}
{97601}{}{The stone floor has collapsed here into the lower level.}
{97700}{}{Ladder Down}
{97701}{}{A manmade hole with a ladder leading down.}
{97800}{}{Door}
{97900}{}{Wall}
{98000}{}{Reactor 5 Sign}
{98100}{}{Door}
{98200}{}{Door}
{98300}{}{Door}
{98400}{}{Door}
{98500}{}{Radioactive Goo}
{98600}{}{Radioactive Goo}
{98700}{}{Radioactive Goo}
{98800}{}{Radioactive Goo}
{98900}{}{Security Door}
{99000}{}{Vault Door}
{99100}{}{Utility Crane}
{99200}{}{Странные камни}
{99201}{}{Этот обвал будто бы возник из ниоткуда!}
{99300}{}{Well}
{99400}{}{Рекламный щит}
{99500}{}{Электрощит}
{99600}{}{Hole}
{99601}{}{You can't see the bottom of this pit.}
{99700}{}{Floor Plate}
{99701}{}{You see a floor plate trap.}
{99800}{}{Disabled Floor Plate}
{99801}{}{This floor plate trap has been disabled.}
{99900}{}{Triggered Floor Plate}
{99901}{}{This floor plate trap has been triggered. Opps!}
{100000}{}{Still}
{100001}{}{This looks like a wood-burning alcohol still.}
{100100}{}{Постер}
{100200}{}{Powerplant Machinery}
{100201}{}{Какая-то сложная техника.}
{100300}{}{Powerplant Machinery}
{100301}{}{Какая-то сложная техника.}
{100400}{}{Powerplant Machinery}
{100401}{}{Какая-то сложная техника.}
{100500}{}{Powerplant Machinery}
{100501}{}{Какая-то сложная техника.}
{100600}{}{Powerplant Machinery}
{100601}{}{Какая-то сложная техника.}
{100700}{}{Powerplant Pump Control}
{100701}{}{This is the coolant pumping machine for the reactor.}
{100800}{}{Постер}
{100900}{}{Car}
{101000}{}{Разбитый патрульный автомобиль}
{101001}{}{Этот автомобиль, видимо, попал в ужасную аварию.}
{101100}{}{Car}
{101200}{}{Gravesite}
{101201}{}{A grave is located here.}
{101300}{}{Headstone}
{101301}{}{Headstone}
{101400}{}{Headstone}
{101401}{}{Headstone}
{101500}{}{Headstone}
{101501}{}{Headstone}
{101600}{}{Headstone}
{101601}{}{Headstone}
{101700}{}{Plow}
{101701}{}{This plow is designed to be dragged by a Brahmin.}
{101800}{}{Plow}
{101801}{}{This plow is designed to be dragged by a Brahmin.}
{101900}{}{Water}
{102000}{}{Каркас}
{102001}{}{Полуразрушенный каркас рекламной консоли.}
{102100}{}{Консоль}
{102101}{}{Неоновая рекламная консоль кафе-клуба.}
{102200}{}{Стена}
{102300}{}{Неоновая реклама}
{102301}{}{Неоновая рекламная консоль отеля "Шестая пуля".}
{102400}{}{Каркас}
{102401}{}{Полуразрушенный металлический каркас, удерживающий рекламную консоль.}
{102500}{}{Диск}
{102501}{}{Вы совершенно не представляете себе, что это такое. Можно лишь догадываться, что когда-то этот диск мог летать.}
{102600}{}{Shadow}
{102700}{}{Ядерный реактор}
{102701}{}{Благодаря ядерному топливу этот реактор сможет вырабатывать энергию еще на протяжении очень многих десятилетий.}
{102800}{}{Газетный автомат}
{102801}{}{Этот древний отреставрированный газетный автомат продает некоторые книги и журналы.}
{102900}{}{Graffiti}
{103000}{}{Метка территории}
{103100}{}{Метка территории}
{103200}{}{Метка территории}
{103300}{}{Постер}
{103400}{}{Постер}
{103500}{}{Graffiti}
{103600}{}{Graffiti}
{103700}{}{Graffiti}
{103800}{}{Graffiti}
{103900}{}{Graffiti}
{104000}{}{Graffiti}
{104100}{}{Graffiti}
{104200}{}{Graffiti}
{104300}{}{Graffiti}
{104400}{}{Graffiti}
{104500}{}{Graffiti}
{104600}{}{Graffiti}
{104700}{}{Постер}
{104800}{}{Постер}
{104900}{}{Постер}
{105000}{}{Постер}
{105100}{}{Постер}
{105200}{}{Постер}
{105300}{}{Graffiti}
{105301}{}{Это граффити гласит: "Страх и ненависть в Лас-Вегасе".}
{105400}{}{Graffiti}
{105500}{}{Graffiti}
{105600}{}{Graffiti}
{105700}{}{Постер}
{105800}{}{Постер}
{105900}{}{Постер}
{106000}{}{Sign}
{106100}{}{Graffiti}
{106200}{}{Graffiti}
{106300}{}{Graffiti}
{106400}{}{Graffiti}
{106500}{}{Graffiti}
{106600}{}{Graffiti}
{106700}{}{Graffiti}
{106800}{}{Graffiti}
{106900}{}{Graffiti}
{107000}{}{Graffiti}
{107100}{}{Разбитое стекло}
{107200}{}{Разбитое стекло}
{107300}{}{Graffiti}
{107400}{}{Graffiti}
{107500}{}{Graffiti}
{107600}{}{Graffiti}
{107700}{}{Graffiti}
{107800}{}{Graffiti}
{107900}{}{Graffiti}
{108000}{}{Graffiti}
{108100}{}{Graffiti}
{108200}{}{Graffiti}
{108300}{}{Graffiti}
{108400}{}{Graffiti}
{108500}{}{Graffiti}
{108600}{}{Graffiti}
{108700}{}{Разбитое стекло}
{108800}{}{Разбитое стекло}
{108900}{}{Graffiti}
{109000}{}{Graffiti}
{109100}{}{Graffiti}
{109200}{}{Graffiti}
{109300}{}{Graffiti}
{109400}{}{Graffiti}
{109500}{}{Graffiti}
{109600}{}{Graffiti}
{109700}{}{Graffiti}
{109800}{}{Постер}
{109900}{}{Постер}
{110000}{}{Постер}
{110100}{}{Постер}
{110200}{}{Постер}
{110300}{}{Постер}
{110400}{}{Постер}
{110500}{}{Постер}
{110600}{}{Карта США}
{110601}{}{Впервые в жизни вы видите карту довоенных США. Большая была страна...}
{110700}{}{Постер}
{110800}{}{Постер}
{110900}{}{Постер}
{111000}{}{Sign}
{111100}{}{Sign}
{111200}{}{Sign}
{111300}{}{Sign}
{111400}{}{Sign}
{111500}{}{Sign}
{111600}{}{Sign}
{111700}{}{Sign}
{111800}{}{Стена}
{111900}{}{Стена}
{112000}{}{Стена}
{112100}{}{Стена}
{112200}{}{Стена}
{112300}{}{Стена}
{112400}{}{Винтиляционная труба}
{112401}{}{Эта здоровенная труба ведет из подземного ангара. Наверняка по ней можно спуститься вниз.}
{112500}{}{Учетная книга}
{112501}{}{Это учетная бухгалтерская книга. Ее чтение будет очень нудным.}
{112600}{}{Автомобиль}
{112601}{}{Этот автомобиль простоял под открытым небом больше десяти лет. Возможно, он еще мог бы проехать какое-то расстояние, но вы все равно не умеете водить.}
{112700}{}{Кости}
{112701}{}{Человеческие кости, принадлежавшие мужчине, женщине и ребенку. Следов насилия на них не видно. Возможно, эти люди умерли от радиации или голода.}
{112800}{}{Кости}
{112801}{}{Человеческие кости, принадлежавшие мужчине, женщине и ребенку. Следов насилия на них не видно. Возможно, эти люди умерли от радиации или голода.}
{112900}{}{Дорожный знак}
{113000}{}{Верх лестницы}
{113100}{}{Низ лестницы}
{113101}{}{Эта лестница находится слишком высоко над землей, чтобы до нее дотянуться.}
{113200}{}{Автомобиль}
{113201}{}{Очень дорогой автомобиль на ядерном ходу.}
{113300}{}{Автомобиль}
{113301}{}{Очень дорогой автомобиль на ядерном ходу.}
{113400}{}{Автомобиль}
{113401}{}{Когда-то это был очень дорогой автомобиль на ядерном ходу. Теперь же - куча ржавого металла.}
{113500}{}{Автомобиль}
{113501}{}{Когда-то это был очень дорогой автомобиль на ядерном ходу. Теперь же - куча ржавого металла.}
{113600}{}{Решетка}
{113700}{}{Заколоченный ящик}
{113701}{}{Заколоченный деревянный ящик. Возможно, в нем есть что-то полезное.}
{113800}{}{Картотечный шкаф}
{113801}{}{Шкаф с ящиками для различных документов. Для коллекционера офисной бумаги - настоящий клад. А для вас ничего интересного.}
{113900}{}{Карта}
{114000}{}{Старые покрышки}
{114001}{}{Эта гора старых покрышек преграждает вам путь. Понадобится трактор или пять фунтов взрывчатки, чтобы очистить это место.}
{114100}{}{Movie Camera}
{114200}{}{Coffin}
{114300}{}{Coffin}
{114400}{}{Coffin}
{114500}{}{Coffin}
{114600}{}{Steel Bars}
{114700}{}{Steel Bars}
{114800}{}{Steel Window Cover}
{114900}{}{Steel Window Cover}
{115000}{}{Laser Tripwire}
{115100}{}{Laser Tripwire}
{115200}{}{Высер}
{115201}{}{Неисправимый мерзавец, привязанный к позорному столбу.}
{115300}{}{Лестница}
{115400}{}{Труп}
{115500}{}{"Out of Business" Sign}
{115600}{}{"Out of Business" Sign}
{115700}{}{Опора}
{115800}{}{Опора}
{115900}{}{Управление мостом}
{116000}{}{Навесной мост}
{116100}{}{Retinal Scanner}
{116101}{}{This is a security device that scans a person's retinal pattern.}
{116200}{}{Control Room Sign}
{116300}{}{Control Room Sign}
{116400}{}{Control Room Sign}
{116500}{}{Construction Zone Sign}
{116501}{}{Большой и тяжелый оградительный знак. Настолько тяжелый, что один человек не сдвинет.}
{116600}{}{Construction Zone Sign}
{116601}{}{Большой и тяжелый оградительный знак. Настолько тяжелый, что один человек не сдвинет.}
{116700}{}{Machine}
{116701}{}{A non-functional machine.}
{116800}{}{Machine}
{116801}{}{A non-functional machine.}
{116900}{}{Door}
{117000}{}{Door}
{117100}{}{Pipes}
{117101}{}{A set of pipes going into the reactor.}
{117200}{}{Tank}
{117300}{}{Tanks}
{117400}{}{Tanks}
{117500}{}{Tanks}
{117600}{}{Vent}
{117700}{}{Vent}
{117800}{}{Стена}
{117900}{}{Заграждение}
{118000}{}{Заграждение}
{118100}{}{Заграждение}
{118200}{}{Vent}
{118300}{}{Vent}
{118400}{}{Окно с решеткой}
{118500}{}{Manager's Office Sign}
{118600}{}{Supply Room Sign}
{118700}{}{Radiation Warning Sign}
{118800}{}{Steam}
{118900}{}{Machine}
{118901}{}{A misc. piece of equipment for the power plant.}
{119000}{}{Tank}
{119100}{}{Fire}
{119200}{}{Water}
{119300}{}{Граффити}
{119400}{}{Граффити}
{119500}{}{Поддон}
{119501}{}{Эти доски навалены как-то нестественно, будто что-то прикрывают.}
{119600}{}{Труба-опора}
{119700}{}{Вывеска}
{119800}{}{Труба-опора}
{119900}{}{Постер}
{120000}{}{Firepit}
{120100}{}{Cave Wall}
{120200}{}{Cave Wall}
{120300}{}{Cave Wall}
{120400}{}{Cave Wall}
{120500}{}{Cave Wall}
{120600}{}{Cave Wall}
{120700}{}{Cave Wall}
{120800}{}{Cave Wall}
{120900}{}{Cave Wall}
{121000}{}{Cave Wall}
{121100}{}{Cave Wall}
{121200}{}{Cave Wall}
{121300}{}{Cave Wall}
{121400}{}{Cave Wall}
{121500}{}{Cave Wall}
{121600}{}{Stake}
{121601}{}{This stake appears to have a person impaled on the top!}
{121700}{}{Stake}
{121701}{}{This stake appears to have a person impaled on the top!}
{121800}{}{Stake}
{121801}{}{This stake appears to have a person impaled on the top!}
{121900}{}{Stake}
{121901}{}{This stake appears to have a person impaled on the top!}
{122000}{}{Stake}
{122001}{}{This stake appears to have a person impaled on the top!}
{122100}{}{Письменный столик}
{122101}{}{Просто столик. Отличается от подобного стола лишь наличием письменных принадлежностей.}
{122200}{}{Stake}
{122201}{}{This stake appears to have a human skull placed on the top.}
{122300}{}{Stake}
{122301}{}{This stake appears to have a human skull placed on the top.}
{122400}{}{Stake}
{122401}{}{This empty stake looks ready for an unwilling victim.}
{122500}{}{Stake}
{122501}{}{This empty stake looks ready for an unwilling victim.}
{122600}{}{Stake}
{122601}{}{This empty stake looks ready for an unwilling victim.}
{122700}{}{Stake}
{122701}{}{This empty stake looks ready for an unwilling victim.}
{122800}{}{Wanted Sign}
{122801}{}{The picture on this sign looks oddly like you!}
{122900}{}{Floor}
{123000}{}{Постер}
{123100}{}{Howitzer}
{123101}{}{This strange-looking cannon looks like a relic from the pre-War days. You wonder how it ended up here.}
{123200}{}{Фонарь}
{123300}{}{Знак радиации}
{123301}{}{"Опасно! Радиация!"}
{123400}{}{Знак радиации}
{123401}{}{"Опасно! Радиация!"}
{123500}{}{Постер}
{123600}{}{Включатель}
{123700}{}{Cross}
{123800}{}{Cross}
{123900}{}{Cross}
{124000}{}{Cross}
{124100}{}{Cross}
{124200}{}{Cross}
{124300}{}{Gas Pump}
{124400}{}{Gas Pump}
{124500}{}{Gas Pump}
{124600}{}{Pep Gas Sign}
{124700}{}{Sign Shadow}
{124800}{}{Haybed}
{124900}{}{Haybed}
{125000}{}{Haybed}
{125100}{}{Haybed}
{125200}{}{Haybed}
{125300}{}{Haybed}
{125400}{}{Вывеска магазина}
{125500}{}{A street vendor's stand}
{125600}{}{A street vendor's stand}
{125700}{}{A street vendor's stand}
{125800}{}{A street vendor's stand}
{125900}{}{Знак-приветствие}
{125901}{}{Приветственный дорожный знак довоенного городка Лавлок.}
{126000}{}{Газетные вырезки}
{126001}{}{Судя по этим вырезкам, местный постоялец одержим страхом инопланетного захвата.}
{126100}{}{Офис шерифа}
{126200}{}{Постер}
{126201}{}{Постер с каким-то мужиком, держащим фотоаппарат. Его лицо всем знакомо, но теперь никто не скажет точно, кто это.}
{126300}{}{Плоды тыквы}
{126400}{}{Постер}
{126500}{}{Лампы}
{126600}{}{Баррикада}
{126700}{}{Грязная вода}
{126800}{}{Грязная вода}
{126900}{}{Грязная вода}
{127000}{}{Грязная вода}
{127100}{}{Casino Sign}
{127200}{}{Casino Sign}
{127300}{}{Pile of Rocks}
{127301}{}{These rocks appear to be keeping something in.}
{127400}{}{Beam}
{127500}{}{Beam}
{127600}{}{Beam}
{127700}{}{Beam}
{127800}{}{Beam}
{127900}{}{Beam}
{128000}{}{Beam}
{128100}{}{Beam}
{128200}{}{Beam}
{128300}{}{Beam}
{128400}{}{Shadow}
{128500}{}{Shadow}
{128600}{}{Shadow}
{128700}{}{Shadow}
{128800}{}{Shadow}
{128900}{}{Shadow}
{129000}{}{Shadow}
{129100}{}{Shadow}
{129200}{}{Shadow}
{129300}{}{Elevator Stub}
{129400}{}{Gas Pump}
{129500}{}{Gas Pump}
{129600}{}{Gas Pump}
{129700}{}{Rope}
{129800}{}{Окно}
{129900}{}{Brahmin Meat}
{130000}{}{Brahmin Meat}
{130100}{}{Brahmin Meat}
{130200}{}{Brahmin Meat}
{130300}{}{Brahmin Meat}
{130400}{}{Brahmin Meat}
{130500}{}{Beam}
{130600}{}{Beam}
{130700}{}{Beam}
{130800}{}{Beam}
{130900}{}{Beam}
{131000}{}{Beam}
{131100}{}{Beam}
{131200}{}{Beam}
{131300}{}{Shadow}
{131400}{}{Shadow}
{131500}{}{Shadow}
{131600}{}{Shadow}
{131700}{}{Shadow}
{131800}{}{Shadow}
{131900}{}{Shadow}
{132000}{}{Shadow}
{132100}{}{Blood}
{132200}{}{Blood}
{132300}{}{Blood}
{132400}{}{Blood}
{132500}{}{Blood}
{132600}{}{Blood}
{132700}{}{Blood with Bones}
{132800}{}{Blood with Bones}
{132900}{}{Blood with Bones}
{133000}{}{Cave Mouth}
{133100}{}{Микрофон}
{133200}{}{Прожектор}
{133300}{}{Прожектор}
{133400}{}{Прожектор}
{133500}{}{Computer}
{133501}{}{A Vault computer terminal, hooked into the main Vault computer.}
{133600}{}{Computer}
{133601}{}{A Vault computer terminal, hooked into the main Vault computer.}
{133700}{}{Кран}
{133701}{}{Проржавевший подъемный кран. На многое рассчитывать не приходится.}
{133800}{}{Гора мусора}
{133801}{}{Гора обыкновенного мусора, сложенная лесенкой.}
{133900}{}{Wall}
{134000}{}{Wall}
{134100}{}{Wall}
{134200}{}{Wall}
{134300}{}{Wall}
{134400}{}{Wall}
{134500}{}{Wall}
{134600}{}{Wall}
{134700}{}{Вентиляция}
{134800}{}{Вентиляция}
{134900}{}{Тень}
{135000}{}{Ангар}
{135100}{}{Ангар}
{135200}{}{Ангар}
{135300}{}{Ангар}
{135400}{}{Ангар}
{135500}{}{Ангар}
{135600}{}{Ангар}
{135700}{}{Ангар}
{135800}{}{Door}
{135900}{}{Панорама}
{136000}{}{Панорама}
{136100}{}{Панорама}
{136200}{}{Панорама}
{136300}{}{Панорама}
{136400}{}{Панорама}
{136500}{}{Firepit}
{136600}{}{Firepit}
{136700}{}{Система управления турелями}
{136701}{}{Это мощная компьютерная система, предназначенная для координации действий турелей на территории базы.}
{136800}{}{Тень}
{136900}{}{Панорама}
{137000}{}{Mountain}
{137100}{}{Cavern}
{137200}{}{Осколки стекла}
{137300}{}{Torch}
{137301}{}{A lit torch in a wall sconce.}
{137400}{}{Torch}
{137401}{}{A lit torch in a wall sconce.}
{137500}{}{Torch}
{137501}{}{A lit torch in a wall sconce.}
{137600}{}{Torch}
{137601}{}{A lit torch in a wall sconce.}
{137700}{}{Тыква со свечой}
{137800}{}{Резервуар}
{137801}{}{Перед вами автоматизированный жидкостный резервуар.}
{137900}{}{Могильный крест}
{137901}{}{На кресте написано: "Эбен Байерс. Вот чем оканчивается чрезмерная забота о здоровье".}
{138000}{}{Wall}
{138100}{}{Wall}
{138200}{}{Wall}
{138300}{}{Wall}
{138400}{}{Wall}
{138500}{}{Wall}
{138600}{}{Light}
{138700}{}{Door}
{138800}{}{Door}
{138900}{}{Door}
{139000}{}{Door}
{139100}{}{Door}
{139200}{}{Door}
{139300}{}{Banners}
{139400}{}{Post}
{139500}{}{Post}
{139600}{}{Banners}
{139700}{}{Banners}
{139800}{}{Post}
{139900}{}{Post}
{140000}{}{Banners}
{140100}{}{Shadow}
{140200}{}{Shadow}
{140300}{}{Грязная бомба}
{140301}{}{Вы затрудняетесь сказать, что это такое. Но внутри под оболочкой этой громадины явно что-то очень радиоактивное.}
{140400}{}{Грязная бомба}
{140401}{}{Вы затрудняетесь сказать, что это такое. Но внутри под оболочкой этой громадины явно что-то очень радиоактивное.}
{140500}{}{Рекламная растяжка}
{140600}{}{Грязная бомба}
{140601}{}{Вы затрудняетесь сказать, что это такое. Но внутри под оболочкой этой громадины явно что-то очень радиоактивное.}
{140700}{}{Перекладина}
{140800}{}{Вывеска}
{140801}{}{Надпись на вывеске: "Аптека"}
{140900}{}{Решетка}
{141000}{}{Указатель ринга}
{141100}{}{Огни ночного клуба}
{141200}{}{Граффити}
{141300}{}{Фирменное граффити}
{141301}{}{Рекламное граффити отеля. Кто-то уже успел немного испортить это творение хулиганскими надписями.}
{141400}{}{Вывеска}
{141401}{}{Надпись на вывеске: "Магазин опалов"}
{141500}{}{Распределитель питания}
{141501}{}{Это устройство предназначено для контроля и распределения электричества.}
{141600}{}{Statue}
{141700}{}{Warehouse Door}
{141800}{}{Warehouse Door}
{141900}{}{График смен}
{141901}{}{График работ на заводе. Смена исключительно дневная, видимо, ночью в цеху никто не работает.}
{142000}{}{Sheriff Sign}
{142100}{}{Учебная доска}
{142101}{}{Вы видите учебную доску со множеством мелованных записей и блок-схем.}
{142200}{}{Останки Джея Кукиша}
{142201}{}{Этот труп совсем свежий. Из него вырезаны некоторые органы точной хирургической рукой.}
{142300}{}{Записная доска}
{142301}{}{Вы видите доску со множеством мелованных заметок и планов по работе завода.}
{142400}{}{График}
{142500}{}{Обрыв}
{142600}{}{Разруха}
{142601}{}{Руины образовались из интерьера ангара во время взрыва. Всего понемногу.}
{142700}{}{Останки}
{142701}{}{Этому скелету уже очень много лет.}
{142800}{}{Телевизор}
{142801}{}{Древнее средство воспроизведения телетрансляций. Как и полагается, смотреть на нем нечего.}
{142900}{}{Робот-уборщик}
{142901}{}{Робот для очистки территории от последствий радиоактивного заражения. Он давно не функционирует.}
{143000}{}{Столб с рупорами}
{143001}{}{Когда-то давно эти громкоговорители предупреждали местных жителей об опасности. Видимо, жителям это не помогло.}
{143100}{}{Уличный фонарь}
{143200}{}{Граффити}
{143300}{}{Rope}
{143301}{}{You can climb over the wall with this rope.}
{143400}{}{Овраг}
{143500}{}{Овраг}
{143600}{}{Window}
{143700}{}{Window}
{143800}{}{Window}
{143900}{}{Window}
{144000}{}{Window}
{144100}{}{Window}
{144200}{}{Window}
{144300}{}{Window}
{144400}{}{Window}
{144500}{}{Window}
{144600}{}{Window}
{144700}{}{Window}
{144800}{}{Двери поезда}
{144900}{}{Door}
{145000}{}{Опора арки}
{145100}{}{Опора арки}
{145200}{}{Arch}
{145300}{}{Arch}
{145400}{}{Вода}
{145500}{}{Вода}
{145600}{}{Вода}
{145700}{}{Вода}
{145800}{}{Вода}
{145900}{}{Вода}
{146000}{}{Вода}
{146100}{}{Танкер}
{146200}{}{Танкер}
{146300}{}{Танкер}
{146400}{}{Танкер}
{146500}{}{Листва}
{146600}{}{Fence Door}
{146700}{}{Fence Door}
{146800}{}{Command Seat}
{146801}{}{This is where the Overseer normally sits.}
{146900}{}{Стена}
{147000}{}{Стена}
{147100}{}{Стена}
{147200}{}{Тень}
{147300}{}{Вход в отель}
{147400}{}{Вход в отель}
{147500}{}{Carpet}
{147600}{}{Casino Entrance}
{147700}{}{Casino Entrance}
{147800}{}{Вход в отель}
{147900}{}{Casino Door}
{148000}{}{Casino Door}
{148100}{}{Casino Entrance}
{148200}{}{Casino Entrance}
{148300}{}{Casino Entrance}
{148400}{}{Casino Entrance}
{148500}{}{Casino Entrance}
{148600}{}{Casino Entrance}
{148700}{}{Casino Entrance}
{148800}{}{Casino Entrance}
{148900}{}{Casino Entrance}
{149000}{}{Casino Entrance}
{149100}{}{Casino Door}
{149200}{}{Casino Door}
{149300}{}{Wall Light}
{149400}{}{Wall Light}
{149500}{}{Wall Light}
{149600}{}{Wall Light}
{149700}{}{Wall Light}
{149800}{}{Wall}
{149900}{}{Wall}
{150000}{}{Fan}
{150100}{}{Fan}
{150200}{}{Fire Ext.}
{150300}{}{Fire Ext.}
{150400}{}{Pipe}
{150500}{}{Power Distributor}
{150600}{}{Power Distributor}
{150700}{}{Wall}
{150800}{}{Wall}
{150900}{}{Wall}
{151000}{}{Wall}
{151100}{}{Wall}
{151200}{}{Wall}
{151300}{}{Wall}
{151400}{}{Wall}
{151500}{}{Wall}
{151600}{}{Wood Paneling}
{151700}{}{Wood Paneling}
{151800}{}{Pipe}
{151900}{}{Pipe}
{152000}{}{Pipe}
{152100}{}{Pipe}
{152200}{}{Pipe}
{152300}{}{Pipe}
{152400}{}{Pipe}
{152500}{}{Pipe}
{152600}{}{Pipe}
{152700}{}{Pipe}
{152800}{}{Pipe}
{152900}{}{Air Vent}
{153000}{}{Air Vent}
{153100}{}{Door}
{153200}{}{Door}
{153300}{}{Door}
{153400}{}{Door}
{153500}{}{Door}
{153600}{}{Door}
{153700}{}{Shower}
{153800}{}{Платформа}
{153900}{}{Платформа}
{154000}{}{Большой бак}
{154100}{}{Цистерны}
{154200}{}{Ящики}
{154300}{}{Радарная установка}
{154400}{}{Радарная установка}
{154500}{}{Антенна}
{154600}{}{Антенна}
{154700}{}{Shadow}
{154800}{}{Forcefield}
{154900}{}{Forcefield}
{155000}{}{Унитаз}
{155100}{}{Рекламный знак}
{155200}{}{Рекламный знак}
{155300}{}{Рекламный знак}
{155400}{}{Рекламный знак}
{155500}{}{Рекламный знак}
{155600}{}{Рекламный знак}
{155700}{}{Рекламный знак}
{155800}{}{Рекламный знак}
{155900}{}{Рекламный знак}
{156000}{}{Рекламный знак}
{156001}{}{Знак "Добро пожаловать в невероятный Лас-Вегас".}
{156100}{}{Рекламный знак}
{156101}{}{Знак "Добро пожаловать в невероятный Лас-Вегас".}
{156200}{}{Рекламный знак}
{156201}{}{Знак "Добро пожаловать в невероятный Лас-Вегас".}
{156300}{}{Городское ограждение}
{156400}{}{Городское ограждение}
{156500}{}{Городское ограждение}
{156600}{}{Shadow}
{156700}{}{Shadow}
{156800}{}{Shadow}
{156900}{}{Shadow}
{157000}{}{Антенна}
{157100}{}{Shadow}
{157200}{}{Обрушенная вывеска}
{157300}{}{Преграда}
{157400}{}{Вытяжка}
{157500}{}{Бронированная дверь}
{157501}{}{Бронированная дверь, открывается только специальной ключ-картой.}
{157600}{}{Door}
{157601}{}{Искусно сделанная деревянная дверь в отличном состоянии.}
{157700}{}{Air Vent}
{157800}{}{Auto-Doc}
{157801}{}{This Auto-Doc is designed to heal illnesses and adminster various drugs.}
{157900}{}{Неработающая турель}
{157901}{}{Эта турель не функционирует.}
{158000}{}{Pile of Rocks}
{158100}{}{Forcefield}
{158101}{}{An energy field is blocking your path.}
{158200}{}{Forcefield}
{158201}{}{An energy field is blocking your path.}
{158300}{}{Forcefield}
{158301}{}{An energy field is blocking your path.}
{158400}{}{Forcefield}
{158401}{}{An energy field is blocking your path.}
{158500}{}{Тень}
{158600}{}{Тень}
{158700}{}{Тень}
{158800}{}{Тень}
{158900}{}{Тень}
{159000}{}{Тень}
{159100}{}{Тень}
{159200}{}{Тень}
{159300}{}{Основание радиовышки}
{159400}{}{Основание радиовышки}
{159500}{}{Обрушение}
{159600}{}{Обрушение}
{159700}{}{Архитектура отеля}
{159800}{}{Аркадный автомат}
{159801}{}{Современный игровой автомат с компьютерной начинкой. Служит для запуска игры аркадного жанра.}
{159900}{}{Аркадный автомат}
{159901}{}{Современный игровой автомат с компьютерной начинкой. Служит для запуска игры аркадного жанра.}
{160000}{}{Wall}
{160100}{}{Wall}
{160200}{}{Floor Depression}
{160300}{}{Stone Bench}
{160400}{}{Stone Bench}
{160500}{}{Бочка в песке}
{160600}{}{Газовая камера}
{160601}{}{Установка для газовых баллонов.}
{160700}{}{Тень}
{160800}{}{Shadow}
{160900}{}{Тень}
{161000}{}{Тень}
{161100}{}{Тень}
{161200}{}{Тень}
{161300}{}{Beam}
{161400}{}{Beam}
{161500}{}{Тень}
{161600}{}{Тень}
{161700}{}{Тень}
{161800}{}{Тень}
{161900}{}{Тень}
{162000}{}{Стеллаж с фигурами}
{162001}{}{Вы видите стеллаж, занятый множеством гипсовых фигур и голов.}
{162100}{}{Топливный бак}
{162101}{}{Бак с топливом для транспорта. И он определенно не пустой.}
{162200}{}{Track}
{162300}{}{Track}
{162400}{}{Track}
{162500}{}{Резервуар}
{162501}{}{Резервуар, наполненный биогелем, в котором плавает мутировавшее медузообразное тело.}
{162600}{}{Резервуар}
{162601}{}{Резервуар, наполненные биогелем, в котором плавает мутировавшее медузообразное тело.}
{162700}{}{Бумаги на столе}
{162800}{}{Разобранный робот}
{162900}{}{Mine Cart}
{163000}{}{Стена}
{163100}{}{Стена}
{163200}{}{Стена}
{163300}{}{Стена}
{163400}{}{Стена}
{163500}{}{Стена}
{163600}{}{Стена}
{163700}{}{Flag}
{163800}{}{Wall}
{163900}{}{Wall}
{164000}{}{Wall}
{164100}{}{Wall}
{164200}{}{Exhaust Port}
{164300}{}{Desk}
{164400}{}{Desk}
{164500}{}{Stairs Down}
{164600}{}{Stairs Up}
{164700}{}{Танкер}
{164800}{}{Танкер}
{164900}{}{Танкер}
{165000}{}{Танкер}
{165100}{}{Танкер}
{165200}{}{Танкер}
{165300}{}{Танкер}
{165400}{}{Танкер}
{165500}{}{Танкер}
{165600}{}{Танкер}
{165700}{}{Танкер}
{165800}{}{Куст паслена}
{165900}{}{Торговый автомат}
{166000}{}{Танкер}
{166100}{}{Танкер}
{166200}{}{Предупредительный знак}
{166201}{}{Знак предупреждает: "Осторожно! За ограждением опасная зона!"}
{166300}{}{Висельник}
{166400}{}{Висельник}
{166500}{}{Большие ящики}
{166501}{}{Стопка ящиков, сложенных "лесенкой". Можно взобраться на самый верх.}
{166600}{}{Высокотехнологическое устройство}
{166700}{}{Пианино}
{166701}{}{Прекрасное пианино с золотым орнаментом.}
{166800}{}{Предупредительный знак}
{166801}{}{Знак предупреждает: "Осторожно! За ограждением опасная зона!"}
{166900}{}{Предупредительный знак}
{166901}{}{Знак предупреждает: "Осторожно! За ограждением опасная зона!"}
{167000}{}{Рекламный плакат}
{167100}{}{Рекламный плакат}
{167200}{}{Рекламный плакат}
{167300}{}{Танкер}
{167400}{}{Танкер}
{167500}{}{Вывеска завода.}
{167600}{}{Вывеска завода.}
{167700}{}{Агитационный плакат}
{167800}{}{Агитационный плакат}
{167900}{}{Агитационный плакат}
{168000}{}{Агитационный плакат}
{168100}{}{Картина}
{168200}{}{Танкер}
{168300}{}{Постер}
{168400}{}{Робот-летун}
{168500}{}{Mine Elevator}
{168600}{}{Mine Elevator}
{168700}{}{Синтезатор одежды}
{168701}{}{Испорченный синтезатор одежды от компании Волт-Тек. Хотя отдельные внутренние детали уцелели, едва ли его можно восстановить.}
{168800}{}{Vertibird}
{168900}{}{Vertibird}
{169000}{}{Vertibird}
{169100}{}{Vertibird}
{169200}{}{Vertibird}
{169300}{}{Shadow}
{169400}{}{Shadow}
{169500}{}{Shadow}
{169600}{}{Shadow}
{169700}{}{Танкер}
{169800}{}{Танкер}
{169900}{}{Танкер}
{170000}{}{Танкер}
{170100}{}{Танкер}
{170200}{}{Танкер}
{170300}{}{Танкер}
{170400}{}{Танкер}
{170500}{}{Танкер}
{170600}{}{Танкер}
{170700}{}{Танкер}
{170800}{}{Танкер}
{170900}{}{Door}
{171000}{}{Door}
{171100}{}{Wall}
{171200}{}{Wall}
{171300}{}{Wall}
{171400}{}{Wall}
{171500}{}{Wall}
{171600}{}{Wall}
{171700}{}{Wall}
{171800}{}{Wall}
{171900}{}{Air Vent}
{172000}{}{Air Vent}
{172100}{}{Bullet Proof Glass}
{172200}{}{Bullet Proof Glass}
{172300}{}{Bullet Proof Glass}
{172400}{}{Heavy Laser Turret}
{172500}{}{Heavy Laser Turret}
{172600}{}{Rocks}
{172700}{}{Rocks}
{172800}{}{Rocks}
{172900}{}{Rocks}
{173000}{}{Rocks}
{173100}{}{Rocks}
{173200}{}{Rocks}
{173300}{}{Rocks}
{173400}{}{Rocks}
{173500}{}{Rocks}
{173600}{}{Rocks}
{173700}{}{Дорожная карта}
{173800}{}{Постер}
{173900}{}{Предупреждение}
{173901}{}{Предупредительный знак, оповещающий о запрете открытого ношения оружия на территории Чистого города.}
{174000}{}{Занавес}
{174100}{}{Занавес}
{174200}{}{Стена}
{174300}{}{Граффити}
{174400}{}{Забаррикадированная дверь}
{174401}{}{Дверь с поперечными металлическими вставками, которые не дают ее открыть и даже выбить.}
{174500}{}{Музыкальный автомат}
{174501}{}{Перед вами старый музыкальный автомат.}
{174600}{}{Fan}
{174700}{}{Fan}
{174800}{}{Люк}
{174900}{}{Указатель выхода}
{175000}{}{Светильник}
{175100}{}{Светильник}
{175200}{}{Out of Order Sign}
{175300}{}{Дыра в земле}
{175301}{}{Глубокое отверстие в земле. Внизу сквозь темноту можно различить металлический пол.}
{175400}{}{Двери поезда}
{175500}{}{Голова в резервуаре}
{175600}{}{Обрыв}
{175700}{}{Мост через каньон}
{175800}{}{Мост через каньон}
{175900}{}{Мост через каньон}
{176000}{}{Мост через каньон}
{176100}{}{Обрыв}
{176200}{}{Обрыв}
{176300}{}{Обрыв}
{176400}{}{Поезд}
{176500}{}{Поезд}
{176600}{}{Поезд}
{176700}{}{Обрыв}
{176800}{}{Тень}
{176900}{}{Мост через каньон}
{177000}{}{Вход}
{177100}{}{Вход}
{177200}{}{Вход}
{177300}{}{Вход}
{177400}{}{Трубы канализации}
{177500}{}{Трубы канализации}
{177600}{}{Овраг}
{177700}{}{Труп Гилмора}
{177701}{}{Правосудие совершено. Это вздернутый на полметра бывший преступник Гэри Марк Гилмор из Прово. И да гори он в аду!}
{177800}{}{Стол}
{177900}{}{Старый ветряк}
{177901}{}{Это внешняя часть ветроэлектростанции, она собрана из различного хлама. Остается лишь похлопать по плечу того, кто это сделал.}
{178000}{}{Тень}
{178100}{}{Тень}
{178200}{}{Тень}
{178300}{}{Тень}
{178400}{}{Тень}
{178500}{}{Мостик через овраг}
{178600}{}{Крыша}
{178700}{}{Крыша}
{178800}{}{Крыша}
{178900}{}{Тень}
{179000}{}{Вышка}
{179100}{}{Вышка}
{179200}{}{Вышка}
{179300}{}{Фонтан}
{179400}{}{Фонтан}
{179500}{}{Фонтан}
{179600}{}{Фонтан}
{179700}{}{Фонтан}
{179800}{}{Фонтан}
{179900}{}{Фонтан}
{180000}{}{Фонтан}
{180100}{}{Окно}
{180200}{}{Обломки}
{180300}{}{Rocks}
{180400}{}{Rocks}
{180500}{}{Rocks}
{180600}{}{Rocks}
{180700}{}{Постер}
{180800}{}{Постер}
{180900}{}{"Мины!"}
{180901}{}{Знак предупреждает об опасности мин.}
{181000}{}{"Мины!"}
{181001}{}{Знак предупреждает об опасности мин.}
{181100}{}{Рекламный знак}
{181200}{}{Рекламный знак}
{181300}{}{Стол}
{181400}{}{Coffin}
{181500}{}{Статуя воина}
{181501}{}{Статуя, изображающая мускулистого воина в берете с гранатами на поясе, который пытается вырваться из плена цепей.}
{181600}{}{Табличка}
{181700}{}{Стол}
{181800}{}{Wood Door}
{181900}{}{Wood Door}
{182000}{}{Холодильник для напитков}
{182100}{}{Холодильник для напитков}
{182200}{}{Stove}
{182300}{}{Stove}
{182400}{}{Stove}
{182500}{}{Stove}
{182600}{}{Stuff}
{182700}{}{Stuff}
{182800}{}{Stuff}
{182900}{}{Stuff}
{183000}{}{Stuff}
{183100}{}{Stuff}
{183200}{}{Stuff}
{183300}{}{Stuff}
{183400}{}{President's Chair}
{183500}{}{Stairs}
{183600}{}{World Map}
{183700}{}{Situation Map}
{183800}{}{Лестница}
{183900}{}{Council Room Table}
{184000}{}{Council Room Table}
{184100}{}{Опора}
{184200}{}{Tree}
{184300}{}{Tree}
{184400}{}{Дозорная вышка}
{184500}{}{Сиденье}
{184501}{}{Вонючий старый стул, который когда-то был автомобильным сиденьем. Пружины потеряли свою упругость.}
{184600}{}{Висельник}
{184700}{}{Конвейер}
{184800}{}{Конвейер}
{184900}{}{Корыто}
{185000}{}{Ветхие доски}
{185001}{}{Участок стены, состоящий из старых досок. Их можно легко разобрать с помощью рабочих инструментов и грубой силы.}
{185100}{}{Steam}
{185200}{}{Тень}
{185300}{}{Тень}
{185400}{}{Тень}
{185500}{}{Тень}
{185600}{}{Тень}
{185700}{}{Тень}
{185800}{}{Тень}
{185900}{}{Дыра в земле}
{185901}{}{Вы видите отверстие в земле. Вниз спускается веревка, надежно прикрепленная к камням.}
{186000}{}{Гроб}
{186100}{}{Вывеска}
{186101}{}{Надпись на вывеске: "Атомное кафе"}
{186200}{}{Граффити}
{186300}{}{Граффити}
{186400}{}{Граффити}
{186500}{}{Граффити}
{186600}{}{Граффити}
{186700}{}{Граффити}
{186800}{}{Люк}
{186900}{}{Люк}
{187000}{}{Старые покрышки}
{187100}{}{Старые покрышки}
{187200}{}{Старые покрышки}
{187300}{}{Старые покрышки}
{187400}{}{Старые покрышки}
{187500}{}{Старые покрышки}
{187600}{}{Старые покрышки}
{187700}{}{Старые покрышки}
{187800}{}{Старые покрышки}
{187900}{}{Фотография артиста}
{188000}{}{Фотография артиста}
{188100}{}{Фотография артиста}
{188200}{}{Трансформатор}
{188201}{}{Уличный распределительный трансформатор.}
{188300}{}{Щиток}
{188301}{}{Электрический щиток со счетчиком. Служит для подачи электроэнергии в дом и ее контроля.}
{188400}{}{Антенна}
{188500}{}{Антенна}
{188600}{}{Антенна}
{188700}{}{Антенна}
{188800}{}{Антенна}
{188900}{}{Металлический трос}
{189000}{}{Металлический трос}
{189100}{}{Лагерный костер}
{189200}{}{Лабораторный стол}
{189300}{}{Верстак}
{189400}{}{Крысоловка}
{189401}{}{Перед вами ржавый капкан. Активирован и очень опасен.}
{189500}{}{Фары}
{189600}{}{Человеческие кости}
{189601}{}{Куча старых обглоданных костей, определенно человеческих. На некоторых видны следы дроби.}
{189700}{}{Человеческие кости}
{189701}{}{Куча старых обглоданных костей, определенно человеческих. На некоторых видны следы дроби.}
{189800}{}{Капот фургона}
{189900}{}{Флаг надежды}
{189901}{}{Такое впечатление, что этот флаг сделан ребенком. Очень мило.}
{190000}{}{Детская качеля}
{190100}{}{Кран для качели}
{190200}{}{Тень}
{190300}{}{Тень}
{190400}{}{Тень}
{190500}{}{Тень}
{190600}{}{Покосившаяся перекладина}
{190601}{}{Вы не видите ничего необычного. Кроме того, что перила прибиты немного косо.}
{190700}{}{Останки брамина}
{190701}{}{Частично разложившиеся куски брамина - голова левая, голова правая и немного того-сего. Самое вкусное, видимо, давно съели.}
{190800}{}{Дыра в земле}
{190801}{}{Просто дыра, из которой вы вылезли.}
{190900}{}{Записка для Майло}
{190901}{}{Эта записка адресована Майло и тем, кто его встретит.}
{191000}{}{Странный автобус}
{191001}{}{Этот автобус в необычной кислотной раскраске будто бы специально обрел здесь вечный покой.}
{191100}{}{Яйцо}
{191101}{}{Это тяжелое яйцо застряло в яме и теперь никуда не сдвинется.}
{191200}{}{Стена дамбы}
{191300}{}{Стена дамбы}
{191400}{}{Стена дамбы}
{191500}{}{Стена дамбы}
{191600}{}{Стена дамбы}
{191700}{}{Стена дамбы}
{191800}{}{Стена дамбы}
{191900}{}{Стена дамбы}
{192000}{}{Стена дамбы}
{192100}{}{Стена дамбы}
{192200}{}{Стена дамбы}
{192300}{}{Стена дамбы}
{192400}{}{Стена дамбы}
{192500}{}{Стена дамбы}
{192600}{}{Стена дамбы}
{192700}{}{Стена дамбы}
{192800}{}{Стена дамбы}
{192900}{}{Стена дамбы}
{193000}{}{Стена дамбы}
{193100}{}{Стена дамбы}
{193200}{}{Стена дамбы}
{193300}{}{Стена дамбы}
{193400}{}{Стена дамбы}
{193500}{}{Стена дамбы}
{193600}{}{Стена дамбы}
{193700}{}{Стена дамбы}
{193800}{}{Стена дамбы}
{193900}{}{Стена дамбы}
{194000}{}{Скала}
{194100}{}{Скала}
{194200}{}{Скала}
{194300}{}{Скала}
{194400}{}{Двое за столиком}
{194500}{}{Двое за столиком}
{194600}{}{Киноэкран}
{194601}{}{Этот рекламный биллборд покрыт старой простынью и используется в качестве экрана кинотеатра.}
{194700}{}{Киноэкран}
{194701}{}{Этот рекламный биллборд покрыт старой простынью и используется в качестве экрана кинотеатра.}
{194800}{}{Лестница}
{194801}{}{Этот лестничный спуск забаррикадирован, чтобы никто не прошел на верхний этаж. Впрочем, вам туда и не нужно.}
{194900}{}{Знак ранчо "Ароматы Марин"}
{195000}{}{Браминий водопой}
{195001}{}{Здесь, должно быть, черпается вода для снабжения браминов в загоне.}
{195100}{}{Бочка с горючим}
{195101}{}{Тот, кто оставил это здесь, рискует устроить пожар.}
{195200}{}{Обгоревшие ящики}
{195300}{}{Обгоревшие ящики}
{195400}{}{Обгоревший ящик}
{195500}{}{Обгоревший ящик}
{195600}{}{Обгоревший ящик}
{195700}{}{Контрольная панель}
{195701}{}{Это узел контроля и синхронизации систем убежища. Разработчиком устройств, как обычно, стала замечательная компания Волт-Тек.}
{195800}{}{Панель управления}
{195801}{}{Панель управления микроклиматом внутри помещения от компании Волт-Тек. Ничего особенного. К тому же уже давно не работает.}
{195900}{}{Стена}
{196000}{}{Раскол}
{196100}{}{Раскол}
{196200}{}{Раскол}
{196300}{}{Раскол}
{196400}{}{Раскол}
{196500}{}{Раскол}
{196600}{}{Раскол}
{196700}{}{Раскол}
{196800}{}{Раскол}
{196900}{}{Раскол}
{197000}{}{Обгорелые человеческие кости}
{197100}{}{Обгорелые человеческие кости}
{197200}{}{Обгорелые человеческие кости}
{197300}{}{Обгорелые человеческие кости}
{197400}{}{Обгорелые человеческие кости}
{197500}{}{Малый генератор}
{197501}{}{Стандартная модель малого электрогенератора от компании Ваттс Электроникс.}
{197600}{}{Полицейское заграждение}
{197700}{}{Полицейское заграждение}
{197800}{}{Полицейское заграждение}
{197900}{}{Полицейское заграждение}
{198000}{}{Плакат}
{198001}{}{Это яркий агитационный плакат.}
{198100}{}{Плакат}
{198101}{}{Это яркий агитационный плакат.}
{198200}{}{Полицейские щиты}
{198300}{}{Полицейские щиты}
{198400}{}{Полицейский щит}
{198500}{}{Полицейский щит}
{198600}{}{Выцветшая картинка}
{198601}{}{Изображение певца. Явно очень древняя картина в фетровой рамке, которая до сих пор неплохо сохранилась.}
{198700}{}{Свалка техники}
{198701}{}{Неработающая бытовая техника и другой мусор. Если хорошо порыться, то отсюда еще можно вытащить что-то полезное.}
{198800}{}{Свалка техники}
{198801}{}{Неработающая бытовая техника и другой мусор. Если хорошо порыться, то отсюда еще можно вытащить что-то полезное.}
{198900}{}{Термоядерная бомба}
{199000}{}{Термоядерная бомба}
{199100}{}{Термоядерная бомба}
{199200}{}{Термоядерная бомба}
{199300}{}{Нора}
{199301}{}{Очевидно, эту нору вырыли животные. Едва ли вы туда пролезете.}
{199400}{}{Рекламный плакат}
{199401}{}{На этом плакате еще можно различить надпись: "Прейзер Инкорпорейтед. Защити свою семью до того, как упадут бомбы!"}
{199500}{}{Рекламный плакат}
{199501}{}{На этом плакате еще можно различить надпись: "Прейзер Инкорпорейтед. Защити свою семью до того, как упадут бомбы!"}
{199600}{}{Рекламный плакат}
{199601}{}{На этом плакате еще можно различить надпись: "Прейзер Инкорпорейтед. Защити свою семью до того, как упадут бомбы!"}
{199700}{}{Байк}
{199701}{}{Этот мотоцикл полностью проржавел.}
{199800}{}{Палатка}
{199900}{}{Висельник}
{199901}{}{Едва ли вы можете назвать это чем-то обыденным.}
{200000}{}{Дерево}
{200100}{}{Гора}
{200101}{}{Эти горные стены выглядят очень неприступными.}
{200200}{}{Гора}
{200201}{}{Эти горные стены выглядят очень неприступными.}
{200300}{}{Гора}
{200301}{}{Эти горные стены выглядят очень неприступными.}
{200400}{}{Гора}
{200401}{}{Эти горные стены выглядят очень неприступными.}
{200500}{}{Гора}
{200501}{}{Эти горные стены выглядят очень неприступными.}
{200600}{}{Оборудование}
{200601}{}{Это оборудование отмечено логотипом компании Волт-Тек.}
{200700}{}{Лестница}
{200701}{}{Старая, несколько расшатанная лестница.}
{200800}{}{Лестница}
{200900}{}{Пересыхающий родник}
{200901}{}{Этот родник почти пересох, но из него все еще можно набрать немного воды.}
{201000}{}{Обвал}
{201001}{}{Этот жуткий обвал камней унес жизнь местного охотника.}
{201100}{}{Стол}
{201101}{}{Этот стол загажен сырыми органами. Вы не можете понять, человеческие они или нет.}
{201200}{}{Люк}
{201201}{}{Прочный металлический люк.}
{201300}{}{Люк}
{201301}{}{Прочный металлический люк.}
{201400}{}{Куст брока}
{201500}{}{Корень ксандер}
{201600}{}{Заросли вокас}
{201700}{}{Поврежденный генератор}
{201701}{}{Электрогенератор от компании Ваттс Электроникс. Конкретно этот генератор сгорел и ремонту не подлежит.}
{201800}{}{Радарное оборудование}
{201900}{}{Стол}
{201901}{}{Обычный офисный стол.}
{202000}{}{Стол}
{202001}{}{Обычный офисный стол.}
{202100}{}{Стол}
{202101}{}{Обычный офисный стол.}
{202200}{}{Стол}
{202201}{}{Обычный офисный стол.}