#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used by town and world map
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#

# Vault 8
{200}{}{Пустошь}
{201}{}{Город Убежища}
{202}{}{Двери Убежища}
{203}{}{Опаловый прииск}
{204}{}{Убежище 8}
{205}{}{Лаборатория}
#
# Wind of War
{210}{}{Свободная стоянка}
{211}{}{Убежище}
{212}{}{Нежилой район}
#
# basa Sigma
{220}{}{Ошибка: пусто}
{221}{}{Ошибка: пусто}
{222}{}{Ошибка: пусто}
{223}{}{Ошибка: пусто}
{224}{}{Ошибка: пусто}
{225}{}{Ошибка: пусто}
#
# Shaienn
{230}{}{Стойбище племени}
{231}{}{База рейдеров}
{232}{}{Плантации}
{233}{}{Радиостанция}
#
# Fake Vault 13 B
{240}{}{Убежище 15}
#
# Gecko
{250}{}{Settlement}
{251}{}{Power Plant}
{252}{}{Свалка}
{253}{}{Ошибка: пусто}
#
# Ely
{260}{}{Железнодорожная развязка}
{261}{}{Residential}
{262}{}{Храм}
{263}{}{Климатическая станция}
#
# New Reno
{270}{}{Отель 'Сильвер'}
{271}{}{Эльдорадо}
{272}{}{Стадион}
{273}{}{Железнодорожная станция}
{274}{}{Ранчо Лучиано}
{275}{}{Boxing Arena}
{276}{}{Место засады}
{277}{}{Ратуша}
{278}{}{Открытый кинотеатр}
{279}{}{Заброшенная ферма}
#
# Zona 51
{280}{}{Рулежная дорожка}
{281}{}{Казармы}
{282}{}{Ангар}
#
# Psifarme
{290}{}{Бриджпорт}
#
# New Vegas
{300}{}{Стоянка караванов}
{301}{}{Дамба Гувера}
{302}{}{Чистый Город}
{303}{}{Кафе 'Хард-Рок'}
{304}{}{Город рабов}
{305}{}{Мертвый Отель}
#
# Provo
{310}{}{Район Прово}
#
# Howthorne
{320}{}{Железнодорожная станция}
{321}{}{Мертвый город}
{322}{}{Территория гарнизона}
{323}{}{Ангар V9}
{324}{}{Помещения реактора}
#
# West Wendover
{330}{}{Downtown}
{331}{}{Мастерская}
{332}{}{Большой ангар}
{333}{}{Ассоциация}
{334}{}{Охотничьи угодья}
{335}{}{Руины Уэндовера}
#
# Salt Lake
{340}{}{Бизнес-центр}
{341}{}{Площадь возрождения}
{342}{}{Железнодорожное депо}
{343}{}{Каньон сточных вод}
{344}{}{Храм}
{345}{}{Трущобы}
{346}{}{Завод ядер-колы}
#
# Rubby
{350}{}{Хижина}
#
# Vault X
{360}{}{Остановка}
{361}{}{Убежище}
{362}{}{Вход в убежище}
{363}{}{Временная остановка}
{364}{}{Президентский уровень}
#
# Artel Jerlack
{370}{}{Поселение}
{371}{}{Место охоты}
#
# Uran-City
{380}{}{Поселение рабочих}
#
# Vegas DrugSet
{390}{}{Питомник}
#
# Buttle-Mauntin, Radar
{400}{}{Центральная улица}
{401}{}{Стоянка байкеров}
#
# Car Out of Gas
{410}{}{Машина без энергии}
#
# Destroyed Vault City
{420}{}{Опустошенный город}
#
# ???
{430}{}{Пустыня}
#
# Wind of War
{440}{}{Облавы патрулей}
#
# Artel Black Rock
{450}{}{Поселение}
{451}{}{Пещеры Блэк-Рок}
#
# Random Encounter Desert
{460}{}{Desert}
{461}{}{Desert}
{462}{}{Desert}
{463}{}{Desert}
{464}{}{Заброшенный лагерь}
{465}{}{Заброшенная ферма}
{466}{}{Кактусовое поле}
{467}{}{Чернолесье}
{468}{}{Чернолесье}
{469}{}{Чернолесье}
#
# Random Encounter Mountain
{470}{}{Mountain}
{471}{}{Cavern}
{472}{}{Mountain}
{473}{}{Cavern}
{474}{}{Cavern}
{475}{}{Cavern}
{476}{}{Cavern}
{477}{}{Cavern}
{478}{}{Mountain}
{479}{}{Mountain}
#
# Random Encounter City
{480}{}{Ruined City}
{481}{}{Ruined City}
{482}{}{Ruined City}
{483}{}{Ruined City}
{484}{}{Ruined City}
{485}{}{Ruined City}
{486}{}{Ruined City}
{487}{}{Ruined City}
{488}{}{Ruined City}
#
# Random Encounter Coast
{490}{}{Coastline}
{491}{}{Coastline}
{492}{}{Coastline}
{493}{}{Coastline}
{494}{}{Coastline}
{495}{}{Coastline}
{496}{}{Coastline}
{497}{}{Coastline}
{498}{}{Coastline}
{499}{}{Coastline}
#
# PepGaz
{500}{}{Заправка}
#
# Special Encounter: Roads
{510}{}{Перекресток}
#
# Special Encounter: AnalDen
{520}{}{Большое отверстие}
#
# Special Encounter: MinaPole
{521}{}{Свалка покрышек}
#
# Special Encounter: Crashed Federation Shuttle
{530}{}{Танкер в пустыне}
#
# Special Encounter: Unwashed Villagers
{540}{}{Desert}
#
# Special Encounter: Interplay Office
{550}{}{Затерянный офис.}
#
# Special Encounter: Cafe
{560}{}{Кафе "Новые надежды"}
#
# Special Encounter: Big Egg
{570}{}{Пустыня}
#
# Special Encounter: Bobby
{580}{}{Пустыня}
#
# Special Encounter: HomeRoad
{590}{}{Дом на колесах}
#
# Special Encounter: AutobusOfKen
{600}{}{"Далше"}
#
# Rangers post
{610}{}{Заброшенный лагерь рейнджеров}
#
# Special Encounter: Piknik
{620}{}{Место для пикника}
#
# Caravan Encounters
{630}{}{Desert}
{631}{}{Mountain}
#
# Atomic
{640}{}{"Дорогой Джон"}
#
# Harrelson
{650}{}{Логово Харрельсона}
#
# Shadow Areas (Those which fit nowhere else
{660}{}{Coastline}
{661}{}{Coastline}
{662}{}{Desert}
{663}{}{Desert}
{664}{}{Desert}
{665}{}{Mountain}
{666}{}{Mountain}
{667}{}{Desert}
{668}{}{Стоянка каравана}
{669}{}{Пугающая тишина}
#
# Environmental Protection Agency
{670}{}{Дорога}



#
# Terrain type names for world map hover button
#
{1000}{}{Desert}
{1001}{}{Mountains}
{1002}{}{City}
{1003}{}{Coast}
{1004}{}{Unknown}  # Unknown/visited city


# Misc messages
{1500}{}{You gained 10,000 experience points!}
{1501}{}{Ruins}
{1502}{}{The car is out of power.}
{1503}{}{This is a car.  It doesn't look like it's running.}


#
# Worldmap Encounter messages
#

{2998}{}{You encounter:}
{2999}{}{Do you wish to encounter:}

# Encounter Table 0
{3000}{}{A party of raiders.}
{3001}{}{Some radscorpions.}
{3002}{}{Giant rats.}
{3003}{}{A merchant party.}
{3004}{}{<Special>}

# Encounter Table 1
{3050}{}{A party of raiders.}
{3051}{}{A swarm of manti.}
{3052}{}{A group of geckos.}
{3053}{}{A group of mole rats.}
{3054}{}{A group of radscorpions.}
{3055}{}{A group of giant rats.}
{3056}{}{A merchant party.}
{3057}{}{<Special>}

# Encounter Table 2
{3100}{}{A party of raiders.}
{3101}{}{A group of radscorpions.}
{3102}{}{A group of giant rats.}
{3103}{}{A merchant party.}
{3104}{}{<Special>}

# Encounter Table 3
{3150}{}{A party of raiders.}

# Encounter Table 4
{3200}{}{A party of raiders.}

# Encounter Table 5
{3250}{}{A party of raiders.}

# Encounter Table 6 -- VCTY_M (горы вокруг Убежища 8)
{3300}{}{Группа серебряных гекко.}
{3301}{}{Семейство гекконов.}
{3302}{}{Группа грызунов.}
{3303}{}{Небольшая группа кротокрысов.}
{3304}{}{Небольшая группа радскорпионов.}
{3305}{}{Патруль Города Убежища.}
{3306}{}{Патруль Города Убежища, отбивающийся от стаи гекко.}
{3307}{}{Патруль Города Убежища, сражающийся с радскорпионами.}

# Encounter Table 7 -- VCTY_D (горы вокруг Убежища 8)
{3350}{}{Группа серебряных гекко.}
{3351}{}{Семейство гекконов.}
{3352}{}{Группа грызунов.}
{3353}{}{Небольшая группа кротокрысов.}
{3354}{}{Небольшая группа радскорпионов.}
{3355}{}{Стадо браминов.}
{3356}{}{Стая койотов.}
{3357}{}{Стадо браминов, отбивающихся от нескольких гекко.}
{3358}{}{Гигантское яйцо.}

# Encounter Table 8 -- BLRCK
{3400}{}{Группа серебряных гекко.}
{3401}{}{Группа грызунов.}
{3402}{}{Небольшая группа кротокрысов.}
{3403}{}{Небольшая группа радскорпионов.}
{3404}{}{Стадо диких браминов.}
{3405}{}{Стая койотов.}
{3406}{}{Стадо браминов, отбивающихся от нескольких гекко.}
{3407}{}{Ловец пустынных ящериц.}

# Encounter Table 9 -- SGMA_M
{3450}{}{Роботы-чистильщики.}
{3451}{}{Группа грызунов.}
{3452}{}{Небольшая группа кротокрысов.}
{3453}{}{Небольшая группа свинокрысов.}
{3454}{}{Небольшая группа радскорпионов.}
{3455}{}{Стадо диких браминов.}
{3456}{}{Стая волков.}
{3457}{}{Кафе "Новые надежды".}
{3458}{}{Перекресток.}
{3459}{}{Большое отверстие.}
{3460}{}{Место для пикника.}
{3461}{}{Дом на колесах.}
{3462}{}{"Далше".}
{3463}{}{Гигантское яйцо.}

# Encounter Table 10 -- SGMA_D
{3500}{}{Группа хищных растений.}
{3501}{}{Группа грызунов.}
{3502}{}{Небольшая группа кротокрысов.}
{3503}{}{Небольшая группа свинокрысов.}
{3504}{}{Небольшая группа радскорпионов.}
{3505}{}{Стадо диких браминов.}
{3506}{}{Стая волков.}
{3507}{}{Отряд охотников.}
{3508}{}{Отряд охотников, сражающийся со скорпионами.}
{3509}{}{Отряд охотников, сражающийся с кротокрысами.}
{3510}{}{Отряд охотников, отбивающийся от волков.}
{3511}{}{Стадо браминов, отбивающихся от волков.}
{3512}{}{Скорпион-легенда.}
{3513}{}{Затерянный офис.}
{3514}{}{Перекресток.}
{3515}{}{Кафе "Новые надежды".}
{3516}{}{Большое отверстие.}
{3517}{}{Место для пикника.}
{3518}{}{Дом на колесах.}
{3519}{}{"Далше".}
{3520}{}{Гигантское яйцо.}
{3521}{}{"Дорогой Джон".}
{3522}{}{Стая койотов.}
{3523}{}{Воды!}

# Encounter Table 11 -- SGMA_T
{3550}{}{Небольшая группа радскорпионов на дороге.}
{3551}{}{Стадо браминов, пересекающее трассу.}
{3552}{}{Стая диких собак, бегущих вдоль трассы.}
{3553}{}{Отряд охотников, возвращающихся с промысла.}
{3554}{}{Группа переселенцев.}
{3555}{}{Группа фермеров.}
{3556}{}{Банда грабителей, укрывшихся в засаде.}
{3557}{}{Банда рейдеров, укрывшихся в засаде.}
{3558}{}{Отряд охотников, отражающих нападение рейдеров.}
{3559}{}{Отряд охотников, отражающих нападение грабителей.}
{3560}{}{Отряд охотников, отражающих нападение радскорпионов.}
{3561}{}{Группа фермеров, отражающих нападение грабителей.}
{3562}{}{Группа фермеров, отражающих нападение радскорпионов.}
{3563}{}{Караван, бредущий вдоль трассы.}
{3564}{}{Перекресток.}
{3565}{}{Затерянный офис.}
{3566}{}{Большое отверстие.}
{3567}{}{Кафе "Новые надежды".}
{3568}{}{Дом на колесах.}
{3569}{}{"Далше".}
{3570}{}{Автостопщик.}
{3571}{}{Неунывающий Бобби.}

# Encounter Table 12 -- SALT_O
{3600}{}{Группа грызунов.}
{3601}{}{Стая диких собак.}
{3602}{}{Стадо диких браминов.}
{3603}{}{Стая кислотных гекко.}
{3604}{}{Отряд охотников.}
{3605}{}{Отряд охотников, сражающийся с грызунами.}
{3606}{}{Отряд охотников, отбивающийся от диких собак.}
{3607}{}{Отряд охотников, отбивающийся от бандитов.}
{3608}{}{Группа бандитов.}
{3609}{}{Группа бандитов, отбивающаяся от диких собак.}
{3610}{}{Беглые каторжники.}
{3611}{}{Панки из Солт-Лейка.}

# Encounter Table 13 -- SALT_T
{3650}{}{Небольшая группа грызунов, застрявших на дороге.}
{3651}{}{Небольшая группа радскорпионов на дороге.}
{3652}{}{Стадо браминов, бредущих вдоль дороги.}
{3653}{}{Стая диких собак, бегущих вдоль трассы.}
{3654}{}{Отряд охотников, возвращающихся в город.}
{3655}{}{Группа бандитов, укрывшихся в засаде.}
{3656}{}{Группа мародеров, укрывшихся в засаде.}
{3657}{}{Группа рейдеров, укрывшихся в засаде.}
{3658}{}{Отряд охотников, отражающих нападение мародеров.}
{3659}{}{Отряд охотников, отражающих нападение рейдеров.}
{3660}{}{Отряд охотников, отражающих нападение грабителей.}
{3661}{}{Отряд охотников, отражающих нападение радскорпионов.}
{3662}{}{Караван, бредущий вдоль трассы.}
{3663}{}{Перекресток.}
{3664}{}{Затерянный офис.}
{3665}{}{Кафе "Новые надежды".}
{3666}{}{Дом на колесах.}
{3667}{}{"Далше".}
{3668}{}{Автостопщик.}
{3669}{}{Неунывающий Бобби.}
{3670}{}{Наемники Солт-Лейка, охотящиеся за вашей головой.}
{3671}{}{Наемники Солт-Лейка, охотящиеся за вашей головой.}
{3672}{}{Наемники Солт-Лейка, охотящиеся за вашей головой.}
{3673}{}{Взбесившийся Мистер Помощник.}
{3674}{}{Скопление машин на пути в город.}
{3675}{}{Крутой бандит с Джекхаммером.}
{3676}{}{Беглые каторжники.}
{3677}{}{Панки из Солт-Лейка.}
{3678}{}{Кочевники Большого Бассейна.}

# Encounter Table 14 -- RDRS_T
{3700}{}{Небольшая группа грызунов, застрявших на дороге.}
{3701}{}{Небольшая группа гекко, случайно выскочивших на дорогу.}
{3702}{}{Небольшая группа радскорпионов на дороге.}
{3703}{}{Стадо браминов, бредущих вдоль дороги.}
{3704}{}{Стая диких собак, бегущих вдоль трассы.}
{3705}{}{Отряд шайеннов, возвращающихся с охоты.}
{3706}{}{Группа переселенцев.}
{3707}{}{Группа бандитов, укрывшихся в засаде.}
{3708}{}{Рейдеры Большого Луи.}
{3709}{}{Рейдеры Большого Луи.}
{3710}{}{Отряд охотников, отражающих нападение грабителей.}
{3711}{}{Отряд охотников, отражающих нападение бандитов.}
{3712}{}{Караван, бредущий вдоль трассы.}
{3713}{}{Перекресток.}
{3714}{}{Кафе "Новые надежды".}
{3715}{}{Дом на колесах.}
{3716}{}{"Далше".}
{3717}{}{Автостопщик.}
{3718}{}{Неунывающий Бобби.}

# Encounter Table 15 -- RDRS_D
{3750}{}{Группа хищных растений.}
{3751}{}{Группа серебряных гекко.}
{3752}{}{Семейство гекконов.}
{3753}{}{Группа грызунов.}
{3754}{}{Небольшая группа кротокрысов.}
{3755}{}{Небольшая группа свинокрысов.}
{3756}{}{Небольшая группа радскорпионов.}
{3757}{}{Стадо браминов.}
{3758}{}{Стая диких собак.}
{3759}{}{Отряд шайеннов, возвращающихся с охоты.}
{3760}{}{Отряд охотников.}
{3761}{}{Группа бандитов.}
{3762}{}{Рейдеры Большого Луи.}
{3763}{}{Рейдеры Большого Луи.}
{3764}{}{Отряд охотников, сражающийся со скорпионами.}
{3765}{}{Отряд охотников, отбивающийся от волков.}
{3766}{}{Отряд охотников, сражающийся с рейдерами.}
{3767}{}{Отряд охотников, сражающийся с бандитами.}
{3768}{}{Перекресток.}
{3769}{}{Кафе "Новые надежды".}
{3770}{}{Затерянный офис.}
{3771}{}{Большое отверстие.}
{3772}{}{Место для пикника.}
{3773}{}{Дом на колесах.}
{3774}{}{"Далше".}
{3775}{}{Гигантское яйцо.}
{3776}{}{Автостопщик.}
{3777}{}{Неунывающий Бобби.}
{3778}{}{"Дорогой Джон".}

# Encounter Table 16 -- RDRS_M
{3800}{}{Группа хищных растений.}
{3801}{}{Группа серебряных гекко.}
{3802}{}{Семейство гекконов.}
{3803}{}{Группа грызунов.}
{3804}{}{Небольшая группа кротокрысов.}
{3805}{}{Небольшая группа радскорпионов.}
{3806}{}{Стадо браминов.}
{3807}{}{Стая волков.}
{3808}{}{Отряд шайеннов, возвращающихся с охоты.}
{3809}{}{Отряд охотников.}
{3810}{}{Рейдеры Большого Луи.}
{3811}{}{Рейдеры Большого Луи.}
{3812}{}{Отряд охотников, сражающийся со скорпионами.}
{3813}{}{Отряд охотников, отбивающийся от волков.}
{3814}{}{Отряд охотников, сражающийся с рейдерами.}
{3815}{}{Отряд шайеннов, отбивающийся от волков.}
{3816}{}{Кафе "Новые надежды".}
{3817}{}{Большое отверстие.}
{3818}{}{Место для пикника.}
{3819}{}{Дом на колесах.}
{3820}{}{"Далше".}
{3821}{}{Гигантское яйцо.}
{3822}{}{"Дорогой Джон".}

# Encounter Table 17 -- RINO_T
{3850}{}{Стая диких собак, бегущих вдоль трассы.}
{3851}{}{Небольшая группа радскорпионов на дороге.}
{3852}{}{Небольшая группа грызунов, застрявших на дороге.}
{3853}{}{Стадо браминов, бредущих вдоль дороги.}
{3854}{}{Группа работорговцев с рабами.}
{3855}{}{Группа работорговцев, пытающихся поработить нескольких людей.}
{3856}{}{Банда работорговцев и несколько собак.}
{3857}{}{Городская банда.}
{3858}{}{Банда грабителей, укрывшихся в засаде.}
{3859}{}{Банда рейдеров, укрывшихся в засаде.}
{3860}{}{Группа мародеров, укрывшихся в засаде.}
{3861}{}{Караван, бредущий через руины.}
{3862}{}{Автостопщик.}
{3863}{}{Наемники Нью-Рино, охотящиеся за вашей головой.}
{3864}{}{Наемники Нью-Рино, охотящиеся за вашей головой.}
{3865}{}{Наемники Нью-Рино, охотящиеся за вашей головой.}
{3866}{}{Грабители, поджидающие одиноких путников.}

# Encounter Table 18 -- RED_D
{3900}{}{Группа хищных растений.}
{3901}{}{Группа серебряных гекко.}
{3902}{}{Семейство гекконов.}
{3903}{}{Группа золотых гекко.}
{3904}{}{Группа грызунов.}
{3905}{}{Небольшая группа кротокрысов.}
{3906}{}{Небольшая группа свинокрысов.}
{3907}{}{Небольшая группа радскорпионов.}
{3908}{}{Стая волков.}
{3909}{}{Куст паслена, охраняемый муравьями.}
{3910}{}{Перекресток.}
{3911}{}{Большое отверстие.}
{3912}{}{"Дорогой Джон".}
{3913}{}{Место для пикника.}
{3914}{}{Дом на колесах.}
{3915}{}{"Далше".}
{3916}{}{Гигантское яйцо.}
{3917}{}{Неунывающий Бобби.}

# Encounter Table 19 -- RED_M
{3950}{}{Группа хищных растений.}
{3951}{}{Группа серебряных гекко.}
{3952}{}{Семейство гекконов.}
{3953}{}{Группа золотых гекко.}
{3954}{}{Группа грызунов.}
{3955}{}{Небольшая группа кротокрысов.}
{3956}{}{Небольшая группа свинокрысов.}
{3957}{}{Стая волков.}
{3958}{}{Куст паслена, охраняемый муравьями.}
{3959}{}{Тело под обвалом.}
{3960}{}{Большое отверстие.}
{3961}{}{Место для пикника.}
{3962}{}{"Дорогой Джон".}
{3963}{}{"Далше".}
{3964}{}{Гигантское яйцо.}
{3965}{}{Заброшенный пост рейнджеров Невады.}

# Encounter Table 20 -- SALTk_D
{4000}{}{Стая кислотных гекко.}
{4001}{}{Группа грызунов.}
{4002}{}{Небольшая группа кротокрысов.}
{4003}{}{Небольшая группа свинокрысов.}
{4004}{}{Небольшая группа радскорпионов.}
{4005}{}{Стадо браминов.}
{4006}{}{Стая диких собак.}
{4007}{}{Отряд охотников.}
{4008}{}{Банда рейдеров.}
{4009}{}{Группа бандитов.}
{4010}{}{Группа бандитов, делящая наживу с рейдерами.}
{4011}{}{Отряд охотников, отбивающийся от группы рейдеров.}
{4012}{}{Отряд охотников, отбивающийся от группы бандитов.}
{4013}{}{Танкер в пустыне.}
{4014}{}{Большое отверстие.}
{4015}{}{Автостопщик.}
{4016}{}{Беглые каторжники.}
{4017}{}{Панки из Солт-Лейка.}
{4018}{}{Охотники за фильтром.}

# Encounter Table 21 -- VGSLT_T
{4050}{}{Небольшая группа грызунов, застрявших на дороге.}
{4051}{}{Небольшая группа радскорпионов на дороге.}
{4052}{}{Стадо браминов, бредущих вдоль дороги.}
{4053}{}{Стая диких собак, бегущих вдоль трассы.}
{4054}{}{Отряд охотников, возвращающихся в город.}
{4055}{}{Группа бандитов, укрывшихся в засаде.}
{4056}{}{Группа переселенцев.}
{4057}{}{Банда грабителей, укрывшихся в засаде.}
{4058}{}{Банда рейдеров, укрывшихся в засаде.}
{4059}{}{Отряд охотников, отбивающихся от рейдеров.}
{4060}{}{Отряд охотников, отбивающихся от грабителей.}
{4061}{}{Караван, бредущий вдоль трассы.}
{4062}{}{Местное население, ступившее на путь грабежа.}
{4063}{}{Перекресток.}
{4064}{}{Затерянный офис.}
{4065}{}{Кафе "Новые надежды".}
{4066}{}{Дом на колесах.}
{4067}{}{"Далше".}
{4068}{}{Автостопщик.}
{4069}{}{Неунывающий Бобби.}
{4070}{}{Суд Линча.}
{4071}{}{Охотники за фильтром.}
{4072}{}{Кочевники Большого Бассейна.}

# Encounter Table 22 -- RINO_D
{4100}{}{Группа хищных растений.}
{4101}{}{Жертвы Апокалипсиса.}
{4102}{}{Группа грызунов.}
{4103}{}{Небольшая группа кротокрысов.}
{4104}{}{Небольшая группа свинокрысов.}
{4105}{}{Небольшая группа радскорпионов.}
{4106}{}{Стадо браминов.}
{4107}{}{Дикий разъяренный брамин.}
{4108}{}{Отряд охотников.}
{4109}{}{Банда рейдеров.}
{4110}{}{Отряд охотников, отбивающийся от рейдеров.}
{4111}{}{Кафе "Новые надежды".}
{4112}{}{Затерянный офис.}
{4113}{}{Большое отверстие.}
{4114}{}{Перекресток.}
{4115}{}{Автостопщик.}
{4116}{}{Место для пикника.}
{4117}{}{Дом на колесах.}
{4118}{}{"Далше".}
{4119}{}{Гигантское яйцо.}
{4120}{}{Неунывающий Бобби.}
{4121}{}{"Дорогой Джон".}

# Encounter Table 23 -- South_D
{4150}{}{Небольшая группа кротокрысов.}
{4151}{}{Небольшая группа радскорпионов.}
{4152}{}{Стая койотов.}
{4153}{}{Семейство когтей смерти}
{4154}{}{Кафе "Новые надежды".}
{4155}{}{Затерянный офис.}
{4156}{}{Большое отверстие.}
{4157}{}{Перекресток.}
{4158}{}{Место для пикника.}
{4159}{}{Дом на колесах.}
{4160}{}{"Далше".}
{4161}{}{Гигантское яйцо.}
{4162}{}{Караван Харди.}
{4163}{}{"Дорогой Джон".}
{4164}{}{Воды!}
{4165}{}{Пересыхающий источник и кротокрысы.}
{4166}{}{Пересыхающий источник и скорпионы.}
{4167}{}{Пересыхающий источник и хищные растения.}
{4168}{}{Пересыхающий источник и рой богомолов.}
{4169}{}{Рой богомолов.}

# Encounter Table 24 -- South_M
{4200}{}{Группа хищных растений.}
{4201}{}{Рой богомолов.}
{4202}{}{Группа золотых гекко.}
{4203}{}{Семейство гекконов.}
{4204}{}{Группа грызунов.}
{4205}{}{Небольшая группа кротокрысов.}
{4206}{}{Небольшая группа свинокрысов.}
{4207}{}{Небольшая группа радскорпионов.}
{4208}{}{Стадо браминов.}
{4209}{}{Стая волков.}
{4210}{}{Охотники Койотов, выслеживающие дичь.}
{4211}{}{Вождь племени Койотов.}
{4212}{}{Кафе "Новые надежды".}
{4213}{}{Большое отверстие.}
{4214}{}{Перекресток.}
{4215}{}{Место для пикника.}
{4216}{}{"Далше".}
{4217}{}{Гигантское яйцо.}
{4218}{}{Неунывающий Бобби.}
{4219}{}{"Дорогой Джон".}
{4220}{}{Племя каннибалов во время трапезы.}

# Encounter Table 25 -- Wind_T
{4250}{}{Небольшая группа грызунов, застрявших на дороге.}
{4251}{}{Небольшая группа кротокрысов, застрявших на дороге.}
{4252}{}{Небольшая группа свинокрысов, застрявших на дороге.}
{4253}{}{Небольшая группа пришельцев, случайно забредших в эти края.}
{4254}{}{Группа серебряных гекко, случайно выскочивших на дорогу.}
{4255}{}{Стая гекко, случайно выскочивших на дорогу.}
{4256}{}{Группа золотых гекко, случайно выскочивших на дорогу.}
{4257}{}{Рой богомолов, мигрирующих вдоль дороги.}
{4258}{}{Небольшая группа радскорпионов на дороге.}
{4259}{}{Стадо браминов, бредущих вдоль дороги.}
{4260}{}{Стая диких собак, бегущих вдоль трассы.}
{4261}{}{Группа работорговцев с рабами.}
{4262}{}{Группа работорговцев, пытающихся поработить нескольких людей.}
{4263}{}{Банда работорговцев и несколько собак.}
{4264}{}{Отряд охотников, возвращающихся в город.}
{4265}{}{Группа бандитов, укрывшихся в засаде.}
{4266}{}{Группа переселенцев.}
{4267}{}{Группа фермеров, бредущих по дороге.}
{4268}{}{Банда грабителей, укрывшихся в засаде.}
{4269}{}{Банда рейдеров, укрывшихся в засаде.}
{4270}{}{Группа мародеров, укрывшихся в засаде.}
{4271}{}{Отряд охотников, отбивающийся от мародеров.}
{4272}{}{Отряд охотников, отбивающийся от рейдеров.}
{4273}{}{Отряд охотников, отбивающийся от грабителей.}
{4274}{}{Группа фермеров, отражающих нападение мародеров.}
{4275}{}{Группа фермеров, отражающих нападение рейдеров.}
{4276}{}{Группа фермеров, отражающих нападение грабителей.}
{4277}{}{Группа фермеров, отражающих нападение радскорпионов.}
{4278}{}{Караван, бредущий вдоль трассы.}
{4279}{}{Супер 8.}
{4280}{}{Перекресток.}
{4281}{}{Затерянный офис.}
{4282}{}{Кафе "Новые надежды".}
{4283}{}{Дом на колесах.}
{4284}{}{Неунывающий Бобби.}
{4285}{}{Новобранец, отчаянно отбивающийся от рейдеров.}

# Encounter Table 26 -- Wind_D
{4300}{}{Группа хищных растений.}
{4301}{}{Стая пришельцев.}
{4302}{}{Рой богомолов.}
{4303}{}{Группа золотых гекко.}
{4304}{}{Семейство гекконов.}
{4305}{}{Группа грызунов.}
{4306}{}{Небольшая группа кротокрысов.}
{4307}{}{Небольшая группа радскорпионов.}
{4308}{}{Стадо браминов.}
{4309}{}{Стая диких собак.}
{4310}{}{Группа работорговцев с рабами.}
{4311}{}{Группа работорговцев, пытающихся поработить нескольких людей.}
{4312}{}{Банда работорговцев и несколько собак.}
{4313}{}{Отряд охотников.}
{4314}{}{Группа бандитов.}
{4315}{}{Банда рейдеров.}
{4316}{}{Отряд охотников, отбивающихся от группы рейдеров.}
{4317}{}{Отряд охотников, отбивающихся от группы бандитов.}
{4318}{}{Отряд охотников, отбивающихся от стаи диких собак.}
{4319}{}{Отряд охотников, отбивающихся от радскорпионов.}
{4320}{}{Отряд охотников, отбивающихся от гекко.}
{4321}{}{Отряд охотников, отбивающихся от богомолов.}
{4322}{}{Отряд охотников, отбивающихся от пришельцев.}
{4323}{}{Группа бандитов, отбивающихся от пришельцев.}
{4324}{}{Банда рейдеров, отбивающихся от пришельцев.}
{4325}{}{Супер 8.}
{4326}{}{Перекресток.}
{4327}{}{Большое отверстие.}
{4328}{}{Кафе "Новые надежды".}
{4329}{}{Место для пикника.}
{4330}{}{Дом на колесах.}
{4331}{}{"Далше".}
{4332}{}{Гигантское яйцо.}
{4333}{}{Неунывающий Бобби.}
{4334}{}{"Дорогой Джон".}
{4335}{}{Новобранец, отчаянно отбивающийся от рейдеров.}

# Encounter Table 27 -- Wind_M
{4350}{}{Группа хищных растений.}
{4351}{}{Рой богомолов.}
{4352}{}{Группа золотых гекко.}
{4353}{}{Семейство гекконов.}
{4354}{}{Группа грызунов.}
{4355}{}{Небольшая группа кротокрысов.}
{4356}{}{Небольшая группа радскорпионов.}
{4357}{}{Стадо браминов.}
{4358}{}{Стая волков.}
{4359}{}{Отряд охотников.}
{4360}{}{Супер 8.}
{4361}{}{Большое отверстие.}
{4362}{}{Кафе "Новые надежды".}
{4363}{}{Место для пикника.}
{4364}{}{Дом на колесах.}
{4365}{}{"Далше".}
{4366}{}{Гигантское яйцо.}
{4367}{}{Неунывающий Бобби.}
{4368}{}{"Дорогой Джон".}
{4369}{}{Новобранец, отчаянно отбивающийся от рейдеров.}

# Encounter Table 28 -- Zona_D
{4400}{}{Стая пришельцев.}
{4401}{}{Семейство гекконов.}
{4402}{}{Группа золотых гекко.}
{4403}{}{Небольшая группа радскорпионов.}
{4404}{}{Большое отверстие.}

# Encounter Table 29 -- VGSX_T
{4450}{}{Небольшая группа грызунов, застрявших на дороге.}
{4451}{}{Небольшая группа радскорпионов на дороге.}
{4452}{}{Стадо браминов, бредущих вдоль дороги.}
{4453}{}{Караван, бредущий вдоль трассы.}
{4454}{}{Местное население, ступившее на путь грабежа.}
{4455}{}{Один из братьев Блум.}
{4456}{}{Перекресток.}
{4457}{}{Затерянный офис.}
{4458}{}{Кафе "Новые надежды".}
{4459}{}{Дом на колесах.}
{4460}{}{"Далше".}
{4461}{}{Автостопщик.}
{4462}{}{Неунывающий Бобби.}
{4463}{}{Суд Линча.}
{4464}{}{Охотники за фильтром.}
{4465}{}{Кочевники Большого Бассейна.}

# Encounter Table 30 -- VEGS_T
{4500}{}{Небольшая группа грызунов, застрявших на дороге.}
{4501}{}{Рой богомолов, мигрирующих вдоль дороги.}
{4502}{}{Группа серебряных гекко, случайно выскочивших на дорогу.}
{4503}{}{Небольшая группа радскорпионов на дороге.}
{4504}{}{Стадо браминов, бредущих вдоль дороги.}
{4505}{}{Стая диких собак, бегущих вдоль трассы.}
{4506}{}{Группа работорговцев с рабами.}
{4507}{}{Группа работорговцев, пытающихся поработить нескольких людей.}
{4508}{}{Банда работорговцев и несколько собак.}
{4509}{}{Группа бандитов, укрывшихся в засаде.}
{4510}{}{Группа фермеров, бредущих по дороге.}
{4511}{}{Банда грабителей, укрывшихся в засаде.}
{4512}{}{Банда рейдеров, укрывшихся в засаде.}
{4513}{}{Группа фермеров, отражающих нападение мародеров.}
{4514}{}{Группа фермеров, отражающих нападение рейдеров.}
{4515}{}{Группа фермеров, отражающих нападение грабителей.}
{4516}{}{Группа фермеров, отражающих нападение радскорпионов.}
{4517}{}{Караван, бредущий через руины.}
{4518}{}{Перекресток.}
{4519}{}{Затерянный офис.}
{4520}{}{Большое отверстие.}
{4521}{}{Кафе "Новые надежды".}
{4522}{}{Дом на колесах.}
{4523}{}{"Далше".}
{4524}{}{Неунывающий Бобби.}
{4525}{}{Наемники Вегаса, охотящиеся за вашей головой.}
{4526}{}{Наемники Вегаса, охотящиеся за вашей головой.}
{4527}{}{Наемники Вегаса, охотящиеся за вашей головой.}
{4528}{}{Одичавший агент патрульной службы.}
{4529}{}{Неоновый Гангстер и его банда.}
{4530}{}{Охотники за фильтром.}
{4531}{}{Банда Королей.}
{4532}{}{Отчаявшийся реднек.}
{4533}{}{Извращенец со своей сексуальной рабыней.}
{4534}{}{Двое из банды Королей, зарывающие тело.}

# Encounter Table 31 -- VEGS_D
{4550}{}{Группа хищных растений.}
{4551}{}{Рой богомолов.}
{4552}{}{Группа серебряных гекко.}
{4553}{}{Семейство гекконов.}
{4554}{}{Группа грызунов.}
{4555}{}{Небольшая группа кротокрысов.}
{4556}{}{Небольшая группа свинокрысов.}
{4557}{}{Небольшая группа радскорпионов.}
{4558}{}{Стадо браминов.}
{4559}{}{Стая койотов.}
{4560}{}{Стая волков.}
{4561}{}{Группа работорговцев с рабами.}
{4562}{}{Группа работорговцев, пытающихся поработить нескольких людей.}
{4563}{}{Банда работорговцев и несколько собак.}
{4564}{}{Отряд охотников.}
{4565}{}{Банда рейдеров.}
{4566}{}{Банда рейдеров, совершающих налет на охотников.}
{4567}{}{Банда рейдеров, отбивающихся от радскорпионов.}
{4568}{}{Банда рейдеров, отбивающихся от грызунов.}
{4569}{}{Отряд охотников, отбивающихся от богомолов.}
{4570}{}{Отряд охотников, отбивающихся от радскорпионов.}
{4571}{}{Отряд охотников, отбивающихся от грызунов.}
{4572}{}{Рейдеры и бандиты, делящие награбленное.}
{4573}{}{Перекресток.}
{4574}{}{Большое отверстие.}
{4575}{}{Кафе "Новые надежды".}
{4576}{}{Место для пикника.}
{4577}{}{Дом на колесах.}
{4578}{}{"Далше".}
{4579}{}{Гигантское яйцо.}
{4580}{}{Неунывающий Бобби.}
{4581}{}{"Дорогой Джон".}
{4582}{}{Суд Линча.}
{4583}{}{Охотники за фильтром.}

# Encounter Table 32 -- VEGS_M
{4600}{}{Группа хищных растений.}
{4601}{}{Группа серебряных гекко.}
{4602}{}{Семейство гекконов.}
{4603}{}{Группа золотых гекко.}
{4604}{}{Группа грызунов.}
{4605}{}{Небольшая группа кротокрысов.}
{4606}{}{Небольшая группа свинокрысов.}
{4607}{}{Небольшая группа радскорпионов.}
{4608}{}{Стая волков.}
{4609}{}{Отряд охотников.}
{4610}{}{Отряд охотников, отбивающихся от группы бандитов.}
{4611}{}{Отряд охотников, охотящихся на дичь.}
{4612}{}{Отряд охотников, охотящихся на дичь.}
{4613}{}{Большое отверстие.}
{4614}{}{Кафе "Новые надежды".}
{4615}{}{Место для пикника.}
{4616}{}{Дом на колесах.}
{4617}{}{"Далше".}
{4618}{}{Гигантское яйцо.}
{4619}{}{"Дорогой Джон".}

# Encounter Table 33 -- VEGS_J
{4650}{}{Группа грызунов.}
{4651}{}{Свалка покрышек.}

# Encounter Table 34 -- SALT_Z
{4700}{}{Пугающая тишина.}

# Encounter Table 35 -- RINW_T
{4750}{}{Стая койотов, рыщущих вдоль трассы.}
{4751}{}{Небольшая группа радскорпионов на дороге.}
{4752}{}{Небольшая группа грызунов, застрявших на дороге.}
{4753}{}{Стадо браминов, бредущих вдоль дороги.}
{4754}{}{Местное население, ступившее на путь грабежа.}
{4755}{}{Группа работорговцев с рабами.}
{4756}{}{Группа работорговцев, пытающихся поработить нескольких людей.}
{4757}{}{Банда работорговцев и несколько собак.}
{4758}{}{Группа бандитов, укрывшихся в засаде.}
{4759}{}{Банда грабителей, укрывшихся в засаде.}
{4760}{}{Банда рейдеров, укрывшихся в засаде.}
{4761}{}{Группа мародеров, укрывшихся в засаде.}
{4762}{}{Караван, бредущий через руины.}
{4763}{}{Перекресток.}
{4764}{}{Затерянный офис.}
{4765}{}{Большое отверстие.}
{4766}{}{Кафе "Новые надежды".}
{4767}{}{Дом на колесах.}
{4768}{}{"Далше".}
{4769}{}{Автостопщик.}
{4770}{}{Неунывающий Бобби.}

# Encounter Table 36 -- South_MD
{4800}{}{Группа хищных растений.}
{4801}{}{Рой богомолов.}
{4802}{}{Группа золотых гекко.}
{4803}{}{Семейство гекконов.}
{4804}{}{Группа грызунов.}
{4805}{}{Небольшая группа кротокрысов.}
{4806}{}{Небольшая группа свинокрысов.}
{4807}{}{Небольшая группа радскорпионов.}
{4808}{}{Стадо браминов.}
{4809}{}{Стая волков.}
{4810}{}{Кафе "Новые надежды".}
{4811}{}{Затерянный офис.}
{4812}{}{Большое отверстие.}
{4813}{}{Перекресток.}
{4814}{}{Место для пикника.}
{4815}{}{"Далше".}
{4816}{}{Гигантское яйцо.}
{4817}{}{Неунывающий Бобби.}
{4818}{}{"Дорогой Джон".}

# Encounter Table 37 -- BLCK_B
{4850}{}{Группа серебряных гекко.}
{4851}{}{Группа грызунов.}
{4852}{}{Небольшая группа кротокрысов.}
{4853}{}{Небольшая группа радскорпионов.}
{4854}{}{Стадо диких браминов.}
{4855}{}{Стая койотов.}
{4856}{}{Стадо браминов, отбивающихся от нескольких гекко.}
{4857}{}{Дом на колесах.}
{4858}{}{Гигантское яйцо.}
{4859}{}{"Дорогой Джон".}
{4860}{}{Дикий разъяренный брамин.}

# Encounter Table 38 -- HTRN_D
{4900}{}{Группа грызунов.}
{4901}{}{Небольшая группа свинокрысов.}
{4902}{}{Небольшая группа кротокрысов.}
{4903}{}{Стая койотов.}
{4904}{}{Несколько отчаянных мародеров.}
{4905}{}{Автостопщик.}

# Encounter Table 39
{4950}{}{Группа пугливых грызунов.}

# Encounter Table 40
{5000}{}{}

# Encounter Table 41
{5050}{}{}

# Encounter Table 42
{5100}{}{}

# Encounter Table 43
{5150}{}{}

# Encounter Table 44
{5200}{}{}

# Encounter Table 45
{5250}{}{}

# Encounter Table 46
{5300}{}{}

# Encounter Table 47
{5350}{}{}

# Encounter Table 48
{5400}{}{}

# Encounter Table 49
{5450}{}{}

# Encounter Table 50
{5500}{}{}

# Encounter Table 51
{5550}{}{}

# Encounter Table 52
{5600}{}{}

# Encounter Table 53
{5650}{}{}

# Encounter Table 54
{5700}{}{}

# Encounter Table 55
{5750}{}{}

# Encounter Table 56
{5800}{}{}

# Encounter Table 57
{5850}{}{}

# Encounter Table 58
{5900}{}{}

# Encounter Table 59
{5950}{}{}

# Encounter Table 60
{6000}{}{}

# Encounter Table 61
{6050}{}{}

# Encounter Table 62
{6100}{}{}

# Encounter Table 63
{6150}{}{}

# Encounter Table 64
{6200}{}{}

# Encounter Table 65
{6250}{}{}

# Encounter Table 66
{6300}{}{}

# Encounter Table 67
{6350}{}{}

# Encounter Table 68
{6400}{}{}

# Encounter Table 69
{6450}{}{}

# Encounter Table 70
{6500}{}{}

# Encounter Table 71
{6550}{}{}

# Encounter Table 72
{6600}{}{}

# Encounter Table 73
{6650}{}{}

# Encounter Table 74
{6700}{}{}

# Encounter Table 75
{6750}{}{}