{100}{}{Вы видите робота.}
{101}{}{Вы видите робота. Есть ощущение, будто в нем скрывается опасность.}
{102}{}{Добро пожаловать}

#Выкрики при нападении
{110}{}{Внимание, на территории посторонний!}
{111}{}{Включить систему безопасности!}
{112}{}{Получена команда уничтожить посторонних! Приступаю к выполнению.}

#Попытка заговорить
{120}{}{Приветствуем вас на станции "Посейдон Ойл"! Пожалуйста, не нарушайте порядок и чистоту в помещениях.}
{121}{}{Приносим извинения за причиненные неудобства. Надеемся, ошибка более не повторится.}
{122}{}{Мы рады приветствовать вас, посетитель.}
{123}{}{Проходите, уважаемый посетитель. Мы всегда вам рады.}

#Попытка отключения
{130}{}{Робот выведен из строя.}
{131}{}{Этот готов}

{132}{}{Вы не смогли разобраться в устройстве робота и лишь привлекли к себе внимание.}
{133}{}{Посторонним не следует этого делать}
{134}{}{Не вынуждайте применять ответную силу}
{135}{}{Обнаружен нарушитель! Ликвидировать немедленно!}

{136}{}{Ваших навыков в ремонте явно недостаточно для отключения робота.}
