{100}{}{Парадная дверь.}
{101}{}{Перед вами мощная кодовая дверь, ведущая на станцию.}
{102}{}{Дверь заперта.}

#Уничтожение двери:
{105}{}{Взрыв сорвал петли, и осколки двери полетели в стороны. Вы получаете 100 опыта.}
{106}{}{Здесь нужно что-то мощное.}

#Применение навыков и предметов
{110}{}{Против лома нет приема: замок слетает с двери.}
{111}{}{Вы демонтировали кодовый замок и открыли дверь.}
{112}{}{Вы взламываете кодовый замок.}
{113}{}{Вы обхитрили кодовый замок.}
{114}{}{Это ничего не даст.}
{115}{}{И на что вы рассчитывали? Этот случай посерьезней!}
{116}{}{Верное направление мысли, однако с вашими навыками здесь делать нечего.}
{117}{}{Эта дверь слишком мощная для вас.}
