{100}{}{Дверь склада.}
{101}{}{Это большая металлическая дверь, ведущая на склад.}
{102}{}{Кажется, дверь заклинило с внутренней стороны. Отсюда ее не открыть.}
{103}{}{Даже такой удар не способен нанести двери вред.}

{104}{}{Дверь заклинило изнутри, отсюда ее не открыть.}
{105}{}{Заклинило изнутри}
{106}{}{С трудом дверь поддается и открывается.}
{107}{}{Дверь заклинило окончательно, она больше не откроется.}
{108}{}{Дверь не поддается}

