{100}{}{Вы видите Вилмута.}
{101}{}{Перед вами доктор Ян Вилмут, но обычно его называют просто Док.}

#Начало диалога:
{102}{}{Да-да, }
{103}{}{? Чем я могу тебе помочь?}
{104}{}{Вот молодец - *живым* пришел!}
{105}{}{Погоди, у меня тут лужа крови. Щас вытру...}
{106}{}{Я, как нормальный гражданин, в твои задачи не лезу, но *очень* хочется.}
{107}{}{Порой мне тяжко думать, что в силу своей работы я *должен* помогать всем подряд. С другой стороны, я могу бросить пострадавшего на произвол и сказать: "Я не навредил!"}

#Медицинские вопросы:
{108}{}{Док, меня ранили, и мне больно. Можете остановить это?}
{109}{}{Док, я себя странно чувствую. Кажется, это радиация...}
{110}{}{Док, я чем-то отравился. Ой, как живот болит!}
{111}{}{Я плохо знаю медицину, а мне в пути это пригодилось бы. Можете дать небольшой урок первой помощи?}
{112}{}{А у вас есть какие-нибудь прививки или вакцины? Я не помню, чтобы мне их делали, а в пути многое может произойти.}
{113}{}{Извините, я лучше пойду. Никогда не любил все эти иголки...}
{114}{}{Упс. Док! Не надо! Я буду хорошим! Очень хорошим! Я пойду домой!}

#Лечение:
{115}{}{А то как же! Я спец в этом деле! Щас только вытру шприц, а то уронил его на пол... Ха-ха-ха! Ладно, шучу! Садись и не плачь. Больно не будет. Через пяток часов будешь танцевать.}
{116}{}{Ладно. Я вам доверяю.}
{117}{}{Нет, доктор! Это слишком долго! Я уж лучше как-нибудь сам вылечусь.}
{118}{}{Этот готов. Следующий!}
{119}{}{Спасибо!}
{120}{}{За такой черный юмор недолго и по морде получить. Пока, Док.}

#Обучение первой помощи:
{121}{}{Нууу... молодой человек, я воодушевлен вашим рвением, но, боюсь, это займет слишком много времени для человека с вашим умом. Будь вы пообразованней...}
{122}{}{Нууу... молодой человек, я воодушевлен вашим рвением! Что ж, пообщаемся пару часов?}
{123}{}{Жалко. Ну тогда в другой раз.}
{124}{}{Жмот вы, доктор! Самый настоящий.}
{125}{}{Отлично, Док! Только обойдемся без искусственного дыхания, ладно?}
{126}{}{Лучше в другой раз. Времени сейчас нет.}
{127}{}{Давай, старик! Заводи шарманку!}

{128}{}{(Вы проводите три часа, слушая лекции о медицине и практикуясь на куклах. Доктор хороший учитель) Это хорошо, но в тяжелых случаях ваших навыков будет недостаточно.}
{129}{}{Фи! Никогда не любил медицину, но приходится действовать. Пока, Док.}
{130}{}{(Вы проводите три часа, слушая лекции о медицине и практикуясь на куклах. Доктор хороший учитель) Это хорошо, но в тяжелых случаях ваших навыков будет недостаточно. Вот вам книжка, почитайте на досуге.}

#Сыворотка
{131}{}{Да. Всем выходящим на поверхность я делаю специальную прививку для повышения радиационной и бактериологической защиты. Но тебе еще не ставил. Вакцина будет действовать на протяжении 7 часов, все это время ты проваляешься в постели под моим пристальным надзором. Тебя сейчас уколоть или позже?}
{132}{}{Колите прямо сейчас! Лучше в начале немного помучиться, чем потом долго и тяжело болеть.}
{133}{}{Я не терплю все эти иголки и прочие медицинские штучки, так что сам себе их вкалывай! Понял? У меня, кстати, вопросы остались.}
{134}{}{Слишком долго. Придется обойтись без прививок. У меня, кстати, вопросы остались.}
{135}{}{Слишком долго. До свидания, Док.}
{136}{}{(Док применил на вас специальную сыворотку. Вы пролежали несколько часов в полуболезненном состоянии, но, отоспавшись, чувствуете себя на взлете!)}
{137}{}{Большое спасибо, Док! Я теперь полон сил! А можно спросить?}
{138}{}{Большое спасибо, Док! Ну я пойду, пожалуй, на поиски SoS.}
{139}{}{После твоего поступка с Джошуа? Извини, дорогуша, не выйдет.}

#Хохма при подробном осмотре
{156}{}{Ты чего меня разглядываешь?}

#Если чуз под кайфом (зависимость)
{157}{}{Пока ты не прекратишь жрать эту дрянь, я с тобой даже разговаривать не стану.}
{158}{}{Понял.}

#Про Моро
{160}{}{Док, вы что-нибудь слышали о Ричарде Грэе, который когда-то давно ушел из нашего убежища? Говорят, он до сих пор жив...}
{161}{}{Ричард Грэй? Я знаю только о Ричарде Моро. Он пропал во время первой вылазки на поверхность 40 лет назад. Я тогда был его ассистентом. Столько лет прошло, что даже лица его не помню. Нормальный мужик, если не считать излишнюю черствость. Если он злился, следовало молчать.}
{162}{}{А тот мертвяк в службе охраны, Гарольд, сказал, что якобы знал Ричарда Грэя из убежища 8.}
{163}{}{Ты бы меньше верил всяким мертвецам ходячим. Кто знает, что у него творится в голове? Хех, бедолаге определенно не повезло. Его поразила какая-то особая неизученная форма вируса, хотя радиация тоже могла сказаться на организме. С другой стороны, этот вирус продлевает ему кроме мучений и жизнь тоже. Если Ричард Моро попал под такое же воздействие и стал таким же мертвецом, то теоретически мог выжить и сменить имя. Но вероятность этого крайне мала. Считай это очередной байкой этого... как его... Гарольда, да.}

#Про артефакт
{170}{}{Я нашел в Пустошах странный артефакт. Есть подозрение, что он поглощает радиацию...}
{171}{}{Серьезно? Ну теоретически, это возможно... Можешь показать?}
{172}{}{Да, вот он.}
{173}{}{Сейчас у меня с собой его нет, занесу потом.}
{174}{}{Больше похоже на корешок угнетенного дерева. Ты уверен, что он поглощает радиацию?}
{175}{}{Ну я могу ошибаться, но...}
{176}{}{Предлагаю проверить. У меня есть нужная аппаратура. Я дам слабый пучок рентгеновского излучения и зафиксирую поглощающую способность поверхности.}
{177}{}{Это было бы любопытно. Приступим сейчас?}
{178}{}{(некоторое время вы провели за любопытными исследованиями) Да, этот корешок действительно поглощает радиацию. Но где он ее хранит или нейтрализует... В общем, я в полном замешательстве! Ты нашел настоящую сенсацию для научного мира.}
{179}{}{О да, я такой. Я много чего нахожу... сенсационного.}
{180}{}{Слушай-ка. Я понимаю, что он тебе нужен для путешествия, но...}
{181}{}{Эээ, нет, Док! Вы хотите забрать у меня самое ценное?}
{182}{}{Ну не забрать. А только взять на изучение. Пойми, это важно не только для тебя. Где твой патриотизм?! Представь, сколько пользы принесет его изучение для нашего города! Мы смогли бы найти панацею от радиации.}
{183}{}{Оно, конечно, понятно, но мне ведь нужно как-то компенсировать недостаток такой находки. Я уже привык к его теплу и округлым формам...}
{184}{}{Что ж, вы правы, Док. Я пожертвую своей безопасностью во имя науки и во имя своего народа! Забирайте артефакт, Док! И не надо благодарностей.}
{185}{}{Что ж, ты прав. Я дам тебе пачку антирадиационных препаратов. А больше у меня и нет ничего.}
{186}{}{Эээ, нет, Док! Мне этого не нужно. Я лучше приберегу артефакт для себя. Счастливо.}
{187}{}{Компенсация, что надо! Держите артефакт.}

{188}{}{Так! Попрошу без обмана, молодой человек!}
{189}{}{Извините, Док. Больше не повторится.}

{190}{}{Здравствуй, спаситель. Как видишь, я все еще пытаюсь быть полезным и работать даже в таком бардаке. Чего тебе нужно, }
{191}{}{?}

{192}{}{Док, а вы тоже знали, что мы клоны?}
{193}{}{Я скажу честно. Да, я знал, хотя никто мне не говорил этого прямо. Но как медик я понимал, к чему это идет и поэтому молчал.}
{194}{}{И к чему же это шло?}
{195}{}{Ну, такого я точно не ожидал! Знаешь, быть чьим-то клоном, наверное, не так уж и плохо. Посмотри на себя - жизнь в убежище дала нам чистое тело, образование и защиту. Много ли в Пустошах еще таких же мест?}
{196}{}{Их почти не осталось. Но и те, кто живут за пределами города еще не опустились ниже плинтуса!}
{197}{}{Хм... Возможно, правительство было жесткого, организовывая нашу базу для своих корыстных целей, но тела наших граждан шли на спасения других людей. Я не знаю, что об этом думать. Мне нужно многое переосмыслить...}
{198}{}{Ладно, док, осмысливайте и дальше. Пока.}

#Сообщения на инфоокне:
{200}{}{Вы получаете 200 опыта за прослушивание уроков Дока.}
{201}{}{Вы получаете 400 опыта за успехи в медицине.}
{202}{}{Вы получаете 300 опыта за прослушивание уроков Дока.}

#Сны Хаккунина:
{238}{hak031}{ }
{243}{hak032}{ }
{244}{hak033}{ }
{245}{hak034}{ }
{246}{hak035}{ }

#Женские реплики:
{1104}{}{Вот молодец - *живой* пришла!}
{1109}{}{Док, я себя странно чувствую. Я, кажется, подхватила радиацию...}
{1110}{}{Док, я чем-то траванулась. Ой, как живот болит!}
{1111}{}{Я тут подумала - я плохо знаю медицину, а мне в пути это пригодилось бы. Можете дать небольшой урок первой помощи?}
{1113}{}{Извините, я лучше пойду. Никогда не любила все эти иголки...}
{1114}{}{Упс. Док! Не надо! Я буду хорошей! Очень хорошей! Я пойду домой! К маме!}
{1117}{}{Нет, доктор! Это слишком долго! Я уж лучше как-нибудь сама вылечусь.}
{1118}{}{Эта готова. Следующий!}
{1121}{}{Нууу... юная леди, я воодушевлен вашим рвением, но, боюсь, это займет слишком много времени для человека с вашим умом. Будь вы пообразованней...}
{1122}{}{Нууу... юная леди, я воодушевлен вашим рвением! Что ж, пообщаемся пару часов?}
{1129}{}{Фи! Никогда не любила медицину, но приходится действовать. Пока, Док.}
{1137}{}{Большое спасибо, Док! Я теперь полна сил! А можно спросить?}
{1158}{}{Поняла.}
{1163}{}{Ты бы меньше верила всяким мертвецам ходячим. Кто знает, что у него творится в голове? Хех, бедолаге определенно не повезло. Его поразила какая-то особая неизученная форма вируса, хотя радиация тоже могла сказаться на организме. С другой стороны, этот вирус продлевает ему кроме мучений и жизнь тоже. Если Ричард Моро попал под такое же воздействие и стал таким же мертвецом, то теоретически мог выжить и сменить имя. Но вероятность этого крайне мала. Считай это очередной байкой этого... как его... Гарольда, да.}
{1170}{}{Я нашла в Пустошах странный артефакт. Есть подозрение, что он поглощает радиацию...}
{1174}{}{Больше похоже на корешок угнетенного дерева. Ты уверена, что он поглощает радиацию?}
{1178}{}{(некоторое время вы провели за любопытными исследованиями) Да, этот корешок действительно поглощает радиацию. Но где он ее хранит или нейтрализует... В общем, я в полном замешательстве! Ты нашла настоящую сенсацию для научного мира.}
{1179}{}{О да, я такая. Я много чего нахожу... сенсационного.}
{1183}{}{Оно, конечно, понятно, но мне ведь нужно как-то компенсировать недостаток такой находки. Я уже привыкла к его теплу и округлым формам...}
{1185}{}{Что ж, ты права. Я дам тебе пачку антирадиационных препаратов. А больше у меня и нет ничего.}
{1188}{}{Так! Попрошу без обмана.}

{1415}{}{Эта готова. Следующий!}
{1450}{}{Я нашла в Пустошах странный артефакт, поглощающий радиацию...}
{1472}{}{Так! Попрошу без обмана, гражданка!}

####################################################
#
#         Самый первый диалог
#
####################################################

{300}{}{Рад видеть вас, }
{301}{}{. Ваш визит ко мне не случаен, верно? Да, я знаю о вашем поиске. Смотритель обсуждал со мной вашу кандидатуру, и, признаться честно, я очень рад, что наше с ним мнение совпало.}
{302}{}{Вы поможете мне?}
{303}{}{Конечно, если вам понадобится медицинская помощь, вы всегда можете обратиться ко мне. Но я не могу покидать свой пост.}
{304}{}{Вы можете дать какой-нибудь совет перед выходом за черту города?}
{305}{}{Остерегайтесь радиации. Это главное.}

{306}{}{Расскажите о радиации?}
{307}{}{Конечно. Что вы хотите знать?}
{308}{}{Опасные зоны.}
{309}{}{Лечение.}
{310}{}{Профилактика.}
{311}{}{Постэффект.}
{312}{}{Пожалуй, этого хватит. До свиданья.}

{313}{}{Это мне знакомо. До свиданья.}
{314}{}{На некоторых территориях радиация действует фоном постоянно. В таких зонах не следует задерживаться. Но некоторые отдельные объекты также могут быть локальным источником радиации. Особенно те, что сделаны металла, например, старые машины. Их можно просто обходить стороной.}
{315}{}{Это возможно только посредством медикаментов. Таблетки "Рад-Х" повышают сопротивляемость организма радиации. Их следует принять перед посещением зараженной местности. Если вы уже подверглись облучению, то поспешите использовать "Антирадин" - он постепенно выводит радиацию из организма. Возможно, вы найдете в пустошах и другие средства, которые мне не известны.}
{316}{}{В ваш Pip-Boy встроен счетчик Гейгера. Проведите им вдоль тела, и счетчик покажет текущий уровень облучения. [кнопка на дополнительной панели интерфейса внизу] Не позволяйте цифре вырасти за 100 рентген - это рискованно.}
{317}{}{Если вы долго находитесь под влиянием облучения, это негативно скажется на вашем организме вплоть до падения силы, ловкости или выносливости. Впрочем после лечения организм может восстановить прежние показатели, но на это уйдет какое-то время.}
{318}{}{Что ж, всего вам доброго, гражданин }
{319}{}{. И да здравствует Город Убежища!}
{320}{}{Да здравствует Город Убежища!}
{321}{}{Э, да, еще увидимся, док.}

####################################################
#
#         Основной диалог
#
####################################################

#Первая реплика дока:
{400}{}{Здравствуй, спаситель. Как видишь, я все еще пытаюсь быть полезным и работать даже в таком бардаке. Чего тебе нужно, }
{401}{}{?}
{402}{}{О, ну и вид! Уж поверьте, гражданин, уколоться этой пакостью - не лучший способ решения проблем.}
{403}{}{Да-да, }
{404}{}{? Чем я могу помочь?}
{405}{}{Порой тяжко думать, что я обязан помогать всем подряд в нашем городе. Не все они того достойны.}

{406}{}{Ну, я пойду.}

#Мед. помощь:
{410}{}{Мне нужна медицинская помощь.}
{411}{}{Конечно же! Сейчас только вытру шприц, а то уронил на пол... Ха-ха-ха! Шучу! Садись, больно не будет.}
{412}{}{Ладно, док, я вам доверяю.}
{413}{}{Лучше ответьте мне на пару вопросов.}
{414}{}{Нет, я уже как-нибудь самостоятельно.}
{415}{}{Этот готов. Следующий!}
{416}{}{Спасибо, док, но у меня еще остались вопросы.}
{417}{}{Спасибо, док.}

####################################################
#
#         Артефакт
#
####################################################

{450}{}{Я нашел в Пустошах странный артефакт, поглощающий радиацию...}

{451}{}{Поглощающий? Это весьма любопытно! Что же это?}
{452}{}{Вот он, смотрите.}
{453}{}{Сейчас у меня его с собой нет, занесу потом.}
{454}{}{Похоже на корешок угнетенного дерева. Неужели он действительно поглощает радиацию?}
{455}{}{Это проверено на практике.}
{456}{}{Что ж, предлагаю проверить на моей аппаратуре. Я дам слабый пучок рентгеновского излучения и зафиксирую поглощающую способность поверхности.}
{457}{}{Это было бы любопытно. Приступим!}
{458}{}{Это настоящая сенсация! Корешок действительно поглощает радиацию. Но где он ее хранит или нейтрализует... В общем, я в полном замешательстве.}
{459}{}{Неожиданно, правда?}

{460}{}{Да, эта вещь требует тщательного анализа. Я очень хотел бы взять предмет на изучение.}
{461}{}{Что вы намерены с ним делать?}
{462}{}{Вы вернете мне его после изучения?}
{463}{}{Не так быстро, док. Что мне за это будет?}
{464}{}{Что ж, я отдам его бесплатно. Вам это нужнее.}
{465}{}{Возвращайте артефакт, и я ухожу отсюда!}

{466}{}{Изучу внимательнее самыми разными, доступными для меня, средствами. Нужно понять, как он захватывает и нейтрализует радиацию. Это могло бы помочь в выработке радзащиты для наших сограждан.}
{467}{}{Боюсь, что нет. Исследование займет много времени и скорее всего от артефакта в итоге ничего не останется.}
{468}{}{Это справедливо. Я компенсирую вашу потерю медикаментами: 5 стимуляторов, 5 антирадинов, 5 Рад-Х и, пожалуй, книжкой по первой помощи. Но лучше представьте, сколько пользы принесет его изучение для города! Подумайте о множестве людей, которым артефакт поможет в лечении и профилактике!}
{469}{}{Отлично, я хочу медикаменты.}
{470}{}{Да... да... Я понимаю. Вы хозяин, вам решать.}
{471}{}{Именно. И я решаю оставить артефакт при себе.}

{472}{}{Так! Попрошу без обмана, гражданин!}
{473}{}{Извините, Док. Больше не повторится.}

####################################################
#
#         Вопрос о клонах
#
####################################################

{480}{}{Док, вы тоже знали, что мы клоны?}

{481}{}{Отвечу честно. Да, я знал.}
{482}{}{Почему вы молчали?}
{483}{}{Все жители убежища были клонами?}
{484}{}{Вы тоже клон?}
{485}{}{Как вы относитесь к миссии убежища 8?}
{486}{}{Вы бы легли под скальпель ради своего "прототипа"?}
{487}{}{Фух, дальше расспрашивать не хочу.}
{488}{}{}
{489}{}{}
{490}{}{}
{491}{}{}

{492}{}{Сказать правду было недопустимо. Тактика руководства была в оболванивании населения. Иначе }
{493}{}{Нет. Руководство убежища состояло из чистокровных людей, которые здесь работали. Но значительная часть этого персонала уже погибла от старости, ведь собственных клонов мы не могли плодить, иначе это привело бы к замешательству среди непосвященного населения.}
{494}{}{Меня вырастили "из пробирки" вскоре после запечатывания убежища. Но значительно позже, когда Ричард Моро исчез из убежища, руководству был нужен новый человек в медсекторе. Поэтому меня посвятили в некоторые тайны. Но лишь в некоторые!}
{495}{}{Хм. Возможно, правительство было жесткого, организовывая нашу базу для своих корыстных целей, но тела наших граждан шли на спасения других людей. Я не знаю, что об этом думать. Мне нужно многое переосмыслить.}
{496}{}{Знаешь, быть чьим-то клоном, наверное, не так уж и плохо. Посмотри на себя - жизнь в убежище дала нам чистое тело, образование и защиту. Много ли в Пустошах еще таких же мест? Счастливо прожить полжизни, чтобы затем еще и спасти чью-то чужую - это довольно неплохо, как мне кажется. Большинству за пределами города повезло гораздо меньше.}
{497}{}{}
{498}{}{}
{499}{}{}

####################################################
#
#     Вопрос о Гарольде и квест о мутациях
#
####################################################

{500}{}{Вы видели того мертвяка у охраны?}
{501}{}{Давайте еще раз поговорим о мутациях.}

#Про Гарольда и мутации
{510}{}{Хех, бедолаге определенно не повезло. Его поразила какая-то особая неизученная форма вируса, хотя радиация тоже могла сказаться на организме. С другой стороны, этот вирус продлевает ему кроме мучений и жизнь тоже.}
{511}{}{Мы рискуем от него заразиться?}
{512}{}{Что вы думаете об интеллектуальных способностях Гарольда?}
{513}{}{Расскажите о Ричарде Грэе?}
{514}{}{Расскажите о мутациях?}
{515}{}{Пожалуй, хватит об этом.}

{521}{}{Едва ли. Он сам по себе не является ни источником радиации, ни носителем вирусов.}
{522}{}{Несмотря на мутации и престарелый возраст, этот мертвец - подросток. Он любит подурачится, но при этом все прекрасно понимает. Он сохранил свой интерес к жизни... по крайней мере пока. Как знать, возможно, продолжительное существование кардинально переменит его взгляды.}
{523}{}{Ричард Грэй? Я знал только Ричарда Моро. Он пропал во время первой вылазки на поверхность 40 лет назад. Я тогда был его ассистентом. Столько лет прошло, что даже лица его не помню.}
{524}{}{А Гарольд сказал, что якобы знал Ричарда Грэя из убежища 8.}
{525}{}{Поменьше верьте всяким мертвецам ходячим. Кто знает, что у него творится в голове? Если Ричард Моро попал под такое же воздействие и стал таким же мертвецом, то теоретически мог выжить и сменить имя. Но вероятность этого крайне мала. Считайте это очередной байкой этого... как его... Гарольда, да.}

{530}{}{Мне известно о трех видах мутаций, если классифицировать их по факторам генезиса - токсичные мутации, радиационные и вирусные. Первые две как правило носят неустойчивый характер и ведут к гибели либо тяжелой искалеченной форме существования. Но вирусная форма - это что-то особенное. К сожалению, у меня мало данных, чтобы делать выводы - попросту нет материала для исследований.}
{531}{}{Вам нужен мутант для опытов?}
{532}{}{Да. Я давно прошу начальника охраны обеспечить меня таким материалом, но получаю лишь отказы. Якобы у патрульных и так работа опасная.}
{533}{}{Я могу достать для вас тело мутанта.}
{534}{}{Неужели?! О, это было бы замечательно. Если вам повезет - принесите тело ко мне. Уж я найду ему применение.}
{535}{}{Хорошо. Но у меня остались другие вопросы.}
{536}{}{Если наткнусь на что-нибудь такое.}

#Квест на мутации
{550}{}{Мне известно о трех видах мутаций: токсичные, радиационные и вирусные. Первые две довольно неустойчивы, то есть ведут к гибели или тяжелой искалеченной форме существования. Но вирусная форма - это что-то особенное. К сожалению, у меня мало данных, чтобы делать выводы - попросту нет материала для исследований.}
{551}{}{Мне удалось достать тело мутанта для ваших исследований.}
{552}{}{Я знаю место, где обитает несколько мутантов.}
{553}{}{Ну а пока вы не заняты, хочу спросить вас еще.}
{554}{}{Это все, что мне хотелось узнать.}
{555}{}{}
{556}{}{}

#Квест по лечению шлюхи в Блэк-Рок
{560}{}{Что вам известно о кожных инфекциях?}
{561}{}{Я не углублялся в этот вопрос. У граждан нет проблем с кожей. А что?}
{562}{}{Есть один... человек, который нуждается в помощи.}
{563}{}{Тогда пускай он придет сюда. Какой его номер?}
{564}{}{Это житель из Пустошей. Он живет в другом месте.}
{565}{}{Оу, боюсь, я не могу помочь...}
{566}{}{Но у вас есть лекарство? Может быть, я просто отнесу его?}
{567}{}{Уф... Ладно, я выдам вам антивирусное средство. Но именно *вам*, а что вы намерены с ним делать - ваше дело. Ок?}
{568}{}{Спасибо, док, я никому не скажу.}
{569}{}{Вы получили предмет антитоксин.}

####################################################
#
#     Про слуг из Джерлака
#
####################################################

{600}{}{Вы уже познакомились с нашими слугами?}

{601}{}{О да. Весьма прелюбопытный материал для анализа.}
{602}{}{Вы их уже обследовали?}
{603}{}{Они безопасны для нас?}
{604}{}{Что вы думаете об их интеллектуальных способностях?}
{605}{}{Вам не кажется, что пичкать их таблетками не этично?}
{606}{}{}
{607}{}{}
{608}{}{Меня интересует другое.}
{609}{}{Это все, что мне хотелось узнать.}

{610}{}{Да, иначе бы их не выпустили из изолированных камер.}
{611}{}{В каком смысле? Если речь о вирусах или другом виде заражения, то нет.}
{612}{}{Довольно несчастные люди. Докатились до уровня приматов и продолжают скатываться еще дальше. Но с ними можно общаться и их даже можно чему-то дрессиро... э, учить, да.}
{613}{}{Нет, не кажется. Мы даем им два раза в день препараты, которые понижают волю и тягу с самореализации. Это нужно для того, чтобы они не создавали нам проблем, а спокойно и монотонно занимались поставленными перед ними задачами. поверьте, так лучше для всех нас.}

####################################################
#
#             Данные из компа и прививки
#
####################################################

#Про компьютер Дока:
{700}{}{Вы позволите воспользоваться вашим компьютером?}
{701}{}{Ни в коем случае! Это закрытая служебная информация, доступная только для медицинского персонала. Да вы и не сможете в ней разобраться - там сугубо медицинские данные.}
{702}{}{Очень жаль.}
{703}{}{Говорят, у вас можно поставить прививки против облучения?}

{704}{}{Верно. Граждане получили их во время последнего профилактического цикла несколько лет назад.}
{705}{}{Но мне их не ставили!}
{706}{}{Действительно, вы неудачно "вписались" между циклами.}
{707}{}{Забудьте про циклы! Мне нужна эта прививка!}
{708}{}{Ладно, уже не важно.}
{709}{}{(Вы проводите сутки в автодоке, пока ваш организм пытается совладать с прививкой) Ну, как ваше самочувствие? Все еще крушится голова? Ничего страшного, скоро пройдет. Поднимайтесь!}
{710}{}{Спасибо, доктор!}



{0}{}{Мал. оружие }
{1}{}{Бол. оружие }
{2}{}{Энерг. оружие }
{3}{}{Рукопашное }
{4}{}{Холодное }
{5}{}{Метательное }
{6}{}{1я помощь }
{7}{}{Доктор }
{8}{}{Скрытность }
{9}{}{Взлом }
{10}{}{Кража }
{11}{}{Ловушки }
{12}{}{Наука }
{13}{}{Ремонт }
{14}{}{Разговор }
{15}{}{Бартер }
{16}{}{Игра }
{17}{}{Натуралист }

