{100}{}{Вы видите Маконса.}
{101}{}{Вы видите мальчика - шайенна по имени Маконс Медвежонок.}

{102}{}{Все не так просто, этому мальчику нужна операция.}
{103}{}{Нужна операция}

#После операции
{110}{}{Хау, мистер!}
{111}{}{Как себя чувствуешь, Маконс?}
{112}{}{Рад был тебя видеть.}
{113}{}{Вы сотворили чудо! Я теперь могу даже бегать! Честно! Вы такой же великий шаман, как и Аванигижиг!}
{114}{}{Молодец. Выздоравливай.}
{115}{}{Я себя отлично чувствую! Жалко только, что уже не смогу ходить также, как раньше. Бегать мне Нискигван вообще запретил. Но зато болезнь ушла из моих ног! Пусть Повелитель Жизни благословит ваш путь!}
{116}{}{Да так. Ноги уже не болят, но бегать я все равно не могу. Мне не хочется хромать, но это лучше, чем было раньше. Я вспоминаю это с ужасом, как те страшные видения, когда я случайно попробовал вечернее снадобье Аванигижига.}

#Лежит в беcсознании
{120}{}{Бедняга лежит в беcсознательном состоянии. Его кровавые распухшие ноги обвязаны тканью и целебной зеленью, а рядом дымится дурман-трава. Без операции он долго не протянет.}
{121}{}{Оставить в покое.}

{122}{}{Провести первичный осмотр.}
{123}{}{У мальчика механические повреждения костей и мышц, а также загноение и опухоль. Ему нужна срочная операция.}
{124}{}{Оценить срок жизни пациента в таком состоянии.}
{125}{}{Оценить свои шансы на лечение.}
{126}{}{Провести детальный осмотр.}

{127}{}{В условиях, которые поддерживает лекарь, мальчик может прожить довольно неопределенное время - от пары недель до полугода. Но в конце концов травма возмет свое.}
{128}{}{Ваши медицинские навыки неубедительны. Возможно, совместив свои умения с умениями более опытного лекаря, вам удалось бы чего-то добиться.}
{129}{}{Глядя на опухшие конечности, вы абсолютно уверенно можете сказать: "Да, я могу совершить чудо"... правда, с некоторой погрешностью.}
{130}{}{Глядя на опухшие конечности, вам даже не удается понять, где переломы. С вашими навыками здесь просто нечего делать.}
{131}{}{Лечение пациента до сих пор велось силами "народной" медицины, включающей обезболивающее, успокоительное, антисептическое и регенерирующее воздействие наркотических средств, таких как отвары из кореньев, цветков, мышиных фекалий и дымокуры. Это воздействие слишком слабое, его хватает лишь для поддержания жизни пациента в полуобморочном состоянии. Кости и ткани не срастаются до конца из-за загноения и воспаления. Таким образом, пациент все время находится в болезненном состоянии на грани жизни и смерти.}
{132}{}{Оценка набора необходимого медицинского инвентаря.}
{133}{}{В палатке лекаря есть некоторый примитивный инвентарь, но его не достаточно. Для лечения понадобится: скальпель либо другой острый предмет для хирургической операции, обезболивающее, аптечка или стандартный докторский набор, стимулятор для ускорения восстановления тканей, а также весьма внушительный уровень медицинских навыков.}
{134}{}{Подготовка пациента.}
{135}{}{Оставить пациента в покое.}

{136}{}{Едва ли лекарю понравится ваше самовольство. Пока он рядом, он не даст вам проводить операцию.}
{137}{}{Пока лекарь находится у костра, рассказывая байки детям, у вас есть около часа, чтобы провести операцию на основе своих, "цивилизованных", методик. Этого времени должно хватить.}
{138}{}{Я готов к операции. Приступим!}
{139}{}{Глядя на опухшие конечности, вам даже не удается понять, где переломы. Про проведение операции своими силами говорить не приходится.}
{140}{}{Макозид не зря таскался за вами по всей деревне. Он явно настроен прервать ваши попытки лечения.}

#Проверка медицинского снаряжения
{141}{}{Маконс может прийти в сознание во время операции. К счастью, у вас есть обезболивающее.}
{142}{}{Маконс может прийти в сознание во время операции. Но вам нечем его обезболить и лишить сознания.}
{143}{}{Далее.}
{144}{}{Прервать подготовку и оставить Маконса.}
{145}{}{В процессе понадобятся бинты, вата и прочие предметы первой медициской помощи. Все это есть в вашем докторском чемодане.}
{146}{}{В процессе понадобятся бинты, вата и прочие предметы первой медициской помощи. Все это есть в вашей аптечке.}
{147}{}{В процессе понадобятся бинты, вата и прочие предметы первой медициской помощи, которых у вас нет.}
{148}{}{Для заживления ран после операции придется также пожертвовать стимулятором из вашего рюкзака.}
{149}{}{Для заживления ран после операции придется также пожертвовать стимулятором... но у вас его нет.}
{150}{}{Для вскрытия также нужен острый режущий предмет. Как раз такой завалялся у вас в рюкзаке.}
{151}{}{Ну что ж, Маконс, держись. Пора показать костям, когда надо срастаться!}
{152}{}{Осталось найти острый режущий предмет для вскрытия.}
{153}{}{У вас есть все необходимое для операции и подходящие для этого условия, пока никто не видит. Самое время начинать!}
{154}{}{После и во время операции понадобится чистая вода для промывки ран и собственных рук.}
{155}{}{Чего-то не хватает для операции. Проверьте снаряжение еще раз, если действительно этого хотите.}
{156}{}{}
{157}{}{}

#Удачная операция
{170}{}{А... кто ты? Ты спаситель, посланный Небесной Матерью?}
{171}{}{Э... Ну, трудно сказать...}
{172}{}{Так, что вы де... О, Повелитель Жизни! Что натворил этот чужак?!}
{173}{}{Все хорошо, Взъерошенные Перья! Его прислала Небесная Мать, чтобы он вылечил меня! И он вылечил!}
{174}{}{Ну-ка посмотрим... о боже, да он сотворил чудо!}
{175}{}{Вы вылечили Маконса и получаете 10000 опыта и всеобщую любовь племени.}

#Неудачная операция
{180}{}{Так, что вы де... О, Повелитель Жизни! Что вы натворили?!}
{181}{}{Я хотел помочь, но... его болезнь была уже слишком запущена...}
{182}{}{Разве я разрешал!? Разве я просил!?}
{183}{}{А вас вообще надо было спрашивать? Он умирал, я пытался помочь!}
{184}{}{В следующий раз занимайтесь своими "благими" делами в другом поселении!}
{185}{}{А теперь убирайтесь из нашего стойбища и не возвращайтесь!}
{186}{}{Отныне ни один шайенн не станет вас здесь терпеть!}
{187}{}{Вы не смогли вылечить Маконса, но для вас это был отличный медицинский опыт (5000 опыта и +10 к навыку доктора).}

#Женские реплики (Kerb)
{1110}{}{Хау, мисс!}
{1112}{}{Рада была тебя видеть.}
{1113}{}{Вы сотворили чудо! Я теперь могу даже бегать! Честно! Вы такая же великая шаманка, как и Аванигижиг!}