{100}{}{Вы видите Живодера.}
{101}{}{Перед вами реднек, пасущий свое стадо. Хотя он больше похож на палача из-за грязного фартука и толстых оголенных рук.}
{102}{}{Эй, тот пастух убегает от вас!}

#Первый разговор
{110}{}{Так, ты все-таки меня нашел. Я ничего плохого не делал, просто вывел своих браминов на пастбище!}
{111}{}{Почему тогда бегаешь от меня?}
{112}{}{А, так ты не из этих тупорылых идиотов из Солт-Лейка? Ну, тогда не мельтеши здесь.}
{113}{}{А почему нет?}
{114}{}{Потому что эти края не в почете у жителей города, и тебе лучше не знать, почему.}
{115}{}{Ну как скажешь.}
{116}{}{Вот и отлично. Тогда я пойду заниматься своим стадом.}
{117}{}{Нет, постой. Кто живет в том большом отеле? Он заперт, но внутри явно живут люди.}
{118}{}{[Оставить]}

#Ответ, кто в отеле живет
{119}{}{Послушай, тебе лучше не знать этого, скиталец. Занимайся своими делами.}
{120}{}{Говори сейчас, сукин сын! Или потом тебе будет мешать сломанная челюсть!!!}
{121}{}{Я к ним по делу. По... *важному* делу. Думаю, ты меня понял.}
{122}{}{Ну и черт с тобой!}

{123}{}{Да ну?! Тогда я будущий шериф Солт-Лейка... В общем, оставь меня в покое!}
{124}{}{Уф... Ну, хорошо, твои проблемы. Подойди к калитке и позвони в звонок рядом, вот так: один короткий, затем один длинный звонок, затем опять короткий. Хозяин в дальней комнате, сразу к нему иди.}
{125}{}{Вот так бы сразу.}
{126}{}{А, черт! Хорошо, я скажу! Но это будут твои проблемы! Там живут изгои из Солт-Лейка. Они никому не доверяют, это отчаянные люди. Если очень надо, подойди к калитке и позвони в звонок рядом, вот так: один короткий, затем один длинный звонок, затем опять короткий. Хозяин в дальней комнате, сразу к нему иди. И оставь меня в покое!}

#Вторичные реплики
{127}{}{Опять ты? Не сказал бы, что это меня радует.}
{128}{}{У тебя есть вяленое мясо?}
{129}{}{Ага, пока.}
{130}{}{Все! А теперь отстань от меня!}
{131}{}{С удовольствием!}

#Женские реплики:
{1110}{}{Так, ты все-таки меня нашла. Я ничего плохого не делал, просто вывел своих браминов на пастбище!}
{1119}{}{Послушай, тебе лучше не знать этого, скиталица. Занимайся своими делами.}
