{100}{}{Вы видите сейф.}
{101}{}{Перед вами прочный настенный сейф с электронным замком.}
{102}{}{Взрыв не оставил и царапины.}

{105}{}{Вы уже взломали этот сейф.}
{106}{}{Это сложнее, чем вам могло показаться.}
{107}{}{Готово}
{108}{}{}
{109}{}{Вы успешно взламываете замок на сейфе.}
{110}{}{Вам не удалось взломать замок на сейфе.}
{111}{}{Тип отмычек не соответствует типу замка.}
{112}{}{Сейф заперт кодовым электронным замком.}
{113}{}{Заперто}