{100}{}{Подставка SoS.}
{101}{}{Вы видите устройство, через которое подключается комплект SoS.}

{102}{}{Вы уже забрали отсюда все, что было возможно.}
{103}{}{Ничего интересного}
{104}{}{Вы изъяли коробку с надписью "S.O.S." Теперь можно возвращаться в Город Убежища.}
{105}{}{Задача выполнена!}
{106}{}{Вы не сможете это сделать во время боя.}
