{100}{}{Перед вами огромные пустыри, где некогда разруливали военные самолеты. На западе виднеются строения.}
{101}{}{Вы вошли на территорию федеральной собственности. В довоенное время вас бы здесь расстреляли.}
{102}{}{Вы проникли в какой-то особенный ангар. Возможно, вы видите то, что полагалось видеть лишь избранным.}
{103}{}{Сильный взрыв разносит внутренности ангара, но корпус строения удержался от обрушения.}
{104}{}{Твоюжмать!!!}

{105}{}{Это место похоже на заправку для авиатехники. В тех баках наверняка осталось топливо.}
{106}{}{Эй! Да тут целый склад топлива!}
{107}{}{Какой здесь смрад...}
{108}{}{Отравляющий газ все еще присутствует в воздухе ангара.}
