{100}{}{Мерзейшего вида поселение, здесь нужно быть всегда начеку.}
{110}{}{Эй-эй, ты! Со стволом нельзя!}
{111}{}{Ты меня слышишь, а? Ствол, говорю, убери!}
{112}{}{Ты нарываешься?!}
{113}{}{Последнее предупреждение!}
{114}{}{ВНИМАНИЕ! ПРОТИВНИК!}

{115}{}{Вау! Вот это неожиданность!}
{116}{}{Теперь понятно, почему механик так яростно сторожит вход в гараж.}

{117}{}{Что это!?}
{118}{}{Эй! Кажется, из гаража около вокзала доносятся звуки мотора!}
