#Описания:
{100}{}{Вы видите сейф.}
{101}{}{Это ваш личный ящик для хранения вещей.}
{102}{}{Перед вами сверхпрочный сейф, который можно использовать для хранения вещей.}
{103}{}{Вы видите свой личный сейф.}

#Юзанье:
{105}{}{Только не во время боя!}
{106}{}{Удар не оставил и следа на таком сверхпрочном сейфе.}

#Начало взлома
{107}{}{У этого сейфа механический замок, состоящий из пяти затворов, каждый из которых управляется собственным числом. Вы могли бы попытаться подобрать код, но этот процесс может отнять некоторое время.}
{108}{}{Подобрать код.}
{109}{}{Не сейчас.}

{110}{}{Выставите первую цифру кода.}
{111}{}{Выставите вторую цифру кода.}
{112}{}{Выставите третью цифру кода.}
{113}{}{Выставите четвертую цифру кода.}
{114}{}{Выставите последнюю, пятую, цифру кода.}
{115}{}{0}
{116}{}{1}
{117}{}{2}
{118}{}{3}
{119}{}{4}
{120}{}{5}
{121}{}{Оставить замок в покое.}

#Результаты взлома
{122}{}{Вы выставляете значение и слышите очень тихий щелчок.}
{123}{}{Вы выставляете значение и слышите обычный щелчок.}
{124}{}{Вы выставляете значение и слышите четкий щелчок.}

{125}{}{Ввести следующее значение.}
{126}{}{Попытаться открыть.}
{127}{}{Бросить это дело.}

{128}{}{Все введенные вами значения оказались верны. Вы поворачиваете ручку, и дверца открывается!}
{129}{}{За взлом замка вы получаете 500 опыта и возможность пользоваться личным сейфом.}
{130}{}{Завершить.}

{131}{}{Вы поворачиваете ручку двери и слышите, как }
{132}{}{ затвора сходят с места и возвращаются обратно. Замок остался закрытым. Иначе говоря, вам удалось подобрать }
{133}{}{ верных значения из пяти.}
{134}{}{Попытаться еще раз.}
{135}{}{Увы, ни одно из введенных вами значений не было верным.}
{136}{}{Вы поворачиваете ручку и слышите, как один затвор сходит с места и возвращается обратно. Замок остался закрытым. Иначе говоря, вам удалось подобрать одно верное значение из пяти.}
{137}{}{За сверхскоростной взлом замка вы получаете 700 опыта и возможность пользоваться личным сейфом.}

#Бонус при достижении "Медвежатник"
{138}{}{Внимательно взглянуть на истертые цифры кодового замка.}
{139}{}{Довольно отчетливо видно, что некоторыми кнопками пользовались наиболее часто. Это значения }
{140}{}{ и }
{141}{}{ соответственно.}
