{100}{}{You see a ghoul.}
{101}{}{You see a local resident.}

#Первый разговор
{110}{}{Whoa, welcome to resplendent Vegas, wanderer!}
{111}{}{Vegas? Dude, it's just a junkyard!}
{112}{}{Vegas? Oh, yeah, sounds great.}

{113}{}{What you see around you is Vegas, just take a look! Isn't it beautiful?}
{114}{}{You're a raving lunatic, buy I don't give a shit. Do you have any tires for my wheels?}
{115}{}{Oh yes. Beautiful indeed. Tell me, do you by any chance have tires for my wheels?}

{116}{}{Of course... not.}
{117}{}{Uh... No? Really? Well, what's that lying around in heaps then dammit?!}
{118}{}{Hah, my dear friend, why would anyone dump good tires in a *junkyard*? If they were of any use, they wouldn't be thrown away!}
{119}{}{Hmm...}

{120}{}{But what I do have for your wheels are these here hands, and some nifty gizmos to go with them... That is, if you really got any wheels.}
{121}{}{What are you talking about?}
{122}{}{No, I was only looking for tires. Take care.}
{123}{}{You're just crazy. What can you make out of junk, other than some other junk!?}
{124}{}{I'm not crazy, I'm full of ideas! These two are often confused, so don't feel bad about that. You see, I might be the last engineer on this godforsaken planet!}
{125}{}{Oh... What exactly are you offering?}
{126}{}{You got a ride? Oh, I see you do. Well... it's rather primitive, but I still got the itch to do some things to it. Just pick from the list of options!}
{127}{}{You got a ride? Oh... pity you don't. See, I got this itch for engineering!}
{128}{}{Great, let's perform an inspection.}
{129}{}{I'm not interested in all that right now. What I am interested in is this Chryslus Motors catalog. Can you say anything about it?}

{130}{}{Huh, the car ain't exactly brand new, is it? When it drove off Chryslus factory, I was probably still crapping in my pants. Yeah, those were the days... Now, what do you want me to do - powerful headlights, fuel cell regulator, bigger trunk, huh?}
{131}{}{Tell me about headlights.}
{132}{}{Tell me about that fuel thingie.}
{133}{}{Tell me about the trunk.}
{134}{}{I don't need any of these.}

{135}{}{A couple of massive halogen lamps on your hood are never out of fashion. It's not too comfortable driving at night when there's no roads anymore, don't you agree? I could install them, no sweat. The question is what will I have in return.}
{136}{}{Oh yes, I'd like that!}
{137}{}{Not now. What else did you say you could do?}
{138}{}{Your car eats up loads of fuel and half of the energy goes heating up the wasteland? Oh yeah, I know how it feels! And I also know how to make it stop draining your batteries like a short fuse. The question is only what will I get in return.}
{139}{}{That'll take some work, but I could do it. Your trunk is quite roomy, and you could fit a dozen or so debtors in there all their gear included, but sometimes it's just still not enough, am I right? A leather tent will let you stuff about 20% more loot in there. But you'll have to motivate me, if you know what I mean.}
{140}{}{Hmm! I didn't have to read in quite a long while. I wouldn't remember the letters, but if you read it to me, I'll try to make some use of it.}
{141}{}{Great, let's do that.}
{142}{}{Just like that? No, no, I got to have a hot meal and wet my whistle first. My head doesn't work right on an empty stomach.}
{143}{}{Whatever.}
{144}{}{Wait a little then - we'll talk about it later.}

{145}{}{You changed your mind yet? Too bad!}
{146}{}{Tell me about your car options again.}
{147}{}{Maybe. But I'm going away anyway.}
{148}{}{Oh yes, that should be enough! Go warm yourself up by that barrel while I finish working on this baby...}
{149}{}{Just be careful, alright?}
{150}{}{Holy Chryslus! It works! I can't believe this!}
{151}{}{What, really?}
{152}{}{Job's done! The pick-up will now use energy more efficiently.}
{153}{}{Now your car lights its way with new headlights.}
{154}{}{This tent will serve you good, increasing your trunk's capacity by about }
{155}{}{Hmm...}
{156}{}{[-more-]}
{157}{}{%.}

{158}{}{Okay, what do you want?}
{159}{}{What snacks and booze have you got?}
{160}{}{[Look for liquor in your backpack]}
{161}{}{[Look for food in your backpack]}
{162}{}{Nothing like that. I'll go get some.}
{163}{}{Forget it. What did you say about my car?}
{164}{}{You already had as much as a deathclaw couldn't eat in a week. I dare you motherfucker, ask me for food once again!}
{165}{}{Hey, easy, buddy! I might have pushed it a little too far, I don't deny it. Well who wouldn't? Oh, don't give me this look.}
{166}{}{Shut your blowhole and get down to work.}
{167}{}{Articles on "Chryslus Motors" vehicles proved to be quite useful. You got some tips on increasing your car's speed and maximum carried weight.}
{168}{}{Need anything else?}
{169}{}{Forget about food. Lets talk about my car.}
{170}{}{You'll have to deal with it. Bye.}

{171}{}{[Give beer]}
{172}{}{[Give booze]}
{173}{}{[Give RotGut]}
{174}{}{[Give "Bloody Mary"]}
{175}{}{(Waits in anticipation)}

{176}{}{[Give sandwich]}
{177}{}{[Give pizza]}
{178}{}{[Give meat jerky]}
{179}{}{[Give iguana bits]}
{180}{}{[Give fruit]}

{181}{}{Oh yeah! It's always good to snatch a bite before work. Even if it's not much, right?}
{182}{}{Wait, you mean it wasn't enough for you?}
{183}{}{Oh yeah! Some fuel in the system - just what a mechanic needs, right? Well, at least for starters.}
{184}{}{Won't you burn up from this much "fuel"?}
{185}{}{You're still not full?!}

{186}{}{Oh yeah, that's a hell of a ride.}
{187}{}{You bet...}

{190}{}{Oh, yeah... }
{191}{}{I see your headlights are shining like the sun out of your ass.}
{192}{}{You don't need a new regulator - the one you got should serve you fine for a many a mile yet.}
{193}{}{Well apparently you don't need a better trunk. What a pity. }
{194}{}{So what do you want?}

#Женские реплики (Rekrut)
{1110}{}{Whoa, welcome to resplendent Vegas, precious!}
{1145}{}{You changed your mind yet, darling? Too bad!}
{1164}{}{You already had as much as a deathclaw couldn't eat in a week. I dare you motherfucker, ask me for food once again!}
{1165}{}{Hey, easy, darling! I might have pushed it a little too far, I don't deny it. Well who wouldn't? Oh, don't give me this look..}

