{100}{}{Вы видите шайенна-охотника.}

{101}{}{Да будет солнце смотреть в спину всем путникам!}
{102}{}{Что вы ищете в этих краях?}
{103}{}{Пути наши расходятся, дитя скитаний.}
{104}{}{May your travels be without pain.}
{105}{}{Да пребудет с тобой сила Духа Пустошей!}
{106}{}{Не пей из ручья.}
{107}{}{Наши духи с тобой не говорят.}