{100}{}{You see a stranger.}
{101}{}{You see a strange creepy man.}
{102}{}{A real giant, he probably has people like you for breakfast.}
{103}{}{?}
{104}{}{Who the hell are you people?!}
{105}{}{I don't answer questions, wanderer. I've come to warn you.}
{106}{}{About what?}
{107}{}{Dam! How did you... from a distance...}
{108}{}{There will be no second warning. Abandon your quest, or you will follow the fate of other pure souls.}
{109}{}{Looks like it was an ambush!}
{110}{}{"Pure souls"? What the hell are you babbling about?!}
{1105}{}{I don't answer questions, wanderer. I've come to warn you.}