{100}{}{You see BlackDesigner.}
{101}{}{You see an ordinary designer, like any other.}

{110}{}{Decided to drop by? Good!}
{111}{}{There are all kinds of shit in the wasteland.}
{112}{}{I'd travel myself, but not with an empty wallet.}
{113}{}{I have to work for food.}
{114}{}{Who wants to lend me two million for my project?}
{115}{}{Some petty two million!}
{116}{}{All right, forget I asked...}
{117}{}{There'll be no sequel. I think you've figured that out by now.}
{118}{}{What am I working on now? It's funny, I'm working on... you!}
{119}{}{Nooo, no, no! I don't have any kind of liquor here.}
{120}{}{Hmm, so *this* is the way you want to roleplay?... Well, it's up to you after all.}
{121}{}{Are you one of those who don't like to read much text too?}
{122}{}{If I called the whole team here, there'd be no room to swing a cat. Sorry.}
{123}{}{The "I know" kid? Don't mind him. He was not the first and certainly he won't be the last.}

{200}{}{You think poking me repeatedly with this thing will get you somewhere?}
{201}{}{Hmm, from your persistence I can tell you think it will result something useful!}
{202}{}{Yes, I know, you expect me to give you some kind of super-dooper device. Sorry to ruin your expectations, but this isn't happening.}
{203}{}{What else would you like me to do? Beat the game for you?}
{204}{}{Yes, go on, I still can't bring myself to break it to you...}
{205}{}{What, you like poking a man with an arrow so much? But what wouldn't you do for a gift, right?}
{206}{}{Yes, right! Almost there!}
{207}{}{Sure. You earned it. I'll go get it now... no, wait. Not yet.}

{210}{}{Damn, so much time and effort for some uber device? A round of applause is in order, I just have to reward you somehow now. Here, a limitless source of experience... well, as long as you got the nerve.}
{211}{}{[Leave]}
{212}{}{I think I've said it all.}