{100}{}{You see a rough-looking person.}
{101}{}{You see a raider.}

{200}{}{You tresspass into our lands. Now you die!}
{201}{}{How dare you come here uninvited!}
{202}{}{Die, city walker!}
{203}{}{Your death should bring me some money.}
{204}{}{Flee before me, puny one!}
{205}{}{You know the drill, gentlemen.}
{206}{}{No witnesses.}
{207}{}{Cover me.}
{208}{}{No mercy!}
{209}{}{The man says no survivors.}
{210}{}{Boss says no trespassing.}
{211}{}{Let's get paid!}