{100}{}{You see a dirty, unshaven man.}
{200}{}{You see a dirty, haggard woman.}
{101}{}{Trapper.}
{102}{}{Best not get too close. Some of the critters in his clothes might be looking for a cleaner
 home.}
{103}{}{Howdy. Don't come across people too often out here in trapper country. Whatcha want?}
{104}{}{Do you have any gecko pelts for sale?}
{105}{}{Just passing through.}
{106}{}{}
{107}{}{Well, I reckon I might be able to sell ya my pelts. It'll save me the trouble of going into
 town.}
{108}{}{What do you have?}
{109}{}{Never mind.}
{110}{}{}
{111}{}{Here's what I got:}
{112}{}{regular gecko pelts.}
{113}{}{golden gecko pelts.}
{114}{}{I'll take all you got.}
{115}{}{Maybe next time. Bye.}
{116}{}{Nice doing business with ya. See you around.}
{117}{}{Bye.}
{118}{}{}
{119}{}{}
{120}{}{Seems you're short on cash. Tell you what, I've been in these woods for a LONG time, if you
 catch my drift. I'll make it worth your while.}
{121}{}{Sure.}
{122}{}{Not a chance. Bye.}
{123}{}{}
{124}{}{}
{125}{}{[You feel dirty in more than one sense of the word - but you got some gecko pelts.]}
{126}{}{Bye.}
{127}{}{[He holds up his right hand and says] How. Me mighty trapper. Hunt big geckos. Me no mean
 trespass on your land. Leave peacefully. [He hands you a gecko pelt as a gift.]}
{128}{}{[END]}
{129}{}{I've got no more business with you.}
{130}{}{Yellow bellied sapsucker!}
{131}{}{This is my hunting territory. Leave!}
{132}{}{I'll skin you alive!}
{133}{}{I'm gonna use your head as a trophy.}

{134}{}{One regular gecko pelt: $}
{135}{}{One golden gecko pelt: $}

{136}{}{OK, warden. You win.}
{137}{}{Lucky for you, I have to go check my traps.}
{138}{}{I think I hear Mom callin' me.}

#Женский вариант.
{10102}{}{Best not get too close. Some of the critters in her clothes might be looking for a cleaner
 home.}
{10136}{}{OK, lady. You win.}
{10137}{}{Lucky for you, I have to go check my traps.}
{10138}{}{I think I hear Mom callin' me.}
