{100}{}{You see a security console.}
{101}{}{You see a plant's security system remote command input console.}
{102}{}{You'll have to use scientific approach to activate the console.}

{103}{}{You have already disabled security system.}
{104}{}{No go}
{105}{}{You have hacked and disabled security system.}
{106}{}{Your scientific knowledge is insufficient to hack this console.}
{107}{}{Can't do}
{108}{}{That's better!}
{109}{}{You failed to hack security system this time.}
{110}{}{Failure}
{111}{}{}
{112}{}{Security system does not respond.}
{113}{}{No signal}