{100}{}{You see a crane.}
{101}{}{You see a rusted out crane. Don't expect much.}
{102}{}{The chain is in no condition to be used. You'll have to replace it with something similar.}
{103}{}{This crane could probably serve some more, but it has no chain.}
{104}{}{You replaced the chain with a rope. Should be enough for light loads.}
{105}{}{You've already replaced the chain.}
{106}{}{You don't need it anymore. Leave it rust in peace.}
{107}{}{Using he crane you've erected a garbage pyramid by the garage wall.}
