{100}{}{You see a garage door.}
{101}{}{You see a massive garage door with no visible locks.}
{102}{}{You can't knock out such a massive door.}
{103}{}{You can't pick the lock, because the door is locked from inside.}
{104}{}{You can't pick the lock because there's no lock.}
{105}{}{You dismount the bolt. The way is clear.}
{106}{}{The door is bolted from the inside. You can't open it from here.}
{107}{}{Locked from inside}
{108}{}{You see a massive garage door.}
