{100}{}{You see a slot machine.}
{101}{}{This slot machine isn't working. You wonder if there might be some change left inside.}

#Использование навыков и пр. на автомате:
{102}{}{You can't do anything with bare hands.}
{103}{}{This slot machine isn't working. How do you expect to gamble?}
{104}{}{}
{105}{}{You couldn't pick the right lockpicks to force the slot machine.}
{106}{}{You take a good swing and kick the rusted casing off. Now all the change belongs to you.}
{107}{}{Using the proper tools it's no trouble for you to open the machine and pocket the change.}
{108}{}{You were unable to kick the lid off this thing.}
{109}{}{The rusty lock on this machine presents no challenge. All the change belongs to you now.}

#Когда взломал автомат:
{110}{}{Yeah, just like that!}
{111}{}{Take it, baby!}
{112}{}{Take it, babe!}
{113}{}{Ha-ha!}
{114}{}{Some pocket money, huh.}
{115}{}{Hey, there's still some change left in here!}
{116}{}{Boy, is it satisfying!}
{117}{}{That's better!}
{118}{}{Kiss my ass! I did it!}
{119}{}{Now I'm rich!}

{120}{}{You've already forced this slot machine and cleared it of all change. There's nothing left.}
{121}{}{No use}
{122}{}{This slot machine hasn't been working for ages. You can't do anything with your bare hands here.}
{123}{}{You can't do anything with this.}
{124}{}{You found }
{125}{}{ bucks.}

#Женские реплики:
{1110}{}{Yeah, just like that!}
{1111}{}{Take it, baby!}
{1112}{}{Take it, babe!}
{1113}{}{Ha-ha!}
{1114}{}{Some pocket money, huh.}
{1115}{}{Hey, there's still some change left in here!}
{1116}{}{Boy, is it satisfying!}
{1117}{}{That's better!}
{1118}{}{Kiss my ass! I did it!}
{1119}{}{Now I'm rich!}
