{100}{}{It's a switch.}
{101}{}{You see the switch that switches on the lights in the hangar... or switches off, whichever you prefer.}
{102}{}{You switch on hangar lights.}
{103}{}{You switch off hangar lights.}

{104}{}{Electric field hurts you!}

{105}{}{Ничего не происходит. Видимо, в ангар не поступает электричество.}

{110}{}{Уф... Надеюсь, до включателя освещения я доберусь быстрее, чем сломаю себе ноги в темноте.}
{111}{}{Похоже, что в этом подземном ангаре обслуживали различную военную технику.}