{100}{}{Вы видите качка.}
{101}{}{Вы видите здоровенного мускулистого качка.}

{110}{}{*grins at you toothlessly*}
{111}{}{*почесывает голову*}
{112}{}{*делает приседания*}
{113}{}{*рычит*}
{114}{}{Хфффф}
{115}{}{Грррр}
{116}{}{*Разминает руки*}
{117}{}{Угу.}
{118}{}{Отвали!}
{119}{}{Жрать хочу, мочи нет...}
{120}{}{*Чешется*}
{121}{}{*Ворчание*}
{122}{}{Э-эрр}
{123}{}{Уффф}
{124}{}{Хррр}
{125}{}{Эххх}
{126}{}{Гррр}
{127}{}{О-оп}

{128}{}{Лучше от меня отстать}
{129}{}{*eyes your head like a punching bag*}
{130}{}{Шлушаю?}
{131}{}{Тебе нужен тренер?}
{132}{}{*Глупо кивает в ответ на каждое ваше слово*}

# boxing boxers messages

# punch
# hit noise
{300}{}{Ernhhh}
{301}{}{Unfff}
{302}{}{Hrghhh}
{303}{}{Nfff}
{304}{}{Hrggg}
{305}{}{Ooof}

# dodge
{310}{}{Too slow!}
{311}{}{Not the face!}
{312}{}{You punch like my grandmother!}
{313}{}{No hitting below the belt!}
{314}{}{You ain't bad.}
{315}{}{Dat all you got?}

# knock down
{320}{}{And stay down!}
{321}{}{You got knocked da fuck out!}
{322}{}{Who's your Daddy?}
{323}{}{If he dies, he dies.}

{330}{}{Coulda been a champ!}
{331}{}{How could such a... geggghhh...}
{332}{}{*Huuuuurrrrllllll*}
{333}{}{Ooo, care bears...}
{334}{}{I think I'll just lay here for a little while.}
{335}{}{No pain, no pain, no pain...}

# punching
{340}{}{Eat this!}
{341}{}{You want some of this?!}
{342}{}{Bitch!}
{343}{}{Now you're mine.}
{344}{}{I eat green berets for breakfast.}
{345}{}{Haadookin.}
{346}{}{Now you DIE.}
{347}{}{SUPER... NUCLEAR... TORNADO... FIST...}

# taunt
{350}{}{Adrian! Adrian!}
{351}{}{You're going down!}
{352}{}{Make you a bitch...}
{353}{}{I must break you.}
{354}{}{You're fighting like a bum!}
{355}{}{You got no guts!}
{356}{}{You're a bum! A bum!}
{357}{}{Gonna beat you like a dog...}

# corner
{360}{}{Ain't gonna be no rematch!}
{361}{}{Hit like a butterfly...}
{362}{}{Keep your hands up...}
{363}{}{Stay sharp!}
{364}{}{Fight past that shit!}
{365}{}{Get critical!}
{366}{}{Cut me, Mick.}
{367}{}{Remember, stick the jab!}
{368}{}{I see three of 'em!}