{100}{}{You see a swole guy.}
{101}{}{You see a humongously swole person.}

{110}{}{*grins at you toothlessly*}
{111}{}{*scratches head*}
{112}{}{*does situps*}
{113}{}{*growls*}
{114}{}{Uhhhh}
{115}{}{Gurrrr}
{116}{}{*flails his arms*}
{117}{}{Uh-huh.}
{118}{}{Back off!}
{119}{}{I'm starving to death...}
{120}{}{*Scratches*}
{121}{}{*Groans*}
{122}{}{Errrm}
{123}{}{Uhhh}
{124}{}{Hurrr}
{125}{}{Ehhh}
{126}{}{Gurr}
{127}{}{Whoa}

{128}{}{You better leave me alone}
{129}{}{*eyes your head like a punching bag*}
{130}{}{Lithenin'?}
{131}{}{You need a coach?}
{132}{}{*Nods numbly to your every word*}

# boxing boxers messages

# punch
# hit noise
{300}{}{Ernhhh}
{301}{}{Unfff}
{302}{}{Hrghhh}
{303}{}{Nfff}
{304}{}{Hrggg}
{305}{}{Ooof}

# dodge
{310}{}{Too slow!}
{311}{}{Not the face!}
{312}{}{You punch like my grandmother!}
{313}{}{No hitting below the belt!}
{314}{}{You ain't bad.}
{315}{}{Dat all you got?}

# knock down
{320}{}{And stay down!}
{321}{}{You got knocked da fuck out!}
{322}{}{Who's your Daddy?}
{323}{}{If he dies, he dies.}

{330}{}{Coulda been a champ!}
{331}{}{How could such a... geggghhh...}
{332}{}{*Huuuuurrrrllllll*}
{333}{}{Ooo, care bears...}
{334}{}{I think I'll just lay here for a little while.}
{335}{}{No pain, no pain, no pain...}

# punching
{340}{}{Eat this!}
{341}{}{You want some of this?!}
{342}{}{Bitch!}
{343}{}{Now you're mine.}
{344}{}{I eat green berets for breakfast.}
{345}{}{Haadookin.}
{346}{}{Now you DIE.}
{347}{}{SUPER... NUCLEAR... TORNADO... FIST...}

# taunt
{350}{}{Adrien! Adrien!}
{351}{}{You're going down!}
{352}{}{Make you a bitch...}
{353}{}{I must break you.}
{354}{}{You're fighting like a bum!}
{355}{}{You got no guts!}
{356}{}{You're a bum! A bum!}
{357}{}{Gonna beat you like a dog...}

# corner
{360}{}{Ain't gonna be no rematch!}
{361}{}{Hit like a butterfly...}
{362}{}{Keep your hands up...}
{363}{}{Stay sharp!}
{364}{}{Fight past that shit!}
{365}{}{Get critical!}
{366}{}{Cut me, Mick.}
{367}{}{Remember, stick the jab!}
{368}{}{I see three of 'em!}