{100}{}{Tribal woman.}
{101}{}{One of the Cheyenne tribe's women working in the field.}

#Толкание
{102}{}{Awrite.}
{103}{}{I move.}
{104}{}{No need be rude.}
{105}{}{Sky Mother protect me!}
{106}{}{Don push!}
{107}{}{You be glad my husband don see it!}
{108}{}{Go push gecko!}
{109}{}{Push me one more time - regret it!}
{110}{}{I scratch you eyes out!}

{111}{}{Help!!!}

#Попытка заговорить
{112}{}{Me no talk.}
{113}{}{Me watch crops and kids.}
{114}{}{Me no chatting.}
{115}{}{Me just wife.}

#Попытка заговорить под действием химии или алкоголя
{116}{}{What have you eat?}
{117}{}{You awrite fren?}
{118}{}{Where you look?}
{119}{}{Me no like it. Goway!}