{100}{}{You see a look-out.}
{101}{}{You see a raider patroling the street.}

#Когда подбегает, что бы арестовать:
{110}{}{Стоять!}
{111}{}{Будешь рыпаться - завалю!}
{112}{}{Эй, ты! Ни с места!}
{113}{}{Куда!?}
{114}{}{Стоять, я сказал!}
{115}{}{Даже не пытайся свалить!}
{116}{}{Руки за голову, это арест!}

#Если ГГ в одежде рейдера:
{120}{}{The look-out spotted you, but didn't recognize you in disguise.}
{121}{}{Hey, Roge, is that you?}
{122}{}{Hey, hold it! Who is this? Oh, it's just you.}
{123}{}{Hey you, in the jacket, who are you?}
{124}{}{Who goes there? Roge, is that you?}
{125}{}{Roge, is that you? Out to throw up again, huh?}

#Когда поймал ГГ:
{150}{}{Стоять! Замерзни на месте! Будешь рыпаться - завалю!}
{151}{}{Эй-эй, полегче! Уже никто никуда не рыпается...}
{152}{}{Только дотронься - и ты умрешь.}
{153}{}{Так-так. Посмотрим, что отвалит за тебя босс. Руки опусти, чтобы я их видел! Теперь иди вперед. И не вздумай меня одурачить. Я таких уже десяток положил.}
{154}{}{Ладно, веди меня к своему боссу. Я буду вести себя мирно.}
{155}{}{[Напасть на рейдера]}
{156}{}{Заткнись! Не долго тебе трепаться осталось. Повторяю последний раз, дернешься - убью.}
{157}{}{Ладно-ладно, я больше не буду рыпаться.}
{158}{}{Сам заткнись!}
{159}{}{}

#Когда Плесень сдох:
{160}{}{Здорово}
{161}{}{Seen the body in those ruins across from the base?}
{162}{}{Bye.}
{163}{}{That's Rot. He OD'd. So we threw him out before he started to smell. Самое интересное - не понятно, где он дозу брал. Мы его не снабжали.}
{164}{}{I see...}

# Когда враждебен, видит и нападает:
{200}{}{Hey you!!!}
{201}{}{Waste this bitch!!!}
{202}{}{Let's get it over with this motherfucker!}
{203}{}{Do you wanna be gutted or falyed?!}
{204}{}{Let's dance, baby!}
{205}{}{Time to make you cry.}
{206}{}{Hold still while I gut you, will ya?}

# Разговаривает сам с собой:
{207}{}{Nobody...}
{208}{}{I wish there was some action...}
{209}{}{So sick of walking in circles here...}
{210}{}{Сейчас бы завалиться на матрас}
{211}{}{Why am I even doing this?}

# Когда не враждебен: 
{212}{}{Great.}
{213}{}{All's quiet.}
{214}{}{Ain't seen nobody.}
{215}{}{Ain't nobody comin' through here!}
{216}{}{Nothing to say, really.}
{217}{}{I'm on watch.}
