{100}{}{Frenzied raider.}
{101}{}{It's your first adversary on the raiders' ring.}

{102}{}{AAAH!!! SWEET PAIN!!!}

{103}{}{Is that all you got?}
{104}{}{You mah bitch!}
{105}{}{I fuck your mother!}
{106}{}{Let it bleed! *squeaks*}
{107}{}{Guys, help me up with this piece of shit!}
{108}{}{You're not sick, are you, buddy? Cause I'm about to eat yer liver and wash it down with a good gallon of yer blood!}
{109}{}{God damn...}

{110}{}{AAAH!!! SEE YOU IN HELL!}


{113}{}{Come out, sissie! Let's have some fun!}
{114}{}{I'll shred you into pieces!}

#Импорт, общее: ловушки:
{200}{}{Hey! What the hell are you doing over there?!}
{201}{}{You've been spotted.}

{202}{}{Mommie!!! Mommie!!!}
{203}{}{Shoo!!!}
{204}{}{Faster!!!}
{205}{}{Help!!!}
{206}{}{Aaaah!!!}
{207}{}{It's a bomb!!!}
{208}{}{Mean outsider!!!}

{210}{}{Children disperse at the sight of your dubious trinkets.}

#Женские реплики
{1108}{}{You're not sick, are you, missy? Cause I'm about to eat yer liver and wash it down with a good gallon of yer blood!}