{100}{}{You see a spectator.}
{101}{}{You see a dirty drunk and/or high raider, who only needs this spectacle to feel complete.}

#Выкрики при получении урона
{102}{}{Dammit!}
{103}{}{What, can't wait to die or something?!}
{104}{}{Come on, you people!}
{105}{}{A-a-ah!}
{106}{}{Ah, pain is beautiful!}
{107}{}{Pain sweet pain!}
{108}{}{Goddammit!}
{109}{}{You little...}
{110}{}{Guess what I did with your mom!}
{111}{}{God fucking...}
{112}{}{Wait till I get to you...}
{113}{}{Just you wait!!!}

#Выкрики во время боя ГГ на ринге
{114}{}{Вали клоуна!}
{115}{}{Oh, come on!}
{116}{}{Waste this punk!}
{117}{}{* yells *}
{118}{}{Уворачивайся!}
{119}{}{В ухо ему! В ухо!}
{120}{}{Punch him! Right in the jaw!}
{121}{}{Смотри, что творит!!!}
{122}{}{Wow, have you seen that?}
{123}{}{Это было жестко!!!}
{124}{}{* yells *}