{100}{}{You see a redneck.}
{101}{}{You see one of the few Provo residents.}
{102}{}{Trespasser!}

{103}{}{We don't take kindly to your kinds round here...}
{104}{}{Want me to kick the shit out of you?}