{100}{}{You see Flayer.}
{101}{}{You see a hick looking after his herd. His appearance resembles that of an executioner with his filthy apron and massive bare arms.}
{102}{}{Hey, that shepherd is running away from you!}

#ѕервый разговор
{110}{}{So, ya got me huh. I ain't done nothin' wrong, just tendin' mah brahmins, is all!}
{111}{}{Then why the hell were you running away?}
{112}{}{Oh, so yer not one of them Salt Lake fools? Well then ya better not be pokin' about here.}
{113}{}{Why not?}
{114}{}{Cause town folks don't much appreciate these parts, and yer better off not knowin' why.}
{115}{}{Whatever.}
{116}{}{All righty then. I'll get back to mah herd.}
{117}{}{Wait a sec. Who lives in that grand hotel? The doors are locked, but it's clearly inhabited.}
{118}{}{[Leave]}

#ќтвет, кто в отеле живет
{119}{}{Listen, ya really don't want to know, buddy. Ya better mind yer own beeswax, if you want my advice.}
{120}{}{Leave me alone!}
{121}{}{}
{122}{}{}

{123}{}{Oh yeah?! Than I am the Salt Lake sheriff... Leave me alone!}
{124}{}{Ugh... All right, but don't come a-whinin' I ain't warned ya. Come to the gate and ring the bell this way: one short, one long and one short. The Boss is in the backroom, go straight to him.}
{125}{}{Now that's better.}
{126}{}{All right, I'll tell ya! But that's gonna be your problem since! Salt Lake outcasts live there. They are a desperate bunch and trust no one. If you really need to get in, come to the gate and ring the bell this way: one short, one long and one short. The Boss is in the backroom, go straight to him, don't talk to nobody else. Now leave me alone!}

#¬торичные реплики
{127}{}{Yer here again? Boy, am I not glad to see ya.}
{128}{}{Got any meat jerky?}
{129}{}{Yeah, bye.}
{130}{}{That's it. Now leave me alone!}
{131}{}{With pleasure!}

{132}{}{Говори сейчас, сукин сын, или потом тебе будет мешать сломанная челюсть!}
{133}{}{Я дам тебе сотню баксов за возможность контакта.}
{134}{}{Почему бы не сказать по-хорошему? Давай же, смелей, это останется между нами.}
{135}{}{Я здесь не для того, чтобы в прятки с ними играть. Мне нужно поговорить с главным.}
{136}{}{Возможно, мы с ними найдем общий язык. Уж я-то знаю, как это делается.}

#∆енские реплики:
{1110}{}{So, ya got me huh. I ain't done nothin' wrong, just tendin' mah brahmins, is all!}
{1119}{}{Listen, ya really don't want to know, sugar. Ya better mind your own beeswax, if you want my advice.}

