{100}{}{Moonshine still.}

{101}{}{You see a still. It has already distilled a whole can of moonshine!}
{102}{}{You see a still. The brew in it isn't ready yet.}
{103}{}{You see a still. Abandoned and useless.}

{104}{}{The still is empty.}
{105}{}{Empty}
{106}{}{That's not for you! Don't try Jackson's patience while he's near you.}
{107}{}{Вот только похимичь еще - и у тебя будут проблемы!}
{108}{}{Done!}
{109}{}{You've expropriated a couple of bottles of booze.}
{110}{}{You've boldly stolen a couple of bottles of booze.}

{111}{}{The moonshine hasn't been distilled yet. Wait a couple of hours.}
{112}{}{Hey! You shitheads! Which one of you's been chugging my booze? If I ever catch any of you at it, I'll rip your fucking arms off!}