{100}{}{You see a generator.}
{101}{}{You see an ordinary generator. judging from the markings, it's responsible for the station's automatics.}

{102}{}{The generator is in poor condition, but it can be repaired.}
{103}{}{Needs repairs}
{104}{}{ exp. points.}
{105}{}{The generator is in working condition and supplies power to the station.}
{106}{}{No use}
{107}{}{The generator's running and doesn't need any repairs.}
{108}{}{You repair the generator and it begins to produce a humming sound. You gain }
{109}{}{Done}
{110}{}{This won't be of any use here. The generator needs repairs.}
{111}{}{You fail to repair the generator.}
{112}{}{Fail}