{100}{}{You see a generator.}
{101}{}{You see an ordinary generator. Judging from the markings, it's responsible for central equipment power supply.}

{102}{}{Видимо, муравьи повредили этот генератор, но его еще можно починить.}
{103}{}{Требуется ремонт}
{104}{}{}
{105}{}{The generator is operational and supplies power to the station.}
{106}{}{No use}
{107}{}{The generator is running and does not require repair.}
{108}{}{Вы ремонтируете генератор. Теперь он обеспечивает электричеством сервер станции.}
{109}{}{Done}
{110}{}{This won't be any good here. The generator needs repair.}
{111}{}{You fail to repair the generator.}