{100}{}{Cabbage head.}
{101}{}{A huge cabbage head that would make for a good salad.}

{102}{}{Delicious greens! Add some brahmin meat and you get a wholesome dinner.}
{103}{}{This vegetable would make for a nice dinner if you had some meat to go with it. But its owner will hardly like this idea of yours.}
{104}{}{Just like that!}
{105}{}{You ravaged the vegetable to make yourself a sandwich. Its owner probably won't like it when she finds out. You dirty thief!}