{100}{}{You see a drill sergeant.}
{101}{}{You see a platoon commander, its instructor and mentor.}

#Попытка заговорить
{102}{}{Civilians?! I have no time for this.}

#Когда бойцы отжимаются
{110}{}{Come on, ladies!}
{111}{}{Like that!}
{112}{}{One-two! One-two!}
{113}{}{Cut out the whining!}
{114}{}{I'll make men out of you, even if it kills you!}
{115}{}{Now with one hand!}
{116}{}{Now with no hands!}
{117}{}{No slacking, private!}
{118}{}{It's not how you do push-ups!}
{119}{}{Hey bone-bags! You'll be cleaning latrines for the rest of the day if you don't start trying this moment!}
{120}{}{Move it, move it!}

#Когда бойцы дерутся
{130}{}{Yes! With the left! Left!}
{131}{}{Before you stands the enemy!}
{132}{}{Anger! I don't see anger in your eyes!}
{133}{}{Grin! Show me your grin!!!}
{134}{}{Come on!!!}
{135}{}{Some of you still have a chance at becoming men!}
{136}{}{Talk about green berets!}
{137}{}{Arrrgh!!!}
{138}{}{Just like that!}
{139}{}{That's what I call a swing!}
{140}{}{Learn from me while I'm still around!}
{141}{}{*These*? Warriors?!}
{142}{}{*Tsk Tsk Tsk*}
{143}{}{*You'll take my life but I'll take yours too*}