{100}{}{You see an inmate.}
{101}{}{It's a criminal put behind the bars by the military.}

{102}{}{You saved the prisoner from death penalty.}
{103}{}{Dayum! That was neat! We did it! Ha-ha! I'm free! Thanks for your help, I owe you one. I'll be all right on my own now. By the way, if you're ever in Vegas, come find me. (winks)}
{104}{}{In Vegas? Ok.}
{105}{}{Shoosh! Not now!}
{106}{}{Don't sweat it. I'll be near.}

{110}{}{A new face, huh? Sweet!}
{111}{}{What are you in for?}
{112}{}{Nothing really.}
{113}{}{Really?}
{114}{}{Yes, goddammit! Of course! What did you think? Here in Wind of War the military are worse than raiders. They want everything for themselves, what they do is take away your money and weapons and then just kick you out, those bastards! Ughhh! (shouts at the door) You will fucking pay for this, you scumbags!!!}
{115}{}{So you're saying, they just stopped you and robbed you at gunpoint, is that how it was?}
{116}{}{No... well yes, but... I mean... Look, I'm here because I put up some resistance. Now they are preparing an execution. They want to make a show of it. Motherfuckers! I hate these pigs!}
{117}{}{Hmm, I'm not sure if I should believe you.}
{118}{}{Whatever! Use your fucking head! They just took your stuff and put you in here, for them you're nothing but dirt under their feet. Think it over, you got some time still. While I'll be executed in several days...}
{119}{}{Hmm...}

{120}{}{So, what do you think?}
{121}{}{I don't know really, got to gather my thoughts.}
{122}{}{You know, I'm in no position to ask anything of you, but here's what I'd do. (whispers) When they're about to let you out, stand in the right spot and ask some stupid question, so that I could grab at this fucker's throat, right? And then all I'll have to do is get around the corner to the fence unnoticed...}
{123}{}{I'll see about that...}
{124}{}{Yeah, you think about it, while we still got time. I'll be by the door if you decide to do something.}
{125}{}{Yeah... that's a tough spot to be in.}

{126}{}{By the way, I'm getting executed tomorrow, in case you were interested.}
{127}{}{The way is clear. Let's get out of here.}
{128}{}{You'll have to wait.}