#Плавающие фразки ГГ когда тот осматривает первых двух убитых

{112}{}{Damn! This one had been worked over for a long time before he died...}
{113}{}{You found the first "Hawk Express" caravanner. He died.}
{114}{}{You found the first "Hawk Express" caravanner. Sadly he's dead too.}
{115}{}{Damn, this "Hawk Express" caravanner was beaten with exceptional brutality.}

#Плавающие фразки ГГ, когда тот осматривает третье тело
{116}{}{This one was shot. Looks like he attempted to run away.}
{117}{}{His skull is fractured. These raiders must have been quite the tough guys.}
{118}{}{The guys were definitely on edge. This one must have been beaten for not less than two hours...}
{119}{}{Wait a moment! What is this?}
{120}{}{Looks like a locket. Maybe it fell off one of the raiders...}
{121}{}{You found some strange piece of evidence.}
