{100}{}{You see a private.}
{101}{}{It's a private, a soldier of the lowest rank.}

{102}{}{Alarm! We're under attack!}
{103}{}{I warned you! Someone's gonna get punished!}

#Стартовая ветка
{110}{}{Hold it! You're not allowed in the barracks. Get out. Move it!}
{111}{}{I walk wherever I want, got it, grunt? Or shall I show you in mime?}
{112}{}{Barracks? I thought it was a hotel of some sort...}
{113}{}{What? You again?! Look, I don't like this. If I see you in the barracks again, I'll tear you limb from limb *personally*! Understood?}