{100}{}{Cell door.}
{101}{}{A heavy cell door.}

#Манипуляции с дверью камеры
{103}{}{The cell is locked}
{104}{}{The cell door is locked with a huge lock. It's not possible to kick it open.}
{105}{}{The lock has already been picked.}
{106}{}{Well, that wasn't hard at all!}
{107}{}{You pick the cell door lock.}
{108}{}{You fail to pick the lock.}
{109}{}{Fail}

#Диалог с тюремным надзирателем после заточения
{110}{}{Hey, you! Be quiet! Just don't give me any trouble, do your 24 hours and you'll be out just fine.}
{111}{}{Can you at least tell me what I'm in for?!}
{112}{}{How the hell am I supposed to know.}
{113}{}{Shit...}

{114}{}{There go your 24 hours. Out you go. Your stuff is in that locker.}
{115}{}{Wait a second, buddy, I just wanted to ask you something... (place yourself "conveniently")}
{116}{}{Finally!}

#Прочее
{117}{}{You can't unlock the door from this side.}
{118}{}{Can't reach}

#Женские реплики:
{1115}{}{Wait a second, buddy, I just wanted to ask you something... (place yourself "conveniently")}
