# 0. QUICK LOOK
{100}{}{You see a dealer.}
{101}{}{You see a dice table.}
{102}{}{ѕеред игрой нужно убрать из рук опасные предметы.}

# has no gambling skill messages
{110}{}{You see a girl.}
{111}{}{You see a table.}

{112}{}{—чет составил: }
{113}{}{ к }
{114}{}{ в вашу пользу.}
{115}{}{ в пользу казино.}

# 0. EXAMINES
# table
{140}{}{You see a table for playing dice games.}
# no skill
{141}{}{You see a table with stuff on it.}

# dealer
{150}{}{You see one of the casino dealers.}
{151}{}{You see one of the casino dealers. She motions for you to come over and play.}
{152}{}{You see one of the casino dealers. Her dress barely covers her body.}
{153}{}{You see one of the casino dealers. She's got some nice gams.}
{154}{}{You see one of the casino dealers. She winks at you.}
{155}{}{You see one of the casino dealers. She smells reeeally nice.}

# use gambling skill on dealer
# dealer dice amounts are screwed up
{175}{}{NO DICE!!!}
{176}{}{TOO MANY DICE!!!}
# dealer has loaded dice planted by player
{177}{}{The odds seem right ever since you switched the dice.}
{178}{}{The odds don't seem quite right.}
{179}{}{You can't gauge the odds for certain.}
# dealer has regular dice
{185}{}{The odds seem about right.}
{186}{}{You can't gauge the odds for certain.}
{187}{}{The odds don't seem quite right.}


# 3. FLOAT [MADE MAN, SAME CASINO] (WTG)
{215}{}{Hello, }
{216}{}{If you're looking for a little company laterЕ}
{217}{}{Hey, youЕ[winks]Еyou looking to gamble?}
{218}{}{He looks soЕ[shivers]Еdangerous.}
{219}{}{Welcome to the casino, }
{220}{}{Put in a good word with the boss for me?}
{221}{}{Hello, ma'am. Let me know if I can help you with anything.}
{222}{}{Looking to gamble, ma'am?}
{223}{}{She looks soЕ[shivers]Еdangerous.}

# 5. FLOAT [MADE MAN, WRONG CASINO] (WTG)
{235}{}{Looks like this one's already gambling with his life.}
{236}{}{Uh, I think he just walked into the wrong casinoЕ}
{237}{}{If he doesn't leave before the boys see himЕ}
{238}{}{Uh-oh. TroubleЕ}
{239}{}{Looks like this one's already gambling with her life.}
{240}{}{Uh, I think she just walked into the wrong casinoЕ}
{241}{}{If she doesn't leave before the boys see herЕ}


# 9. FLOAT [PORN STAR] (WTG)
{270}{}{Hey there, movie man. You looking to spend some chips?}
{271}{}{Hey, }
{272}{}{Hey, }
{273}{}{If you're looking to win some chips }
{274}{}{Lady Luck's in the house tonightЕnothing but winners!}
{275}{}{Step right up, }
{276}{}{Need another drink?}
{277}{}{Welcome to the casino, }
{278}{}{Hey there, Ms. Movie Star. Looking to spend a paycheck?}
{279}{}{You dancing tonight?}

# 11. FLOAT [MALE, NO REP] (WTG)
{290}{}{Hey there, sweetie. You looking to spend some chips?}
{291}{}{Hey, sweetieЕ[winks]Еyou looking to gamble?}
{292}{}{Hey, sweetieЕ[smiles]Еwanna take a chance?}
{293}{}{If you're looking to win some chips, you came to the right place.}
{294}{}{Lady Luck's in the house tonightЕnothing but winners!}
{295}{}{Step right up, win some chips.}
{296}{}{Need another drink, honey?}
{297}{}{Welcome to the casino, honey.}
{298}{}{This table's free if you're looking to gambleЕ}
{299}{}{Hey there, honey. You looking to spend some chips?}
{300}{}{Looking to gamble, honey?}
{301}{}{Welcome to the casino, honey.}

# 13.  PLACE YOUR BETS (WTG)
{320}{}{[The dealer looks at you nervously, then chews her lip.] Um, place your betsЕminimum bet $}
{321}{}{Place your bet, sir. Minimum bet $}
{322}{}{Place your bet, ma'am. Minimum bet $}
{323}{}{Place your bets, minimum bet $}
{324}{}{Me bet-ter than you}
{325}{}{Me play craps in pants}
{326}{}{What this game? Can you bet gecko skin?  Me got geckЕoooohЕpretty lights! [Wander off.]}
{327}{}{[You have $}
{328}{}{Bet $}
{329}{}{Whoa, too rich for my blood.}
{330}{}{No bets today, thanks.}
{331}{}{Uhhh, sorry, I don't know how to play these crazy games.}

# 14.  RETARD (14)
{340}{}{UmЕI hear they're giving away brains out back. Maybe you should go check it out.}
{341}{}{Uh, very well, sir. Come back soon.}
{342}{}{Uh, very well, ma'am. Come back soon.}
{343}{}{Byeee-byeeee}
{344}{}{Gooodie. }
{345}{}{UhЕbrainsЕwhat them?! Me go see!}

# 15. POOR MAN (13)
{350}{}{Very well, sir. Come back soon.}
{351}{}{Very well, ma'am. Come back soon.}
{352}{}{[Dealer raises an eyebrow.] $}
{354}{}{I will, thanks.}
{355}{}{Maybe so.}

# 16. LOOOOOOSER (13)
{400}{}{Sorry, better luck next time.}
{401}{}{Sorry, sir. Better luck next time.}
{402}{}{Sorry, ma'am. Better luck next time.}

{410}{}{Winner!}
{411}{}{Winner! Well done, sir!}
{412}{}{Winner! Well done, ma'am!}

{420}{}{Winner! You've doubled your money!}
{421}{}{Winner! You've doubled your money! Well done, sir!}
{422}{}{Winner! You've doubled your money! Well done, ma'am!}

{430}{}{Winner! You've tripled your money!}
{431}{}{Winner! You've tripled your money! Luck is in the house tonight! Well done, sir!}
{432}{}{Winner! You've tripled your money! Luck is in the house tonight! Well done, sir!}

{440}{}{Call it a day.}
{441}{}{Call it a night.}

{445}{}{»звините, этот стол временно закрыт. ¬оспользуйтесь пока другим столом, если хотите продолжить.}
{446}{}{»звините, стол закрыт. ќткроетс€ через пару минут.}
{447}{}{—толик открыт}

#17. TABLE TAMPER
{450}{}{Sorry, this table has been closed. Someone has been tampering with the dice.}
{451}{}{Sorry sir, this table has been closed. Someone has been tampering with the dice.}
{452}{}{Sorry ma'am, this table has been closed. Someone has been tampering with the dice.}
{453}{}{Uhhh, OK.}
{454}{}{Sorry to hear that. Thanks.}

# message parts
{2203}{}{! Welcome to the casino, hero!}
{2215}{}{. Can I help you withЕ*anything?*}
{2219}{}{.}
{2255}{}{. Looking to spend some chips?}
{2258}{}{, win some chips.}
{2260}{}{.}
{2261}{}{. Let me know if I can help you with anything.}
{2262}{}{?}
{2263}{}{.}
{2321}{}{. Place your betsЕ}
{2327}{}{.] }
{2328}{}{.}
{2344}{}{ could always use new inventory item [Leave.]}
{2352}{}{? 'Too rich for your blood?' [Scoffs.] Pal, you're in the wrong town.}
{2353}{}{? 'Too rich for your blood?' [Scoffs.] Girl, you're in the wrong town.}
