{100}{}{Ваша неопытность привела к уничтожению световых элементов фонаря. Свет гаснет и по-видимому навсегда.}
{101}{}{You successfully repair this source of light.}
{102}{}{Your skill is insufficient to repair this device.}
{104}{}{Repair not required.}
{105}{}{You gain }
{106}{}{ exp. points.}
{107}{}{You fail to repair that.}
{108}{}{This source of light works impeccably.}
{109}{}{This source of light works irregularly. It can be repaired though.}
{110}{}{Этот источник света больше не работает.}
{111}{}{Это больше не подлежит ремонту.}