{100}{}{A well with muddy water. Then again, it's clearer than in some other places.}
{101}{}{You wanted to get something else from it?}
{102}{}{By disinfecting and boiling some of the muddy well water you got yourself some clean water.}
{103}{}{You've already taken water today, leave some for the tribe!}
{104}{}{Mmm! Water!}
{105}{}{Wait a bit, the water hasn't settled yet and is still muddy.}
{106}{}{The water isn't ready yet.}
{107}{}{I wish I knew how to purify water!}
{108}{}{You purified some water with disinfectant.}

{110}{}{You've poisoned this well. Have you forgotten?}
{111}{}{Damn, the water's poisoned...}
{112}{}{You've already poisoned this well and doing it again won't make any sense for some time.}
{113}{}{The water is already poisoned.}
{114}{}{You've poisoned the well and now it's dangerous to drink from it. How vicious of you.}
{115}{}{The well is poisoned!}
{116}{}{You can't drink this water, there's still some poison in it.}
{117}{}{No! Poisoned!}
{118}{}{A well with muddy poisoned water. The water will be undrinkable for some time.}
{119}{}{You've poisoned the well of a very small settlement. The consequences of your actions are likely to be lethal.}
{120}{}{You gain experience for a non-violent expunging of a whole settlement!}
{121}{}{You don't have enough outdoorsman skills to purify water.}
{122}{}{}
{123}{}{You need a container to store water.}
{124}{}{I need a vessel}
{125}{}{Use containers to store water.}
{126}{}{Этот колодец пуст. Возможно, когда-нибудь он вновь наполнится водой.}
{127}{}{Этот колодец высох}