{100}{}{This car doesn't appear to be functional right now, but maybe it can be fixed.}
{101}{}{You can't start a car in combat!}
{102}{}{You've stolen the car!}

#Примение контроллера, регулятора или навыка ремонта на машине
{200}{}{You successfully repair the car with the fuel cell controller.}
{210}{}{You fail to repair the car. You fail to repair the car with the fuel cell controller.}
{211}{}{Your skills are not enough to to install the regulator into this complicated machinery.}
{212}{}{Fuel cell regulator installed! Now your ride will eat up less power.}
{213}{}{Now your vehicle lights its way with brand new headlights.}
{214}{}{With your skill you don't even know where to start dismounting the broken headlights.}
{215}{}{There's absolutely no need in replacing perfectly working headlights.}

{300}{}{Skill alone will not suffice.}

#Диалог при юзании машины
{301}{}{This vehicle won't start, as there's one critical part missing - a fuel cell controller. К тому же вы не находите поблизости ключей от зажигания.}
{302}{}{Try to install the part.}
{303}{}{Not now.}
{304}{}{It's a miracle! You easily attach the part to wires and hoses!}
{305}{}{-more-}
{306}{}{The car is in working order, but it won't go, as there's no charge left. You'll need at least two microfusion cells.}
{307}{}{Replace microfusion cells.}
{308}{}{It is done!}
{309}{}{Woah! Now we're getting somewhere!}
{310}{}{The car is ready, the only thing left to do is start it. Ключа для зажигания в машине не оказалось.}
{311}{}{[Attempt to hotwire]}
{312}{}{Start the car with the key taken from technician Anders.}
{313}{}{It's alive! Alive!}
{314}{}{Let's roll!}
{315}{}{Вам не удается разобраться в столь необычной для вас технике.}
{316}{}{That's too bad.}
{317}{}{Shields up, weapons online!}
{318}{}{The car is up and running!}
{319}{}{You couldn't figure which wires go where.}
{320}{}{That's too confusing.}

#Плавающие фразки техника, когда крадем машину
{321}{}{You son of a gun! I'll fucking kill you!!!}
{322}{}{I'll find you and I'll kill you!!! Do you hear me?!}

{323}{}{Попытаться перемонтировать систему зажигания.}
