{100}{}{You spotted a trap.}
{101}{}{By a fluke the mine did not go off.}
{102}{}{You disarmed the trap.}
{103}{}{That was a bad idea.}
{104}{}{You failed to disarm the trap.}
{105}{}{It's a trap!}
{106}{}{ spotted a mine.}
{107}{}{Disarmed}
{108}{}{you successfully evaded the mine.}
{109}{}{You discover a trap with the metal detector.}
{110}{}{The trap breaks because of your clumsiness.}
{111}{}{You spotted the trap just in time to jump over it.}
{112}{}{This trap is too complicated for you.}
{113}{}{Эта напольная ловушка в настоящий момент активна и представляет опасность.}