{100}{}{Door Entry Computer.}
{101}{}{This computer controls the large vault door.}
{102}{}{Err... I have no clue how this is supposed to work...}
{103}{}{This console should not be operated by laymen. Go study some.}
{104}{}{Nobody answers your call.}
{105}{}{You gain experience for locating fellow vault dwellers.}

{107}{}{You see a console. You can't open the vault door from it, but you can try to send in a signal.}
{108}{}{Contact the vault.}
{109}{}{(leave)}
{110}{}{(Noise and interference come out of the speaker, some crackling, and then a voice) Err... Hello...}
{111}{}{Did you order pizza?}
{112}{}{Wha... (pause) Umm... No.}
{113}{}{What about the "Deepthroat" movie?}
{114}{}{No.}
{115}{}{Aren't you missing a handkerchief?}
{116}{}{No.}
{117}{}{Oh, what do you know! It's so pretty... By the way can you tell me what time it is?}
{118}{}{No.}
{119}{}{Weird... Could you...}
{120}{}{No.}
{121}{}{Oh... Are you sure its not your handkerchief?}
{122}{}{No, It's not.}
{123}{}{Why am I still here then?}
{124}{}{I don't know. Where exactly are you?}
{125}{}{Outside, by the vault door. Isn't it kind of obvious?}
{126}{}{But... but it cannot be! Where are you?! I mean... are you calling from another vault?}
{127}{}{Well not exactly. I mean, I am from another vault. But right now I happen to be in front of yours.}
{128}{}{Hmm... and how did you get here?!}
{129}{}{On foot. It wasn't hard. Well, it wouldn't have been, if it wasn't for mutants and raiders and the like filling the wasteland. Could you possibly open the door, so that we could talk over a glass of cold Nuka?}
{130}{}{(pause) Sorry, but I can not take the risk. I don't know what the situation is behind that door. What if these... mutants and raiders get in here? Besides, I'm still not sure this all isn't some kind of a joke.}
{131}{}{What about your vault monitors? Do you even check them? You can exit to the surface already! We have, and now we're constructing a city.}
{132}{}{Constructing? Constructing how?}
{133}{}{Why, with G.E.C.K of course!}
{134}{}{Maybe you're right, we'll have to check your information. But for the time being I think we'll stay behind these doors. Thank you for contacting us. Sorry I couldn't talk to you any longer, I have an important meeting.}
{135}{}{Wha... Hold on...}

{136}{}{(signal lost)}
{137}{}{Damn wussie!}
{138}{}{(Exit)}
{139}{}{No you! (signal lost again)}
{140}{}{(Exit)}