{100}{}{You see Rekrut.}
{101}{}{You see an apathetic man, who looks like a doctor or an engineer. He's constantly adjusting his spectacles.}

{110}{}{How many times did wanderer girl make poor Sam blush?}
{111}{}{Don't you think it's easier to play with female character?}

{112}{}{Please, speak proper English.}
{113}{}{It's "you're", not "your".}
{114}{}{It's "their", not "there".}
{115}{}{You guessed it, I can be a nerd sometimes.}
{116}{}{You expected to find a dog in here? Sorry, no dogs allowed.}
{117}{}{I like to criticize other people's suggestions.}
{118}{}{Why not aid a good man?}
{119}{}{I've always said it's a good idea!}
{120}{}{No task is impossible for a man who doesn't have to perform it himself.}
