{100}{}{You see Kerb.}
{101}{}{You see none other than Kerb!}

#Если ГГ бухой или обколотый:
{110}{}{And this junkie is the one to save the world? Well... why the hell not. Like priest, like people.}

#Обычные ответные реплики:
{111}{}{2.4 megabytes... 2.4 megabytes!!!}
{112}{}{Looking at you all I see is endless lines of dialog...}
{113}{}{Non profit project, huh? At least there's no need to worry about [censored] censorship!}
{114}{}{Damn it, what the fuck? Oh, never mind, it's ok...}
{115}{}{And to hell with political correctness!}
{116}{}{War. War never changes... Come on, somebody had to say it!}
{117}{}{Don't lose spirit, comrade! 2077 is nearer with every minute!}
{118}{}{I can't help but wonder what's going on in what used to be USSR.}
{119}{}{I'd have Lynette's liver with a glass of Chianti now... or at least Morpheus' heart with some beer.}

#При применении воровства:
{130}{}{Hey! Get your filthy claws off me!!}
#При применении науки:
{131}{}{Sociopath with  manic depressive disorder, you say? Well look at yourself.}
#При применении бухла:
{132}{}{Better decant me a glass of sweet blood instead.}
#При применении drug-предметов:
{133}{}{Hey! Maybe I too would like to poke you with something, like a knife! But you don't see me doing it!}
