{100}{}{You see a stalker.}
{101}{}{You see a stalker who's been stalking as long as he remembers.}
{102}{}{Hey there. You still thinking about it? Forget it, it's too dangerous.}

{110}{}{Whoa, looks like I'm not the only guy brave or stupid enough to come here?!}
{111}{}{Actually I sort of stumbled here by accident...}
{112}{}{Yeah, sure. Like I'd believe that.}
{113}{}{What's so incredible about it?}
{114}{}{What's incredible about it!? Do you really not know what this place is?}
{115}{}{Nope.}
{116}{}{Well, listen then. Places like this are called "anomalies", because really strange things are going on there. And many would like to know why, but this secret must be hidden somewhere deep underground, so nobody can find out the truth.}
{117}{}{Strange things? Like what?}
{118}{}{Do you see the air shimmer over there? You don't go in such spots - the level of radiation and voltage is so high there you'd be fried in no time.}
{119}{}{Wow!}
{120}{}{Many venture to enter the station, but all of them fail - they either chicken out and come back, or remain there... forever.}
{121}{}{Can't you just bypass these dangerous spots?}
{122}{}{Well, you can. But the thing is, these anomalies are constantly shifting. Today they are here, tomorrow - somewhere else.}
{123}{}{Hmm. But why would anybody want to infiltrate this station anyway? What's so special about it?}
{124}{}{As the legend goes, there's a unique item there called an artifact. It's said to cure anything... Even radiation poisoning!}
{125}{}{Cool! This "artifact" would be of extreme use for me.}
{126}{}{Exactly. It would be for pretty much anyone. But no one can get it... If it even exists, nobody knows that for sure. So I'm wondering if it's worth it.}
{127}{}{Thanks for the story! Take care.}

{1111}{}{Actually I sort of stumbled here by accident...}
