{100}{}{Seemingly a very deep opening. It strongly reeks of fecal matter, but is no longer pulsating.}
{101}{}{You see something inconceivable! It's hard to tell if it's living or not, but it pulsates and exhales toxic gases.}
{102}{}{This does nothing.}
{103}{}{The opening pulsates and keeps on exhuming toxic gases. You probably don't want to go there.}
{104}{}{If you plan on going down that fetid hole, you'll need a rope.}
{105}{}{You already lowered a rope down this hole. You don't need another one.}
{106}{}{The rope is fastened and lowered.}
{107}{}{It's still too dangerous to go down there... and why would you anyway? Come to your senses!}
