#Описания
{100}{}{You see a hood.}
{101}{}{You see a car hood.}
{102}{}{After the "repairs" it's just a hunk of metal. The owner must really be upset.}
{103}{}{Despise the wearing and decent mileage, the engine will serve its owner for some time still.}

#Разное
{105}{}{You can't rummage in the engine in combat.}

#Режим диалога
{110}{}{The engine is humming like it's whispering the words of gratitude to you.}
{111}{}{After the "repairs" it's just a hunk of metal. The owner must really be upset. It's not a lost cause yet though.}
{112}{}{Try to restore the engine.}
{113}{}{You lift up the hood. The look of countless parts and wires sends you into a bout of panic attack.}
{114}{}{Try to figure out the problem.}
{115}{}{Leave it.}

{116}{}{Seems like it's nothing too overcomplicated, but you can't make out what the problem is.}
{117}{}{}
{118}{}{The engine is fully functional, it just requires routine maintenance.}
{119}{}{Do the maintenance.}
{120}{}{Strip the engine of useful parts - I need them more than he does!}
{121}{}{Bang-up job!}
{122}{}{That's better.}
{123}{}{You dismantled all the worthwhile junk, took the energy supply controller and a good microreactor. The owner probably won't like it, but you knew what you were in for, didn't you?}
{124}{}{Exactly.}
{125}{}{The car won't run without the parts you stole.}
{126}{}{Do the maintenance.}
