{100}{}{What a nice place! You feel the urge to take off your helmet and breathe in the fresh air...}
{101}{}{You accidentally step on some kind of spore fungus. It pops, releasing a cloud of spores.}
{102}{}{Oh... I feel so sleepy...}
{103}{}{I... can't... take it... anymore...}
{104}{}{Your consciousness starts to fade into sweet and much desired sleep. But upon waking up you find yourself horrified...}
{105}{}{Ouch, this place is not as good as it seemed at first.}
