{100}{}{Your head aches like hell. Looks like something in this cave has changed while you were unconscious.}
{101}{}{The Universal Mind must have heard your pleas and opened up a passage that you would never be able to open yourself.}
{102}{}{Oh!}
{103}{}{Things finally start to clear up for you.}
{104}{}{Dang! I was so close!}
{105}{}{Your consciousness slips into blackness again.}
{106}{}{Something seems to clear up...}
{107}{}{Dang! I was so close!}

{110}{}{Ehh, Overseer?}
{111}{}{Huh? Who is this?}
{112}{}{Overseer! It's me!}
{113}{}{... so dark...}
{114}{}{What?}
{115}{}{... Do not waste time!}
{116}{}{My body's decayed... I'm dying...}
{117}{}{It's unbearable! Kill me!}
{118}{}{Only in death...}
{119}{}{... de-e-eath...}
