{100}{}{You stumble upon an abandoned nuclear power plant workers village.}
{101}{}{The nuclear power plant emits heavy amounts of radiation. You better hurry up!}
{102}{}{I got some strange sensations! Where's the Geiger counter?}