#Комп в АЭС - часть 1
{100}{}{Вы видите работающий терминал.}
{101}{}{Вы видите терминал управления реактором.}
{102}{}{Вы видите терминал. Похоже, он работает.}
{103}{}{Требуется научный метод.}
{104}{}{Недоступно во время боя.}

{110}{}{Идет загрузка системы, пожалуйста, подождите... Команда не распознана. Начато форматирование жесткого диска.}
{111}{}{И что это значит?}
{112}{}{Вам удалось загрузить терминал. Кое-что в нем можно распознать.}
{113}{}{Изучить архивы.}
{114}{}{Выйти.}

{115}{}{В компьютере много обычной, ничем не примечательной документации. Однако один из разделов засекречен и заблокирован сложным паролем.}
{116}{}{Попытаться взломать пароль.}
{117}{}{Оставить.}

#???
{124}{}{Нужен научный метод.}
{125}{}{}

#Применение наркоты на криттере, который за это нападает на ГГ:
{126}{}{А вот это было зря!}
{127}{}{}

#Для достижения "Друг нищих"
{132}{}{Вы получили новое достижение.}
{133}{}{Вы потеряли достижение "Друг нищих".}

#Для кола-продаж
{150}{}{Вы совершили удачную сделку по продаже ядер-колы. Поздравляем!}
{151}{}{Вы получили новое достижение.}
{152}{}{Договор о продаже ядер-колы в этом заведении отныне не действует.}
{153}{}{Похоже, что доход в этом месте упадет ниже плинтуса}

#Комп в АЭС - часть 2
{158}{}{Нет, ваших познаний в области программирования недостаточно для взлома этой системы.}
{159}{}{Оставить.}
{160}{}{Вам удалось взломать систему. Судя по внутренней документации, эта станция использовалась правительством не только для мирных целей.}
{161}{}{Смотреть отчеты об обеспечении урановой рудой.}
{162}{}{Смотреть информацию о проекте радиостанции "Лавлок".}
{163}{}{Смотреть координаты радиостанции "Лавлок".}
{164}{}{Смотреть отчет об отладке сети ПосейдонНет.}
{165}{}{Так как урановая руда использовалась в военных целях, ее добыча и распределение контролировались правительством. Поэтому администрация станции "Посейдон Ойл" была вынуждена регулярно терпеть проверки и вести строгую отчетность. Если верить этим записям, запасов урана для поддержания энергии АЭС на момент консервирования станции должно было хватить на 200 лет вперед в экономном режиме.}
{166}{}{Радиостанция недалеко от поселения Лавлок должна была стать опорным пунктом на случай глобальной катастрофы и имела повышенные средства защиты. В частности, станция располагалась в бронированном подземном бункере. АЭС должна была поставлять достаточное количество энергии для обеспечения этой станции.}
{167}{}{Вы вносите координаты станции в свой Pip-Boy. На карте мира открыта новая локация.}
{168}{}{Видимо, эта станция расположена в том же районе, где сейчас находится племя шайеннов.}
{169}{}{Вы уже копировали координаты. Станция располагается на юге.}
{170}{}{Это компьютерная сеть для связи на дальних расстояниях. Она призвана объединить различные пункты военного и правительственного назначения Америки, однако сеть не работает. Что совсем не удивительно.}
{171}{}{Завершить.}
{172}{}{Вы вносите координаты станции в свой Pip-Boy. Видимо, эта станция расположена в том же районе, где сейчас находится племя шайеннов.}
{173}{}{Это та самая станция недалеко от племени шайеннов. Вы уже ее посещали.}

{174}{}{Свериться со списком из сейфа управляющего.}
{175}{}{Так и есть - в списке на листке управляющего значится радиостанция "Лавлок". Теперь этот список бесполезен.}


#########################################################################
#
#            Реакция нпс на крики и ловушки
#
#########################################################################

#-------------- Начало реплик

#Тест для кнопки SOS
{388}{}{Кто-то кричал?!}
{389}{}{Чертовы туристы!}
{390}{}{Я больше на это не куплюсь!}

{391}{}{?!}
{392}{}{!!}
{393}{}{ }

#Для трудяг, фермеров, горожан
{400}{}{Это кто тут раскричался?}
{401}{}{А зачем так кричать-то?}
{402}{}{Это вы мне?}
{403}{}{Я вообще-то прекрасно слышу!}
{404}{}{А можно потише?}
{405}{}{Психов выпустили на улицу...}
{406}{}{Что-то произошло?!}
{407}{}{А что случилось?!}
{408}{}{Полиции на вас не хватает}

{450}{}{Я больше на эту чушь не куплюсь!}
{451}{}{Очередные психопаты!}
{452}{}{Нет уж, лучше я в сторонке постою...}
{453}{}{Что? Опять?!}
{454}{}{Ну сколько можно!}
{455}{}{Пора бы уже и успокоиться!}

{460}{}{Это была типа шутка?}
{461}{}{Ну и что здесь произошло?}
{462}{}{Э, а где кричали-то?}
{463}{}{Не пойму, где кричали-то}
{464}{}{А разве здесь не кричали?}
{465}{}{Чертовы туристы! Только нервы напрягают!}
{466}{}{Ну все - больше я на позывные не куплюсь!}
{467}{}{Э... Это что было?}

{470}{}{ЧТО? ЧТО СЛУЧИЛОСЬ?!}
{471}{}{Кто-то кого-то зарезал?!}
{472}{}{Вот черт!?}
{473}{}{Что за крики!!?}
{474}{}{Э... Это что было?}
{475}{}{}
{476}{}{}
{477}{}{}

#Для примитивных существ:
{500}{}{Это хто тут кричать?}
{501}{}{Почему твоя кричать?}
{502}{}{Твоя *мне* кричать?}
{503}{}{Моя слышать, да...}
{504}{}{Эй! Твоя слишком громкий!}
{505}{}{Злые души забрать твоя разум}
{506}{}{Что не так?!}
{507}{}{Твоя наступить на колючку?!}

{550}{}{Не, моя больше не бегать на крики злых духов}
{551}{}{Опять злые духи играть с моя!}
{552}{}{Нет уж, моя в сторонке стоять...}
{553}{}{Что? Опять?!}
{554}{}{Сколько можно опять!?}
{555}{}{Твоя очень буйный, твоя надо дать сонной травы}

{560}{}{Твоя шутить плохо-плохо!}
{561}{}{Э?!}
{562}{}{Где кричать?!}
{563}{}{Моя не понимать, где злые духи?}
{564}{}{Фуф... Надо меньше дурман травы курить...}
{565}{}{Моя глюки ловить?}
{566}{}{Не, моя больше не бегать на крики злых духов}
{567}{}{Э...}

{570}{}{ЧТО?! ЧТО СЛУЧИЛОСЯ?!}
{571}{}{Драка!? Кто драться!?}
{572}{}{О!? Злые духи!!!}
{573}{}{Моя не понять - кто где кричать?}
{574}{}{Э?}
{575}{}{}
{576}{}{}
{577}{}{}

#Для агрессивно настроенных существ и крутых парней (рейдеры, бандиты, охранники):
{600}{}{Какого черта ты орешь?!}
{601}{}{Эй, бестолочь! Кончай орать!}
{602}{}{Твою мать! Ты мне орешь, что ли?}
{603}{}{Эй, у меня отличный слух, заканчивай!}
{604}{}{Эй! Ты кого тут заманить пытаешься?}
{605}{}{По ходу, передо мной еще один клиент дурдома...}
{606}{}{Что тебе оторвали, если ты так орешь?}
{607}{}{Мать твою! Заткнись!}
{608}{}{Да иди ты!!}
{609}{}{Да, срать-пересрать, заткнись уже!}

{650}{}{Не обращай внимания - это тело с головой не дружит}
{651}{}{Да пошло оно все!}
{652}{}{Лучше в сторонке постоять...}
{653}{}{Что? Опять?!}
{654}{}{Ну сколько можно, мать твою!}
{655}{}{Смотри - еще одному мозгов не хватает}

{660}{}{Черт, самое интересное уже закончилось!}
{661}{}{Черт, опять зрелище не удалось посмотреть!}
{662}{}{А разве не здесь кого-то резали?}
{663}{}{Кто-нибудь обяснит мне - где орали-то?}
{664}{}{Вот черт! Была драка - и нету! Чудеса!}
{665}{}{Твою мать! У меня глюки, что ли?!}
{666}{}{Э... Так мне это причудилось?}
{667}{}{Хрен с ним, лучше пойду подремлю}

{670}{}{ЧТО? ЧТО СЛУЧИЛОСЬ?!}
{671}{}{Да! Кому-то морду бьют!!}
{672}{}{Ага! Наконец-то мордобой!!}
{673}{}{Драка!? Надо взглянуть!}
{674}{}{Вот черт! Это что было?}

#Для браминов
{700}{}{Му!}
{701}{}{Му-у!}
{702}{}{М-м-му!}
{703}{}{Му?}
{704}{}{Му-у?}

#-------------- Конец реплик