{100}{}{Кодовая дверь.}
{101}{}{Перед вами мощная кодовая дверь, ведущая на станцию. Заперта намертво.}
{102}{}{Дверь заперта.}

#Уничтожение двери:
{105}{}{Взрыв сорвал петли, и осколки двери полетели в стороны. Вы получаете 100 опыта.}
{106}{}{Здесь нужно что-то мощное.}

#Применение навыков и предметов
{110}{}{Против лома нет приема. Замок слетает с двери, и вы получаете 1000 опыта, повышая навык владения холодным оружием.}
{111}{}{Вы демонтировали кодовый замок и открыли дверь. Вы получаете 1000 опыта и повышаете навык ремонта.}
{112}{}{Вы взламываете кодовый замок, получая 1000 опыта и повышая навык взлома.}
{113}{}{Вы обхитрили кодовый замок, получая 1000 опыта и повышая навык науки.}
{114}{}{Это ничего не даст.}
{115}{}{И на что вы рассчитывали? Этот случай посерьезней!}
{116}{}{Верное направление мысли, однако с вашими навыками здесь делать нечего.}
{117}{}{Эта дверь слишком мощная для вас.}
