{100}{}{Code door.}
{101}{}{You see a reinforced code door leading to the power plant. Predictably locked.}
{102}{}{The door is locked.}

#Уничтожение двери:
{105}{}{The blast blews the door off the hinges, sending its debris into the air. You earn 100 exp. points.}
{106}{}{You'll need something powerful.}

#Применение навыков и предметов
{110}{}{Might makes right! The lock falls off. You earn 1000 exp. points and improve your melee weapons skill.}
{111}{}{You've dismantled the lock and opened the door. You earn 1000 exp. points and improve your repair skill.}
{112}{}{You've forced the lock. You earn 1000 exp. points and improve your lockpicking skill.}
{113}{}{You've tricked the code lock with a security exploit. You earn 1000 exp. points and improve your science skill.}
{114}{}{This does nothing.}
{115}{}{What did you expect? This case is way more serious!}
{116}{}{Good thinking, but your skills leave much to be desired.}
{117}{}{This door is too strong for you.}
