{100}{}{You see a thug.}
{101}{}{You see a private.}

{102}{}{You see an ordinary thug from Big Louie's gang.}
{103}{}{You see a Wind of War patrolman.}

{104}{}{Don't talk to me, pal, talk to da man}
{105}{}{Don't talk to me, gal, talk to da man}
{106}{}{This area is off limits, sir, if you need something, talk to our commanding officer}
{107}{}{This area is off limits, ma'am, if you need something, talk to our commanding officer}

#Первая фраза для атаки при игре мужиком
{110}{}{There he is!}
{111}{}{Get him!}
{112}{}{Pigs are here!}
{113}{}{Waste him!}
{114}{}{You're going down, boy!}

{120}{}{Enemy spotted!}
{121}{}{To arms!}
{122}{}{The enemy's on the move! Attack!}
{123}{}{Hold it!}
{124}{}{Die, you scum!}

#Первая фраза для атаки при игре девушкой
{210}{}{There she is!}
{211}{}{Get her!}
{212}{}{Pigs are here!}
{213}{}{Waste her!}
{214}{}{You're going down, girl!}

{220}{}{Enemy spotted!}
{221}{}{To arms!}
{222}{}{The enemy's on the move! Attack!}
{223}{}{Hold it!}
{224}{}{Die, you bitch!}
