{100}{}{Это рейдер.}
{101}{}{Один из стервятников Большого Луи, который сопровождает вас в походе до Хоторна.}
{102}{}{Черт! Они убили Кенни!}
{103}{}{Эй, мачо! Мы сами за себя, но если ты нас кинешь - считай себя трупом.}

#Когда по напарнику попадает турель (для героя-мужчины):
{104}{}{Твою мать!}
{105}{}{Куда ты меня завел?!}
{106}{}{Ах, ты! Я же предупреждал!}
{107}{}{Гадство! Я тебе не телохранитель!}
{108}{}{Когда я его прикончу, тебе, мачо, будет хреново!}
{109}{}{Мачо, мать твою! Я тебе это припомню!}

#Диалог:
{110}{}{Ну и? Будешь лясы точить?}
{111}{}{Стой здесь, мне надо разведать ситуацию.}
{112}{}{Пошли дальше, я нашел безопасный путь.}
{113}{}{Ты прав, надо лясы поточить. Расскажи об этом месте.}
{114}{}{Понял, отстал.}

{115}{}{Это был военный город. Ну, знаешь, вон там казармы, а здесь город. Даже казино вон там стоит. Бар и казарма в одном месте. Круто, правда? Только, бля, этих роботов понаставили, суки, мать их! Нашел бы - урыл козлов по самые гланды!}
{116}{}{Братан, я тута не бывал. Знаю только, что это что-то вроде склада с пукалками и всякой военной техникой. Еще знаю, что эти штабные суки поставили здесь везде турели. Ты не тормози, думай, мать твою, как их отключить.}
{117}{}{Ну и че скажешь?}
{118}{}{Ты в этом районе бывал раньше?}
{119}{}{Помоги мне перелезть через забор напротив.}

#На карте складов, таймер:
{120}{}{Добрались, мать твою!!!}
{121}{}{Ты погляди, сколько барахла в этих складах?!}
{122}{}{Наша взяла, ха!}
{123}{}{Вот теперь-то всех за горло прижмем!}
{124}{}{... черт, турель, подлюка. Порви меня на флаг, если она не рабочая.}
{125}{}{Так, мачо, мы здесь в теньке посидим, а ты думай, как мимо турелей пройти.}
{126}{}{Не придумаешь - мы тебя вперед ногами занесем и проверим, работают эти консервные банки или нет. Ясно?}
{127}{}{Давай, двигай жопой!}

{128}{}{Черт, эти турели заставляют понервничать. Может, у *тебя* есть какие-нибудь соображения, как их обезвредить?}
{129}{}{Значит так. Турели точняк работают от какого-нибудь генератора. Найди его, штепсель из розетки - и все дела. А вообще я не знаю, сам думай.}

#Сдача квеста
{130}{}{Трепещи! Я обезвредил охранную систему, теперь можете без опаски бродить по складам.}
{131}{}{Епт... Лады, пошли, Кенни, займемся делом. Ну а ты, мачо, крут. Отлично послужил. В общем, ты свое дело сделал, так что мы тебя не держим, возвращайся на базу.}
{132}{}{И никакой благодарности, я так и знал...}
{133}{}{Вы нашли способ безопасного проникновения на склады для рейдеров и получаете 700 опыта.}

#Женские реплики (Иван):
{1103}{}{Эй, мучача! Мы сами за себя, но если ты нас кинешь - считай себя трупом.}

{1104}{}{Твою мать!}
{1105}{}{Куда ты меня завела?!}
{1106}{}{Ах, ты! Я же предупреждал!}
{1107}{}{Гадство! Я тебе не телохранитель!}
{1108}{}{Когда я его прикончу, тебе, мучача, будет хреново!}
{1109}{}{Мучача, мать твою! Я тебе это припомню!}

{1112}{}{Пошли дальше, я нашла безопасный путь.}
{1114}{}{Ясно, отстала.}
{1116}{}{Сеструха, я тута не бывал. Знаю только, что это что-то вроде склада с пукалками и всякой военной техникой. Еще знаю, что эти штабные суки поставили здесь везде турели. Ты не тормози, думай, мать твою, как их отключить.}
{1120}{}{Добрались, мать твою!!!}
{1125}{}{Так, мучача, мы здесь в теньке посидим, а ты думай, как мимо турелей пройти.}
{1126}{}{Не придумаешь - мы тебя вперед ногами занесем и проверим, работают эти консервные банки или нет. Ясно?}
{1128}{}{Черт, эти турели заставляют понервничать. Может, у *тебя* есть какие-нибудь соображения, как их обезвредить?}
{1129}{}{Значит так. Турели точняк работают от какого-нибудь генератора. Найди его, штепсель из розетки - и все дела. А вообще я не знаю, сама думай.}
{1130}{}{Трепещи! Я обезвредила охранную систему, теперь можете без опаски бродить по складам.}
{1131}{}{Епт... Лады, пошли, Кенни, займемся делом. Ну а ты, мучача, крута! В общем, ты свое дело сделала, так что мы тебя не держим, возвращайся на базу.}
{1132}{}{И никакой благодарности, я так и знала...}