{100}{}{Heavy warehouse door.}
{101}{}{It's a very heavy and strong metal door with an embedded lock.}
{102}{}{The door could undoubtedly endure much harder impacts.}

{103}{}{Your skills are useless here, better look for a key.}
{104}{}{Need a key}
{105}{}{The door is locked securely with a very sturdy lock. Find a key to open it.}
{106}{}{The door is locked securely with a very sturdy lock. Find a key to open it.}
{107}{}{No use}

{108}{}{You lock the door.}
{109}{}{Locked}
{110}{}{You unlock the door.}
{111}{}{Unlocked}
