{100}{}{Warehouse door.}
{101}{}{It's a huge metal door leading into the warehouse.}
{102}{}{Looks like the door's blocked from the other side. Can't be opened from here.}
{103}{}{Even this strong a blow does not make the door budge.}

{104}{}{The door is jammed from the inside, it can't be opened from here.}
{105}{}{Jammed from the inside}
{106}{}{With great effort you finally manage to pry open the door.}
{107}{}{The door is jammed for good now, it's not going to open.}
{108}{}{The door doesn't give way}

