{100}{}{You can't operate this device in combat!}

#Главное меню
{110}{}{You see a standard issue recon robot. Developed for diagnostics purposes. It can be assembled, but to put it online you have to have a control program.}
{111}{}{Try to put the robot online.}
{112}{}{Repair the robot.}
{113}{}{Try to finish the robot's control program.}
{114}{}{Leave.}
{115}{}{This robot is still not functioning.}

#Починка
{120}{}{You fail to assemble the robot, which is unsurprising with your skills...}
{121}{}{Back.}
{122}{}{Making the most of your technical skills you manage to fix the robot and put it in stand-by mode.}
{123}{}{For fixing the robot you gain 350 exp. points.}

#Написание программы
{130}{}{This recon robot was programmed to do mine sweeping. You can hardly expect more of it. The control program however is unfinished.}
{131}{}{Load the program from holodisk.}
{132}{}{Try to finish the program yourself.}
{133}{}{For restoring the program you gain 350 exp. points.}
{134}{}{Hmm, maybe this holodisk from the desk will do?}
{135}{}{Program not recognized. Unexpected termination of file. It appears that the program is unfinished and has some bugs in it.}
{136}{}{Error: Program not recognized.}
{137}{}{Well, I guess I'm not hacker enough. Got to let it go.}
{138}{}{Damn, If I were a little better at programming... Go back.}
{139}{}{Program recognized. Checking for errors... No errors found. AI Protocol initialization... Done.}
{140}{}{Great, the program's working.}

#Запуск робота
{150}{}{Status: robot not functioning.}
{151}{}{Status: failed to load program.}
{152}{}{Status: robot ready for launch.}
{153}{}{Start up the robot.}
