{100}{}{Это распределительный электрощит.}
{101}{}{Электрощит гудит, значит, через него все еще куда-то поставляется электричество.}
{102}{}{Этот электрощит вышел из строя. Навсегда.}

#Использование
{110}{}{Ремонту не подлежит.}
{111}{}{Этот щиток выглядит работоспособным, но, видимо, источник питания больше не поставляет по нему электричество.}
{112}{}{Вы не сможете ничего с этим сделать во время боя.}
{113}{}{Этот щиток отныне бесполезен.}
{114}{}{С этим щитком больше нет смысла что-либо делать.}
{115}{}{Щиток и без этого не работает, так как источник питания не поставляет по нему электричество.}
{116}{}{Не задерживайтесь! Скоро щиток взорвется!}

#Диалог
{119}{}{В этом уже нет смысла. Оставить.}
{120}{}{Электрощит гудит, значит, через него все еще поставляется электричество к работающей технике. Напряжение очень высокое.}
{121}{}{Открыть дверцу и изучить внимательней.}
{122}{}{Оставить.}

{123}{}{Провода тянутся под стену здания, но есть ответвление с высоким напряжением, уходящее под землю. Именно по этим проводам идет ток. Вполне возможно, что через этот щиток питаются турели у входа в здание.}
{124}{}{Перекусить провода инструментами.}
{125}{}{Попытаться демонтировать щит.}
{126}{}{Попытаться взорвать щит.}
{127}{}{Попытаться вырвать провода силой.}
{128}{}{Назад.}
{129}{}{Оставить.}

{130}{}{Это небезопасно! Вы все еще не передумали?}
{131}{}{Перекусить провода, находящиеся под напряжением.}
{132}{}{Даже если у вас есть инструменты для демонтажа щитка, вам также понадобятся технические навыки, чтобы сделать это без риска для здоровья.}
{133}{}{Использовать суперремнабор.}
{134}{}{Для этого вам нужна взрывчатка.}
{135}{}{Заложить динамит.}
{136}{}{Заложить пластид.}
{137}{}{Заложить динамитную шашку.}
{138}{}{Вы должны быть чертовски сильны, чтобы вырвать эти провода вручную!}
{139}{}{Воспользоваться руками.}
{140}{}{Использовать кувалду.}
{141}{}{Использовать монтировку.}

{149}{}{10 секунд до взрыва}
{150}{}{Вы установили взрывчатку.}
{151}{}{Замыкание выводит из строя щит, и вдруг турели на улице замирают.}
{152}{}{Вы рвете провода, замыкание выводит из строя щит, и вдруг турели на улице замирают.}
{153}{}{Срань господня! Это было хреново!}

{155}{}{Вас ударило током, но защитный костюм погасил удар.}
{156}{}{Сапоги частично погасили удар током.}
{157}{}{Вас ударило сильным током!}
{158}{}{Вас бы ударило сильным током, если бы вы вовремя не отскочили от щитка!}

{160}{}{За успешное применение навыка ремонта вы получаете 300 опыта.}
{161}{}{Вы не смогли разобраться в хитросплетениях проводов, хомутов и коробов.}
{162}{}{Попробовать еще раз.}
{163}{}{Вы умело отключаете электропитание турелей.}
