{100}{}{}

{110}{}{They make for a nice salad...}
{111}{}{Better exterminate them before they start talking!}
{112}{}{Note to self - weed only those with teeth...}
{113}{}{One less mouth}
{114}{}{Who crossed a dandelion with a rhino?}
{115}{}{Root out weeds? Well, at least that's better than killing rats with a shovel.}
{116}{}{Kill a plant - save a fly!}
{117}{}{How do you like that?}
{118}{}{Was that mutated hemp?}

{119}{}{He-he! Petty flora!}
{120}{}{Boy, was that boring, but I did it!}
{121}{}{Boy, was that boring, but I did it!}
{122}{}{The last weed on this plantation is exterminated.}

{150}{}{You killed }
{151}{}{ of 10 plants.}
