{100}{}{Это Форсажник.}
{101}{}{Вы видите рейдера по кличке Форсажник.}

#Когда взорвана дверь:
{110}{}{Что за...}
{111}{}{Какого хрена!}
{112}{}{Хватай стволы!}
{113}{}{Ну кто там нарисовался?!}
{114}{}{Ни хрена себе!..}
{115}{}{Метнулись - глянули, че там!}
{116}{}{Очередная живая мишень?}
{117}{}{Ты слышал?!}
{118}{}{Твою ж мать!}
{119}{}{Кто такой шумный?}

{120}{}{Короче на хрен...}
{121}{}{Я ниче не понял!}
{122}{}{Повалили назад.}
{123}{}{Это типа шутка?}
{124}{}{У меня, наверно, глюки!}
{125}{}{Ладно, хрен с ним!}

#Когда враждебен, видит и нападает:
{126}{}{Эй ты!!!}
{127}{}{Сдохни!!!}
{128}{}{Сделаем это по-быстрому!}
{129}{}{Подцепить тебя на крюк, а?!}
{130}{}{Выходи танцевать по-хорошему!}
{131}{}{Кого-то пора подкоротить.}
{132}{}{Стой смирно и не рыпайся!}
{133}{}{Смотрите, кто на нас наехать решился!}
{134}{}{Сделаем на раз!}
{135}{}{Это ты-то тут проблемы создаешь?}

#Диалог:
{150}{}{Чего скажешь, приятель? Или просто решил помухлевать на моих картах? Ну как, рискнешь?}
{151}{}{Чем сейчас банда занимается?}
{152}{}{Где-то здесь должна быть радиостанция. Слышал что-нибудь про нее?}
{153}{}{Тут один знахарь из племени интересуется своими принадлежностями. Не в курсе?}
{154}{}{Насчет карт - отличная мысль. Какие ставки?}
{155}{}{Забудь, я ухожу.}

{156}{}{Чудило, чем банда может заниматься? Отрываемся по полной, в покер катаем, бесим дикарей из племени. В общем, ни хрена не делаем. Все четко, в общем.}
{157}{}{Радио... что? Не, не знаю. Если и есть такая, то отсюда не видно. Тут только развалины и племя дикарей на юге.}

{158}{}{Давай вернемся к началу разговора.}
{159}{}{Э, барыга! Ты это с чего спросил вдруг?}
{160}{}{Это поможет в моей врачебной практике.}
{161}{}{У меня возникли планы на эти вещи, когда Нискигван проболтался.}
{162}{}{Нискигван просил достать.}

#Выкуп:
{163}{}{О, как мило! А теперь мои условия. Раз ты свой бизнес ведешь, я хочу часть этого бизнеса. 1000 баксов - и барахло пернатого коновала твое. И ничего личного.}
{164}{}{По мне, цена что надо. Вот деньги.}
{165}{}{Пойми, *никто* и *никогда* не купит у тебя это барахло за 1000 баксов. 500 - и не больше!}
{166}{}{Забудь. Вернемся к началу разговора.}
{167}{}{То-то же! (кладет деньги себе в карман)}
{168}{}{Черт, денег нет.}

{169}{}{Вернемся к началу разговора.}
{170}{}{Я ухожу.}
{171}{}{Черт, загрузил ты меня, мачо. Ну, давай 500.}
{172}{}{Тысяча - и не меньше!}

#Выиграть рюкзак знахаря:
{173}{}{А ты у него в шестерках или как? Да ладно, ниче личного, просто бизнес. Лично с тобой я готов его отыграть. В карты.}
{174}{}{Отличная идея. Какие ставки?}
{175}{}{(Невероятно! Вы выиграли!) Да на! Да подавись! (бросает на стол сумку со знахарскими принадлежностями) И больше не подходи ко мне!}
{176}{}{Да как ты смеешь, шваль запомоенная?! Пора тебе крови пустить...}

{177}{}{Обычно я играю на деньги. Скажем, не меньше 500. Но если у тебя есть хорошая наркота - могу поиграть и на нее. Ну, что ставишь? (достает свои карты, вы не уверены, что они не крапленые)}
{178}{}{Я не играю.}

{179}{}{Ставлю 500 баксов.}
{180}{}{Ставлю 5 пачек антикурильщика.}
{181}{}{Ставлю суперстимулятор.}
{182}{}{Ставлю 3 стимулятора.}
{183}{}{Ставлю бутылку "Вианса Винери".}

{184}{}{Ставка что надо. Ха, да я тебя обыграю в первой же партии!}
{185}{}{Хорош порожняк гнать. Играем.}
{186}{}{(Форсажник раскладывает карты, вы выбираете свою партию, он свою. Пока все честно)}
{187}{}{(дальше)}
{188}{}{Ха-ха! Да кто так сдает? Просрал туза и даму! Да я тебя в следующей партии уже заделаю!}
{189}{}{Ух ты! Ух ты! Откуда у тебя туз появился? Он же вроде... А, ну да. Давай дальше.}
{190}{}{(Игра подходит к концу, пора разворачивать карты и подсчитывать очки)}
{191}{}{(Выложить карты)}

{192}{}{Ничья! Черт, да ты серьезный противник, надо с тобой играть поосторожнее.}
{193}{}{Сыграем еще раз.}
{194}{}{Да ты шулер! Отдавай рюкзак!!!}
{195}{}{Я же говорил, что тебя уделаю! Твое теперь стало моим. А ты иди, поплачь о потере.}

#Игра
{200}{}{Меня интересуют баксы, поэтому я ставлю со своей стороны какие-то вещи, обычно наркоту, а ты ставишь наличку. Все еще интересует?}
{201}{}{Интересует. Что ставишь на этот раз?}
{202}{}{Не интересует. Еще вопрос.}
{203}{}{Не интересует, я ухожу.}

{204}{}{Я ставлю целебный порошок. Все стерильно, не ссы. У Жирюги с этим делом всегда все нормально. Ставка с твоей стороны 50 баксов.}
{205}{}{Не дергайся, монета есть. Играем.}
{206}{}{Но у меня не хватает наличности...}
{207}{}{Я играю *только* на деньги.}

{208}{}{Я опозорю тебя уже в первой партии. (Достает карты и начинается игра)}
{209}{}{(Отказаться от игры)}
{210}{}{Да ты шулер! (попытаться отобрать деньги)}
{211}{}{Да что б тебя!... (бросает на стол ваш выигрыш)}
{212}{}{Отвали от меня. Я больше играть с тобой не буду.}

{213}{}{Я ставлю суперстимулятор. С твоей стороны 100 баксов.}
{214}{}{Я ставлю психо - величайший наркотик из тех, что тебе попадались в этом регионе! Ставка 300 баксов с твоей стороны.}
{215}{}{Черт, ты меня начинаешь нервировать. Хорошо, я рискну и поставлю свой ствол с патронами. 500 баксов с твоей стороны - вот мои условия.}
{216}{}{Вот дерьмо! Это будет моя крайняя ставка! Или я тебя сделаю, или вообще завяжу с картами! 700 баксов с твоей стороны за мощнейший наркотик! (показывает вам странное вязкое вещество, завернутое в газетку) Его вывели наркоделы в Рино, уникальный образец. Чувака, который сделал эту жвачку, прикончили, поэтому ты больше нигде не найдешь такой дозы. Забьемся?}

#Отработка рюкзака лекаря сексом
{217}{}{О, пупсик, давай не будем усложнять? У тебя товар, а у меня подходящее тело. Соображаешь?}
{218}{}{Я быстрее соглашусь трахнуть геккона в жопу. Там хотя бы будет экстрим.}
{219}{}{Хам!}
{220}{}{Ну как хочешь.}
{221}{}{О, детка! Прелесть сама лезет в штаны! Ущипните меня, это правда или меня все еще торкает после вчерашнего?! Черт, я готов прямо сейчас, но предупреждаю - я любитель погорячее!}
{222}{}{Горячего захотелось? М... тогда отменяется.}
{223}{}{Эй-эй-эй, детка! Не спеши, давай все обсудим! (задвигает к вам)}
{224}{}{Только попробуй, кобель - и получишь по яйцам!}
{225}{}{Не трогай меня!}
{226}{}{Эй! Я понял тебя, детка, я понял! Остынь.}
{227}{}{То-то же!}
{228}{}{(переигрывает с насмешкой) "Не трогай меня", ла-ла-ла. Ты откуда такая, нежная, вылезла? Ладно, вали отсюда, пока я не передумал!}
{229}{}{Ишь какое хамье пошло...}
{230}{}{Ну вот и хорошо.}
{231}{}{По мне, что надо! Доставай контрацептив... Да, и рюкзачок не забудь выложить.}
{232}{}{(Вы уходите в подвал, чтобы заняться там грязным и грубым сексом)}
{233}{}{(Далее)}
{234}{}{О-о-о! Детка, я так еще не кончал!!!}
{235}{}{Упыхался так, до завтра не отлежусь... О-о-о! Детка, я так еще не кончал!!!}
{236}{}{После длительного жесткого секса вы получаете предмет, который требовали.}
{237}{}{Ой, да ладно тебе, дружок, я хотела тебя позлить. Давай сделаем это, расслабься!}
        
#Женские реплики (Kerb)
{1150}{}{Чего скажешь, подруга? Или просто решила помухлевать на моих картах? Ну как, рискнешь?}
{1159}{}{Э, барыга! Ты это с чего спросила вдруг?}
{1171}{}{Черт, загрузила ты меня, мучача. Ну, давай 500.}
{1188}{}{Ха-ха! Да кто так сдает? Просрала туза и даму! Да я тебя в следующей партии уже заделаю!}