{100}{}{You see Rot.}
{101}{}{You see a filthy smelly junkie nicknamed Rot.}

#Плавающие фразки перед пропоем:
{102}{}{Damn... fucking withdrawals...}
{103}{}{I'm out...}
{104}{}{Probably... or better not?}
{105}{}{I guess I should get high}
{106}{}{Looks like I threw up a bit here}
{107}{}{*moans*}
{108}{}{*scratches his groin*}
{109}{}{Damn...}
{110}{}{There must be a price on my head already}
{111}{}{Go away!}
{112}{}{Fuck off!}
{113}{}{Let me freshen the nip first}
{114}{}{Some booze would make my day...}
{115}{}{I think I'm about to die!..}
{116}{}{Get me some liquid... I don't care what, brahmin piss, whatever!}
{117}{}{What? Who? Where? Why?!}
{118}{}{You're a towel!}
{119}{}{::points at you:: You're fired!}
{120}{}{I'm thirsty...}
{121}{}{I wanna live...}
{122}{}{I wanna die...}
{123}{}{Who's a dopehead, you're a dopehead!}
{124}{}{Just a sip! Don't be such a miser!?}
{125}{}{Just a glass will do!}
{126}{}{If you don't pour me one, I'll... I... Nah, never mind.}
{127}{}{Look, I'm really having it bad this time. Get me some booze, or it will be the end of me.}
{128}{}{Who the hell are you? Then, what do I care.}
{129}{}{Oh come on! half a bottle!}
{130}{}{I'm not asking for much, theses withdrawals gonna do me in, you see?}

# Когда применен на нем не тот предмет:
{131}{}{Suck it!}
{132}{}{Go to hell!}
{133}{}{I'll fucking...}
{134}{}{Get off of me!}
{135}{}{What the shit is this fuck?}
{136}{}{What are you trying for?}
{137}{}{Hey, keep your distance!}
{138}{}{I never asked for this!}
{139}{}{Trying to cheat me, huh?!}

# Когда примено бухло: 
{140}{}{Whoa what the...}
{141}{}{Dayum...}
{142}{}{Oh-oh-oh!!! Here it goes!!!}
{143}{}{I'm off...}

# Когда упал после применения бухла: 
{144}{}{I'm out, man. Wayyyy out...}
{145}{}{*snores*}
{146}{}{Either I just shit myself or... no, that is it...}
{147}{}{*unconscious*}
{148}{}{*zzzzzz*}
{149}{}{*it appears he has shat his pants*}

# Диалог
{150}{}{Hey, dude, your booze was real swill! I've barfed my insides out! Can you get me something less awful? I'm having it real tough...}
{151}{}{Can't you manage yourself? I think I've seen a still in the next room.}
{152}{}{No, don't give a shit. Bye.}
{153}{}{You shouldn't drink that much.}

{154}{}{You see, the thing is - Fatso says he's had enough of me. So he won't give me any. I have no voice in this gang. And you're new, they might share with you.}
{155}{}{All right, I'll get you something to drink. Try not to die in the meantime.}

{156}{}{So, where's the booze?}
{157}{}{Give him beer.}
{158}{}{Give him booze.}
{159}{}{Give him Rot Gut.}
{160}{}{Give him a "Bloody Mary".}
{161}{}{Oh yeah, wait a sec, I'll get it.}

{162}{}{Damn, thanks, friend... (avidly chugs the alcohol and burps loudly) Aah! Man, you... I'm... just... wow! You see, in this gang it's, well, complicated. You're new, so you'll understand later. Listen... Maybe you could do me another one? My body is in poor shape, as you can see. I need some treatment. Fatso makes this healing powder from weeds. Man, it makes you fly and take you high! Could you ask him for some, mmm? I'm kind of dying here...}
{163}{}{You get experience for the "delivery".}
{164}{}{I'll try to.}

{165}{}{Man, I'm cracking up... I need medicine... Like healing... herbs, heh heh... Oh...}
{166}{}{There you go. Go on, heal up.}
{167}{}{Good luck then.}
{168}{}{Wh... Are you serious? Friend!! Thank you! Thanks! Come on, gimme a hug, man!}
{169}{}{You got the junkie another fix.}

{170}{}{(Rot is writhing on the floor in convulsions) Aaah... ma-an... It's bad! This time for real... I need a fix... now... you gotta give me some acid... painkillers... anti-smoker... It's bad, real bad, can't you see? For real...}
{171}{}{Hey, Rot, here's some pills for you. This should help! (put anti-smoker in his mouth)}
{172}{}{Hold on, dopehead! Here come the mounties to the rescue!}
{173}{}{Do I look like a dealer to you? What do I got to do with your withdrawals?}

{174}{}{(He seems to feel a bit better)}
{175}{}{Leave him on the floor.}

{176}{}{(almost crying) You scum of the Earth! I'm dying here, and you have the... Here, you stinker! just get me a fix... Get it to me! (gives you his last money)}
{177}{}{You get another fix for the junkie and gain 250 exp. points.}

{178}{}{Psss... eh... wh... pssssycho... get... ps.... psychoooo... (he looks like he badly needs a dose)}
{179}{}{Inject him with psycho.}
{180}{}{Hey, what am I, Mother Teresa!? (search junkie's clothes for valuables)}
{181}{}{You perform a cavity search on the junkie, trying unsuccessfully to ignore the stench. All he has on him is an old pistol, which you take as payment for your troubles.}
{182}{}{You struggle to find a vein on the junkie's withered lacerated arm and pierce it with a needle. Convulsions stop, but Rot remains unconscious.}
{183}{}{Leave him to sleep it off.}

# Отладка:
{184}{}{Perception: }

{185}{}{(slip anti-smoker into his mouth)}
{186}{}{(slip painkillers into his mouth)}

# Когда враждебен, видит и нападает:
{200}{}{Hey you!!!}
{201}{}{Waste the motherfuckers!!!}
{202}{}{Let's get it over with already, I want to shoot up!}
{203}{}{Die! Diiie!!!}
{204}{}{Let's dance, girl!}
{205}{}{Remember God's gonna cut you down! Or maybe I will!}
{206}{}{Be a good sport and hold still!}
{207}{}{Somebody thinks they are cool, eh?}
{208}{}{We'll get 'em!}
{209}{}{That should take my mind off withdrawal pains...}

# Женские реплики
{1150}{}{Hey, girl, your booze was real swill! I've barfed my insides out! Can you get me something less awful? I'm having it real tough...}
{1162}{}{Damn, thanks, friend... (avidly chugs the alcohol and burps loudly) Aah! Man, you... I'm... just... wow! In this gang it's all, well, complicated. You're new, so you'll understand later. Listen... Maybe you could do me another one? My body is in poor shape, as you can see. I need some treatment. Fatso makes these healing powders from weeds. Man, they take you high and make you fly! Could you ask him, mmm? I'm kind of dying here...}
{1168}{}{Wh... Are you serious? Friend!! Thank you! Thanks! Come on, gimme a hug, man!}
{1170}{}{((Rot is writhing on the floor in convulsions) Aaah... ma-an... It's bad! This time for real... I need a fix... now... you gotta give me acid... painkillers... anti-smoker... It's bad, real bad, can't you see? For real...}