{100}{}{Hunter.}
{101}{}{A seasoned and experienced hunter of the Cheyenne tribe.}

#Попытаться подвинуть
{102}{}{Me move.}
{103}{}{We go.}
{104}{}{Slow down, outlander.}
{105}{}{Me shuffle way.}
{106}{}{Awrite.}

#Попытка заговорить
{107}{}{Me no talk your tongue.}
{108}{}{Me come eat.}
{109}{}{Me no talk.}
{110}{}{Me no want.}

#Попытка заговорить при зависимости от наркоты
{111}{}{Magic herbs, yes?}
{112}{}{Your soul escape your body, fren?}
{113}{}{What you look at?}
{114}{}{Me no like this.}

{115}{}{It no smell good.}
{116}{}{You do wrong.}
{117}{}{We no want, but you force.}
{118}{}{Bad outsider! Shoo!}
{119}{}{What tribe you from?}
{120}{}{Our tribe never forget it!}
{121}{}{Son of the Eater must die!}

{122}{}{}
{123}{}{Bad outsider! Bad!}
{124}{}{Your tribe has our respect.}
{125}{}{I never forgive it!}

{126}{}{Ooh! Baby boy so big already!}
{127}{}{My child.}
{128}{}{You behave?}
{129}{}{Kid look like me.}
{130}{}{Me make this child.}
{131}{}{If child happy, me happy.}
{132}{}{We a family, child. Behave.}
{133}{}{You behave, child?}
{134}{}{Me want food!}
{135}{}{Me go to roof!}
{136}{}{Mmm! Magic herb tea.}
{137}{}{Mmm! Gecko stew with shrooms today!}
{138}{}{Mmm! Kitchen smell so good!}

{139}{}{Who go there?}
{140}{}{Who you?}
{141}{}{We know you?}
{142}{}{Outlander come to trade?}
{143}{}{Outlander want gecko pelt?}
{144}{}{Outlander buy gecko pelt?}
{145}{}{We no like outsiders.}
{146}{}{We want outlander leave soon.}