{101}{}{You see The Boss.}
{101}{}{Before you stands the local boss, who's known simply as... the Boss.}
{102}{}{Alarm! We got an intruder!}

#talk starts
{108}{}{Nothing. I'm getting outta here}
{109}{}{You again? Nice. What is it this time?}
{110}{}{Stop right there and keep your hands in sight, pal! Why the heck have you stormed in here?}
{111}{}{Got any job for a stranger?}
{112}{}{Ya heard the news? Factory ain't recovering from the troubles any time soon.}
{113}{}{I'm executing Salt Lake Sheriff's will and hereby demand that you give up the criminal Gary Gilmore to justice right fucking now!}
{114}{}{Heard the news? Salt Lake Sheriff's dead!}
{115}{}{Thought it'd be some kind of a hotel. Apparently it's not.}

#nuka plant sabotage
{116}{}{The messenger already told us about the sabotage. You've proven to be a useful asset, so we won't kill ya. *smiles* Here's your pay (gives you $20,000). And kiddo, if I were you - I'd lie low for a coupla' weeks in another city.}
{117}{}{Huh, wish all my jobs paid that well.}
{118}{}{Maybe... If you and I... umm... have an agreement. Ya see me?}
{119}{}{Smells like shady deals. I like it.}
{120}{}{}
{121}{}{Guess you already know about the Nuka-Cola plant in Salt Lake. That is, all residents of our camp live and dream to see somebody sabotagin' the damned thing. You got two options here: either break the conveyor or poison the tanks.}
{122}{}{What's the pay?}
{123}{}{No way, no more dirty business for me!}
{124}{}{}

{125}{}{Don't you worry about the money. Let's say... 20,000. I think that should do it. I'll provide the poison from my own stash, still keep a few flasks for an occasion like this one...}
{126}{}{Why'd you want this plant sabotaged?}
{127}{}{We're going to settle accounts with Salt Lake. Some old affairs, which are none of your business, lemme tell you. Just get the job done and the cash is yours.}
{128}{}{Fine. I'm ready to get down to work.}
{129}{}{Ain't gonna do no more dirty business. No!}
{130}{}{Excellent! Take the flask, then. You only have to break into the workshop and pour it into tanks, and I don't care how you're gonna do it. There's a rumor going round about a tunnel underneath leading to the site... The means are up to you, we pay for the result.}
{131}{}{I'll do that.}

#refusing the sabotage quest
{132}{}{What's the matter, wanderer? Don't have the guts for the job?}
{133}{}{I disapprove any shady business!}
{134}{}{Well, the choice is yours. But remember - good money's waiting for ya, and sure as hell it's not gonna wait for long.}
{135}{}{I need some time to think it over.}

#Gacy line
{136}{}{(Squints at you) Not sure if I heard this name before...}
{137}{}{So is he here or not?}
{138}{}{Huh. Why the fuck should I give him away anyway?}
{139}{}{So you admit it. Let's settle this matter the good way.}
{140}{}{And what ya gonna do?! There's no mommy-sheriff here to stand up for ya, sucker...}
{141}{}{I'll slaughter all of you and bring your heads as a gift to the sheriff!}
{142}{}{Nevermind. I'll find him myself.}

{143}{}{Just like I thought, the sheriff doesn't have the balls to visit us in person. Send him my words, he's just a sissy with a mustache!}
{144}{}{Hmm... If you dislike the sheriff so much, I could consider a counteroffer for an adequate sum.}
{145}{}{How dare you slander the name of this saint! [attack]}
{146}{}{I'll send him your message, and soon we'll be back with bloodthirsty friends and heavy fireworks.}

{147}{}{That's impressive! If he's taken care of, I'll pay you 20 grand.}
{148}{}{OK, I'll do that.}
{149}{}{No, I don't like the sound of it.}
{150}{}{But don't forget - we had nothing to do with this.}
{151}{}{Got it. You may start gathering the cash.}
{152}{}{Good news. Gotta give you credit - not many would venture to do that even for such money (gives you $20,000). Excellent job.}
{153}{}{Wow, assassin wasn't the worst career choice by far.}

{1110}{}{Stop right there and keep your hands in sight, girl! Why the heck have you stormed in here?}
{1111}{}{Got any job for a stranger?}
{1130}{}{Excellent! Take the flask, then. You only have to break into the workshop and pour it into tanks, and I don't care how you're gonna do it. There's a rumor going round about a tunnel underneath leading to the site... The means are up to you, we pay for the result.}
{1132}{}{What's the matter, sweetie? Don't have the guts for the job?}

#Переводчик: Pyotr
#Редактура: Rigel

