#Стартовые сообщения районов Солт-Лейка:
{100}{}{You enter a gloomy and cheerless-looking town. It smells of damp and rotting foliage.}
{101}{}{You enter Salt Lake City's residential area. Seeing children play in the streets without a care in the world makes your eyes moist.}
{102}{}{You walk into an abandoned locomotive depot.}
{103}{}{These derelict slums are long deserted. But still some rather fresh footprints can be seen in the sand.}
{104}{}{This place still screams of blood and suffering. Looks like the vault inhabitants had a quarrel and beat each other to death.}
