{100}{}{A water cooler with water in it.}
{101}{}{An empty water cooler.}

{102}{}{You see a cooler filled with clean spring water.}
{103}{}{You see an empty cooler. Someone has chugged all the water.}

{104}{}{Not a drop of water left in this cooler.}
{105}{}{You pour a flaskfull of pure spring water.}
{106}{}{}

{107}{}{There's some water left in this cooler. You'll need a vessel if you want to collect it.}
{108}{}{Need a bottle}
