{100}{}{}
{101}{}{}

{110}{}{These boards are still quite suitable for construction.}
{111}{}{You don't need these boards anymore.}
{112}{}{With your physique carrying such weights can result in trauma.}
{113}{}{Oomph...}
{114}{}{This will hardly be of use here.}
{115}{}{Construction finished}
{116}{}{You've built the hinged part of the bridge.}
{117}{}{These boards could be used for construction.}
{118}{}{Just some boards}
