{0}{}{}
{100}{}{You see a console.}
{101}{}{You see a password entry console. It got to be controlling the door nearby.}
{102}{}{You've already hacked this console, it has no use for you anymore.}
{103}{}{I don't need this}
{104}{}{This console has no power supply.}
{105}{}{No power}

#Начало диалога:
{110}{}{Welcome. Please enter password.}
{111}{}{Hmm, maybe I should try these passwords from Power Plant manager's note?}
{112}{}{Try to guess the password.}
{113}{}{Exit.}

{114}{}{Password accepted. Welcome!}
{115}{}{Finish.}
{116}{}{You hack the security system and gain }
{117}{}{ exp. points.}
{118}{}{Password incorrect.}
{119}{}{Well, time to enjoy the comforts of someone's office.}

#Процесс подбора пароля
{120}{}{The system only accepts passwords consisting of letters of the English alphabet. All that's left for you to do is cycle through variants.}
{121}{}{Enter the password.}
{122}{}{You are entering: }
{123}{}{?}
{124}{}{Clear last letter.}
{125}{}{Clear everything and start over.}
{126}{}{Password incorrect.}
{127}{}{Password accepted. Welcome!}
{128}{}{}
{129}{}{}
{130}{}{}

{150}{}{A}
{151}{}{B}
{152}{}{C}
{153}{}{D}
{154}{}{E}
{155}{}{F}
{156}{}{G}
{157}{}{H}
{158}{}{I}
{159}{}{J}
{160}{}{K}
{161}{}{L}
{162}{}{M}
{163}{}{N}
{164}{}{O}
{165}{}{P}
{166}{}{Q}
{167}{}{R}
{168}{}{S}
{169}{}{T}
{170}{}{U}
{171}{}{V}
{172}{}{W}
{173}{}{X}
{174}{}{Y}
{175}{}{Z}
{176}{}{-more-}
{177}{}{Finish entering the password.}
{178}{}{To the beginning of the alphabet.}
{179}{}{Back.}
