{100}{}{It's a switch.}
{101}{}{You see a light switch. It's in the "on" position.}
{102}{}{You see a light switch. It's in the "off" position.}
{103}{}{This switch turns the lights on or off on the underground level of the station.}

{110}{}{You switch off the light and the underground level of the station sinks into darkness.}
{111}{}{You turn on the light on the underground level of the station.}
{112}{}{Hmm, flipping the switch doesn't appear to have any effect. Maybe the power is out?}
{113}{}{Done}
{114}{}{Let there be darkness!}
{115}{}{Let there be light!}
{116}{}{Nothing happens}
