{100}{}{You see a water tank.}
{101}{}{You see a huge tank full of fetid water. It's rusted through and is leaking in several spots.}
{102}{}{You see a huge water tank in okay condition.}
{103}{}{You can't examine the water tank in combat!}

#Описание при юзанье или использовании навыков
{110}{}{It's just a huge tank}
{111}{}{You see a huge water tank. It's almost empty.}
{112}{}{Good as new!}
{113}{}{The water tank hull is restored to the joy of the whole tribe.}

#Описание в режиме диалоге
{120}{}{You see a defective water tank belonging to the tribe.}
{121}{}{Examine thoroughly.}
{122}{}{Attempt to repair.}
{123}{}{Leave it be.}

{124}{}{The tank has rusted through in several spots and can not hold water anymore. To repair it one will have to replace several metal plates using a welding apparatus and some scrap. And if scarp is hardly ever a problem, all the rest might take some work to procure. Technicians in bigger settlements may have something of the sort.}
{125}{}{The tank has rusted through in several spots and can not hold water anymore. To repair it one will have to replace several metal plates using a welding apparatus and some scrap.}
{126}{}{You don't have the necessary equipment for the repair.}
{127}{}{You don't have scrap metal for welding.}
{128}{}{You start working and as one sloppy conglomeration of metal after the other takes its place on the side of the water tank, your belief that you just don't have the necessary repair skills for this job only grows stronger.}
{129}{}{Using a welding apparatus and your skillful hands you restore the damaged spots of the tank. Now this tank will serve the tribe for another twenty-some years.}
{130}{}{Great!}
{131}{}{You repair the water tank and gain }
{132}{}{ exp. points.}
