{100}{}{Decrepit wall falls apart completely.}

{101}{}{You examine the water tank and discover some muddy rainwater in it. Looks like that's what the raiders drink when they can't find anything stronger. They all must suffer from flux. And if you spoil the water any further - it may actually become fatal even for them.}
{102}{}{Leave.}
{103}{}{ You have some poison in your posession, but it's not enough for such an amount of water.}
{104}{}{ You have enough poison to lethally intoxicate all the raiders.}
{105}{}{Release poison into the water tank.}
{106}{}{You've released deadly poison into the water tank. Now everyone who drinks this water will die... Or so you hope. You should check back in a day or so to verify the veracity this theory.}
{107}{}{You gain 3000 exp. points.}
{108}{}{Water is still undrinkable.}
{109}{}{You examine the water tank and discover some muddy rainwater in it. Looks like that's what the raiders drank when they couldn't find anything stronger. They all must have suffered from flux.}
{110}{}{The water is still poisoned.}
{111}{}{One dose of poison won't be enough, you'll need at least two more. [Leave]}
{112}{}{Two doses of poison are not enough. If someone is left alive, the'll realize what happened at once. If only you could get another dose... [Leave]}
{113}{}{Looks like the poison acted violently. The raiders are dead! And looks like their death was nothing like gentle and easy.}

{114}{}{Not during combat!}
{115}{}{Raiders used to drink this muddy water. Now it's unneeded.}
{116}{}{The water is poisoned.}
