{100}{}{Труп.}
{101}{}{Труп засосало в матку по грудь, но, кажется, эти останки все еще дышат!}

#Диалог:
{102}{}{Мм... ммммм....}
{103}{}{Эй! Вы меня слышите? Вы понимаете, что я вам говорю?}

{104}{}{Мэээээ...}
{105}{}{Мужик, тебе, кажется, хреново. Может, тебя вытащить из матки?}
{106}{}{Оставить его в покое.}

{107}{}{Сс... спассии...}
{108}{}{Попытаться вытащить.}
{109}{}{Оставить его.}

#Таймерная сцена:
{110}{}{Эй, мужик, вставай, пока нас не сожрали!}
{111}{}{Ну же!}
{112}{}{Срань господня!...}
{113}{}{Тебе повезло, мужик, что живой остался!}
{114}{}{Хреново как... погоди... я... сейчас...}
{115}{}{Что?}
{116}{}{ААААААААА!!!}

{117}{}{ОХРЕНЕТЬ! Это что было?}
{118}{}{Увы, жизнь этого бедняги была предрешена.}
{119}{}{}

#Таймерные плавающие реплики
{120}{}{::стон::}
{121}{}{::хрипение::}
{122}{}{Ооохх...}
{123}{}{Хрр...}
{124}{}{Ммм...}
{125}{}{Спаси...}

#После выпуска газа
{200}{}{Этот мертвяк - не жилец. Похоже, что он умер не от биомассы, засосавшей его, а наоборот - когда биомасса погибла от газа, погиб и этот человек… то есть то, что от него осталось.}
{201}{}{Проверить карманы трупа.}
{202}{}{Оставить труп.}
{203}{}{Теперь эти останки не представляют из себя ничего интересного.}
{204}{}{Неожиданно вы находите в останках прибор наведения для энергетического оружия и красную ключ-карту.}
{205}{}{Больше здесь ничего нет.}
