{100}{}{Nothing happens}
{101}{}{The remote doesn't work from here.}
{102}{}{No luck}
{103}{}{The signal didn't come through, move closer to the field generator.}
{104}{}{Done}
{105}{}{The remote worked.}
