{100}{}{You see a door.}
{101}{}{An electronic door. Sadly it will never open without power.}
{102}{}{An electronic door. Due to unstable power supply its behavior is unpredictable.}
{103}{}{With no power the door won't open}
{104}{}{The power supply is unstable, right now there's not enough power to open the door.}
{105}{}{An electronic door. There must be an emergency opening system somewhere.}
{106}{}{Your skills are useless here. look for an emergency opening system.}
{107}{}{Access key required.}
{108}{}{Access key is required, but you don't have one. There must be an emergency opening mechanism.}
