{0}{}{.}
{100}{}{Сейф с кодовым замком.}
{101}{}{Перед вами сейф, запертый на сложный кодовый замок.}
{102}{}{Перед вами сейф со вскрытым кодовым замком.}

#Использование предметов и скиллов:
{110}{}{Это ничего не даст, вы уже вскрыли сейф.}
{111}{}{Вы не можете это делать во время боя!}
{112}{}{Один из паролей подошел к замку!}
{113}{}{Заперто}
{114}{}{Сейф заперт на кодовый замок.}

#Использование предметов
{120}{}{Сейф заперт на механический замок с роликовым затвором. Так как им почти не пользовались, то взломать по слуху будет почти невозможно.}
{121}{}{Набрать код в ручную.}
{122}{}{Попытаться взломать.}
{123}{}{Уйти.}

{124}{}{Код: }
{125}{}{ -- }
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

{130}{}{1}
{131}{}{2}
{132}{}{3}
{133}{}{4}
{134}{}{5}
{135}{}{6}
{136}{}{7}
{137}{}{8}
{138}{}{9}
{139}{}{0}

{140}{}{Еще.}
{141}{}{Назад.}
{142}{}{Удалить.}
{143}{}{Завершить.}
{144}{}{}

{145}{}{Код введен неверно.}
{146}{}{Очистить и начать заново.}
{147}{}{Завершить.}

{150}{}{Введен правильный код! Сейф открывается.}
{151}{}{С таким восприятием, как у вас, вы не сможете услышать даже выстрел под ухом, не то что подобрать на слух код.}
{152}{}{Ваших навыков явно недостаточно для вскрытия замка. Даже не пытайтесь - ничего не получится, слишком это сложно для вас.}
{153}{}{Ничего не происходит. Попробуйте еще раз, более внимательно.}
{154}{}{Попробовать еще раз.}
