{100}{}{Контроллер подачи электроэнергии.}

#Описания:
{101}{}{Вы видите контроллер подачи энергии из резервуаров подстанции в здания базы. Он поврежден.}
{102}{}{Нужен ремонт и замена деталей}
{103}{}{Вы видите сгоревший контроллер подачи электроэнергии в здания базы. Он гудит и источает ток.}
{104}{}{Работает}

#Использование предметов:
{110}{}{Что вы собираетесь ремонтировать? Сперва внимательно осмотрите эту технику.}
{111}{}{Сперва нужно изучить повреждения}
{112}{}{Эта техника не нуждается в ремонте, т.к. находится в рабочем состоянии.}
{113}{}{В ремонте не нуждается}

#использование навыков:
{114}{}{Техника работает. Вы не знаете, надолго ли...}
{115}{}{У контроллера повреждены кабели, но они по-прежнему находятся под напряжением.}
{116}{}{Нужен металлолом для замены деталей}

#Починка:
{117}{}{Вы не сможете починить генератор без новых деталей.}
{118}{}{Вы не сможете ничего сделать голыми руками. Здесь нужны инструменты.}
{119}{}{Нужны инструменты}

{120}{}{Система в порядке, а вот вас немного "поджарило"!}
{121}{}{Вот дерьмо!}
{122}{}{Система в полном порядке!... на некоторое время.}
{123}{}{Готово!}

{124}{}{Починка не удалась. Что-то вы делаете не так.}
{125}{}{Ваших навыков в ремонте не достаточно.}
{126}{}{Не получилось}
{127}{}{Не хватает умения}

#Диалог:
{130}{}{Перед вами контроллер подачи электроэнергии в распределительные системы из резервуаров подстанции. Далее электричество должно поступать в строения базы, но некоторые кабели и детали повреждены и обгорели, поэтому половина зданий обесточена. Дело отнюдь не сложное, но нужны новые детали и инструменты, а также техническое мастерство, чтобы вас не поджарило как цыпленка.}
{131}{}{Ясно, нужен металлолом для замены деталей и инструменты.}