{100}{}{Компьютер службы безопасности.}
{101}{}{Этот компьютер вполне работоспособный.}

{102}{}{С вашими знаниями вы не сможете получить от этого компьютера ничего полезного.}
{103}{}{Отмена.}
{104}{}{Дальше.}

{105}{}{Перед вами компьютер службы безопасности.}

#Активация бомбы:
{106}{}{Искать описание к бомбе из Хоторна.}

{107}{}{Как вы и полагали, это ядерная микробомба с плутониевым зарядом мощностью 0,3 килотонн.}
{108}{}{Смотреть историю разработки.}
{109}{}{Смотреть историю испытаний.}
{110}{}{Искать инструкцию.}
{111}{}{Оставить этот раздел.}

{112}{}{Обычные ядерные бомбы были тяжелыми, поэтому их приходилось сбрасывать с самолетов или запускать в виде ракеты. Такое оружие могли успеть зафиксировать уже на подлете и даже сбить. Поэтому военные США пытались разработать мобильный минизаряд для локальных диверсий. Разработка велась на нескольких военных базах, основные испытания проводили на полигоне в 100 км от Лас-Вегаса.}
{113}{}{Испытания прототипов увенчались слабыми результатами. Неразрешимых проблем оказалось две. Первая - результаты подрыва ядерного заряда такой малой величины зависят от многих внешних факторов, и поэтому заранее предсказать эффективность взрыва практически невозможно. Вторая - большая критическая масса веществ, необходимых для возникновения самоподдерживающейся цепной реакции ядерного деления. Для плутония такая масса составляет 22 фунта. С учетом корпуса, электроники и прочих компонентов плутониевые микробомбы весили от 40 фунтов и более, что просто не отвечало поставленной задаче - сделать бомбу мобильной.}
{114}{}{Вы находите схемы сборки. Процесс выглядит довольно замудренным, но благодаря этому терминалу вы, скорее всего, сможете собрать бомбу и активировать ее.}
{115}{}{Попытаться собрать и активировать бомбу.}
{116}{}{Нет, оставить штуку в покое.}
{117}{}{Вы провели час за анализом микросхем, и наконец у вас получилось! Вы смело снимаете крышку таймера. Бомба готова к активации. Какое время установить? (Хорошо обдумайте свои действия! После взрыва попасть в ангар будет невозможно!)}

{119}{}{Вы задаете время и смело жмете на красную кнопку. Пора призадуматься о своем будущем, если не хотите стать частью радиационного фона...}
{120}{}{Бежать со всех ног...}

{121}{}{1 минута.}
{122}{}{2 минуты.}
{123}{}{3 минуты.}
{124}{}{4 минуты.}
{125}{}{5 минут.}
{126}{}{Отказаться от активации и выйти.}
{127}{}{Вернуться в главное меню.}
{128}{}{Отмена. Вернуться в главное меню.}

{129}{}{Вы находите схемы сборки. Однако процесс выглядит для вас слишком замудренным, поэтому без специальных знаний в области подрывного дела эти схемы вам ничем не помогут.}

{130}{}{Не доступно во время боя.}
{131}{}{Не работает}
{132}{}{Терминал отключен.}

#Активация турелей:
{200}{}{Изучить программу управления турелями.}
{201}{}{Запустить программу управления турелями.}
{202}{}{Вернуться в главное меню.}
{203}{}{Завершить.}
{204}{}{Видимо, программа не функционирует.}
{205}{}{Искать отчеты.}
{206}{}{В компьютере имеется незаконченный отчет об ошибке, но четкого алгоритма лечения программы не выявлено.}
{207}{}{Смотреть исходный код программы.}
{208}{}{Это слишком сложно для вас.}
{209}{}{Проведя 6 часов за анализом кода, вы обнаруживаете, что ошибка находилась в циклической процедуре, проверяющей переменные сигнала турелей. Но так как сигнал и цикл оказывались не синхронны, то программа принимала это как сбой в работе компьютера и начинала перезагрузку. Вы могли бы обнулись цикл, что избавит от этой проблемы, и сделать программу вновь работоспособной.}
{210}{}{Рекомпилировать программный код и запрограммировать на повальное уничтожение пришельцев.}
{211}{}{Готово. Запустить программу?}
{212}{}{Да.}
{213}{}{Нет, оставить отключенной.}
{214}{}{Готово! Программа приступила к работе. На мониторах видеонаблюдения видно, как турели расстреливают пришельцев, ползающих за стенами ангара.}
{215}{}{Только не с вашими интеллектуальными способностями.}
{216}{}{С вашим образованием здесь *абсолютно* делать нечего.}
{217}{}{Будь вы намного более образованней, возможно, этот код удалось бы прочитать.}
{218}{}{Возможно, вы смогли бы разобраться в коде, будь вы немного образованней.}
