{100}{}{Forcefield generator.}
{101}{}{You see a forcefield generator.}

{110}{}{The forcefield inflicts heavy damage.}

#Просто поюзать (рука, предметы,скиллы):
{111}{}{Access denied}
{112}{}{The forcefield will not turn on unless you have highest level access.}
{113}{}{This does nothing.}
{114}{}{No use}
{115}{}{A different approach is needed.}

#Включение и выключение поля:
{116}{}{You switch off the forcefield.}
{117}{}{You switch on the forcefield.}
{118}{}{Done}

#Взлом системы защиты:
{120}{}{You fail to bypass protection.}
{121}{}{Fail}

{122}{}{You successfully hack this complicated electronic mechanism and the forcefield restores.}
{123}{}{You successfully hack this complicated electronic mechanism and the forcefield disappears.}
{124}{}{Done!}
