{100}{}{You see a private.}
{101}{}{You see an ordinary private... though his mug looks more like that of a common criminal.}

#Когда видит и бежит к чузу
{102}{}{There he is! Halt! I said stop right there!!!}

#Пытаются запрятать за решетку
{110}{}{Hey you! Put your hands in the air! You're under arrest! }
{111}{}{Hey, easy, man! I haven't done anything!}
{112}{}{Bullshit!}

{113}{}{We'll see about that...}
{114}{}{(you are taken to the local prison cell, stripped of all belongings)}
{115}{}{It appears you weren't arrested, but barbarously robbed!}

#Женские реплики (Kerb)
{1102}{}{There she is! Halt! I said stop right there!!!}
{1110}{}{Hey you! Put your hands in the air! You're under arrest! }
{1111}{}{Hey, easy, man! I haven't done anything!}