{100}{}{You see a townsman.}
{101}{}{You see a common Wind of War citizen.}

{102}{}{You shouldn't be out here...}

#Наем проводника:
{500}{}{Are you allowed to be here? Who are you looking for?}
{501}{}{I'm looking for daring folks who want to make some easy dough on a pleasure trip. Seen any?}
{502}{}{Not you, that's for sure.}
{503}{}{Hey, smartass! This isn't some caravan shack. Which is where you should be heading. And don't loiter here. Got it?}
{504}{}{Got it.}
{505}{}{Well, come to think of it... What's there to keep me from making some extra money? If it is as easy as you say it is. What did you say I got to do?}
{506}{}{(explain the task)}
{507}{}{Deal. Sounds simple enough for me. But caravaners won't take me to Salt Lake. I'll have to get to Vegas first, and then... I reckon... Yeah, that'll take about fifteen hundred to get me there.}
{508}{}{Here's the money. See you in Salt Lake.}
{509}{}{I'll be back with the money, don't go anywhere.}

{510}{}{You got yourself a conductor. Now you can go back to Salt Lake and proceed with your mission.}

#Женские реплики
{1503}{}{Hey, smartass! This isn't some caravan shack. Which is where you should be heading. And don't loiter here. Got it?}