{100}{}{You've already studied this work. Now let life be your school.}

{101}{}{The author must have been mad.}
{102}{}{Scientific literature? Not for you!}
{103}{}{This monograph is aimed at qualified medics, you're not able to understand anything in it.}
{104}{}{This monograph abounds in abstract scientific terms, with your level of knowledge trying to to understand anything would be a bit overoptimistic.}
{105}{}{You lack the scientific knowledge necessary to make sense of this monograph.}

{106}{}{Wow, that was quite a bout of brain work!}
{107}{}{You learn a lot about medical practice, but this monograph certainly didn't let you in on any professional secrets.}
{108}{}{You learn nothing new.}
{109}{}{To your own surprise you discover some secrets of human and animal anatomy. This would help you both in therapy and in combat.}
{110}{}{To your own surprise you discover some secrets of human and animal anatomy.}
