{100}{}{You see a Nuka-Cola machine. You wonder if it still works.}

{101}{}{[thunk thunk chaching... sheeew]}
{102}{}{You get a not so fresh bottle of Nuka-Cola.}
{103}{}{Dooohhhh!}
{104}{}{You trick the vending machine.}
{105}{}{ skillfully tricks the vending machine.}
{106}{}{The machine seems to be out of stock.}

{107}{}{He-he! Thieves will be thieves!}
{108}{}{Your coin is forever lost in the depths of this vending machine!}
{109}{}{You receive a new achievement and your stealing skill is increased by 5.}

{110}{}{This vending machine still has several bottles of soda.}
{111}{}{This machine is out of stock.}
{112}{}{Hey! Come back here!}

{113}{}{You see a Nuka-Cola vending machine. Price: $}
{114}{}{.}
{115}{}{This machine requires identity verification.}
{116}{}{This does nothing.}
{117}{}{Insufficient funds.}
