{100}{}{A wanted poster with a crude sketch of the wanted person. The features look familiar.}
{101}{}{The caption goes:}
{102}{}{Wanted dead or alive for infanticide and unscrupulous pilfering. Reward $10 000 dead or $5 000 alive.}
{103}{}{Wanted dead or alive for infanticide. Reward $10 000 dead or $5 000 alive.}
{104}{}{Wanted dead or alive for unscrupulous pilfering. Reward $10 000 dead or $5 000 alive.}
{105}{}{Wanted dead or alive for caravan robberies. Reward $5 000 dead or $2 000 alive.}

#Женский вариант
{1102}{}{Wanted dead or alive for infanticide and unscrupulous pilfering. Reward $10 000 dead or $5 000 alive.}
{1103}{}{Wanted dead or alive for infanticide. Reward $10 000 dead or $5 000 alive.}
{1104}{}{Wanted dead or alive for unscrupulous pilfering. Reward $10 000 dead or $5 000 alive.}
{1105}{}{Wanted dead or alive for caravan robberies. Reward $5 000 dead or $2 000 alive.}
