{100}{}{You see head of the family.}
{101}{}{You see a grim-looking to the point of harshness man.}

#Первый разговор
{110}{}{(Talks nervously and disconnectedly, but his hands clutching a shotgun are not trembling) No abrupt movements, stranger. Keep your hands so that I'd see them at all times.}
{111}{}{Hey, easy! My hands are right here, see. Far from any weapons. Why don't you do the same?}
{112}{}{I suggest we each go our own ways, there's enough wasteland for everyone.}

{113}{}{(Slowly lowers the gun, without taking his keen eyes off you) Sorry, but I got a family to protect, I can't afford being incautious.}
{114}{}{I can understand that, but don't you think you're a bit over-obsessed with security?}
{115}{}{Let's talk later when you've calmed down a bit.}

{116}{}{I'll be watching you.}
{117}{}{It's flattering that I arouse such interest. But let me ask you, why so suspicious?}
{118}{}{Likewise, partner. [Leave]}

{119}{}{Are you saying the world we live in gives much room for trust? We've come a long way, visited a bunch of "civilized" settlements, and the more we see, the more we lean towards keeping away from everybody.}
{120}{}{So what's the problem - nobody's insisting on keeping you company, are they?}
{121}{}{Where are you heading?}

{122}{}{That's true, but we still need to restock our supply of food and spare parts. Besides, there's another problem that drives us westward.}
{123}{}{Problem? Well I happen to be a sort of a problem solver.}
{124}{}{From where did you start your journey?}

{125}{}{Vault 53... What, you don't look surprised? You've heard about the project? Then you know the story in general, and the details... They hardly matter now, given the Vault has been long abandoned. But it never fully functioned anyway, so nothing of value was lost.}
{126}{}{No, wait. I always have time for a good story.}
{127}{}{Yes, you're right, we got to live in the present. You were saying something about some problems...}
{128}{}{Yeah, let's wish each other luck now.}

#Повторный старт диалога
{129}{}{You again?}
{130}{}{I just thought you could use some help. Am I right?}
{131}{}{You got me wondering about your place of origin.}
{132}{}{Let's talk later.}

#История убежища 53
{148}{}{Nothing really good about this story... When the war began, our evacuation went quite swiftly, but that was about it with the good news. I don't know who built Vault 53, but they definitely weren't our fans. All the equipment was constantly failing: a problem with the door mechanism - and we listen to Geiger counter like the fucking radio, faulty water chip - and we drink water mixed with some shit the composition of which better stay unknown. And because of the "innovative" power supply system a part of the Vault had to be cut off completely.}
{149}{}{[-more-]}
{150}{}{The failures came like on fucking schedule - not rarer than once a month. It wasn't just an unlucky coincidence. We were placed under those conditions intentionally, whatever the goal might have been. But if they expected panic and disorder from us, boy were they wrong. Diseases, depression and menacing death only brought us closer together. People grew weary of all that shit - and the survivors decided to come out to the surface. Through the radiated ruins of a big city we got to an old car park, where we created a new settlement... Wow, you're still listening?}
{151}{}{Thanks for the story, but let's turn to more urgent issues. I know I don't look much like a Good Samaritan, but maybe I could help you with something?}
{152}{}{Interesting... Have you personally seen anything worthwhile in your travels?}
{153}{}{Thank you for your time, I need to think about all this...}

{154}{}{The East was deserted... We observed the ruins of Washington and Chicago, but we couldn't even get close to the suburbs because of radiation. And I wanted to show Capitol and Millennium Park to my daughter so much... Don't forget the flora and fauna mutilated by radiation, awaiting to taste your flesh. Once, near Cleveland we bumped into a caravan. Or what remained of it: something crawled out of the catacombs and tore  two dozens of armed men to bits, their blood still steaming in the cold... Seldom have I prayed as vehemently and sincerely as that moment, running away as fast as was humanly possible. You can find life over there only in very small settlements, but the more we took to the West, the more people we met.}
{155}{}{Well, I'm postponing my trip to those parts for now. In the meantime, do you maybe have some work for me?}
{156}{}{Not a very inspiring image. See you later.}

#Лейкемия
{170}{}{(He evidently hesitates before speaking, fidgeting a copper cross on his neck) Nah, what the hell... I'm ready to clutch at any straw by now. Do you know what leukemia is?}
{171}{}{Blood cancer - a lymphoblastic disease of the circulatory system. Is this what you're talking about?}
{172}{}{Err... Yeah, sounds familiar.}

{173}{}{Ha! Do I have the luck of talking to a colleague? Then you understand my predicament - my daughter has T-lymphotropic leucosis. Sure, the search for a cure in this setting sounds like a hopeless endeavor, but I can't just sit and watch her die slowly... What I need is qualified specialists with adequate equipment. Aren't you by any chance an oncologist?}
{174}{}{Me - no... But you could use the experience of Chinese scientists from Beiyang Military Medical Center. I once encountered an interesting article on the subject...}
{175}{}{Sorry, but there's no way I can help you with that.}

{176}{}{I see... Well, do you at least know what bone marrow is? All right, in terms that you'd understand - my daughter has a blood disease that rarely entails favorable outcome. That's why we're looking for people qualified enough to help our girl.}
{177}{}{That's a sad story... It's a pity I can't help you. But you must have other problems apart from that?}
{178}{}{Sucks to be you. Well, good luck.}

{179}{}{(For some time you discuss the cancer-fighting methods of your eastern colleagues) ...and you can avoid bone marrow transplant? Interesting... I heard that in San Francisco resides a group of military doctors from People's Republic of China, who studied in Beiyang university. Don't know if they can help us, but it's a lead. Thank you! This means a lot to me.}
{180}{}{Don't thank me! Good luck to you, you definitely deserve it.}
{181}{}{Yeah, that's nice, but such information has its cost... Catch my drift?}

{182}{}{Oh, sure... I save every penny for my daughter's treatment, but you definitely deserve a part. Thanks again.}
{183}{}{Great. Good luck reaching the coast.}
{184}{}{You got }
{185}{}{ bucks as reward.}

#Мини-квесты
{200}{}{We're running out of water, my wife is trying to cook something edible from odds and ends... Besides, I suspect that my shotgun might have some issues with shell feeder or something. And the engine of this rattletrap is giving me hell again. After our hotdamn vault I became paranoid, I'm constantly checking all the mechanisms, but I just don't have enough skills... I'm a doctor, not an engineer.}
{201}{}{I got water as pure as in a mountain brook. Let's barter?}
{202}{}{I could have a look at your gun. Deal, doc?}
{203}{}{It's been a while since I last rummaged in old engines...}
{204}{}{Did you say "Vault"?}
{205}{}{I don't believe these things are what makes you roam about the land.}
{206}{}{Whoa, you really got a load of problems. I'll go think what I can do.}
{207}{}{Nothing changed since the last time you asked, it's all the same problems...}

{208}{}{I don't have much choice... Well, If you can help, I will surely make it up to you.}
{209}{}{I'll go have a look then.}

{210}{}{About that engine...}
{211}{}{What, you fixed it?}
{212}{}{No, not yet...}
{213}{}{Look, I'm terribly sorry, but now the car's not going anywhere - I killed the engine.}
{214}{}{What!? Good grief, I am such an idiot for trusting a stranger! Ugh... Get out of my sight before I blow your brains out! And don't ever show up again!}
{215}{}{Hey, I tried...}
{216}{}{Wasn't I clear enough!? Then I'll pop one in your brain!}

{217}{}{It's all right now.}
{218}{}{Damn! Thank you, traveler! Purrs like a cat... (hands you a stimpak) I know it's not much for such a bang-up job, but we're tough on supplies, you got to understand.}
{219}{}{Just don't forget to clean the fuel injectors from time to time. Anything else?}
{220}{}{It's good we could help each other out. Well, maybe we'll meet again some day.}

{221}{}{Err... Thanks, but I'd rather sort it out myself.}
{222}{}{What you don't trust me? Good thinking, man. Good thinking.}
{223}{}{Maybe I can help with something else then?}

{224}{}{Hmm... (he hesitates, suspiciously looking into your eyes, but then gives up and hands you the shotgun) Let's see how good you are.}
{225}{}{Don't worry, I know what I'm doing.}
{226}{}{Beware, I might lose my nerve.}
{227}{}{Here you go, good as new.}
{228}{}{Then you better take some pills right fucking now, 'cause you're not getting the gun back!}
{229}{}{Good job! Gunsmiths, like any specialists, are scarce in the wasteland these days... Take this and our gratitude. (hands you $100)}
{230}{}{Nah it was just a worn spring... But gratitude is a good thing, especially when it goes with something substantial. Any other problems?}

{250}{}{I can't offer much for barter. But I learned to make stimpaks from herbs. Will it do? Then I'll trade you one stimpak for every 10 pounds of clean water.}
{251}{}{Just like before - water for stimpaks. Deal?}
{252}{}{[Trade 5 flasks for 1 stimpak]}
{253}{}{[Trade 10 flasks for 2 stimpaks]}
{254}{}{[Trade 15 flasks for 3 stimpaks]}
{255}{}{[Trade 20 flasks for 4 stimpaks]}
{256}{}{Let's talk about it next time. What else did you say you need?}
{257}{}{Maybe, I'll come back when I get some clean water.}
{258}{}{Thank you. That was very timely. If you ever have any more water you can spare, bring it to me, I'm always ready for exchange.}
{259}{}{You're welcome.}
{260}{}{What else can I do for you?}
{261}{}{Do you still need clean water?}
{262}{}{What did you say about water?}

{263}{}{The engine's all right, the shotgun too, got myself some clean water... What else does a traveler need, right?}
{264}{}{What's wrong with the shotgun?}
{265}{}{Hah, that's what *I'm* asking. If you don't know jack shit about guns, don't try to meddle.}

#Женские реплики (Rekrut)
{1110}{}{(Talks nervously and disconnectedly, but his hands clutching a shotgun are not trembling) No abrupt movements, stranger. Keep your hands so that I'd see them at all times.}
{1151}{}{Thanks for the story, but let's turn to more urgent issues. I know I don't look much like a Good Samaritan, but maybe I could help you with something?}
{1203}{}{It's been a while since I last rummaged in old engines...}
{1207}{}{Nothing changed since the last time you asked, it's all the same problems... There are no new problems, though, which is not half bad.}
{1215}{}{Hey, I tried...}
{1218}{}{Damn! Thank you, traveler! Purrs like a cat... (hands you a stimpak) I know it's not much for such a bang-up job, but we're tough on supplies, you got to understand.}
