{100}{}{You see a deranged man.}
{101}{}{You see a deranged man with a sign saying "I know" on his chest. He seems deeply troubled.}
{102}{}{You injected sedative into kiddo's butt.}
{103}{}{Oh damn, I just got worked up, and you...}

{110}{}{It's a deception! All of this isn't here!}
{111}{}{Somebody pinch me! I must be dreaming!}
{112}{}{It's-a-nightmare-and-I-can't-wake-up!!!}
{113}{}{None of this actually exists - no Nevada, no cafe, no me even!}
{114}{}{We've all been manipulated!}
{115}{}{Somebody created this hallucination! It can't be real!}
{116}{}{Someone's just playing us!}
{117}{}{You've been fooled! It's all a lie!}
{118}{}{It may look real, sound real, but it isn't real!}
{119}{}{You're just a plaything! A pawn! A puppet in clever hands!}
{120}{}{Don't trust them! They want to trick you!}

{200}{}{It's stupid... way too stupid...}
{201}{}{Why!?...}
{202}{}{Oh damn, ruined all the fun...}
{203}{}{It was just about to take pace...}
