{100}{}{You see a robot.}
{101}{}{You see a robot. You got a hunch that it might be a threat.}
{102}{}{Welcome}

#Выкрики при нападении
{110}{}{Alarm! Trespasser spotted!}
{111}{}{Activate security system!}
{112}{}{Received command to eliminate trespassers! Engaging.}

#Попытка заговорить
{120}{}{Welcome to "Poseidon Oil" Power Plant! Please do not disrupt public order and keep facility grounds clean.}
{121}{}{We apologize for the inconvenience. We hope no such incident occurs again.}
{122}{}{Welcome, vistor.}
{123}{}{Welcome, visitor. We are always glad to see you.}

#Попытка отключения
{130}{}{Robot disabled.}
{131}{}{This one is done for}

{132}{}{You fail to make sense of robot's system and only draw unwanted attention.}
{133}{}{Unauthorised personnel shouldn't do this}
{134}{}{Don't make me use force}
{135}{}{Trespasser detected! Eliminate immediately!}

{136}{}{Your repair skill is clearly not enough to disable the robot.}
