#Описания
{100}{}{You see a code safe.}
{101}{}{You see a formidably-looking safe.}

#При нанесении урона
{102}{}{Explosion leaves no damage on the safe, it must be made from some super-strong alloy.}

#При получение бонуса - бумажки управляющего
{103}{}{Your keenness of observation is astounding! You discover a hidden compartment within the safe, containing some note.}

#Применение навыков и предметов
{104}{}{It's a very strong manager's safe. These things are generally known to hold lots of valuables.}
{105}{}{This won't do any good.}
{106}{}{A very strong-looking safe. It's bound to have some valuables in it.}
{107}{}{No use}
{108}{}{Mechanical lockpicks won't do you any good - this safe has an electronic kind of lock.}
{109}{}{That's not what I need}

#Попытка обезвредить ловушку
{110}{}{You spot an electric trap on the safe, but you don't have enough skill to disarm it.}
{111}{}{You've disarmed the trap on the safe.}
{112}{}{Just like that!}
{113}{}{The trap hits you with an electric charge, but your gear absorbs the damage.}
{114}{}{The trap hits you with an electric charge, but your rubber boots help reduce the damage.}
{115}{}{The trap hits you with an electric charge.}
{116}{}{Failure}
{117}{}{Dammit!}
{118}{}{No traps.}

#Попытка взлома
{120}{}{This safe has already been picked.}
{121}{}{Your skill is too low to pick this lock. There's no use trying.}
{122}{}{There's an electric trap protecting this safe. You better disarm it before trying to pick it.}
{123}{}{There's a trap}
{124}{}{The safe is protected by very high voltage.}

{125}{}{You skillfully pick the lock.}
{126}{}{Well, what do we have here?!}
{127}{}{You fail to pick this safe.}

#Плавающие реплики при неудаче взлома:
{130}{}{Fail}
{131}{}{Come on!}
{132}{}{Ugh!}
{133}{}{Open up, damn you!}
{134}{}{By the power invested in me by...}
{135}{}{Come on already!}
{136}{}{How many more times?!}
{137}{}{I want you to open this very instant!}
{138}{}{Come on, what are you hiding from me?}
{139}{}{A little more...}
{140}{}{Just a teensie-weensie bit more...}
{141}{}{Ummmm...}
{142}{}{Aw crap...}
{143}{}{Bullshit!}
{144}{}{I smell valuables...}
