{100}{}{A raider.}
{101}{}{One of Big Louie's vultures, chaperoning you to Hawthorne.}
{102}{}{oh no! They killed Kennie!}

#Когда по напарнику попадает турель (для героя-мужчины):
{104}{}{Goddammit!}
{105}{}{Where the hell are you leading us?!}
{106}{}{You little! I warned you!}
{107}{}{Shit! I'm not your fucking bodyguard!}
{108}{}{When I'm done with him, you're next on my list, macho!}
{109}{}{Dammit, macho! I'll remember this!}

#Диалог:
{110}{}{So? Are you gonna just keep talking?}
{111}{}{Find some cover, I got to do some recon.}
{112}{}{Let's get going, I found a safe passage.}
{113}{}{Wait here, I have some scouting to do.}
{114}{}{Gotcha.}

{115}{}{I'm resting, macho. Do not disturb}

#Женские реплики (Иван):
{1104}{}{Goddammit!}
{1105}{}{Where the hell are you leading us?!}
{1106}{}{You little! I warned you!}
{1107}{}{Shit! I'm not your fucking bodyguard!}
{1108}{}{When I'm done with him, you're next on my list, muchacha!}
{1109}{}{Dammit, muchacha! I'll remember this!}

{1112}{}{Let's get going, I found a safe passage.}
{1114}{}{Gotcha.}
{1115}{}{I'm resting, muchacha. Do not disturb}
