{100}{}{Sentry turret.}
{101}{}{You see a sentry turret armed with twin miniguns.}

#Попытка обезвредить ремонтом
{102}{}{You can't do this in combat!}
{103}{}{You can't make heads or tails of such a complex system.}
{104}{}{You short the wires and the turret bursts into flames.}
{105}{}{This will do noting now.}

#Фразки партнеров-рейдеров
{110}{}{Hey! Quit fucking around, let's go!}
{111}{}{Well, that was awesome. What now?}
{112}{}{I'd rather not comment on that}
{113}{}{Enough already!}
{114}{}{Leave the turret alone, we gotta move}
{115}{}{Stop wasting time, I'm getting hungry!}
