##############################################
#
#   Генератор - устаревший диалог, не используется
#
##############################################

{100}{}{Генератор охранной системы.}
{101}{}{Генератор питает электричеством компьютер, управляющий турелями.}
{102}{}{Генератор обесточен и больше не поставляет электричество.}
{103}{}{Генератор уничтожен и больше не поставляет электричество.}
{104}{}{Генератор для питания охранной системы электричеством.}

{105}{}{Взрыв уничтожает многие важные детали генератора, и тот начинает источать радиацию! Турели на улице замирают.}
{106}{}{Вы демонтировали ядерные батареи и тем самым обесточили генератор.}
{107}{}{Из-за вашего неумения вас ударило током.}

{108}{}{Вы заминировали генератор, лучше отбежать подальше!}
{109}{}{10 секунд до взрыва!}
{110}{}{Вы не смогли разобраться в сложных хитросплетениях этой техники.}
{111}{}{Вас ударило током, но сапоги частично погасили удар.}

{112}{}{Вы замкнули определенные провода, после чего генератор сгорает, а вы получаете 500 опыта.}
{113}{}{Уничтожен}
{114}{}{Ваших навыков недостаточно, чтобы обезвредить эту машину.}
{115}{}{Этот генератор предназначен для питания охранных турелей вокруг ангара V9. Если его обесточить, то турели перестанут функционировать.}
{116}{}{Этот генератор питал электричеством турели вокруг ангара V9, но теперь ни он, ни турели не работают.}
{117}{}{}
{118}{}{Не работает}

##############################################
#
#   Переход в ангар
#
##############################################

{120}{}{Вы проникли в здание большого ангара, где до войны обслуживали различное военное оборудование.}
{121}{}{Вентиляция.}
{122}{}{Это большое вентиляционное отверстие. Возможно, оно ведет внутрь ангара V9.}
{123}{}{Это большое вентиляционное отверстие, ведущее внутрь ангара.}

##############################################
#
#   Генератор - новый диалог:
#
##############################################

{200}{}{Вы видите генератор.}
{201}{}{Перед вами генератор охранной системы. Он все еще работает.}
{202}{}{Перед вами генератор охранной системы. Он обесточен.}
{203}{}{Перед вами генератор охранной системы. Он уничтожен.}
{204}{}{Перед вами генератор охранной системы. Он уничтожен.}
{205}{}{Вы не сможете воспользоваться генератором во время боя.}
{206}{}{Не работает}
{207}{}{Этот генератор обесточен и поэтому не работает.}
{208}{}{Этот генератор не работает после критического замыкания.}
{209}{}{Этот генератор сильно поврежден и не работает.}

#Главное меню
{210}{}{Перед вами генератор охранной системы. По-видимому, он питает турели и другую автоматику вокруг ангара V9. По крайней мере, так следует из инструкций и предупреждений на борту устройства.}
{211}{}{Попытаться отключить питание от генератора.}
{212}{}{Попытаться выключить генератор.}
{213}{}{Попытаться взорвать генератор.}
{214}{}{Открыть крышку корпуса.}
{215}{}{Оставить.}
{216}{}{Назад.}
{217}{}{Завершить.}

#Отключить питание
{220}{}{С генератором связано огромное количество проводов и автоматических сенсоров, порой их назначение вам непонятно. Разобраться в этом сможет только человек, хорошо подкованный в науке, иначе процесс может оказаться летальным.}
{221}{}{Моих научных знаний недостаточно.}
{222}{}{Отключить питание генератора от внешних потребителей.}
{223}{}{Вы справились! Теперь генератор работает вхолостую, и от него не поступает электричество ни к одной турели.}
{224}{}{Вы получаете опыт за отключение турелей.}

#Отключить генератор
{230}{}{Вы могли бы это сделать при наличии богатых навыков в области техники и ремонта, так как надежная автоматика в приборе не позволит вам просто выключить рубильник.}
{231}{}{Моих технических навыков недостаточно.}
{232}{}{Выключить генератор.}
{233}{}{Вы справились! Обманув автоматику, вы вытаскиваете запасной микрореактор и отключаете основные урановые компоненты от сети. Турели больше не получают электричество.}
{234}{}{Вы получаете опыт за отключение турелей.}

#Подрыв
{240}{}{Для этого вам потребуется взрывчатка. Однако взрыв может повредить урановые компоненты генератора, после чего они начнут излучать радиацию в окружающую среду.}
{241}{}{Заложить динамит.}
{242}{}{Заложить динамитную шашку.}
{243}{}{Заложить пластид.}
{244}{}{Вы все еще не передумали?}
{245}{}{Да, заложить взрывчатку.}
{246}{}{Нет, пока обойдемся без взрывов.}
{247}{}{Генератор скоро будет взорван!}
{248}{}{Лучше не задерживаться}

{249}{}{Вы заминировали генератор, лучше отбежать подальше!}

#Открыть крышку
{250}{}{Крышка плотно прикреплена болтами к корпусу.}
{251}{}{Хм...}
{252}{}{Вскрыть крышку гаечным ключом.}
{253}{}{Крышка открыта.}
{254}{}{Готово.}
{255}{}{Дальше.}
{256}{}{Влить воды внутрь корпуса.}
{257}{}{Влить молоко брамина внутрь корпуса.}
{258}{}{Испустить мочи внутрь корпуса.}
{259}{}{Ничего интересного.}

{260}{}{Вы уверены? Это очень рискованно!}
{261}{}{Да, я рискну!}
{262}{}{Нет, не надо.}
{263}{}{Влить бутылку колы внутрь корпуса.}
{264}{}{Из-за жидкости провода замкнуло, и корпус начинает дымиться!}
{265}{}{Ток проходит по струе и поджаривает вас как цыпленка.}
{266}{}{К вашему счастью, ничего не произошло.}

{270}{}{Раз!}
{271}{}{Два!}
{272}{}{Три!}
{273}{}{Генератор уничтожен и больше не поставляет электричество для турелей.}
{274}{}{Вы получили незначительную дозу радиации.}
{275}{}{Вы получили небольшую дозу радиации.}
{276}{}{Вы получили большую дозу радиации.}
