{100}{}{The ruins of this old settlement give off the air of oblivion. It's like the time had stopped for this place since the last blast of the Great War died down.}
{101}{}{You enter Hawthorne outskirts. It's pretty quiet here.}
{102}{}{You've walked into the Test Site. Better watch your step here.}
{103}{}{You found a whole depot of train fuel. You should note this. Who knows when it might come in handy?}
{104}{}{Bet there's still some fuel left in those tanks. Then again, not like I need it or anything...}
{105}{}{These raiders don't seem to trust you much. Don't leave them for too long.}
{106}{}{Hey, we need to get to the storage area past that office building.}
{107}{}{Hey, looks like that generator is still working...}
{108}{}{Your buddies reached the destination point, you can go ahead to the storage area.}
{109}{}{You're a couple feet short of the ladder. Find a way to elevate yourself.}
{110}{}{Too high}
{111}{}{You see rodent carcasses ahead.}
{112}{}{Watch out!}
{113}{}{Hey, seems like there are some new lodgers in these ruins!}
