{100}{}{Look-out.}
{101}{}{You see a raider on patrol.}

# Когда поймал ГГ:
{110}{}{Freeze! You move - you die!}
{111}{}{Hey, hey! Easy! I'm still, see?!}
{112}{}{Hey, don't even think about touching me, buddy!}
{113}{}{НWell, I'll be damned! Let's see what boss has got to give me for your ass...}
{114}{}{(The look-out takes you to a two-story building holding you at gunpoint)}

# Когда подбегает, что бы арестовать:
{115}{}{Stop right there!}
{116}{}{You move, you die!}
{117}{}{Hold it right there, punk!}
{118}{}{Don't move!}
{119}{}{I said don't move!}
{120}{}{Don't even dream about getting away!}
{121}{}{Put your hands on your head, scum!}

# Когда Плесень сдох:
{122}{}{Seen the body in those ruins across from the base?}
{123}{}{Bye.}
{124}{}{That's Rot. He OD'd. So we threw him out before he started to smell.}
{125}{}{I see...}

#Если ГГ в одежде рейдера:
{130}{}{The look-out spotted you, but didn't recognize you in disguise.}
{131}{}{Hey, Roge, is that you?}
{132}{}{Hey, hold it! Who is this?}
{133}{}{Hey you, in the jacket, who are you?}
{134}{}{Who goes there? Roge, is that you?}
{135}{}{Roge, is that you? Out to throw up again, huh?}

# Когда враждебен, видит и нападает:
{200}{}{Hey you!!!}
{201}{}{Waste this bitch!!!}
{202}{}{Let's get it over with this motherfucker!}
{203}{}{Do you wanna be gutted or falyed?!}
{204}{}{Let's dance, baby!}
{205}{}{Time to make you cry.}
{206}{}{Hold still while I gut you, will ya?}

# Разговаривает сам с собой:
{207}{}{Nobody...}
{208}{}{I wish there was some action...}
{209}{}{So sick of walking in circles here...}
{210}{}{No one again!}
{211}{}{Why am I even doing this?}

# Когда не враждебен: 
{212}{}{Heya there.}
{213}{}{All's quiet.}
{214}{}{Ain't seen nobody.}
{215}{}{Ain't nobody comin' through here!}
{216}{}{Nothing to say, really.}
{217}{}{I'm on watch.}
{218}{}{It's a bit boring...}

{219}{}{Oh! It's you!}
{220}{}{All quiet. The boss need not worry.}
{221}{}{Ain't seen nobody.}
{222}{}{No one gets through me!}
{223}{}{Nothing to report.}
{224}{}{How's boss?}
{225}{}{You seem to get along with the boss well. Respect...}


# Женские реплики (Kerb)
{1110}{}{Freeze! You move - you die!}
{1117}{}{Hold it right there, bitch!}
