{100}{}{You see a gate.}
{101}{}{You see a gate equipped with a doorbell.}

{102}{}{Hey! Anybody home?! Nobody?}
{103}{}{The gate is locked and nobody answers the doorbell. looks like you're being ignored!}
{104}{}{Knock-knock!}
{105}{}{Someone remotely opened the door after your "secret" ring.}
{106}{}{The door is already open}
{107}{}{You easily pick the lock on the door.}
{108}{}{Done}
{109}{}{Fail}
{110}{}{You fail to pick a simple lock.}