{100}{}{Вы видите жителя Прово.}
{101}{}{Вы видите Гэри Гилмора.}
{102}{}{Перед вами мерзкий тип.}
{103}{}{Вы видите того самого Гилмора. Но лучше бы вы его не видели.}
{104}{}{Гэри Гилмор сдох! May his soul be condemned to torments of hell!}

#Реплики, когда квест от шерифа на него не получен
{110}{}{А ты еще кто?!}
{111}{}{Я здесь по делу, так что сиди тихо и не рыпайся.}
{112}{}{Опаньки! Какие люди!}

#Решение квеста шерифа
{113}{}{Так-так, посмотрите, что тут у нас. Ищешь неприятностей, а? Ну так ты по адресу.}
{114}{}{Притихни, я тут по делу.}
{115}{}{(совершить над гадом насильственное правосудие)}
{116}{}{Властью шерифа Солт-Лейка ты приговорен к повешению. Тебе есть, что сказать в оправдание?}

{117}{}{ДА, черт возьми, мне есть, что сказать! Что шериф - старый кусок дерьма, а ты...}
{118}{}{А по существу дела?}
{119}{}{А ну заткнись, мразота! [напасть]}
{120}{}{Не горячись, я не хочу проблем.}

{121}{}{Эти никчемные люди сами были виноваты. Я только помог городу, очистив его от грязи, на что звездатому шишкарю в городе не хватает духа.}
{122}{}{Звездатому? Ты про шерифа?}
{123}{}{Я тебе что - библиотека?! Да, про шерифа!}
{124}{}{Я так понимаю, ты наворотил каких-то бед в городе?}
{125}{}{Ты правда хочешь знать? Хорошо, я расскажу. Ни один сукин сын меня не хочет выслушать! А уж понять - тем более. Но все, что мне было нужно - это немного человеческого тепла. И что же? Вся жизнь для меня прошла в мучениях из-за чужой глупости. Так что я решил им всем отомстить, а заодно избавить мир от лишних людей.}
{126}{}{И поэтому ты пошел на насилие?}
{127}{}{Насилие? Нет, они недолго мучились. У меня еще остались в душе человеческие задатки и честь, чего нельзя сказать о них. Посуди сам, меня бы в Солт-Лейке никто так легко не убил, сначала бы пытали целый день. А значит, я сделал им большое одолжение.}
{128}{}{Надо же, бандит, а говорит о чести...}
{129}{}{А, что?! Да как ты смеешь! Да я... я... (начинает истерить и корчить рожи) Ты представляешь, каково это - резать горло сукину сыну? Или вытягивать тонкую кишку через пупок? Это невыносимо! Каждый раз в конце у меня случается припадок. Я больше так не могу!}

{130}{}{Выпустить бы тебе потроха прямо здесь, но в Солте не поверят. Ты пойдешь со мной, и тебя повесят прилюдно.}
{131}{}{Тогда получай свой приговор! Привести в исполнение немедленно!}
{132}{}{Душераздирающая история. Надеюсь, ты когда-нибудь исправишься.}

{133}{}{Что? Вот так просто - взять и сдохнуть? Да хрен вам!}
{134}{}{Ну, все, мне это надоело! Я свершу правосудие прямо сейчас!}
{135}{}{Ты подумай, а я еще вернусь.}

{136}{}{Вы уводите Гилмора в Солт-Лейк-Сити на повешение. Город будет счастлив этому событию.}
{137}{}{Прилюдно? Значит, обо мне еще долго будут помнить, верно? Да, я пойду и сдохну, как они все хотят! И это сделаешь ты! Ты!}
{138}{}{Пошли в Солт-Лейк, кусок говна...}

{139}{}{Перед уходом в Солт-Лейк-Сити вы забрали весь инвентарь Гилмора.}
{140}{}{Этого достаточно. Пора совершить правосудие прямо сейчас! [нападение]}
