{100}{}{You see Flayer.}
{101}{}{You see a hick looking after his herd. His appearance resembles that of an executioner with his filthy apron and massive bare arms.}
{102}{}{Hey, that shepherd is running away from you!}

#Первый разговор
{110}{}{So, ya got me huh. I ain't done nothin' wrong, just tendin' mah brahmins, is all!}
{111}{}{Then why the hell were you running away?}
{112}{}{Oh, so yer not one of them Salt Lake fools? Well then ya better not be pokin' about here.}
{113}{}{Why not?}
{114}{}{Cause town folks don't much appreciate these parts, and yer better off not knowin' why.}
{115}{}{Whatever.}
{116}{}{All righty then. I'll get back to mah herd.}
{117}{}{Wait a sec. Who lives in that grand hotel? The doors are locked, but it's clearly inhabited.}
{118}{}{[Leave]}

#Ответ, кто в отеле живет
{119}{}{Listen, ya really don't want to know, buddy. Ya better mind yer own beeswax, if you want my advice.}
{120}{}{Spill now, you son of a bitch! It will be much harder to do with a broken jaw!}
{121}{}{I have business with them... *Important* business. I think you got me.}
{122}{}{To hell with you!}

{123}{}{Oh yeah?! Than I am the Salt Lake sheriff... Leave me alone!}
{124}{}{Ugh... All right, but don't come a-whinin' I ain't warned ya. Come to the gate and ring the bell this way: one short, one long and one short. The Boss is in the backroom, go straight to him.}
{125}{}{Now that's better.}
{126}{}{Oh dammit! All right, I'll tell ya! But that's gonna be your problem since! Salt Lake outcasts live there. They are a desperate bunch and trust no one. If you really need to get in, come to the gate and ring the bell this way: one short, one long and one short. The Boss is in the backroom, go straight to him. Now leave me alone!}

#Вторичные реплики
{127}{}{Yer here again? Boy, am I not glad to see ya.}
{128}{}{Got any meat jerky?}
{129}{}{Yeah, bye.}
{130}{}{That's it. Now leave me alone!}
{131}{}{With pleasure!}

#Женские реплики:
{1110}{}{So, ya got me huh. I ain't done nothin' wrong, just tendin' mah brahmins, is all!}
{1119}{}{Listen, ya really don't want to know, sugar. Ya better mind your own beeswax, if you want my advice.}
