{100}{}{You see a door.}
{101}{}{You see a door equipped with keycard access system.}
{102}{}{This door is too strong.}

{110}{}{No power}
{111}{}{This door can't be opened from the outside while there's a power outage.}
{112}{}{Keycard required}
{113}{}{The electronic lock requires a keycard to be opened.}
{114}{}{This door is already open.}
{115}{}{No use}

{116}{}{This won't do any good while there's no power.}
{117}{}{This won't be any good here.}
{118}{}{It's open}
{119}{}{Keycard accepted. The door is open.}
{120}{}{Done}
{121}{}{You succeeded in tricking the electronic lock. The door is open.}
{122}{}{}
{123}{}{You fail to pick the electronic lock.}
{124}{}{Fail}
{125}{}{No power}
{126}{}{Lockpick type is different from lock type.}
