{100}{}{You see a generator.}
{101}{}{You see an ordinary generator. Judging from the markings, its responsibility is the station's lights.}

{102}{}{The generator is in working condition, it just needs a fresh microfusion cell.}
{103}{}{The generator's depleted}
{104}{}{Needs a new battery}
{105}{}{The generator is operational and supplies power to the station.}
{106}{}{No use}
{107}{}{The generator is already refilled and running.}
{108}{}{You refill the generator with a microfusion cell and it starts humming cheerfully.}
{109}{}{Done}
{110}{}{This won't help here.}
{111}{}{Generator's running}