{100}{}{You see a generator.}
{101}{}{You see an ordinary generator. Judging from the markings, it's responsible for antennae power supply.}

{102}{}{The generator is heavily rusted and inoperational. Repair would require new parts.}
{103}{}{Parts needed}
{104}{}{ exp. points.}
{105}{}{The generator is operational and supplies power to the station.}
{106}{}{No use}
{107}{}{The generator is running and does not require repair.}
{108}{}{You repair the generator. As you start it, it begins making a humming noise. You gain }
{109}{}{Done}
{110}{}{This won't be any good here. The generator needs repair and new parts.}
{111}{}{You failed to repair the generator.}
{112}{}{Fail}
{113}{}{You can't make use of what you got. New parts are required.}
{114}{}{Repair and new parts required}
{115}{}{Generator is running}