{100}{}{You see a safe.}
{101}{}{You see a solid wall safe with electronic lock.}
{102}{}{The explosion leaves no scratch on the safe.}

{105}{}{You've already picked this safe.}
{106}{}{It's harder than it seemed.}
{107}{}{Done}
{108}{}{}
{109}{}{You successfully pick the lock on this safe.}
{110}{}{You fail to pick the lock on this safe.}
{111}{}{Lockpick type is different from lock type.}
{112}{}{The safe is locked with electronic code lock.}
{113}{}{Locked}