{100}{}{You see a punching bag.}
{101}{}{You see a boxing punchbag. It's calling to you to try it out, as if saying "Don't miss the chance".}
{102}{}{You can try out your moves on this punchbag.}
{103}{}{Hmm, why the hell not?}
{104}{}{After your training the punchbag is too worn out and useless.}
{105}{}{This punchbag is useless}
{106}{}{This punchbag could help you improve your skills if they weren't so damn high already.}
{107}{}{Training? Who needs this...}
{108}{}{You spend an hour training with the punching bag and improve your unarmed skill by 1.}
{109}{}{Not half bad}

{110}{}{You shouldn't be training while there are enemies nearby.}
{111}{}{Can't risk it, aliens all around}