{0}{}{.}
{100}{}{It's a gas release system.}
{101}{}{You see an installation designed to release gas into the hangar ventilation system.}
{102}{}{You can't do this in combat!}

{110}{}{You install a gas cylinder into the system.}
{111}{}{First cylinder attached}
{112}{}{Second cylinder attached}
{113}{}{Third cylinder attached}
{114}{}{The installation is fully functional. All that's left is to enter the code and push the button.}

{120}{}{This installation would release gas into the ventilation, but it doesn't have a single gas cylinder.}
{121}{}{This installation can be run *only* when there are three gas cylinders attached.}
{122}{}{Needs gas cylinders}
{123}{}{Not enough gas cylinders}
{124}{}{This installation has played its part.}
{125}{}{Installation useless}
{126}{}{Finish.}

{127}{}{Enter code.}
{128}{}{The apparatus is completely filled. All that's left is to enter the code and push the button.}

{129}{}{0}
{130}{}{1}
{131}{}{2}
{132}{}{3}
{133}{}{4}
{134}{}{5}
{135}{}{6}
{136}{}{7}
{137}{}{8}
{138}{}{9}

{139}{}{-more-.}
{140}{}{Back.}
{141}{}{Finish.}
{142}{}{Clear.}
{143}{}{ -- }
{144}{}{Code: }

{145}{}{Code incorrect.}
{146}{}{Finish.}
{147}{}{Clear and start over.}

{148}{}{The installation is fully functional. All that's left is to enter the code and push the button.}
{149}{}{Initiate the release.}
{150}{}{Code accepted! The installation is ready to run. All that's left to do is push the button.}

{151}{}{Warning! Lethal gas is about to be released into the ventilation system. Do you confirm?}
{152}{}{Yes.}
{153}{}{No, let's do this later.}
{154}{}{Warning! Lethal gas is about to be released into the ventilation system! Evacuate the premises immediately.  }
{155}{}{Run...}
{156}{}{Exit.}

{157}{}{Warning! }
{158}{}{ seconds till release!}
{159}{}{ seconds till release.}
{160}{}{Gas has been released!}

#Женские реплики:
{1152}{}{Yes.}