{0}{}{.}
{100}{}{Combination safe.}
{101}{}{You see a safe locked with complex combination lock.}
{102}{}{You see a safe with a forced combination lock.}

#Использование предметов и скиллов:
{110}{}{This will do nothing, you've already picked the safe.}
{111}{}{You can't do this in combat!}
{112}{}{One of the codes opened the safe!}
{113}{}{Locked}
{114}{}{The safe is locked with a combination lock.}

#Использование предметов
{120}{}{The safe is locked with a dial combination mechanism. As it has seen virtually no use, picking it by sound would be nearly impossible.}
{121}{}{Dial a code.}
{122}{}{Attempt to pick.}
{123}{}{leave.}

{124}{}{Code: }
{125}{}{ -- }
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

{130}{}{1}
{131}{}{2}
{132}{}{3}
{133}{}{4}
{134}{}{5}
{135}{}{6}
{136}{}{7}
{137}{}{8}
{138}{}{9}
{139}{}{0}

{140}{}{More.}
{141}{}{Back.}
{142}{}{Delete.}
{143}{}{Finish.}
{144}{}{}

{145}{}{The code is incorrect.}
{146}{}{Clear and try again.}
{147}{}{Finish.}

{150}{}{The code is correct! The safe opens.}
{151}{}{With perception like yours you wouldn't be able to hear a gunshot if it was fired next to your ear, let alone pick a lock by sound.}
{152}{}{Your skills are nowhere near enough to pick this lock. Don't even try, it's just way too difficult for you.}
{153}{}{Nothing happens. Try again paying more attention.}
{154}{}{Try again.}
