{100}{}{Power supply controller.}

#Описания:
{101}{}{You see a power supply controller that is responsible for power supply to base facilities. It is damaged.}
{102}{}{Needs repair and part replacement}
{103}{}{You see a burnt out power supply controller. It's buzzing and sparkling.}
{104}{}{It's working}

#Использование предметов:
{110}{}{What in particular are you planning on repairing? Examine the piece of equipment first.}
{111}{}{Got to assess the damage first}
{112}{}{This machinery does not need repairs, as it is in working condition.}
{113}{}{No repairs needed}

#использование навыков:
{114}{}{The equipment is working so far...}
{115}{}{Some cables of this controller are damaged, but mind that they are still alive.}
{116}{}{Some spare parts are required here}

#Починка:
{117}{}{You can't fix the generator without spare parts.}
{118}{}{You can't do anything with your bare hands. You'll need some tools.}
{119}{}{Tools are a must here}

{120}{}{The system's all right, but you got a little "fried"!}
{121}{}{Dang it!}
{122}{}{The system's gonna be all right! ...for some time.}
{123}{}{Done!}

{124}{}{Repair failed. You must be doing something wrong.}
{125}{}{Your repair skill is insufficient.}
{126}{}{Didn't work out}
{127}{}{Not enough skill}

#Диалог:
{130}{}{You see a power supply controller that is supposed to supply power to the distributing systems. From there the power should be distributed around the facilities, but several parts and cables are either burnt out or damaged, so half of the buildings are blacked out. It's nothing too complicated, but one would need proper tools and parts, and also some deftness in order to not get baked like a turkey.}
{131}{}{Got it, I'll need tools and parts for replacement.}