{100}{}{You can't do that in combat.}
{101}{}{The hatch is inseparable from the fuselage now. You can't open it the regular way.}
{102}{}{So what now?}

{110}{}{The hatch has been deformed from impact, you can't open it the regular way.}
{111}{}{Try to blow it up.}
{112}{}{Leave.}

{113}{}{If you're not skillful enough with explosives you may accidentally destroy the contents of the cockpit as well.}
{114}{}{Place explosives and blow it up.}
{115}{}{Leave.}

{116}{}{Choose explosives.}
{117}{}{Dynamite.}
{118}{}{Plastic explosives.}
{119}{}{Dynamite stick.}
{120}{}{Nothing. Leave it.}
{121}{}{Explosion in 10 seconds.}
{122}{}{It's gonna blow!}
{123}{}{The hatch is so bent from the explosion that getting inside is now impossible.}
{124}{}{Thanks to your skill with explosives the blast neatly destroys the hatch leaving the cockpit intact.}
{125}{}{Due to your lack of skill the explosion obliterated the inside of the cockpit together with the hatch.}
