#Аварийный выключатель в ремсекторе:
{100}{}{Emergency lights switch.}
{101}{}{You see the emergency lights closer.}
{102}{}{You switch on the lights in all corridors on the floor.}
{103}{}{You switch off the lights in all corridors on the floor.}

#Обычный выключатель света в лаборатории:
{110}{}{It's a light switch.}
{111}{}{You see an ordinary lab light switch.}
{112}{}{You switch on the light in the laboratory.}
{113}{}{You switch off the light in the laboratory.}
