{100}{}{You see Jessica's brother.}
{101}{}{You see a Wind of War citizen.}
{102}{}{You're not half bad, for an outsider}
{103}{}{Go back to the wastes, ape! This is no place for you!}
{104}{}{What we gonna do now without our sister?!}
{105}{}{*Script error*}

{108}{}{Not that I'm an advocate of such measures, it just sort of... happened, you know. Look, outsider, here's $1000 to keep your mouth shut, keep it down now, will you?}
{109}{}{I know how to hold my tongue when the money's right...}

#Диалог
{110}{}{Well, well, well. What do we have here? Another radiated bonebag. He-he... Like, a bag with bones in it! (talks to brother) Did you hear that, brother!? A bonebag! Pft-ha-ha-ha-ha!}
{111}{}{You can laugh all you want, funny guys. When Robert takes away your girl, you won't be laughing anymore.}
{112}{}{So funny! If you don't like me so much, I'll leave.}
{113}{}{So funny... not! I'll go before I have to hear any more of your "jokes".}

{114}{}{I don't get it, what's it saying? Robert? That mongrel is at it again?!}
{115}{}{Yup. Where do you think did the keys to your house go?}
{116}{}{Robert? What Robert? You must have misheard something.}

{117}{}{Ha! (talks to brother) Hey, brother. I guess it's time to to turn out somebody's pockets. That scum of the Earth is asking for it again! (talks to you) But mark my words, outsider. If we don't find the keys on him - it would be your last joke.}
{118}{}{Way to go, fighters! Off to war!}

#Скриптовая сцена
{120}{}{Where do you think you're going, you piece of brahmin dung?}
{121}{}{Hey... what do you want, guys?}
{122}{}{To go through your pockets, in case some stray keys wandered in there!}
{123}{}{I... don't have your keys...}
{124}{}{Shut up!}
{125}{}{ }
{126}{}{Take this, dweeb!}
{127}{}{Oh shit! What have we done?!}
{128}{}{Let's split before we get busted!}

#Женские реплики (Kerb):
{1108}{}{Not that I'm an advocate of such measures, it just sort of... happened, you know. Look, outsider, here's $1000 to keep your mouth shut, keep it down now, will you?}
{1117}{}{Ha! (talks to brother) Hey, brother. I guess it's time to to turn out somebody's pockets. That scum of the Earth is asking for it again! (talks yto you) But mark my words, outsider. If we don't find the keys on him - it would be your last joke.}