{100}{}{You see a private.}
{101}{}{It's a private, a soldier of the lowest rank.}

{102}{}{Alarm! We're under attack!}
{103}{}{I warned you! Someone's gonna get punished!}

#Стартовая ветка
{110}{}{Hold it! You're not allowed in the barracks. Get out. Move it!}
{111}{}{I walk wherever I want, got it, grunt? Or shall I show you in mime?}
{112}{}{Barracks? I thought it was a hotel of some sort...}
{113}{}{What? You again?! Look, I don't like this. If I see you in the barracks again, I'll tear you limb from limb *personally*! Understood?}

#Наем проводника:
{501}{}{Aren't you sick of sticking in these barracks? I know a way you could have some fun. I need a conductor for a train ride.}
{502}{}{Judging from your vernacular, soldiers here are more like inmates. He-he.}
{503}{}{Look here, pal. There's a word in the street of a suspicious fellow sniffing around, being all suspicious, you know. This couldn't by any chance be you, could it? We don't much like this kind of people here, keep that in mind. Now clear the premises!}
{504}{}{All right, all right. No need to get all uptight.}
{505}{}{Well, let me think... You don't look like the kind we dip face down in latrines. All right, go ahead, convince me.}
{506}{}{(explain the task)}
{507}{}{Damn, I'm in! I'll need some money though, 2000 bucks. I can't get to Salt Lake on my own, and me and caravan drivers don't see eye to eye, if you know what I mean.}
{508}{}{I see. Here's the money. See you in Salt Lake.}
{509}{}{I see. I'll try to get the money ASAP. Damn, two grand is quite a sum...}
{510}{}{You got yourself a conductor. Now you can go back to Salt Lake and proceed with your mission.}

#Женские реплики (Kerb)
{1112}{}{Barracks? I thought it was a hotel of some sort...}
{1503}{}{Look here, girl. There's a word in the street of a suspicious lass sniffing around, being all suspicious, you know. This couldn't by any chance be you, could it? We don't much like this kind of people here, keep that in mind. Now clear the premises!}
{1504}{}{All right, all right. No need to get all uptight.}
