{100}{}{This is one odious looking settlement, staying alert at all times would be a good idea.}
{110}{}{Hey, you! No guns allowed!}
{111}{}{Can you hear me? Put your gun away!}
{112}{}{You're asking for it, aren't you?!}
{113}{}{This is your final warning!}
{114}{}{ALARM! WE'RE UNDER ATTACK!}

{115}{}{Wow! That's unexpected!}
{116}{}{Now you get why the mechanic guards the garage entrance so hecticly.}

{117}{}{What is that!?}
{118}{}{Hey! Seems like the sound of a running engine is coming from the garage by the station!}
