{100}{}{A wanted poster with a crude charcoal sketch of a wanted person. The person on the poster looks familiar.}
{101}{}{The caption reads.}
{102}{}{Wanted Dead or Alive for Child Killing and being a Rat Bastard. Reward $10,000 Dead or $5,000 Alive.}
{103}{}{Wanted Dead or Alive for Child Killing. Reward $10,000 Dead or $5,000 Alive.}
{104}{}{Wanted Dead or Alive for Being a Rat Bastard. Reward $10,000 Dead or $5,000 Alive.}
{105}{}{Wanted Dead or Alive for Caravan Robberies. Reward $5 000 Dead or $2 000 Alive.}

#Женский вариант
{1102}{}{Wanted Dead or Alive for Child Killing and being a Rat Bastard. Reward $10,000 Dead or $5,000 Alive.}
{1103}{}{Wanted Dead or Alive for Child Killing. Reward $10,000 Dead or $5,000 Alive.}
{1104}{}{Wanted Dead or Alive for Being a Rat Bastard. Reward $10,000 Dead or $5,000 Alive.}
{1105}{}{Wanted Dead or Alive for Caravan Robberies. Reward $5 000 Dead or $2 000 Alive.}
