{0}{}{ }

#Использование навыков
{90}{}{Вы обезвредили ловушку.}
{91}{}{Вам не удалось обезвредить ловушку.}
{92}{}{Это было неудачное решение.}

#Примитивное сознание
{100}{}{Аргхх!!!}

{101}{}{Упс! Моя споткнулся?!}
{102}{}{Над моя насмехались?}
{103}{}{Моя повезло - не ушибся.}
{104}{}{Моя это заберет себе.}
{105}{}{Ух ты! Моя нос разбил!}
{106}{}{На что моя наступил?}
{107}{}{Ух ты! Теперь это моя будет.}
{108}{}{::непереводимая игра слов::}
{109}{}{::грозно ворчит и ругается::}

#Дети
{110}{}{Черт!!!}
{111}{}{Ну вот! Опять штаны порвал. Мама будет ругаться...}
{112}{}{Нуууууу воооооот!!!}
{113}{}{Какой я неуклюжий!}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}

#Проститутки
{120}{}{Вот зараза!!!}

{121}{}{Ой! Трусики спадают!}
{122}{}{Никто не увидел мои трусики?}
{123}{}{::одергивает юбку::}
{124}{}{Это не смешно!}
{125}{}{Мне за грязную морду не заплатят.}
{126}{}{Опять я порастеряла все свои причиндалы!}
{127}{}{Чертовы детишки! Найду - высеку!}
{128}{}{}
{129}{}{}

#Рядовые граждане
{130}{}{Что за черт!!!}

{131}{}{Что это за глупые шутки?!}
{132}{}{Таких хулиганов нужно драть за уши!}
{133}{}{Это какая-то глупая шутка, знаете ли...}
{134}{}{Это не смешно!}
{135}{}{Кто это сделал?! КТО?!}
{136}{}{Кажется, здесь не стоит разгуливать...}
{137}{}{Чертовы детишки! Найду - высеку!}
{138}{}{Эй! Кто это здесь такой шутник отыскался?! Высеку!}
{139}{}{И надо же было попасть в эту дурацкую уловку!}

#Рядовые рабочие
{140}{}{Твою мать!!!}

{141}{}{Какой кретин это сделал!?}
{142}{}{Ну что за день такой хреновый!}
{143}{}{После такого надо пивка хлебнуть.}
{144}{}{Вот гадство! Опять штаны замарал.}
{145}{}{Уф... Подошве, кажется, конец.}
{146}{}{Найду этого шутника - и мордой в грязь! Ага.}
{147}{}{Ну, шпана, держитесь! Достали вы меня!}
{148}{}{Какой молокосос издевается?! А?}
{149}{}{Эй, шутник! Выходи, дырка от задницы!!!}

#Фермеры
{150}{}{Тьфу ты!!!}

{151}{}{Какой балбес это сделал!?}
{152}{}{Ну что за день такой хреновый!}
{153}{}{Это что, шутка?! Не смешно!}
{154}{}{Я весь день работал, а вы, гады, издеваетесь надо мной?!}
{155}{}{Уф... Подошве, кажется, конец.}
{156}{}{Найду этого шутника - и мордой в грязь! Ага.}
{157}{}{ЧТОБЫ ТАК БОЛЬШЕ НЕ ДЕЛАЛИ!!!}
{158}{}{Какой молокосос издевается?! А?}
{159}{}{}

#Опустившиеся
{160}{}{Ох!!!}

{161}{}{!?}
{162}{}{Эх... очередная неудача...}
{163}{}{Это что, шутка?! То же мне!}
{164}{}{Да я... Да я... Да вы знаете, КТО Я!?}
{165}{}{Уффф...}
{166}{}{::кряхтя, поднимается из грязи::}
{167}{}{ЧТОБЫ ТАК БОЛЬШЕ НЕ ДЕЛАЛИ!!!}
{168}{}{}
{169}{}{}

#Анклав
{170}{}{ТВОЮ МАТЬ!!!}
{171}{}{Найду эту суку - разорву на куски!!!}
{172}{}{КАКАЯ СУКА НАДО МНОЙ ПОТЕШАЕТСЯ?! ВЫХОДИ!!! ДЕРИСЬ!!!}

#Братство
{180}{}{Твою мать!!!}

{181}{}{Это сделали для меня или как?!!!}
{182}{}{Неудачная шутка, покойник!}
{183}{}{Ну все! Ты покойник!}
{183}{}{Ты влетел на бабло, приятель!}
{184}{}{Кто это сделал?! Кто это сделал?!!!}
{185}{}{Так! Что тут у нас? Еще один шутник-покойник, а?}
{186}{}{Эй, шутник? А может выйдешь, и мы по-мужски поговорим, а?}

#Боевые ребята
{190}{}{Твою мать!!!}

{191}{}{Это для меня сделали или как?!!!}
{192}{}{Эй, козлина! Ты покойник!!!}
{193}{}{Да я тебя сейчас мордой в жопу засуну!!!}
{193}{}{Я этого шутника из-под земли достану! Клянусь!}
{194}{}{Кто это сделал?! КТО ЭТО СДЕЛАЛ?!!!}
{195}{}{Да я за такие шутки!... Да я *не знаю*, что с тобой сделаю!!!}
{196}{}{Эй, шутник! А может, выйдешь, и мы поговорим, а?}

#Мутанты
{200}{}{АРРРГХХХ!!!}
{201}{}{Моя сейчас кому-то оторвет руки! и ноги!... и... пенис!}
{202}{}{Найду - утопчу до уровня гроба!}
{203}{}{Отлично! Еще одним покойником будет больше. Ты только покажись!}

#Гули
{210}{}{Айя-йя-яй!!!}
{211}{}{Одним глазом меньше. Подумаешь!}
{212}{}{Кажется, ухо отвалилось...}
{213}{}{Не видели, куда откатился мой большой палец?}
{214}{}{А я не так уж и плохо сохранился!}
{215}{}{Уф! Ну хотя бы жив остался!}
{216}{}{Молодые люди! Нельзя так издеваться!}

#Панки
{220}{}{Хайя!!!}
{221}{}{Так, кому яйца отрезать?! Признавайся, живо!}
{222}{}{Слышь, бычара, выходи, не ссы! Да я тебя не трону!}
{223}{}{Шутничок! Я тебя просек! Это ты, я знаю! Выходи танцевать!}
{224}{}{Кто это сделал?! Спрятался, как девочка, да?! ТЫ ОПУЩЕН, ОПУЩЕН!!!}
{225}{}{Найду этого козла - и мордой в тапки!}

#Хабологи, дети детей храма
{230}{}{Ох!!!}
{231}{}{Мм... Кажется, я попал в ловушку.}
{232}{}{Не думаю, что это проделки смазливой ребятни.}
{233}{}{Я не уверен, но на меня покушались!}
{234}{}{Интересно, кому была предназначена эта ловушка?}

#Роботы
{270}{}{Обнаружено препятствие.}
{271}{}{Препятствие ликвидировано.}
{272}{}{Зафиксировано опасное устройство. Возможно наличие врагов поблизости.}
{273}{}{Задействована программа повышенного внимания.}
{274}{}{ВНИМАНИЕ! ЗАФИКСИРОВАНО ДИВЕРСИОННОЕ УСТРОЙСТВО!!!}

{300}{}{Ваша ловушка успешно сработала, нанеся вред жертве.}
{301}{}{Ваша ловушка успешно сработала, жертва падает и разбрасывает свои вещи.}
{302}{}{Вашу ловушку вовремя обнаружили и обезвредили.}
